# Slide aggiuntive inserite prima della citazione finale di alcune lezioni
from h import *
EXTRA = {}
EXTRA['1.1'] = [
 CF('Cinque perdite di fila', dict(t='Rischio 1%', punti=[['Dopo 5 perdite', '−4,9%'], ['Capitale da 10.000 €', '9.510 €']]), dict(t='Rischio 5%', punti=[['Dopo 5 perdite', '−22,6%'], ['Capitale da 10.000 €', '7.738 €']]),
  ["Vediamo cosa significa nella pratica. Cinque perdite di fila sono normali in qualsiasi sistema.", "Con il rischio all'uno per cento, cinque perdite consecutive costano il 4,9 per cento: da diecimila euro scendi a 9.510. Si recupera senza drammi.", "Con il rischio al cinque per cento, le stesse cinque perdite costano il 22,6 per cento: da diecimila euro scendi a 7.738. Per tornare al punto di partenza serve un guadagno di quasi il 30 per cento.", "La serie di perdite è identica. Cambia solo quanto rischiavi. È la dimensione del rischio a trasformare una serie normale in un disastro."], 'Stessa serie di perdite: cambia solo il rischio.'),
 ES('rischio 2%', [['Capitale', '20.000 €'], ['Rischio per trade', '2%'], ['Domanda 1', 'perdita massima su un trade?'], ['Domanda 2', 'capitale dopo 3 perdite di fila?']], [['Perdita sul trade', '2% di 20.000 = 400 €'], ['Dopo 3 perdite', '20.000 × 0,98³'], ['Capitale', '18.824 €']], 'Perdita totale: 1.176 € (5,9%, non 6%)',
  ["Ora tocca a te. Metti in pausa il video, se vuoi. Hai ventimila euro e rischi il due per cento a operazione. Quanto perdi al massimo su un trade? E quanto ti resta dopo tre perdite di fila?", "La perdita massima su un trade è il due per cento di ventimila: quattrocento euro. Dopo tre perdite, il capitale è ventimila per zero virgola novantotto alla terza: diciottomilaottocentoventiquattro euro. Hai perso 1.176 euro, cioè il 5,9 per cento, non il 6: le perdite si compongono, ogni volta il due per cento si applica a un capitale più piccolo."]),
 RIEP(['Il rischio per trade decide se sopravvivi e quanto soffri', 'Stessa strategia, rischio diverso: destini molto diversi', 'Tre numeri da scrivere: perdita massima, perdite di fila, punto di stop'],
  ["Riassumiamo.", "Il rischio per trade decide se sopravvivi e quanto soffri.", "Con la stessa strategia, un rischio diverso porta a destini molto diversi.", "E ci servono tre numeri scritti: la perdita massima per operazione, quante perdite di fila reggi, e il punto in cui ti fermi."]),
]
EXTRA['1.2'] = [
 TB('Il rischio in euro cambia con il capitale', ['Capitale', 'Rischio 1%'], [['10.000 €', '100 €'], ['12.000 € (dopo +20%)', '120 €'], ['8.000 € (dopo −20%)', '80 €']],
  ["Una cosa importante: il rischio in percentuale resta fisso, ma in euro cambia con il capitale.", "Con diecimila euro, l'uno per cento è cento euro.", "Se il conto sale a dodicimila, l'uno per cento diventa centoventi euro: rischi di più in valore assoluto, ma lo stesso in proporzione.", "Se il conto scende a ottomila, diventa ottanta euro. Quando perdi, le posizioni si rimpiccioliscono da sole. È un freno automatico che protegge il capitale."], nota='Il rischio in % si adatta da solo: più piccolo quando perdi.'),
 ES('rischio 0,5%', [['Capitale', '25.000 €'], ['Rischio per trade', '0,5%'], ['Domanda', 'quanto rischi in euro?']], [['Calcolo', '25.000 × 0,005']], 'Rischio = 125 €',
  ["Un esercizio rapido. Hai venticinquemila euro e rischi mezzo per cento a operazione. Quanto rischi in euro?", "Venticinquemila per zero virgola zero zero cinque: centoventicinque euro."]),
 RIEP(['Rischio = quanto perdi se il trade va male', 'Si esprime in percentuale e si decide prima di entrare', 'Il rischio in euro si adatta al capitale: scende quando perdi'],
  ["Riassumiamo.", "Il rischio è quanto perdi se il trade va male.", "Si esprime in percentuale e si decide prima di entrare.", "E in euro si adatta al capitale: quando perdi, le posizioni si rimpiccioliscono da sole."]),
]
EXTRA['1.3'] = [
 EX('Come si sceglie lo stop', [['Ingresso long', '1,1000'], ['Ultimo minimo rilevante', '1,0980'], ['Margine per il rumore', '5 pip'], ['Stop loss', '1,0975'], ['Distanza', '25 pip']], risultato='Stop deciso dal grafico, non dal portafoglio', k=[1,2,3,4,5,6],
  voce=["Un esempio pratico. Vuoi comprare a uno virgola uno zero zero zero.", "L'ultimo minimo rilevante è a uno virgola nove otto zero: sotto quel livello l'idea di acquisto non vale più.", "Lasci un margine di cinque pip, perché il prezzo può sfiorare un livello senza romperlo.", "Lo stop va quindi a uno virgola zero nove sette cinque.", "Che significa venticinque pip di distanza.", "Notare l'ordine: lo stop è stato deciso guardando il grafico, non guardando quanto avresti voluto rischiare."]),
 ES('stop e valore del pip', [['Rischio', '60 €'], ['Stop', '30 pip'], ['Domanda', 'quanto deve valere un pip?']], [['Valore del pip', '60 ÷ 30'], ['Pip da 2 € = lotto', '0,2']], 'Valore pip = 2 € → 0,2 lotti',
  ["Esercizio. Vuoi rischiare sessanta euro con uno stop a trenta pip. Quanto deve valere un pip, perché la perdita massima sia sessanta euro?", "Sessanta diviso trenta: due euro a pip. Con circa dieci euro a pip per un lotto, significa zero virgola due lotti. Nella prossima lezione trasformiamo questo ragionamento in una formula."]),
 RIEP(['Lo stop è il prezzo in cui l\'idea è sbagliata', 'Si sceglie dal grafico; il lotto si adatta al rischio', 'Si può stringere, mai allargare'], ["Riassumiamo.", "Lo stop è il prezzo in cui l'idea è sbagliata.", "Si sceglie dal grafico, e il lotto si adatta al rischio.", "Si può stringere, ma mai allargare."]),
]
EXTRA['1.4'] = [
 EX('Secondo esempio', [['Capitale', '20.000 €'], ['Rischio per trade', '0,5% = 100 €'], ['Stop', '40 pip'], ['Lotti', '100 ÷ (40 × 10)']], risultato='= 0,25 lotti', k=[2,3,4,5],
  voce=["Secondo esempio, con un conto più grande ma un rischio più piccolo.", "Capitale ventimila euro, rischio mezzo per cento: sempre cento euro.", "Stop a quaranta pip.", "Cento diviso quaranta per dieci: zero virgola venticinque lotti."]),
 ES('calcola il lotto', [['Capitale', '5.000 €'], ['Rischio', '2%'], ['Stop', '20 pip'], ['Valore pip', '10 € per lotto']], [['Rischio in euro', '5.000 × 0,02 = 100 €'], ['Lotti', '100 ÷ (20 × 10)']], 'Lotti = 0,5',
  ["Esercizio. Capitale cinquemila euro, rischio due per cento, stop a venti pip, valore del pip dieci euro per lotto. Quanti lotti?", "Il rischio in euro è cento. Cento diviso venti per dieci fa zero virgola cinque. Mezzo lotto."]),
 RIEP(['Lotti = rischio in € ÷ (stop in pip × valore del pip)', 'Stop più largo → lotto più piccolo, rischio uguale', 'Arrotonda per difetto e controlla il valore del pip del tuo conto'], ["Riassumiamo.", "Lotti uguale rischio in euro diviso stop in pip per valore del pip.", "Uno stop più largo comporta un lotto più piccolo, a parità di rischio.", "E arrotonda sempre per difetto, controllando il valore del pip del tuo conto."]),
]
EXTRA['1.5'] = [
 TB('Lo stesso RR, win rate diversi (10 trade)', ['RR', 'Vinti su 10', 'Risultato'], [['3', '3', '+2 R'], ['2', '4', '+2 R'], ['1', '5', '0 R']],
  ["Vediamo come RR e percentuale di vittorie lavorano insieme, su dieci operazioni.", "Con RR tre, bastano tre vittorie su dieci: tre per tre fa nove, meno sette perdite, più due R.", "Con RR due, quattro vittorie su dieci: otto meno sei, più due R.", "Con RR uno, cinque su dieci ti portano a zero: sei in pareggio, prima dei costi."], nota='Prima dei costi di spread e commissioni.'),
 ES('RR 2 e win rate 40%', [['RR', '2'], ['Operazioni', '10'], ['Vinte', '4 (40%)'], ['Domanda', 'risultato in R?']], [['4 vinte', '4 × 2 = +8 R'], ['6 perse', '6 × 1 = −6 R']], 'Totale: +2 R',
  ["Esercizio. RR due, dieci operazioni, quattro vinte. Quanto fai in R?", "Quattro vinte per due: più otto R. Sei perse per uno: meno sei R. Totale: più due R."]),
 RIEP(['RR = guadagno obiettivo ÷ rischio', 'Un RR alto da solo non basta: conta con il win rate', 'Si può guadagnare anche vincendo meno della metà delle volte'], ["Riassumiamo.", "RR è il guadagno obiettivo diviso il rischio.", "Un RR alto da solo non basta: conta in combinazione con il win rate.", "E si può guadagnare anche vincendo meno della metà delle volte."]),
]

# ---- disegni animati e schermate (inseriti dopo la slide indicata) ----
INS = {}
DEL = {'3.2': ['Il paradosso'], '5.1': ['Un ventaglio di futuri'], '8.1': ['Trailing a scatti']}
INS['1.3'] = [('Dove si mette', D('Sul grafico: dove sta lo stop', 'trade', ['minimo', 'ingresso', 'stop'],
  ["Vediamolo su un grafico. Il prezzo scende, rimbalza e forma un minimo.", "Ecco l'ultimo minimo rilevante: uno virgola nove otto zero. Sotto quel livello, l'idea di acquisto non è più valida.", "Entri a uno virgola uno zero zero zero, dopo il rimbalzo.", "Lo stop va un po' sotto il minimo, a uno virgola zero nove sette cinque: venticinque pip, un R di rischio. Il margine di cinque pip serve a non farti fermare dal rumore. Lo stop l'hai deciso guardando il grafico, non il portafoglio."],
  didascalia='Esempio illustrativo con prezzi simulati.'))]
INS['1.4'] = [('Esempio svolto', SC('Lo stesso calcolo in uno strumento', 'sch_calc.png', [('Saldo 10.000 €, rischio 1%', 'cioè 100 € da rischiare'), ('Stop 25 pip, 10 € a pip', 'i dati dell\'esempio'), ('Risultato: 0,40 lotti', 'rischio 100 €, se colpisci 2 R guadagni 200 €')],
  ["Lo stesso calcolo, in un calcolatore. Dichiaro che questo è un mio strumento gratuito, sul sito riskly punto trade, ma ottieni lo stesso risultato con la formula, o con un foglio di calcolo.", "Inserisci il saldo di diecimila euro e il rischio all'uno per cento: sono cento euro da rischiare.", "Poi lo stop di venticinque pip e il valore del pip, dieci euro per lotto.", "Il risultato è zero virgola quaranta lotti, con un rischio di cento euro. E se arrivi a due R, ne guadagni duecento. Esattamente come nel nostro esempio svolto."]))]
INS['1.5'] = [('Esempio', D('Lo stesso trade sul grafico', 'trade', ['ingresso', 'stop', 'target', 'esito'],
  ["Rivediamo il trade di prima sul grafico, questa volta con il target.", "Entri a uno virgola uno zero zero zero.", "Lo stop è venticinque pip sotto: rischi un R.", "Il target è quarantacinque pip sopra: puoi guadagnare uno virgola otto R. Il rapporto è la distanza verde divisa per quella rossa.", "E se il prezzo arriva al target, hai guadagnato uno virgola otto volte quello che rischiavi. Se invece tocca lo stop, perdi un R."],
  didascalia='Esempio illustrativo con prezzi simulati.'))]
INS['2.5'] = [('Strumenti: un mio prodotto, dichiarato', SC('Le statistiche del journal (dati dimostrativi)', 'sch_journal.png', [('Winrate e profit factor', 'sul totale delle operazioni registrate'), ('Drawdown massimo dal picco', 'in euro, e la serie massima di vittorie e perdite'), ('Aspettativa per trade e R medio', 'le stesse misure delle lezioni 2.1 e 2.2')],
  ["Questa è una schermata del Riskly Journal, che è un mio prodotto, con dati dimostrativi. Mostra le stesse misure che hai imparato.", "Il win rate e il profit factor calcolati sulle operazioni registrate.", "Il drawdown massimo dal picco, e la serie massima di vittorie e di perdite.", "E l'aspettativa per trade, con l'R medio: la expectancy della lezione due punto uno. Con un foglio di calcolo ottieni gli stessi numeri."]))]
INS['3.1'] = [('Esempio', D('Il drawdown sulla curva del conto', 'equity', ['massimo', 'minimo', 'drawdown'],
  ["Guardiamo l'esempio sulla curva del conto, che sale e scende.", "Il conto sale fino a dodicimila euro: questo è il massimo.", "Poi scende fino a novemilaseicento: il punto più basso.", "La distanza tra i due, in percentuale del massimo, è il drawdown: meno venti per cento. Il drawdown si misura sempre dal picco, non dal punto di partenza."],
  didascalia='Esempio illustrativo.'))]

INS['5.1'] = [('Come funziona', D('Un percorso, poi molti', 'mc', ['uno', 'pochi', 'molti', 'bande'],
  ["Vediamo il metodo che prende forma, un passo alla volta.", "Una sola simulazione: duecento operazioni del nostro sistema di esempio, a rischio uno per cento. Un possibile futuro.", "Ne aggiungiamo altre cinque. Le stesse regole, ma ogni percorso è diverso.", "Con sessanta percorsi il ventaglio comincia a prendere forma: alcuni finiscono molto in alto, altri meno.", "Con centinaia di percorsi si distinguono tre linee: la mediana, e il decimo e il novantesimo percentile, che racchiudono l'ottanta per cento dei casi."],
  didascalia='Sistema di esempio, rischio 1%, 200 operazioni.'))]
INS['8.1'] = [('Due strumenti, due scopi', D('Trailing a scatti di 1 R', 'trailing', ['ingresso', 'r1', 'r2', 'r3', 'uscita'],
  ["Vediamo un trailing a scatti su un grafico, misurato in R.", "Entri con lo stop iniziale a meno un R.", "Quando il prezzo arriva a più un R, lo stop va a pareggio: il trade non può più perdere.", "A più due R, lo stop sale a più un R: un guadagno minimo è già assicurato.", "A più tre R, lo stop va a più due R.", "Poi il prezzo torna indietro e scatta lo stop: esci a più due R, senza aver dovuto indovinare il massimo."],
  didascalia='Esempio illustrativo.'))]
INS['8.2'] = [('L\'idea', D('Tre scaglioni sul grafico', 'scaglioni', ['ingresso', 'tp1', 'tp2', 'tp3', 'totale'],
  ["Vediamo gli scaglioni su un grafico.", "Entri con lo stop a meno un R e tre target pianificati: più un R, più due R, più tre R.", "Il prezzo sale e tocca il primo: esce la metà della posizione, e incassi.", "Tocca il secondo: esce il trenta per cento.", "Tocca il terzo: esce il restante venti per cento.", "Il risultato finale è zero virgola cinque per uno, più zero virgola tre per due, più zero virgola due per tre: più uno virgola sette R."],
  didascalia='Esempio illustrativo con prezzi simulati.'))]
INS['8.4'] = [('Gli strumenti Riskly (miei prodotti, dichiarato)', SC('Un esempio: RiskGuard', 'sch_riskguard.png', [('Pausa dopo una perdita', 'e blocco dopo N perdite consecutive, scelto da te'), ('Limite di perdita e di operazioni giornaliere', 'le regole della lezione 6.2'), ('Chiusura al target e blocco di MetaTrader', 'il software applica ciò che hai scritto nel piano')],
  ["Un esempio concreto: RiskGuard, che come ti ho detto è un mio prodotto.", "Pausa obbligatoria dopo una perdita, e blocco dopo un numero di perdite consecutive che scegli tu.", "Limite di perdita e di operazioni giornaliere: sono le regole della lezione sei punto due.", "Chiusura al target e blocco di MetaTrader. Il software non decide per te: applica ciò che hai scritto nel piano."]))]
INS['3.2'] = [('Perdere è facile, **recuperare** no', D('Il paradosso del 50%', 'barre', ['parti', 'perdi', 'guadagni', 'serve'],
  ["Parti da diecimila euro. Perdi il cinquanta per cento, e guadagni il cinquanta per cento: sei tornato a diecimila? Guardiamo.", "Il conto parte da diecimila euro.", "Perdi il cinquanta per cento: ne restano cinquemila.", "Guadagni il cinquanta per cento: ma è il cinquanta per cento di cinquemila, cioè duemilacinquecento. Arrivi a settemilacinquecento.", "Per tornare a diecimila ti serve un guadagno del cento per cento, non del cinquanta. Il guadagno si applica a una base più piccola."]))]
