LEZIONE = dict(id='0.0', modulo='Introduzione', modTitolo='Prima di cominciare', titolo='Benvenuto e come usare il corso', slide=[
 dict(tipo='titolo', kicker='RISKLY · CORSO DI GESTIONE DEL RISCHIO', titolo='Il rischio viene **prima** della strategia', sotto='Dalle basi alla gestione avanzata, con numeri veri e un piano scritto alla fine.',
  voce=["Benvenuto. In questo corso impari a gestire il rischio nel trading, partendo da zero e arrivando fino agli strumenti dei professionisti. Il filo conduttore è uno solo: non puoi controllare il mercato, ma puoi controllare quanto rischi."]),
 dict(tipo='punti', titolo='A chi serve questo corso', punti=[('A chi inizia', 'e vuole partire con le regole giuste, prima di perdere i primi soldi'), ('A chi ha già un conto', 'e sente che i risultati dipendono troppo dall\'umore del giorno'), ('A chi fa una prova di prop firm', 'e non vuole bruciare la sfida per un limite superato')],
  voce=["Il corso serve a tre tipi di persone.", "A chi inizia, e vuole partire con le regole giuste prima di perdere i primi soldi.", "A chi ha già un conto, ma sente che i risultati dipendono troppo dall'umore del giorno.", "E a chi affronta la sfida di una prop firm, e non vuole perderla per un limite superato di un soffio."]),
 dict(tipo='punti', titolo='Come è fatto', punti=[('Dieci moduli, quarantasei lezioni', 'ogni lezione dura pochi minuti e tratta un solo concetto'), ('Prima il perché, poi i numeri', 'ogni formula arriva con un esempio svolto'), ('Alla fine un piano scritto', 'il tuo piano di gestione del rischio, su una pagina')],
  voce=["Il corso è diviso in dieci moduli e quarantasei lezioni. Ogni lezione dura pochi minuti e tratta un solo concetto.", "Prima ti spiego il perché, poi arrivano i numeri. Ogni formula è accompagnata da un esempio svolto, passo per passo.", "E alla fine del percorso avrai scritto il tuo piano di gestione del rischio, su una sola pagina."]),
 dict(tipo='tabella', titolo='I dieci moduli', intest=['Modulo', 'Di cosa parla'], k=[10], righe=[
   ['1 · Le basi', 'rischio per trade, stop, lotto, R'], ['2 · Misurare un sistema', 'expectancy, profit factor, campione'], ['3 · Drawdown e perdite', 'recuperi, serie, composizione'],
   ['4 · Dimensionare', 'rischio fisso, ATR, Kelly, correlazione'], ['5 · Simulare', 'Monte Carlo e probabilità di rovina'], ['6 · Disciplina', 'regole, limiti, checklist'],
   ['7 · Prop firm', 'limiti giornalieri e trailing'], ['8 · Gestire la posizione', 'break-even, scaglioni, strumenti'], ['9 · Tecniche avanzate', 'compounding, trailing, scaglioni, mitigazione, hedging'], ['10 · Il tuo piano', 'scrittura e revisione']],
  voce=["Ecco la mappa. Si parte dalle basi, poi si impara a misurare un sistema, a capire il drawdown e a dimensionare le posizioni. Poi si simula, si costruisce la disciplina, si affrontano le regole delle prop firm, e si gestisce la posizione aperta. Poi le tecniche avanzate: compounding, trailing stop, scaglioni, mitigazione e hedging. L'ultimo modulo è il tuo piano personale."]),
 dict(tipo='avviso', titolo='Un avviso importante', testo=["**Questo corso è educativo e non è consulenza finanziaria.**", "Il trading con leva, su forex, CFD e futures, comporta un rischio elevato: **puoi perdere tutto il capitale investito**.", "I numeri che vedrai sono esempi e simulazioni: non sono promesse di guadagno e non indicano risultati futuri.", "Nelle lezioni in cui parlo di strumenti Riskly lo dichiaro: **sono prodotti miei**."],
  voce=["Prima di iniziare, un avviso importante. Questo corso è educativo e non è consulenza finanziaria. Il trading con leva, su forex, CFD e futures, comporta un rischio elevato: puoi perdere tutto il capitale. I numeri che vedrai sono esempi e simulazioni, non promesse di guadagno e non indicano risultati futuri. E quando parlerò di strumenti Riskly, lo dichiarerò: sono prodotti miei."]),
 dict(tipo='citazione', testo='Non controlli il mercato. Controlli **quanto rischi**.', voce=["Cominciamo. Non controlli il mercato. Controlli quanto rischi."]),
])
