LEZIONE = dict(id='1.1', modulo='Modulo 1', modTitolo='Le basi', titolo='Perché il rischio viene prima della strategia', slide=[
 dict(tipo='titolo', kicker='LEZIONE 1.1', titolo='Perché il rischio viene **prima**', sotto='Due trader, la stessa strategia, due destini diversi.',
  voce=["Lezione uno punto uno. Perché il rischio viene prima della strategia."]),
 dict(tipo='punti', titolo='Il pensiero comune', punti=[('«Se trovo la strategia giusta, guadagno»', ''), ('Si cercano indicatori, pattern, segnali', ''), ('La domanda «quanto rischio?» arriva dopo, o mai', '')],
  voce=["La maggior parte delle persone pensa che il trading sia trovare la strategia giusta.", "Si studiano indicatori, pattern e segnali.", "E la domanda su quanto rischiare arriva dopo, quando arriva. Ed è l'ordine sbagliato."]),
 dict(tipo='confronto', titolo='Stessa strategia, rischio diverso', sx=dict(t='Trader B · rischia 1%', punti=[['Drawdown tipico', '−10%'], ['Capitale dopo 200 trade', '×1,65'], ['Casi sotto −50%', '~0%']]), dx=dict(t='Trader A · rischia 4%', punti=[['Drawdown tipico', '−35%'], ['Capitale dopo 200 trade', '×6,9'], ['Casi sotto −50%', '~10%']]),
  risultato='A guadagna di più sulla carta. Ma quanto male sopporta?',
  voce=["Prendiamo due trader con la stessa identica strategia. Vince il 45 per cento delle volte; quando vince guadagna 1,8 volte quello che rischia, quando perde ne perde una. Simulati su duecento operazioni, questi sono i risultati tipici.", "Il trader B rischia l'1 per cento a operazione. Il suo peggior momento tipico è un meno 10 per cento, e dopo duecento trade il capitale è circa 1,65 volte l'iniziale.", "Il trader A rischia il 4 per cento. Sulla carta guadagna molto di più, fino a quasi sette volte il capitale. Ma il suo drawdown tipico è meno 35 per cento, e in un caso su dieci supera il meno 50.", "La domanda quindi non è chi guadagna di più. È: quanti riescono a sopportare un meno 35 per cento senza cambiare piano, senza raddoppiare, senza fermarsi nel momento sbagliato?"]),
 dict(tipo='punti', titolo='Il rischio decide due cose', punti=[('Se sopravvivi', 'un rischio troppo alto trasforma una serie normale di perdite in una rovina'), ('Quanto soffri', 'anche senza rovina, un grande drawdown ti fa sbagliare le decisioni')],
  voce=["Il rischio per trade decide due cose.", "Se sopravvivi: un rischio troppo alto trasforma una normale serie di perdite in una rovina.", "E quanto soffri: anche senza rovina, un grande drawdown ti porta a sbagliare le decisioni. Il piano migliore sulla carta è inutile se non riesci a seguirlo."]),
 dict(tipo='punti', titolo='Le tre domande di questo corso', punti=['Quanto posso perdere al massimo su una singola operazione?', 'Quante perdite di fila posso reggere?', 'Quando mi fermo, prima che sia troppo tardi?'],
  voce=["Queste sono le tre domande a cui risponderemo, lezione dopo lezione.", "Quanto posso perdere al massimo su una singola operazione?", "Quante perdite di fila posso reggere?", "E quando mi fermo, prima che sia troppo tardi? Se alla fine hai tre risposte scritte e numeriche, hai fatto metà del lavoro."]),
 dict(tipo='citazione', testo='Prima di chiederti **quanto puoi guadagnare**, chiediti quanto puoi perdere.', voce=["Ricorda questa frase. Prima di chiederti quanto puoi guadagnare, chiediti quanto puoi perdere."]),
])
