LEZIONE = dict(id='1.2', modulo='Modulo 1', modTitolo='Le basi', titolo='Il rischio per trade', slide=[
 dict(tipo='titolo', kicker='LEZIONE 1.2', titolo='Il rischio **per trade**', sotto='Quanto del capitale sei disposto a perdere su una singola operazione.',
  voce=["Lezione uno punto due. Il rischio per trade."]),
 dict(tipo='punti', titolo='Cosa significa rischiare', punti=[('Rischio = quanto perdi se il trade va male', 'cioè se il prezzo arriva al tuo stop loss'), ('Si misura in percentuale del capitale', 'non in pip, non in lotti'), ('Si decide prima di entrare', 'mai a operazione già aperta')],
  voce=["Il rischio di un'operazione è quanto perdi se va male, cioè se il prezzo raggiunge il tuo stop loss.", "Lo misuriamo in percentuale del capitale. Non in pip, e non in lotti.", "E si decide prima di entrare, mai a operazione già aperta."]),
 dict(tipo='esempio', titolo='Un esempio concreto', righe=[['Capitale', '10.000 €'], ['Rischio per trade', '1%'], ['Perdita massima sul trade', '100 €']], risultato='Se il trade va male, perdi 100 €. Non un euro in più.',
  voce=["Facciamo un esempio. Hai un conto da diecimila euro.", "Decidi di rischiare l'uno per cento a operazione.", "Significa che la perdita massima accettata su un singolo trade è cento euro.", "Se va male, perdi cento euro. Non un euro di più. Questo è un numero che conosci prima di cliccare."]),
 dict(tipo='tabella', titolo='Quanto rischiare: un ordine di grandezza', intest=['Rischio', 'Su 10.000 €', 'Per chi'], righe=[['0,5%', '50 €', 'prudente, prop firm'], ['1%', '100 €', 'riferimento comune'], ['2%', '200 €', 'già alto'], ['5%', '500 €', 'molto aggressivo']], nota='Non esiste il numero giusto per tutti: dipende dal sistema e da quanto drawdown reggi.',
  voce=["Questi sono gli ordini di grandezza.", "Mezzo per cento è un rischio prudente, tipico di chi affronta una prop firm.", "L'uno per cento è il riferimento più comune.", "Il due per cento è già alto.", "Il cinque per cento è molto aggressivo: bastano poche perdite di fila per un grosso danno.", "Non esiste un numero giusto per tutti. Dipende dal tuo sistema e da quanto drawdown riesci davvero a sopportare. Lo calcoleremo nei prossimi moduli."]),
 dict(tipo='punti', titolo='Gli errori più comuni', punti=['Rischiare di più dopo una perdita per «rifarsi»', 'Rischiare di più quando ci si sente sicuri', 'Non sapere quanto si rischia finché non si è dentro'],
  voce=["Tre errori da evitare.", "Rischiare di più dopo una perdita per rifarsi.", "Rischiare di più quando ci si sente sicuri di un trade.", "E non sapere quanto si rischia finché non si è già dentro. Il rischio si fissa prima, con un numero, ogni volta."]),
 dict(tipo='citazione', testo='Il rischio è un numero che decidi **prima**, non un sentimento che provi **dopo**.', voce=["Il rischio è un numero che decidi prima, non un sentimento che provi dopo."]),
])
