LEZIONE = dict(id='1.3', modulo='Modulo 1', modTitolo='Le basi', titolo='Lo stop loss', slide=[
 dict(tipo='titolo', kicker='LEZIONE 1.3', titolo='Lo **stop loss**', sotto='Dove si mette e perché non si sposta.',
  voce=["Lezione uno punto tre. Lo stop loss."]),
 dict(tipo='punti', titolo='A cosa serve', punti=[('È il prezzo in cui l\'idea è sbagliata', 'non il prezzo in cui «ti fa male»'), ('Trasforma una perdita ignota in una perdita nota', 'è lui che rende il rischio un numero'), ('Senza stop non esiste rischio per trade', 'esiste solo la speranza')],
  voce=["Lo stop loss non è il prezzo in cui ti fa male. È il prezzo in cui la tua idea è sbagliata.", "Trasforma una perdita ignota in una perdita nota. È lui che rende il rischio un numero.", "Senza stop non esiste un rischio per trade. Esiste solo la speranza."]),
 dict(tipo='punti', titolo='Dove si mette', punti=[('Oltre un livello che invalida l\'idea', 'sotto un minimo, sopra un massimo, fuori da un range'), ('Con un margine per il rumore', 'il prezzo oscilla: uno stop troppo vicino salta per caso'), ('Mai scelto in base a quanto vuoi rischiare', 'prima si sceglie lo stop, poi si adatta il lotto')],
  voce=["Dove si mette? Oltre un livello che invalida l'idea: sotto un minimo, sopra un massimo, fuori da un range.", "Con un margine per il rumore. Il prezzo oscilla, e uno stop troppo vicino salta per caso.", "E soprattutto, non si sceglie in base a quanto vuoi rischiare. Prima si sceglie lo stop dove ha senso, e poi si adatta la dimensione dell'operazione."]),
 dict(tipo='confronto', titolo='Due modi di ragionare', sx=dict(t='Giusto', punti=[['1. Dove invalida l\'idea?', 'stop'], ['2. Quanto rischio?', '1%'], ['3. Quindi il lotto è', 'calcolato']]), dx=dict(t='Sbagliato', punti=[['1. Lotto che mi piace', 'a occhio'], ['2. Stop dove «ci sta»', 'comodo'], ['3. Rischio', 'quel che viene']]),
  risultato='Lo stop comanda. Il lotto si adatta.',
  voce=["Ci sono due modi di ragionare.", "Il modo giusto: prima chiedi dove l'idea è invalidata, quello è lo stop. Poi decidi quanto rischiare, per esempio l'uno per cento. E solo a quel punto il lotto viene calcolato di conseguenza.", "Il modo sbagliato: scegli un lotto che ti piace, metti lo stop dove ci sta comodo, e il rischio è quello che viene.", "Lo stop comanda, il lotto si adatta."]),
 dict(tipo='punti', titolo='La regola che protegge', punti=['Lo stop si può stringere, mai allargare', 'Se il prezzo si avvicina, non spostarlo «solo un po\'»', 'Se non accetti la perdita, non entrare'],
  voce=["Una regola che protegge. Lo stop può essere stretto, ma mai allargato.", "Se il prezzo si avvicina, non spostarlo solo un po'. Ogni volta che lo fai, hai cambiato il rischio senza decidere.", "Se non sei pronto ad accettare quella perdita, la soluzione è non entrare."]),
 dict(tipo='citazione', testo='Lo stop non è il **costo** del trading. È il suo **prezzo d\'ingresso**.', voce=["Lo stop non è il costo del trading. È il suo prezzo d'ingresso."]),
])
