from h import *
LEZIONE = L('1.4', 'Modulo 1', 'Le basi', 'Lotto, pip e dimensione della posizione', [
 T('LEZIONE 1.4', 'Quanto **comprare**: il lotto', 'Dallo stop e dal rischio alla dimensione dell\'operazione.', "Lezione uno punto quattro. Lotto, pip e dimensione della posizione."),
 P('Tre parole da conoscere', [('Pip', 'la più piccola unità di movimento che si usa: sul cambio euro dollaro, la quarta cifra decimale'), ('Lotto', 'la dimensione dell\'operazione; un lotto standard sono centomila unità di valuta'), ('Valore del pip', 'quanto guadagni o perdi per ogni pip di movimento')],
  ["Tre parole da conoscere prima di calcolare.", "Il pip: la più piccola unità di movimento di uso comune. Sul cambio euro dollaro è la quarta cifra decimale.", "Il lotto: la dimensione dell'operazione. Un lotto standard sono centomila unità della valuta base.", "E il valore del pip: quanto guadagni o perdi per ogni pip di movimento. Su euro dollaro, con un lotto standard e un conto in dollari, vale circa dieci dollari."]),
 F('La formula della dimensione', 'Lotti = Rischio in € ÷ ( Stop in pip × Valore del pip )', [('Rischio', 'quanto accetti di perdere, in euro'), ('Stop', 'distanza tra ingresso e stop loss, in pip'), ('Valore pip', 'per un lotto; circa 10 su EURUSD')],
  ["Ecco la formula che collega tutto.", "I lotti si ottengono dividendo il rischio in euro per lo stop in pip moltiplicato per il valore del pip.", "Il rischio è quanto accetti di perdere, in euro. Lo hai deciso nella lezione uno punto due.", "Lo stop è la distanza tra ingresso e stop loss, in pip. L'hai deciso nella lezione precedente.", "Il valore del pip dipende dallo strumento: circa dieci per un lotto su euro dollaro. Il tuo broker o la tua piattaforma lo mostrano."]),
 EX('Esempio svolto', [['Capitale', '10.000 €'], ['Rischio per trade', '1% = 100 €'], ['Stop', '25 pip'], ['Valore del pip', '10 € per lotto'], ['Lotti', '100 ÷ (25 × 10)']], risultato='= 0,4 lotti', k=[2,4,5,6],
  voce=["Facciamo i conti. Capitale diecimila euro, rischio l'uno per cento, quindi cento euro.", "Lo stop è di venticinque pip, il valore del pip è dieci euro per lotto.", "Cento diviso venticinque per dieci: zero virgola quattro lotti.", "Con quattro decimi di lotto, se il prezzo arriva allo stop perdi esattamente cento euro."]),
 CF('Stesso rischio, stop diverso', dict(t='Stop 25 pip', punti=[['Rischio', '100 €'], ['Lotti', '0,40']]), dict(t='Stop 50 pip', punti=[['Rischio', '100 €'], ['Lotti', '0,20']]),
  ["Cosa succede se lo stop è più largo?", "Con lo stop a venticinque pip, il lotto è zero virgola quaranta.", "Con lo stop a cinquanta pip, il lotto dimezza: zero virgola venti.", "Il rischio in euro è identico: cento. Cambia il lotto, non la perdita. Ecco perché lo stop comanda."], 'Stop più largo → lotto più piccolo. Il rischio resta 100 €.'),
 P('Controlli prima di cliccare', ['Il lotto è arrotondato per difetto, mai per eccesso', 'Il valore del pip è quello del tuo strumento e del tuo conto', 'Spread e commissioni non sono nello stop: il rischio reale è un po\' più alto'],
  ["Tre controlli prima di cliccare.", "Il lotto si arrotonda per difetto, mai per eccesso.", "Il valore del pip deve essere quello del tuo strumento e della valuta del tuo conto: su un conto in euro non è esattamente dieci.", "E ricorda che spread e commissioni non sono dentro lo stop: il rischio reale è sempre un po' più alto di quello calcolato."]),
 Q('Il lotto non si **sceglie**. Si **calcola**.', "Il lotto non si sceglie. Si calcola."),
])
