from h import *
LEZIONE = L('1.6', 'Modulo 1', 'Le basi', 'Win rate e win rate di pareggio', [
 T('LEZIONE 1.6', 'Quante volte devi **vincere**?', 'Il win rate non dice niente senza il rapporto rischio/rendimento.', "Lezione uno punto sei. Win rate e win rate di pareggio."),
 P('Cos\'è il win rate', [('Operazioni vinte ÷ operazioni totali', 'quindi 45 vinte su 100 sono un win rate del 45%'), ('Non dice se il sistema guadagna', 'un 70% può perdere, un 35% può guadagnare'), ('Va letto insieme al RR', 'è la coppia che decide')],
  ["Il win rate è la percentuale di operazioni vinte sul totale. Quarantacinque vinte su cento sono un win rate del quarantacinque per cento.", "Da solo non dice se il sistema guadagna. Un settanta per cento può perdere soldi, un trentacinque per cento può guadagnarne.", "Va sempre letto insieme al rapporto rischio rendimento: è la coppia che decide."]),
 F('Il win rate di pareggio', 'WR pareggio = 1 ÷ (1 + RR)', [('RR', 'guadagno medio ÷ perdita media'), ('WR pareggio', 'percentuale di vittorie sotto la quale perdi')],
  ["Esiste una formula semplice: il win rate di pareggio. È la percentuale minima di vittorie sotto la quale il sistema perde.", "Si calcola come uno diviso uno più RR.", "Dove RR è il guadagno medio diviso la perdita media. Se vinci più spesso di così, guadagni; se vinci meno, perdi."]),
 TB('Win rate di pareggio per RR', ['RR', 'Pareggio'], [['0,5', '67%'], ['1', '50%'], ['1,5', '40%'], ['2', '33%'], ['3', '25%']],
  ["Ecco i valori principali.", "Con RR zero virgola cinque devi vincere due volte su tre solo per pareggiare.", "Con RR uno: la metà delle volte.", "Con RR uno virgola cinque: il quaranta per cento.", "Con RR due: un terzo delle volte.", "Con RR tre: una volta su quattro."], nota='Prima di spread e commissioni.'),
 G('La curva del pareggio', 'winrate_rr', ["Lo stesso concetto in un grafico. Sulla curva il sistema è in pareggio. Sopra la curva, cioè con un win rate più alto, guadagna. Sotto perde.", "Più sali con il RR, più la soglia scende. Ma ricorda: un RR più alto spesso significa un win rate più basso, quindi devi controllare il tuo caso reale."], 'Sopra la curva: guadagni. Sotto: perdi.'),
 EX('Il tuo sistema, misurato', [['Win rate misurato', '45%'], ['RR medio', '1,8'], ['Pareggio con RR 1,8', '1 ÷ 2,8 = 36%'], ['Margine', '45% − 36% = 9 punti']], risultato='Il sistema ha un margine positivo', k=[1,2,3,4,5],
  voce=["Mettiamo insieme le due cose su un sistema reale.", "Hai misurato un win rate del quarantacinque per cento.", "Con un RR medio di uno virgola otto, il win rate di pareggio è uno diviso due virgola otto: circa trentasei per cento.", "Vinci il quarantacinque, la soglia è trentasei: hai nove punti percentuali di margine.", "Il sistema ha un margine positivo. Nella prossima parte del corso lo trasformeremo in un solo numero: l'expectancy."]),
 *ES('win rate di pareggio', [['RR del sistema', '3'], ['Win rate misurato', '28%'], ['Domanda', 'sei sopra o sotto il pareggio?']], [['Pareggio', '1 ÷ (1 + 3) = 25%'], ['Margine', '28% − 25% = +3 punti']], 'Sopra il pareggio, ma di poco',
  ["Esercizio. Il tuo sistema ha RR tre e un win rate misurato del ventotto per cento. Sei sopra o sotto il pareggio?", "Il pareggio è uno diviso quattro: venticinque per cento. Sei a ventotto, quindi sopra di tre punti. Ma è un margine sottile: su pochi trade potrebbe essere solo rumore, ne parliamo nel modulo due."]),
 RIEP(['Win rate = vinte ÷ totali', 'Pareggio = 1 ÷ (1 + RR)', 'Vincere il 35% può bastare con RR alto; vincere il 70% può non bastare con RR basso'], ["Riassumiamo.", "Win rate è vinte diviso totali.", "Il pareggio è uno diviso uno più RR.", "Vincere il trentacinque per cento può bastare con RR alto, e vincere il settanta può non bastare con RR basso."]),
 Q('Il win rate da solo è una **vanità**. La coppia win rate e RR è un **fatto**.', "Il win rate da solo è una vanità. La coppia win rate e RR è un fatto."),
])
