from h import *
LEZIONE = L('1.7', 'Modulo 1', 'Le basi', 'L\'unità R', [
 T('LEZIONE 1.7', 'Misurare tutto in **R**', 'Un linguaggio comune per ogni operazione, su ogni mercato.', "Lezione uno punto sette. L'unità R."),
 P('Il problema dei pip e degli euro', [('Un trade da +50 pip su un lotto grosso e uno da +20 su uno piccolo', 'quale è andato meglio?'), ('Gli euro dipendono dal capitale', 'e dal lotto che hai deciso quel giorno'), ('I pip dipendono dallo strumento', 'cinquanta pip non valgono lo stesso ovunque')],
  ["Come confronti due operazioni? Una ha fatto più cinquanta pip con un lotto grosso, un'altra più venti pip con uno piccolo. Quale è andata meglio?", "Gli euro dipendono dal capitale e dal lotto che hai deciso quel giorno.", "I pip dipendono dallo strumento: cinquanta pip non valgono lo stesso su tutti i mercati."]),
 P('La soluzione: l\'unità R', [('1 R = il rischio iniziale di quel trade', 'cioè la distanza dallo stop, in valore'), ('Ogni risultato si esprime in multipli di R', '+2 R: hai guadagnato il doppio di quello che rischiavi'), ('Stop preso = −1 R', 'e se lo stop è stato rispettato, sempre −1 R')],
  ["La soluzione è misurare tutto in R.", "Un R è il rischio iniziale di quell'operazione, cioè la distanza dallo stop, espressa in valore.", "Ogni risultato diventa un multiplo di R. Più due R significa che hai guadagnato il doppio di quello che rischiavi.", "Se prendi lo stop, il risultato è meno un R. Sempre, a qualsiasi strumento e a qualsiasi dimensione. Negli esempi di prezzo continueremo a usare i pip, che sono più immediati. L'R lo useremo per le statistiche, dove serve confrontare operazioni con stop diversi."]),
 TB('Quattro operazioni, linguaggi diversi', ['Trade', 'Euro', 'Pip', 'R'], [['Oro, lotto 0,1', '+180 €', '+60', '+1,8 R'], ['EURUSD, lotto 0,4', '−100 €', '−25', '−1 R'], ['Indice, lotto 2', '+150 €', '+30', '+1,5 R'], ['GBPUSD, lotto 0,2', '−100 €', '−50', '−1 R']],
  ["Guarda quattro operazioni su strumenti diversi.", "Un trade sull'oro: più centoottanta euro, che per un rischio di cento euro vuol dire più uno virgola otto R.", "Uno su EURUSD che va allo stop: meno cento euro, meno un R.", "Un trade su un indice: più centocinquanta euro, più uno virgola cinque R.", "E uno su GBPUSD allo stop: meno un R. Euro, pip e strumenti sono diversi, ma in R diventano tutti confrontabili."], nota='Rischio iniziale di 100 € per ogni trade.'),
 EX('Il bilancio in R', [['Trade 1', '+1,8 R'], ['Trade 2', '−1 R'], ['Trade 3', '+1,5 R'], ['Trade 4', '−1 R'], ['Trade 5', '−1 R']], risultato='Totale: +0,3 R', k=[0,1,2,3,4,5,6],
  voce=["Sommiamo una serie di operazioni in R.", "Più uno virgola otto.", "Meno uno.", "Più uno virgola cinque.", "Meno uno.", "E ancora meno uno.", "Totale: più zero virgola tre R. Se il tuo R vale cento euro, sono trenta euro. Ma soprattutto: lo stesso conto vale su qualsiasi capitale."]),
 N('Perché funziona', '± R', ["Misurare in R fa tre cose. Ti obbliga a definire il rischio prima di entrare, perché senza stop non esiste R.", "Ti permette di confrontare sistemi, strumenti e periodi senza farti ingannare dal capitale.", "E ti prepara al prossimo modulo: le statistiche di un sistema, come expectancy e profit factor, si calcolano tutte in R."], "Un solo linguaggio per tutti i trade"),
 *ES('somma in R', [['Risultati', '+2 R, −1 R, −1 R, +0,5 R, −1 R, +3 R'], ['Domanda', 'totale in R? E con R = 80 €?']], [['Somma', '2 − 1 − 1 + 0,5 − 1 + 3'], ['Totale', '+2,5 R'], ['In euro', '2,5 × 80 = 200 €']], 'Totale: +2,5 R = 200 €',
  ["Esercizio. Sei operazioni: più due R, meno uno, meno uno, più zero virgola cinque, meno uno, più tre. Quanto fai in R? E in euro se un R vale ottanta euro?", "Due meno uno meno uno fa zero; più zero virgola cinque fa mezzo; meno uno fa meno mezzo; più tre fa due virgola cinque. Totale più due virgola cinque R, che a ottanta euro per R sono duecento euro."]),
 RIEP(['1 R = il rischio iniziale del trade', 'Ogni risultato è un multiplo di R; stop preso = −1 R', 'In R puoi confrontare strumenti, dimensioni e periodi'], ["Riassumiamo.", "Un R è il rischio iniziale del trade.", "Ogni risultato è un multiplo di R, e uno stop preso vale meno un R.", "In R puoi confrontare strumenti, dimensioni e periodi diversi. Con questo il primo modulo è completo: da qui si passa a misurare un sistema."]),
 Q('Se non sai quanto **rischiavi**, non sai quanto hai **guadagnato**.', "Se non sai quanto rischiavi, non sai quanto hai guadagnato."),
])
