from h import *
LEZIONE = L('2.1', 'Modulo 2', 'Misurare un sistema', 'L\'expectancy', [
 T('LEZIONE 2.1', 'L\'**expectancy**', 'Quanto guadagna, in media, ogni operazione del tuo sistema.', "Lezione due punto uno. L'expectancy."),
 P('La domanda giusta', [('Non «ho vinto oggi?»', 'una singola operazione è quasi sempre rumore'), ('Ma «cosa succede in media, su molte operazioni?»', 'un sistema si giudica sul lungo periodo'), ('L\'expectancy è quella media', 'quanto vale in R una operazione tipica')],
  ["Un sistema non si giudica da un trade e nemmeno da una giornata. Si giudica da cosa succede in media su molte operazioni.", "Quella media si chiama expectancy, aspettativa.", "Ti dice quanto vale, in R, una operazione tipica del tuo sistema."]),
 F('La formula', 'E = ( W × Gm ) − ( 1 − W ) × Pm', [('W', 'percentuale di operazioni vinte'), ('Gm', 'guadagno medio, in R'), ('Pm', 'perdita media, in R (di solito 1)')],
  ["La formula è semplice. L'expectancy è la probabilità di vincere per il guadagno medio, meno la probabilità di perdere per la perdita media.", "W è il win rate.", "Gm è il guadagno medio quando vinci, espresso in R.", "E Pm la perdita media, in R, che di solito è uno se rispetti sempre lo stop."]),
 EX('Esempio svolto', [['Win rate W', '45%'], ['Guadagno medio', '1,8 R'], ['Perdita media', '1 R'], ['0,45 × 1,8', '0,81'], ['0,55 × 1', '0,55'], ['Expectancy', '0,81 − 0,55']], risultato='E = +0,26 R per trade', k=[0,1,2,3,4,5,6,7],
  voce=["Calcoliamolo su un sistema.", "Win rate quarantacinque per cento.", "Guadagno medio uno virgola otto R.", "Perdita media un R.", "Zero virgola quarantacinque per uno virgola otto fa zero virgola ottantuno.", "Zero virgola cinquantacinque per uno fa zero virgola cinquantacinque.", "Zero virgola ottantuno meno zero virgola cinquantacinque dà più zero virgola ventisei.", "Questo sistema vale, in media, zero virgola ventisei R per operazione."]),
 EX('Cosa significa in pip e in euro', [['Expectancy', '+0,26 R'], ['Con uno stop di 25 pip', '+6,5 pip a trade'], ['Con 0,4 lotti (10 € a pip per lotto)', '+26 € a trade'], ['Su 100 trade', '+650 pip = +2.600 €']], risultato='In media. Non è una promessa.', k=[1,2,3,4,5],
  voce=["E in pip? Con uno stop di venticinque pip, zero virgola ventisei R sono sei virgola cinque pip a operazione.", "Con zero virgola quattro lotti, un pip vale quattro euro, quindi circa ventisei euro a trade.", "Su cento operazioni, seicentocinquanta pip, circa duemilaseicento euro.", "Attenzione alle parole: in media. Non è una promessa. Il risultato reale di cento trade può essere molto diverso, ed è proprio per questo che nei prossimi moduli lo simuleremo.", "Il segno dell'expectancy è l'informazione più importante. Se è positiva, il sistema ha un vantaggio. Se è zero o negativa, nessuna gestione del rischio lo salva."]),
 TB('Tre sistemi a confronto', ['Sistema', 'Win rate', 'Guadagno medio', 'Expectancy'], [['A · trend', '35%', '3 R', '+0,40 R'], ['B · reversal', '60%', '0,8 R', '+0,08 R'], ['C · ingannevole', '50%', '0,8 R', '−0,10 R']],
  ["Confrontiamo tre sistemi. Tutti con perdita media di un R.", "Il sistema A vince solo il trentacinque per cento, ma quando vince guadagna tre R: expectancy più zero virgola quaranta.", "Il sistema B vince il sessanta per cento, ma guadagna solo zero virgola otto R: expectancy appena più zero virgola zero otto.", "Il sistema C vince la metà delle volte, ma guadagna poco: expectancy negativa, meno zero virgola dieci. Sembra un buon sistema perché vince spesso, ma perde nel tempo."], nota='Chi vince più spesso non è per forza il migliore.'),
 G('Expectancy e varianza', 'expectancy', ["Questo grafico mostra otto serie simulate di cento trade dello stesso sistema, quello da più zero virgola ventisei R.", "La linea tratteggiata è la media attesa. Ma le singole serie si allontanano molto da essa: alcune finiscono in perdita, altre molto più su. Ecco perché una expectancy positiva non esclude periodi lunghi sotto zero."], 'Stesso sistema, otto serie diverse di 100 trade.'),
 *ES('expectancy', [['Win rate', '40%'], ['Guadagno medio', '2,5 R'], ['Perdita media', '1 R']], [['0,40 × 2,5', '1,00'], ['0,60 × 1', '0,60'], ['Differenza', '+0,40 R']], 'E = +0,40 R per trade',
  ["Esercizio. Win rate quaranta per cento, guadagno medio due virgola cinque R, perdita media un R. Qual è l'expectancy?", "Zero virgola quaranta per due virgola cinque fa uno. Zero virgola sessanta per uno fa zero virgola sessanta. La differenza: più zero virgola quaranta R."]),
 RIEP(['Expectancy = W × guadagno medio − (1 − W) × perdita media', 'Si misura in R: quanto vale in media un trade', 'Positiva = vantaggio; zero o negativa = nessuna gestione del rischio lo salva'], ["Riassumiamo.", "L'expectancy è la media in R di un trade.", "Si calcola con win rate, guadagno medio e perdita media.", "Se è positiva c'è un vantaggio. Se è zero o negativa, nessuna gestione del rischio può salvare il sistema."]),
 Q('La gestione del rischio protegge un vantaggio. Non lo **crea**.', "La gestione del rischio protegge un vantaggio. Non lo crea."),
])
