from h import *
LEZIONE = L('2.2', 'Modulo 2', 'Misurare un sistema', 'Il profit factor', [
 T('LEZIONE 2.2', 'Il **profit factor**', 'Quanto guadagni per ogni euro che perdi.', "Lezione due punto due. Il profit factor."),
 F('La definizione', 'PF = Guadagni lordi ÷ Perdite lorde', [('Guadagni lordi', 'somma di tutte le operazioni vinte'), ('Perdite lorde', 'somma, in valore assoluto, di tutte le perse'), ('PF > 1', 'il sistema è in attivo')],
  ["Il profit factor risponde a una domanda semplice: quanto guadagni per ogni euro che perdi?", "Si calcola dividendo la somma dei guadagni lordi per la somma delle perdite lorde.", "I guadagni sono la somma di tutte le operazioni vinte; le perdite, in valore assoluto, la somma di tutte quelle perse.", "Se il profit factor è sopra uno, il sistema è in attivo."]),
 EX('Esempio su 100 trade', [['Vinte', '45 × 1,8 R = 81 R'], ['Perse', '55 × 1 R = 55 R'], ['PF', '81 ÷ 55']], risultato='PF = 1,47', k=[1,2,3,4],
  voce=["Prendiamo un sistema su cento trade.", "Quarantacinque vinte da uno virgola otto R: ottantuno R di guadagni.", "Cinquantacinque perse da un R: cinquantacinque R di perdite.", "Ottantuno diviso cinquantacinque: uno virgola quarantasette. Per ogni euro perso, ne guadagni uno virgola quarantasette."]),
 TB('Come si legge', ['PF', 'Lettura'], [['< 1', 'sistema perdente'], ['1,0 – 1,3', 'margine sottile: i costi lo erodono'], ['1,3 – 2,0', 'zona sana per molti sistemi'], ['> 2,5', 'attenzione: spesso pochi trade o dati troppo ottimizzati']],
  ["Come si legge il profit factor. Sotto uno: il sistema perde.", "Tra uno e uno virgola tre: il margine è sottile e i costi possono mangiarselo.", "Tra uno virgola tre e due: una zona sana per molti sistemi.", "Sopra due e mezzo: occhio. Spesso significa pochi trade, oppure un sistema ottimizzato troppo sul passato. Un numero troppo bello è più un campanello d'allarme che una buona notizia."], nota='Indicazioni generali, non soglie ufficiali.', k=[1,2,3,5]),
 CF('Expectancy e profit factor', dict(t='Expectancy', punti=[['Cosa dice', 'media per trade'], ['Unità', 'R'], ['Soglia', '> 0']]), dict(t='Profit factor', punti=[['Cosa dice', 'guadagni / perdite'], ['Unità', 'rapporto'], ['Soglia', '> 1']]),
  ["Come stanno insieme i due indicatori?", "L'expectancy ti dice la media per trade, in R. È positiva sopra zero.", "Il profit factor ti dice il rapporto tra guadagni e perdite. È in attivo sopra uno.", "Sono due modi di guardare la stessa cosa: se uno è in attivo, lo è anche l'altro. Usali insieme perché la expectancy ti dà la dimensione del vantaggio, il profit factor ti dà un colpo d'occhio."], k=[0,1,2,2]),
 *ES('profit factor', [['Vinte', '40 trade da 1,5 R'], ['Perse', '60 trade da 1 R']], [['Guadagni', '40 × 1,5 = 60 R'], ['Perdite', '60 × 1 = 60 R'], ['PF', '60 ÷ 60']], 'PF = 1,0: pareggio, prima dei costi',
  ["Esercizio. Quaranta trade vinti da uno virgola cinque R e sessanta persi da un R. Qual è il profit factor?", "Quaranta per uno virgola cinque fa sessanta R. Sessanta per uno fa sessanta R. Sessanta diviso sessanta: uno. Sei in pareggio, e dopo i costi saresti in perdita. Ecco perché guardare il win rate da solo inganna."]),
 RIEP(['PF = guadagni lordi ÷ perdite lorde', 'Sopra 1 il sistema è in attivo; 1,3–2 è una zona sana', 'Un PF troppo alto è spesso un campanello d\'allarme'], ["Riassumiamo.", "Il profit factor è guadagni lordi diviso perdite lorde.", "Sopra uno il sistema è in attivo, e tra uno virgola tre e due è una zona sana.", "Un profit factor troppo alto è spesso un campanello d'allarme, non una buona notizia."]),
 Q('Un risultato **troppo bello** va sempre controllato due volte.', "Un risultato troppo bello va sempre controllato due volte."),
])
