from h import *
LEZIONE = L('2.3', 'Modulo 2', 'Misurare un sistema', 'Campione e rumore', [
 T('LEZIONE 2.3', 'Campione e **rumore**', 'Quanti trade servono per fidarsi dei numeri.', "Lezione due punto tre. Campione e rumore."),
 P('Il problema dei pochi trade', [('Venti trade vinti su trenta sembrano un sistema', 'ma una moneta può fare lo stesso'), ('Il caso genera serie bellissime e serie terribili', 'senza che il sistema c\'entri'), ('Servono abbastanza dati per distinguere vantaggio e fortuna', 'quanti? Vediamo')],
  ["Venti trade vinti su trenta sembrano un grande sistema. Ma anche il caso, ogni tanto, produce serie così.", "Il caso genera serie bellissime e serie terribili senza che il sistema c'entri.", "Per distinguere un vantaggio dalla fortuna servono abbastanza dati. Vediamo quanti."]),
 TB('Quanto è incerto il win rate', ['Trade', 'Win rate misurato', 'Incertezza (95%)'], [['30', '45%', '± 18 punti'], ['100', '45%', '± 10 punti'], ['400', '45%', '± 5 punti']],
  ["Supponiamo che il tuo vero win rate sia quarantacinque per cento. Cosa misureresti?", "Con trenta trade, il valore misurato può cadere ovunque tra circa il ventisette e il sessantatré per cento. Un'incertezza di diciotto punti in più o in meno.", "Con cento trade, circa dieci punti in più o in meno.", "Con quattrocento, circa cinque punti. Solo qui il numero comincia a essere affidabile."], nota='Intervalli indicativi, approssimati.'),
 TB('E l\'expectancy?', ['Trade', 'Expectancy vera', 'Misurata tra circa'], [['30', '+0,26 R', '−0,24 e +0,76'], ['100', '+0,26 R', '−0,01 e +0,53'], ['400', '+0,26 R', '+0,12 e +0,40']],
  ["Per l'expectancy è peggio. Prendiamo il sistema da più zero virgola ventisei R.", "Con trenta trade, la misura può cadere tra meno zero virgola ventiquattro e più zero virgola settantasei: non sai nemmeno se il sistema è in attivo.", "Con cento trade, tra circa zero e più zero virgola cinquantatré. Siamo al limite.", "Solo con quattrocento trade si esclude lo zero. Ecco perché venti o trenta operazioni non dimostrano niente."], nota='Stima su un sistema con 45% di vincite e +1,8 / −1 R.'),
 P('Cosa fare in pratica', [('Raccogli almeno 100 trade prima di giudicare', 'meglio 200 o più'), ('Non cambiare le regole dopo 10 perdite', 'a meno che sia un errore di esecuzione, non di risultato'), ('Dividi: demo o rischio minimo per raccogliere dati', 'i dati costano meno del capitale')],
  ["Cosa fare allora? Raccogli almeno cento trade prima di giudicare un sistema, meglio duecento o più.", "Non cambiare le regole dopo dieci perdite, a meno che tu abbia individuato un errore di esecuzione, non di risultato.", "E per raccogliere dati usa rischio minimo o un conto demo: i dati costano meno del capitale."]),
 *ES('quanti trade', [['Test', '20 trade, 14 vinti'], ['Domanda', 'è una prova del vantaggio?']], [['Win rate', '70%'], ['Campione', 'solo 20 trade'], ['Incertezza', 'circa ± 20 punti']], 'No: è compatibile con un win rate vero del 50% o poco più',
  ["Esercizio. Hai fatto venti trade e ne hai vinti quattordici, il settanta per cento. È una prova che il sistema funziona?", "No. Con venti trade l'incertezza è di circa venti punti in entrambe le direzioni. Il risultato è compatibile con un win rate vero intorno al cinquanta per cento, e anche meno se hai avuto fortuna. Per concludere serve molto più campione."]),
 RIEP(['Pochi trade = molto rumore', 'Per giudicare un sistema servono almeno ~100 trade, meglio 200+', 'Non cambiare le regole per una serie di perdite'], ["Riassumiamo.", "Con pochi trade c'è molto rumore.", "Per giudicare un sistema servono almeno cento operazioni, meglio duecento o più.", "E le regole non si cambiano per una serie di perdite."]),
 Q('Dieci trade sono una **storia**. Mille trade sono una **statistica**.', "Dieci trade sono una storia. Mille trade sono una statistica."),
])
