from h import *
LEZIONE = L('2.4', 'Modulo 2', 'Misurare un sistema', 'I costi: spread, commissioni e slippage', [
 T('LEZIONE 2.4', 'I **costi** nascosti', 'Spread, commissioni e slippage: quanto pesano davvero.', "Lezione due punto quattro. I costi: spread, commissioni e slippage."),
 P('I tre costi', [('Spread', 'la differenza tra prezzo di acquisto e di vendita: lo paghi entrando'), ('Commissioni', 'una cifra per lotto, tipica dei conti con spread ridotto'), ('Slippage', 'la differenza tra il prezzo che volevi e quello che ottieni, soprattutto con notizie e stop')],
  ["Tre costi riducono il tuo risultato.", "Lo spread: la differenza tra prezzo di acquisto e di vendita. Lo paghi appena entri.", "Le commissioni: una cifra per lotto, tipica dei conti con spread ridotto.", "Lo slippage: la differenza tra il prezzo che volevi e quello che ottieni, soprattutto durante le notizie e quando scatta uno stop."]),
 F('Il vantaggio per trade, in pip', 'Netto = ( Expectancy × Stop ) − Costi', [('Expectancy', 'in R, per esempio +0,26'), ('Stop', 'in pip: lo stop che usi'), ('Costi', 'spread + commissioni + slippage, in pip')],
  ["Per capire quanto pesano, traduci tutto in pip.", "Il vantaggio netto per trade, in pip, è l'expectancy per lo stop, meno i costi.", "L'expectancy, in R, per esempio zero virgola ventisei. Moltiplicata per lo stop dà il guadagno medio lordo in pip.", "Lo stop è quello che usi, in pip.", "E i costi sono spread, commissioni e slippage, sempre in pip. Un costo fisso pesa poco se lo stop è lontano, e molto se è vicino."], k=[1,1,2,3,4]),
 TB('Lo stesso costo (1,5 pip), stop diversi', ['Stop', 'Vantaggio lordo', 'Costi', 'Netto'], [['50 pip', '+13 pip', '−1,5 pip', '+11,5 pip'], ['25 pip', '+6,5 pip', '−1,5 pip', '+5 pip'], ['10 pip', '+2,6 pip', '−1,5 pip', '+1,1 pip'], ['5 pip', '+1,3 pip', '−1,5 pip', '−0,2 pip']],
  ["Guarda cosa succede con un costo di uno virgola cinque pip, tra spread e commissione, e un sistema da più zero virgola ventisei R.", "Con uno stop a cinquanta pip, il vantaggio lordo è tredici pip. Tolti i costi, restano undici virgola cinque.", "Con venticinque pip, il vantaggio lordo è sei virgola cinque. Restano cinque pip: i costi ne mangiano già un quarto.", "Con dieci pip il lordo è due virgola sei pip, e ne restano uno virgola uno: più della metà del vantaggio è sparita.", "Con cinque pip il lordo è uno virgola tre, i costi uno virgola cinque: il risultato è negativo. Il vantaggio è sparito."], nota='Sistema di esempio: expectancy +0,26 R.'),
 P('Conseguenze pratiche', [('Gli stop molto corti sono sensibili ai costi', 'lo scalping richiede costi bassissimi e vantaggio alto'), ('Misura i costi nel tuo conto reale', 'non usare i dati del sito del broker'), ('Includi i costi nel test del sistema', 'altrimenti l\'expectancy che vedi è più alta di quella vera')],
  ["Tre conseguenze pratiche.", "Gli stop molto corti sono molto sensibili ai costi. Lo scalping richiede costi bassissimi e un vantaggio alto.", "Misura i costi sul tuo conto reale, non fidarti dei dati pubblicitari del broker.", "E includi sempre i costi quando testi un sistema: altrimenti l'expectancy che vedi è più alta di quella vera."]),
 *ES('costi in pip', [['Stop', '20 pip'], ['Spread + commissione', '2 pip'], ['Expectancy lorda', '+0,30 R']], [['Vantaggio lordo', '0,30 × 20 = 6 pip'], ['Costi', '− 2 pip'], ['Netto', '4 pip  (= +0,20 R)']], 'Netto = +4 pip per trade',
  ["Esercizio. Stop venti pip, costo due pip, expectancy lorda zero virgola trenta R. Quanti pip ti restano a trade?", "Zero virgola trenta per venti: sei pip lordi. Meno due di costi: quattro pip netti, che corrispondono a zero virgola venti R. Un terzo del vantaggio è andato in costi."]),
 RIEP(['Spread, commissioni e slippage riducono ogni trade', 'Si convertono in R dividendo per lo stop', 'Stop corti = costi pesanti: includili sempre nei calcoli'], ["Riassumiamo.", "Spread, commissioni e slippage riducono ogni trade.", "Si convertono in R dividendo per lo stop.", "Stop corti significano costi pesanti: includili sempre nei calcoli."]),
 Q('Il vantaggio che non **sopravvive ai costi** non è un vantaggio.', "Il vantaggio che non sopravvive ai costi non è un vantaggio."),
])
