from h import *
LEZIONE = L('2.4', 'Modulo 2', 'Misurare un sistema', 'I costi: spread, commissioni e slippage', [
 T('LEZIONE 2.4', 'I **costi** nascosti', 'Spread, commissioni e slippage: quanto pesano davvero.', "Lezione due punto quattro. I costi: spread, commissioni e slippage."),
 P('I tre costi', [('Spread', 'la differenza tra prezzo di acquisto e di vendita: lo paghi entrando'), ('Commissioni', 'una cifra per lotto, tipica dei conti con spread ridotto'), ('Slippage', 'la differenza tra il prezzo che volevi e quello che ottieni, soprattutto con notizie e stop')],
  ["Tre costi riducono il tuo risultato.", "Lo spread: la differenza tra prezzo di acquisto e di vendita. Lo paghi appena entri.", "Le commissioni: una cifra per lotto, tipica dei conti con spread ridotto.", "Lo slippage: la differenza tra il prezzo che volevi e quello che ottieni, soprattutto durante le notizie e quando scatta uno stop."]),
 F('Il costo in R', 'Costo in R = Costo totale in pip ÷ Stop in pip', [('Costo totale', 'spread + commissioni + slippage, in pip'), ('Stop', 'distanza dallo stop loss, in pip')],
  ["Per capire quanto pesano, convertili in R.", "Il costo in R è il costo totale in pip, diviso lo stop in pip.", "Un costo fisso pesa poco se lo stop è lontano, e molto se è vicino."]),
 TB('Lo stesso costo, stop diversi', ['Stop', 'Costo 1,5 pip', 'Expectancy +0,26 R diventa'], [['50 pip', '0,03 R', '+0,23 R'], ['25 pip', '0,06 R', '+0,20 R'], ['10 pip', '0,15 R', '+0,11 R'], ['5 pip', '0,30 R', '−0,04 R']],
  ["Guarda cosa succede con un costo di uno virgola cinque pip, tra spread e commissione, e un sistema da più zero virgola ventisei R.", "Con uno stop a cinquanta pip, il costo è zero virgola zero tre R: l'expectancy scende a zero virgola ventitré.", "Con venticinque pip, zero virgola zero sei: resta zero virgola venti.", "Con dieci pip il costo è zero virgola quindici: l'expectancy cala a zero virgola undici, meno della metà.", "Con cinque pip il costo è zero virgola trenta R e l'expectancy diventa negativa. Il vantaggio è sparito."], nota='Esempio: 1,5 pip di costo totale per operazione.'),
 P('Conseguenze pratiche', [('Gli stop molto corti sono sensibili ai costi', 'lo scalping richiede costi bassissimi e vantaggio alto'), ('Misura i costi nel tuo conto reale', 'non usare i dati del sito del broker'), ('Includi i costi nel test del sistema', 'altrimenti l\'expectancy che vedi è più alta di quella vera')],
  ["Tre conseguenze pratiche.", "Gli stop molto corti sono molto sensibili ai costi. Lo scalping richiede costi bassissimi e un vantaggio alto.", "Misura i costi sul tuo conto reale, non fidarti dei dati pubblicitari del broker.", "E includi sempre i costi quando testi un sistema: altrimenti l'expectancy che vedi è più alta di quella vera."]),
 *ES('costi in R', [['Stop', '20 pip'], ['Spread + commissione', '2 pip'], ['Expectancy lorda', '+0,30 R']], [['Costo', '2 ÷ 20 = 0,10 R'], ['Expectancy netta', '0,30 − 0,10']], 'Expectancy netta = +0,20 R',
  ["Esercizio. Stop venti pip, costo due pip, expectancy lorda zero virgola trenta R. Qual è quella netta?", "Il costo è due diviso venti: zero virgola dieci R. Sottratto a zero virgola trenta dà zero virgola venti R. Un terzo del vantaggio è andato in costi."]),
 RIEP(['Spread, commissioni e slippage riducono ogni trade', 'Si convertono in R dividendo per lo stop', 'Stop corti = costi pesanti: includili sempre nei calcoli'], ["Riassumiamo.", "Spread, commissioni e slippage riducono ogni trade.", "Si convertono in R dividendo per lo stop.", "Stop corti significano costi pesanti: includili sempre nei calcoli."]),
 Q('Il vantaggio che non **sopravvive ai costi** non è un vantaggio.', "Il vantaggio che non sopravvive ai costi non è un vantaggio."),
])
