from h import *
LEZIONE = L('2.5', 'Modulo 2', 'Misurare un sistema', 'Il journal: R previsto contro R realizzato', [
 T('LEZIONE 2.5', 'Il **journal**', 'Per migliorare devi misurare quello che fai davvero.', "Lezione due punto cinque. Il journal: R previsto contro R realizzato."),
 P('Perché tenere un journal', [('La memoria seleziona', 'ricordi i trade belli e dimentichi i piccoli errori'), ('I numeri non hanno umore', 'mostrano quando e dove perdi'), ('Trasforma le sensazioni in dati', '«oggi ho operato male» diventa «ho violato la regola 3»')],
  ["Perché tenere un journal? Perché la memoria seleziona: ricordi i trade belli e dimentichi i piccoli errori.", "I numeri non hanno umore: mostrano quando e dove perdi.", "E trasformano le sensazioni in dati. Oggi ho operato male diventa: ho violato la regola tre."]),
 TB('Cosa registrare per ogni trade', ['Campo', 'Perché serve'], [['Data, ora, strumento', 'trovare gli orari e i mercati peggiori'], ['Ingresso, stop, target', 'calcolare il rischio e il RR previsto'], ['Rischio in € e in %', 'verificare che rispetti il piano'], ['Risultato in R', 'confrontare tutto'], ['Errore o regola violata', 'trovare le perdite evitabili']],
  ["Cosa registrare per ogni trade.", "Data, ora e strumento: servono a trovare gli orari e i mercati peggiori.", "Ingresso, stop e target: per calcolare il rischio e il RR previsto.", "Il rischio in euro e in percentuale: per verificare che rispetti il piano.", "Il risultato in R, per confrontare tutto.", "E un campo per l'errore o la regola violata, perché le perdite evitabili sono diverse da quelle normali."]),
 CF('Previsto contro realizzato, in pip', dict(t='Previsto', punti=[['Ingresso', '1,1000'], ['Stop', '1,0975'], ['Target', '1,1045'], ['Atteso', '+45 pip']]), dict(t='Realizzato', punti=[['Uscita', '1,1018'], ['Motivo', 'paura'], ['Chiuso a', '+18 pip'], ['Differenza', '−27 pip']]),
  ["La misura più preziosa è il confronto tra il risultato previsto e quello realizzato.", "Prevedevi di entrare a uno virgola uno zero zero zero, con lo stop venticinque pip sotto e il target quarantacinque sopra: un guadagno atteso di quarantacinque pip.", "In realtà hai chiuso a mano a diciotto pip, per paura.", "Hai lasciato per strada ventisette pip. Se succede spesso, il vantaggio reale del tuo sistema è molto più basso di quello sulla carta."], 'Differenza: 27 pip lasciati sul tavolo.'),
 N('Il costo di non seguire il piano', '−27 pip', ["Prendiamo quel trade. Meno ventisette pip rispetto al piano.", "Il nostro sistema vale in media circa sei virgola cinque pip a trade, con uno stop di venticinque pip. Se ti capita una volta su cinque, perdi in media cinque virgola quattro pip a trade: più dell'ottanta per cento del vantaggio.", "Il problema non è il sistema. È l'esecuzione. Ma lo scopri solo se registri i numeri."], 'in un solo trade, uscendo prima del target'),
 P('Strumenti: un mio prodotto, dichiarato', [('Un foglio di calcolo basta', 'colonne per ogni campo, e due formule per R e totale'), ('Oppure il Riskly Journal', 'è un mio prodotto: raccoglie le operazioni, calcola le statistiche e mostra gli orari in cui perdi di più'), ('Qualunque strumento va bene', 'purché lo compili ogni giorno e senza eccezioni')],
  ["Per tenere il journal ti basta un foglio di calcolo, con una colonna per ogni campo e due formule per calcolare R e totale.", "Oppure puoi usare il Riskly Journal. Dichiaro che è un mio prodotto: raccoglie le operazioni, calcola le statistiche e mostra, per esempio, gli orari in cui perdi di più.", "Qualunque strumento va bene, purché lo compili ogni giorno e senza eccezioni."]),
 RIEP(['Il journal trasforma sensazioni in dati', 'Registra rischio, R previsto e R realizzato per ogni trade', 'Il confronto previsto/realizzato mostra l\'errore di esecuzione'], ["Riassumiamo.", "Il journal trasforma le sensazioni in dati.", "Registra rischio, R previsto e R realizzato per ogni trade.", "E il confronto tra previsto e realizzato mostra l'errore di esecuzione, spesso più dannoso del sistema stesso."]),
 Q('Quello che **non misuri** non puoi migliorarlo.', "Quello che non misuri non puoi migliorarlo."),
])
