from h import *
LEZIONE = L('3.2', 'Modulo 3', 'Drawdown e perdite', 'Perché recuperare costa di più', [
 T('LEZIONE 3.2', 'Perdere è facile, **recuperare** no', 'La matematica asimmetrica del drawdown.', "Lezione tre punto due. Perché recuperare costa di più."),
 EX('Il paradosso', [['Capitale', '10.000 €'], ['Perdi il 50%', '5.000 €'], ['Guadagni il 50%', '7.500 €']], risultato='Non sei tornato a 10.000', k=[1,2,3,4],
  voce=["Parti da diecimila euro. Perdi il cinquanta per cento: ne restano cinquemila. Poi guadagni il cinquanta per cento. Sei tornato a diecimila?", "No. Il cinquanta per cento di cinquemila è duemilacinquecento: arrivi a settemilacinquecento.", "Per tornare a diecimila ti serve un guadagno del cento per cento, non del cinquanta.", "Perdere e recuperare non sono simmetrici: il guadagno si applica a una base più piccola."]),
 F('La formula del recupero', 'Recupero = 1 ÷ (1 − Drawdown) − 1', [('Drawdown', 'in decimale: 0,30 per −30%'), ('Recupero', 'guadagno percentuale necessario per tornare al massimo')],
  ["La formula del recupero è: uno diviso uno meno il drawdown, meno uno.", "Il drawdown va espresso in decimale: zero virgola trenta per meno trenta per cento.", "Il risultato è il guadagno necessario per tornare al massimo."]),
 TB('Quanto serve per recuperare', ['Perdita', 'Guadagno necessario'], [['−10%', '+11,1%'], ['−20%', '+25%'], ['−30%', '+42,9%'], ['−40%', '+66,7%'], ['−50%', '+100%'], ['−60%', '+150%'], ['−70%', '+233%'], ['−80%', '+400%'], ['−90%', '+900%']],
  ["Ecco la tabella completa.", "Perdi il dieci per cento, ti serve l'undici virgola uno.", "Perdi il venti, ti serve il venticinque.", "Il trenta, il quarantadue virgola nove.", "Il quaranta, il sessantasei virgola sette.", "Il cinquanta, il cento.", "Il sessanta, il centocinquanta.", "Il settanta, il duecentotrentatré.", "L'ottanta, il quattrocento.", "E il novanta, il novecento per cento."], nota='Dopo −50%, ogni punto in più costa sempre di più.'),
 G('La curva del recupero', 'recupero', ["Sul grafico si vede bene la curva. Fino a circa meno venti per cento la salita è dolce, poi diventa ripida, e oltre meno cinquanta diventa quasi verticale.", "Per questo molti trader seri hanno limiti di drawdown intorno al dieci o venti per cento: oltre quella soglia recuperare diventa sempre più difficile."], 'Oltre −50% la strada del ritorno diventa quasi impossibile.'),
 *ES('recupero', [['Drawdown', '−35%'], ['Domanda', 'guadagno necessario per tornare al massimo?']], [['Formula', '1 ÷ (1 − 0,35) − 1'], ['Calcolo', '1 ÷ 0,65 − 1 = 0,538']], 'Servono +53,8%',
  ["Esercizio. Sei in drawdown del trentacinque per cento. Quanto devi guadagnare per tornare al massimo?", "Uno diviso zero virgola sessantacinque fa uno virgola cinquecentotrentotto, meno uno: zero virgola cinquecentotrentotto. Servono più cinquantatre virgola otto per cento."]),
 RIEP(['Il recupero richiede più della perdita', 'Recupero = 1 ÷ (1 − DD) − 1', 'Oltre −50% il recupero diventa quasi impossibile: meglio evitare di arrivarci'], ["Riassumiamo.", "Il recupero richiede sempre più della perdita.", "La formula è uno diviso uno meno il drawdown, meno uno.", "E oltre il meno cinquanta per cento il recupero diventa quasi impossibile: meglio non arrivarci."]),
 Q('Il tuo primo lavoro è **non perdere molto**. Il secondo, guadagnare.', "Il tuo primo lavoro è non perdere molto. Il secondo, guadagnare."),
])
