from h import *
LEZIONE = L('3.3', 'Modulo 3', 'Drawdown e perdite', 'Le serie di perdite', [
 T('LEZIONE 3.3', 'Le serie di **perdite**', 'Quante perdite di fila sono normali? Più di quante pensi.', "Lezione tre punto tre. Le serie di perdite."),
 P('Un\'illusione comune', [('«Ho perso 6 volte di fila, c\'è qualcosa che non va»', 'forse. O forse è solo statistica'), ('Le serie di perdite fanno parte di ogni sistema', 'anche di quelli buoni'), ('Il problema non è la serie, ma il rischio per trade', 'è lui a decidere quanto ti costa')],
  ["Un'illusione comune: ho perso sei volte di fila, c'è qualcosa che non va.", "Forse. Ma forse è solo statistica. Le serie di perdite fanno parte di ogni sistema, anche di quelli buoni.", "Il problema non è la serie in sé, ma il rischio per trade: è lui a decidere quanto ti costa."]),
 G('Quante perdite di fila aspettarsi', 'serie', ["Questo grafico mostra la serie di perdite più lunga che ti aspetti, in mediana, su duecento operazioni, al variare del win rate.", "Con un win rate del trentacinque per cento ti aspetti dieci perdite di fila. Al quarantacinque, otto. Al sessanta, cinque. Anche con il sessanta per cento di vittorie, cinque perdite consecutive sono normali."], 'Valori mediani da simulazione su 200 trade.'),
 TB('Con win rate 45%, su 200 trade', ['Serie di almeno…', 'Probabilità'], [['5 perdite', '99%'], ['6 perdite', '93%'], ['8 perdite', '53%'], ['10 perdite', '19%'], ['12 perdite', '6%']],
  ["Con un win rate del quarantacinque per cento, su duecento operazioni, quanto è probabile una serie lunga?", "Una serie di almeno cinque perdite quasi certa: novantanove per cento.", "Sei perdite: novantatré per cento.", "Otto perdite: circa una volta su due.", "Dieci perdite: circa una volta su cinque.", "Dodici: circa una su sedici."], nota='Simulazione, 40.000 percorsi.'),
 TB('Quanto costa una serie', ['Rischio', '8 perdite', '10 perdite'], [['1%', '−7,7%', '−9,6%'], ['2%', '−14,9%', '−18,3%'], ['5%', '−33,7%', '−40,1%']],
  ["E quanto costa? Dipende dal rischio per trade.", "Con l'uno per cento, otto perdite costano il sette virgola sette per cento; dieci perdite il nove virgola sei.", "Con il due per cento, il quattordici virgola nove e il diciotto virgola tre.", "Con il cinque per cento, il trentatré virgola sette e il quaranta virgola uno. La stessa serie, un costo cinque volte superiore."], nota='Le perdite si compongono (lezione successiva).'),
 *ES('quanto rischiare', [['Obiettivo', 'dopo 10 perdite di fila, al massimo −15%'], ['Domanda', 'rischio massimo per trade?']], [['Condizione', '(1 − r)¹⁰ ≥ 0,85'], ['Soluzione', 'r ≤ 1 − 0,85^(1/10)'], ['Calcolo', '1 − 0,9839']], 'r ≈ 1,6% a trade',
  ["Esercizio, un po' più avanzato. Vuoi che dieci perdite di fila non ti costino più del quindici per cento. Qual è il rischio massimo per trade?", "Serve che uno meno r, alla decima, sia almeno zero virgola ottantacinque. Quindi r è al massimo uno meno la radice decima di zero virgola ottantacinque, cioè uno virgola sei per cento circa. Con l'uno virgola cinque per cento sei dentro il limite."]),
 RIEP(['Le serie di perdite sono normali in ogni sistema', 'Con win rate 45%, 8 perdite di fila su 200 trade sono quasi una su due', 'Il costo di una serie dipende dal rischio per trade'], ["Riassumiamo.", "Le serie di perdite sono normali in qualsiasi sistema.", "Con il quarantacinque per cento di vittorie, otto perdite di fila su duecento operazioni capitano circa una volta su due.", "Il costo di una serie dipende dal rischio per trade: ecco perché il rischio va deciso pensando alla peggiore serie plausibile."]),
 Q('Il rischio per trade si sceglie guardando la **serie peggiore**, non il caso medio.', "Il rischio per trade si sceglie guardando la serie peggiore, non il caso medio."),
])
