from h import *
LEZIONE = L('3.4', 'Modulo 3', 'Drawdown e perdite', 'Le perdite si compongono', [
 T('LEZIONE 3.4', 'Le perdite si **compongono**', 'Perché 8 perdite del 5% non fanno −40%.', "Lezione tre punto quattro. Le perdite si compongono."),
 P('Il principio', [('Ogni perdita si applica al capitale che resta', 'non al capitale iniziale'), ('Quindi le perdite successive pesano meno in valore', 'ma restano percentuali dello stesso capitale ridotto'), ('Il risultato è sempre meno della somma semplice', 'e vale lo stesso per i guadagni, al contrario')],
  ["Ogni perdita si applica al capitale che resta, non a quello iniziale.", "Quindi le perdite successive pesano meno in valore assoluto, anche se sono la stessa percentuale.", "Il risultato è sempre meno grave della somma semplice. E per i guadagni vale il contrario: crescono più della somma."]),
 F('La formula', 'Capitale finale = Capitale × (1 − r)ⁿ', [('r', 'rischio per trade, in decimale'), ('n', 'numero di perdite consecutive'), ('Perdita totale', '1 − (1 − r)ⁿ')],
  ["La formula è il capitale iniziale per uno meno r, elevato a n.", "r è il rischio per trade in decimale.", "n è il numero di perdite consecutive.", "E la perdita totale è uno meno quel fattore."]),
 EX('8 perdite al 5%', [['Fattore per perdita', '0,95'], ['Dopo 8 perdite', '0,95⁸ = 0,663'], ['Perdita totale', '1 − 0,663']], risultato='−33,7%, non −40%', k=[1,2,3,4],
  voce=["Facciamo il conto con otto perdite del cinque per cento.", "Ogni perdita moltiplica il capitale per zero virgola novantacinque.", "Otto volte: zero virgola novantacinque alla ottava dà zero virgola seicentosessantatré.", "Hai perso il trentatré virgola sette per cento, non il quaranta come la somma semplice farebbe pensare."]),
 G('Somma semplice contro composta', 'composizione', ["Sul grafico, la linea tratteggiata è la somma semplice, quella rossa le perdite composte. Più perdite consecutive, più si allontanano.", "Ma attenzione: questa differenza è a tuo favore sulle perdite. Quella che pesa davvero è l'asimmetria del recupero che abbiamo visto nella lezione precedente."], 'Rischio 5% per trade.'),
 TB('Quanto vale la perdita composta', ['Rischio', '5 perdite', '10 perdite', '15 perdite'], [['1%', '−4,9%', '−9,6%', '−14,0%'], ['2%', '−9,6%', '−18,3%', '−26,1%'], ['3%', '−14,1%', '−26,3%', '−36,7%'], ['5%', '−22,6%', '−40,1%', '−53,7%']],
  ["Ecco una tabella da tenere a portata di mano.", "Con l'uno per cento, cinque perdite fanno meno quattro virgola nove, dieci fanno meno nove virgola sei, quindici meno quattordici.", "Con il due per cento, meno nove virgola sei, meno diciotto virgola tre, meno ventisei virgola uno.", "Con il tre per cento, meno quattordici, meno ventisei, meno trentasei virgola sette.", "Con il cinque per cento, meno ventidue virgola sei, meno quaranta, e dopo quindici perdite oltre il cinquanta per cento."], nota='1 − (1 − r)ⁿ'),
 *ES('perdita composta', [['Rischio', '3%'], ['Perdite di fila', '8']], [['Fattore', '0,97⁸'], ['Calcolo', '0,784'], ['Perdita', '1 − 0,784']], 'Perdita = −21,6% (non −24%)',
  ["Esercizio. Rischio tre per cento, otto perdite di fila. Quanto perdi?", "Zero virgola novantasette alla ottava dà zero virgola settecentottantaquattro. La perdita è venti uno virgola sei per cento, non ventiquattro."]),
 RIEP(['Le perdite si applicano al capitale rimasto', 'Perdita totale = 1 − (1 − r)ⁿ', 'Mai sommare le percentuali: componile'], ["Riassumiamo.", "Le perdite si applicano al capitale rimasto.", "La perdita totale è uno meno uno meno r alla n.", "E non sommare mai le percentuali: componile."]),
 Q('Le percentuali **non si sommano**. Si moltiplicano.', "Le percentuali non si sommano. Si moltiplicano."),
])
