from h import *
LEZIONE = L('3.5', 'Modulo 3', 'Drawdown e perdite', 'Rischio per trade e drawdown atteso', [
 T('LEZIONE 3.5', 'Quanto drawdown **aspettarsi**', 'Dal rischio per trade al peggiore calo tipico.', "Lezione tre punto cinque. Rischio per trade e drawdown atteso."),
 P('Il collegamento', [('Rischio per trade alto → drawdown più profondo', 'è la relazione più importante di tutto il corso'), ('Il drawdown massimo dipende dalla sequenza dei trade', 'quindi non è un numero, è una distribuzione'), ('Lo possiamo stimare con una simulazione', 'dato un sistema con le sue statistiche')],
  ["Questa è la relazione più importante del corso: più alto è il rischio per trade, più profondo sarà il drawdown.", "Il drawdown massimo dipende dalla sequenza dei trade, quindi non è un singolo numero: è una distribuzione.", "Possiamo stimarlo con una simulazione, dato un sistema con le sue statistiche."]),
 EX('Il sistema di esempio', [['Win rate', '45%'], ['Guadagno medio', '+1,8 R'], ['Perdita media', '−1 R'], ['Expectancy', '+0,26 R'], ['Operazioni simulate', '200 per percorso']], risultato='40.000 percorsi per ogni livello di rischio', k=[1,2,3,4,5,6],
  voce=["Usiamo un sistema di esempio. Win rate quarantacinque per cento.", "Guadagno medio uno virgola otto R.", "Perdita media un R.", "Quindi expectancy più zero virgola ventisei R.", "Simuliamo duecento operazioni.", "Ripetendo la simulazione quarantamila volte per ogni livello di rischio, per vedere cosa capita nel tipico e nel brutto."]),
 G('Drawdown massimo tipico', 'dd_rischio', ["Ecco il drawdown massimo mediano, quello che capita nella metà dei casi.", "Rischiando lo zero virgola cinque per cento, il drawdown tipico è circa il cinque. Con l'uno per cento, circa il dieci. Con il due, circa il diciannove. Con il tre, ventotto. Con il cinque per cento, quarantatré.", "Il drawdown cresce quasi in proporzione al rischio: raddoppi il rischio, raddoppi il drawdown."], 'Mediana su 200 trade, win rate 45%, +1,8 R / −1 R.'),
 TB('Anche il caso peggiore conta', ['Rischio', 'Tipico', '9 casi su 10 sotto'], [['0,5%', '−5%', '−8%'], ['1%', '−10%', '−15%'], ['2%', '−19%', '−28%'], ['3%', '−28%', '−40%'], ['5%', '−43%', '−59%']],
  ["Il tipico non basta. Guarda anche il caso peggiore: il novantesimo percentile, cioè nove volte su dieci il drawdown è inferiore.", "Con lo zero virgola cinque per cento: tipico meno cinque, quasi sempre sotto meno otto.", "Con l'uno per cento: tipico meno dieci, quasi sempre sotto meno quindici.", "Con il due per cento: meno diciannove, e sotto meno ventotto.", "Con il tre per cento: meno ventotto, e sotto meno quaranta.", "Con il cinque per cento: tipico meno quarantatré e nel caso peggiore oltre meno cinquantanove."], nota='Simulazione: non è una previsione.'),
 P('Come usare questa informazione', [('Parti dal drawdown che sopporti', 'e scegli il rischio di conseguenza, non il contrario'), ('Lascia margine rispetto al tipico', 'il peggio può essere peggiore della mediana'), ('Rifai il calcolo con i tuoi numeri', 'win rate e RR del tuo sistema cambiano tutto')],
  ["Come si usa tutto questo? Parti dal drawdown che sei disposto a sopportare, e scegli il rischio di conseguenza, non il contrario.", "Lascia un margine rispetto al tipico: nel caso peggiore il calo è molto più profondo.", "E rifai il calcolo con i tuoi numeri. Win rate e RR del tuo sistema cambiano tutto. Nel modulo cinque imparerai a farlo con un simulatore."]),
 *ES('scegli il rischio', [['Drawdown che sopporti', 'circa −20% nel caso tipico'], ['Sistema', 'quello di esempio']], [['Dalla tabella', '2% → −19% tipico'], ['Caso peggiore', 'fino a −28%']], 'Rischio ≈ 2%, ma con prudenza 1–1,5%',
  ["Esercizio. Dici di sopportare circa il venti per cento di drawdown nel caso tipico. Quale rischio per trade scegli?", "Dalla tabella, il due per cento dà un tipico di meno diciannove. Ma nel caso peggiore arrivi a meno ventotto. Per questo conviene scendere, tra l'uno e l'uno e mezzo per cento: avrai ancora margine se le cose vanno male."]),
 RIEP(['Rischio per trade e drawdown crescono insieme', 'Il drawdown è una distribuzione: guarda tipico e caso peggiore', 'Parti dalla perdita che sopporti e scegli il rischio di conseguenza'], ["Riassumiamo.", "Rischio per trade e drawdown crescono insieme.", "Il drawdown è una distribuzione: guarda sia il tipico sia il caso peggiore.", "E parti dalla perdita che sopporti, poi scegli il rischio di conseguenza."]),
 Q('Non scegli il rischio per **quanto vuoi guadagnare**. Lo scegli per quanto puoi **perdere**.', "Non scegli il rischio per quanto vuoi guadagnare. Lo scegli per quanto puoi perdere."),
])
