from h import *
LEZIONE = L('4.1', 'Modulo 4', 'Dimensionare la posizione', 'Rischio fisso in percentuale', [
 T('LEZIONE 4.1', 'Il rischio fisso **in percentuale**', 'Il metodo più semplice e più usato per dimensionare ogni operazione.', "Lezione quattro punto uno. Il rischio fisso in percentuale."),
 P('Tre modi di dimensionare', [('Lotto fisso', 'sempre 0,4 lotti, qualunque stop e qualunque capitale'), ('Importo fisso', 'sempre 100 € di rischio, anche se il conto cala'), ('Percentuale fissa', 'sempre l\'1% del capitale corrente, con il lotto che ne risulta')],
  ["Ci sono tre modi principali di dimensionare le operazioni.", "Lotto fisso: sempre lo stesso lotto, qualunque stop e qualunque capitale.", "Importo fisso: sempre cento euro di rischio, anche se il conto cala.", "E percentuale fissa: sempre l'uno per cento del capitale corrente, con il lotto che ne risulta."]),
 TB('Cosa succede quando il conto scende del 20%', ['Metodo', 'Rischio prima', 'Rischio dopo −20%'], [['Lotto fisso (0,4)', '1,0%', '1,25% (sale)'], ['Importo fisso (100 €)', '1,0%', '1,25% (sale)'], ['Percentuale fissa (1%)', '1,0%', '1,0% (resta)']],
  ["Vediamo cosa succede quando il conto scende del venti per cento, da diecimila a ottomila euro.", "Con il lotto fisso, la perdita massima resta cento euro, che ora è l'uno virgola venticinque per cento del conto: rischi di più, proprio quando sei in difficoltà.", "Stesso discorso con l'importo fisso.", "Con la percentuale fissa, il rischio resta l'uno per cento: in euro scende a ottanta. Le posizioni si riducono da sole mentre il conto cala."], nota='Conto da 10.000 € a 8.000 €.'),
 EX('Dalla regola al lotto', [['Capitale corrente', '8.000 €'], ['Rischio 1%', '80 €'], ['Stop', '25 pip'], ['Lotti', '80 ÷ (25 × 10)']], risultato='= 0,32 lotti', k=[1,2,3,4,5],
  voce=["Applichiamo la regola dopo la perdita del venti per cento.", "Il capitale corrente è ottomila euro.", "L'uno per cento è ottanta euro.", "Lo stop è venticinque pip.", "Ottanta diviso venticinque per dieci: zero virgola trentadue lotti. Prima, con diecimila euro, erano zero virgola quaranta: la posizione si è ridotta del venti per cento."]),
 CF('Vantaggi e limiti', dict(t='Vantaggi', punti=[['Protegge dopo le perdite', ''], ['Semplice da calcolare', ''], ['Funziona su ogni strumento', '']]), dict(t='Limiti', punti=[['Dopo una serie, il recupero è lento', ''], ['Richiede un calcolo a ogni trade', ''], ['Non considera la volatilità', '']]),
  ["Vantaggi e limiti del metodo.", "Protegge il conto dopo le perdite, è semplice da calcolare e funziona su qualsiasi strumento.", "Il recupero dopo una serie negativa è più lento, perché le posizioni sono più piccole; richiede un calcolo a ogni trade; e non considera la volatilità del mercato, ma a questo penseremo nella prossima lezione."], 'È una base solida, non l\'unico strumento.'),
 *ES('rischio %', [['Capitale', '14.000 €'], ['Rischio', '1,5%'], ['Stop', '30 pip'], ['Valore pip', '10 € per lotto']], [['Rischio in €', '14.000 × 0,015 = 210 €'], ['Lotti', '210 ÷ (30 × 10)']], 'Lotti = 0,70',
  ["Esercizio. Capitale quattordicimila euro, rischio uno e mezzo per cento, stop trenta pip, dieci euro per pip e per lotto. Quanti lotti?", "Il rischio è duecentodieci euro. Diviso trenta per dieci fa zero virgola sette lotti."]),
 RIEP(['La percentuale fissa riduce le posizioni quando perdi', 'Lotti = (capitale × %) ÷ (stop × valore pip)', 'È una base: nella lezione dopo si adatta alla volatilità'], ["Riassumiamo.", "La percentuale fissa riduce le posizioni quando perdi.", "I lotti si calcolano dal capitale per la percentuale, diviso stop per valore del pip.", "È una base solida, che nella prossima lezione adatteremo alla volatilità."]),
 Q('Il tuo lotto deve **rispondere** al conto. Non l\'umore del giorno.', "Il tuo lotto deve rispondere al conto, non all'umore del giorno."),
])
