from h import *
LEZIONE = L('4.2', 'Modulo 4', 'Dimensionare la posizione', 'Stop e volatilità: l\'ATR', [
 T('LEZIONE 4.2', 'Stop e volatilità: l\'**ATR**', 'Adattare la distanza dello stop a quanto si muove il mercato.', "Lezione quattro punto due. Stop e volatilità: l'ATR."),
 P('Il problema dello stop fisso', [('Venti pip sono tanti o pochi?', 'dipende da quanto si muove il mercato in quel momento'), ('Con volatilità alta, uno stop fisso scatta per rumore', 'e vieni fermato prima dell\'idea'), ('Con volatilità bassa, uno stop fisso è inutilmente largo', 'e rischi più del necessario per quell\'idea')],
  ["Uno stop fisso a venti pip è tanto o poco? Dipende da quanto si muove il mercato in quel momento.", "Con volatilità alta, uno stop fisso scatta per puro rumore: vieni fermato prima che l'idea sia sbagliata.", "Con volatilità bassa, lo stesso stop è inutilmente largo."]),
 F('L\'ATR', 'ATR = media dell\'escursione dei prezzi su N candele', [('Standard', 'N = 14 candele del tuo timeframe'), ('Cosa misura', 'quanto si muove tipicamente una candela'), ('Dove si trova', 'è un indicatore standard di ogni piattaforma')],
  ["L'ATR, Average True Range, misura quanto si muove in media una candela.", "Di solito si usa su quattordici periodi del timeframe su cui operi.", "È un indicatore standard di ogni piattaforma: non devi calcolarlo a mano."], k=[1,2,4]),
 F('Stop basato sull\'ATR', 'Stop = k × ATR', [('k', 'moltiplicatore: spesso tra 1,5 e 2'), ('Esempio', 'ATR 20 pip, k = 2 → stop 40 pip'), ('Il lotto', 'poi si calcola con la formula di sempre')],
  ["Lo stop si può definire come un multiplo dell'ATR: stop uguale k per ATR.", "k è un moltiplicatore, spesso tra uno e mezzo e due. Va scelto e testato sul tuo sistema.", "Per esempio con ATR venti pip e k uguale due, lo stop è quaranta pip.", "Il lotto lo calcoli poi con la formula che già conosci."]),
 TB('Lo stesso rischio, tre volatilità', ['ATR', 'Stop (2×)', 'Rischio', 'Lotti'], [['10 pip', '20 pip', '100 €', '0,50'], ['20 pip', '40 pip', '100 €', '0,25'], ['40 pip', '80 pip', '100 €', '0,125']],
  ["Vediamo il risultato con un rischio di cento euro.", "Con mercato tranquillo, ATR dieci pip: stop venti pip, mezzo lotto.", "Con volatilità media, ATR venti: stop quaranta pip, un quarto di lotto.", "Con volatilità alta, ATR quaranta: stop ottanta pip, un ottavo di lotto.", "Il rischio in euro è sempre lo stesso. Quando il mercato è più nervoso, la posizione si rimpicciolisce da sola."], nota='Con k = 2 e valore pip 10 € per lotto.'),
 P('Attenzioni', [('Il target va adattato', 'se lo stop è più largo, a parità di RR anche il target si allontana'), ('Non vale per tutti i sistemi', 'se l\'idea ha uno stop strutturale preciso, prevale quello'), ('Testa k sui tuoi dati', '1,5 e 2 danno risultati diversi per ogni sistema')],
  ["Tre attenzioni. Il target va adattato: se lo stop è più largo, a parità di RR anche il target si allontana.", "Non vale per tutti i sistemi: se l'idea ha un livello strutturale preciso, quello prevale.", "E testa il moltiplicatore sui tuoi dati: uno e mezzo e due danno risultati diversi per ogni sistema."]),
 *ES('lotti con ATR', [['Rischio', '120 €'], ['ATR', '30 pip'], ['Moltiplicatore', '2'], ['Valore pip', '10 € per lotto']], [['Stop', '2 × 30 = 60 pip'], ['Lotti', '120 ÷ (60 × 10)']], 'Lotti = 0,20',
  ["Esercizio. Rischio centoventi euro, ATR trenta pip, moltiplicatore due, dieci euro per pip e per lotto. Quanti lotti?", "Lo stop è due per trenta: sessanta pip. I lotti sono centoventi diviso sessanta per dieci: zero virgola due."]),
 RIEP(['L\'ATR misura quanto si muove il mercato', 'Stop = k × ATR (k spesso 1,5–2)', 'Volatilità alta → posizione più piccola, a rischio costante'], ["Riassumiamo.", "L'ATR misura quanto si muove il mercato.", "Lo stop si può porre a un multiplo dell'ATR, di solito tra uno e mezzo e due.", "Con volatilità alta la posizione si rimpicciolisce, e il rischio resta costante."]),
 Q('Il mercato decide quanto **respira**. Il rischio decide quanto **compri**.', "Il mercato decide quanto respira. Il rischio decide quanto compri."),
])
