from h import *
LEZIONE = L('4.3', 'Modulo 4', 'Dimensionare la posizione', 'Il criterio di Kelly e le sue frazioni', [
 T('LEZIONE 4.3', 'Il criterio di **Kelly**', 'Una formula famosa per il rischio ottimale, e perché va usata a pezzi.', "Lezione quattro punto tre. Il criterio di Kelly e le sue frazioni."),
 P('L\'idea', [('Esiste un rischio che massimizza la crescita nel lungo periodo', 'non quello che massimizza il guadagno di un trade'), ('Lo calcola la formula di Kelly', 'a partire da win rate e rapporto guadagno/perdita'), ('Sopra quel valore la crescita cala, poi diventa negativa', 'rischiare troppo non è solo pericoloso: è perdente')],
  ["L'idea di Kelly è che esista un rischio che massimizza la crescita del capitale nel lungo periodo.", "La formula lo calcola a partire dal win rate e dal rapporto tra guadagno e perdita.", "E il punto sorprendente è che, sopra quel valore, la crescita cala e poi diventa negativa. Rischiare troppo non è solo pericoloso: è perdente."]),
 F('La formula', 'f* = W − (1 − W) ÷ R', [('f*', 'frazione del capitale da rischiare'), ('W', 'win rate'), ('R', 'guadagno medio ÷ perdita media')],
  ["La formula è f stella uguale W meno uno meno W diviso R.", "f stella è la frazione di capitale da rischiare.", "W è il win rate.", "E R è il rapporto tra guadagno medio e perdita media."]),
 EX('Esempio', [['Win rate W', '45%'], ['Rapporto R', '1,8'], ['(1 − W) ÷ R', '0,55 ÷ 1,8 = 0,306'], ['Kelly f*', '0,45 − 0,306']], risultato='f* = 14,4% del capitale', k=[1,2,3,4,5],
  voce=["Calcoliamolo sul sistema di esempio. Win rate quarantacinque per cento.", "R uguale uno virgola otto.", "Zero virgola cinquantacinque diviso uno virgola otto fa zero virgola trecentosei.", "Zero virgola quarantacinque meno zero virgola trecentosei: zero virgola centoquarantaquattro.", "Kelly dice di rischiare il quattordici virgola quattro per cento del capitale a trade. Sembra enorme. Lo è: ed è qui che arriva il trucco."]),
 G('Cosa succede se rischi più o meno di Kelly', 'kelly', ["Il grafico mostra la crescita del capitale al variare del rischio, come multiplo del Kelly.", "A Kelly pieno la crescita è massima, ma il drawdown è enorme. A metà Kelly, crescita al settantasei per cento del massimo. A un quarto di Kelly, quarantacinque per cento.", "Il punto chiave è il lato destro: a due volte Kelly la crescita è quasi zero. Rischiare il doppio non è solo rischioso, azzera il vantaggio."], 'Crescita come percentuale del massimo.'),
 P('Perché si usa una frazione', [('I tuoi numeri sono stime', 'se win rate e R sono sovrastimati, Kelly pieno è già troppo'), ('Il drawdown a Kelly pieno è molto profondo', 'difficile da sopportare senza cambiare piano'), ('Un quarto o un mezzo Kelly riducono molto il rischio', 'perdendo solo una parte della crescita')],
  ["Per questo, in pratica, si usa una frazione di Kelly.", "I tuoi numeri sono stime: se win rate e rapporto sono sovrastimati, Kelly pieno è già troppo.", "Il drawdown a Kelly pieno è molto profondo, e difficile da sopportare.", "Un quarto o un mezzo Kelly riducono molto il rischio, perdendo solo una parte della crescita. Un quarto di Kelly, nel nostro esempio, è circa il tre virgola sei per cento."]),
 *ES('Kelly', [['Win rate', '40%'], ['R', '2']], [['f*', '0,40 − 0,60 ÷ 2'], ['Calcolo', '0,40 − 0,30 = 0,10'], ['¼ Kelly', '2,5%']], 'f* = 10%; ¼ Kelly = 2,5%',
  ["Esercizio. Win rate quaranta per cento, R uguale due. Calcola Kelly e un quarto di Kelly.", "Zero virgola quaranta meno zero virgola sessanta diviso due: zero virgola quaranta meno zero virgola trenta. Dieci per cento. Un quarto è due virgola cinque per cento."]),
 RIEP(['Kelly: f* = W − (1 − W) ÷ R', 'Rischiare sopra Kelly riduce la crescita, fino ad azzerarla', 'In pratica: un quarto o metà Kelly, con stime prudenti'], ["Riassumiamo.", "Kelly indica la frazione ottimale di capitale da rischiare.", "Rischiare sopra Kelly riduce la crescita, fino ad azzerarla.", "In pratica si usa un quarto o metà Kelly, con stime prudenti. E Kelly non è un obiettivo: è un tetto."]),
 Q('Kelly è un **tetto**, non un **obiettivo**.', "Kelly è un tetto, non un obiettivo."),
])
