from h import *
LEZIONE = L('4.4', 'Modulo 4', 'Dimensionare la posizione', 'Quando aumentare e quando ridurre il rischio', [
 T('LEZIONE 4.4', 'Aumentare o **ridurre**?', 'Regole per cambiare il rischio senza farsi guidare dall\'emozione.', "Lezione quattro punto quattro. Quando aumentare e quando ridurre il rischio."),
 P('La tentazione', [('Dopo le vincite: «sono in forma, rischio di più»', 'è fiducia eccessiva travestita da strategia'), ('Dopo le perdite: «devo recuperare, rischio di più»', 'è il modo più rapido di trasformare un drawdown in una rovina'), ('Entrambe le decisioni sono emotive', 'e le emozioni non conoscono la tua statistica')],
  ["La tentazione è cambiare il rischio in base all'umore.", "Dopo le vincite: sono in forma, rischio di più. È fiducia eccessiva travestita da strategia.", "Dopo le perdite: devo recuperare, rischio di più. È il modo più rapido di trasformare un drawdown in una rovina.", "Entrambe le decisioni sono emotive, e le emozioni non conoscono la tua statistica."]),
 EX('La martingala: raddoppiare dopo la perdita', [['Perdita 1 · rischio 1%', 'capitale 99,0%'], ['Perdita 2 · rischio 2%', '97,0%'], ['Perdita 3 · rischio 4%', '93,1%'], ['Perdita 4 · rischio 8%', '85,7%'], ['Perdita 5 · rischio 16%', '72,0%'], ['Perdita 6 · rischio 32%', '48,9%']], risultato='6 perdite → −51% del capitale', k=[0,1,2,3,4,5,6,7],
  voce=["Il caso estremo è la martingala: raddoppiare il rischio dopo ogni perdita, sperando di recuperare tutto con una vincita.", "Prima perdita, rischio uno per cento: resta il novantanove.", "Seconda, rischio due: novantasette.", "Terza, rischio quattro: novantatré virgola uno.", "Quarta, rischio otto: ottantacinque virgola sette.", "Quinta, rischio sedici: settantadue.", "Sesta, rischio trentadue: quarantotto virgola nove.", "Sei perdite consecutive, che in un sistema reale capitano, e hai perso più della metà del capitale."]),
 P('Regole sane per cambiare il rischio', [('Ridurre dopo un drawdown', 'per esempio dimezzare il rischio se il calo supera il 10%'), ('Tornare alla normalità solo dopo un recupero', 'non dopo un solo trade vincente'), ('Aumentare solo per scalini e su nuovi massimi', 'e solo dopo molti trade, con regole scritte')],
  ["Esistono regole più sane.", "Ridurre il rischio dopo un drawdown. Per esempio, dimezzarlo se il calo supera il dieci per cento.", "Tornare alla normalità solo dopo un recupero, non dopo un solo trade vincente.", "E aumentare il rischio solo per scalini e su nuovi massimi, dopo molti trade, con regole scritte in anticipo."]),
 TB('Esempio di regola scritta', ['Condizione', 'Rischio per trade'], [['Normale', '1%'], ['Drawdown oltre 10%', '0,5%'], ['Drawdown oltre 15%', '0,25% o stop'], ['Nuovo massimo, dopo 50+ trade', 'puoi valutare +0,25 punti']],
  ["Un esempio di regola scritta.", "In condizioni normali, rischi l'uno per cento.", "Se il drawdown supera il dieci per cento, scendi a zero virgola cinque.", "Oltre il quindici, a zero virgola venticinque, oppure ti fermi.", "E solo con un nuovo massimo, dopo almeno cinquanta trade, valuti di aumentare di un quarto di punto. Le soglie sono un esempio: le tue le decidi tu, a mente fredda."], nota='Soglie indicative, da adattare al proprio sistema.'),
 *ES('martingala', [['Rischio iniziale', '2%'], ['Raddoppi dopo ogni perdita', '2%, 4%, 8%, 16%'], ['Domanda', 'capitale dopo 4 perdite?']], [['Fattori', '0,98 × 0,96 × 0,92 × 0,84'], ['Capitale', '72,7%']], 'Perdita: −27,3%',
  ["Esercizio. Parti rischiando il due per cento e raddoppi dopo ogni perdita: due, quattro, otto, sedici. Quanto resta dopo quattro perdite di fila?", "Moltiplichi zero virgola novantotto per zero virgola novantasei per zero virgola novantadue per zero virgola ottantaquattro: circa zero virgola settecentoventisette. Hai perso il ventisette per cento in quattro operazioni."]),
 RIEP(['Cambiare il rischio per umore è il modo più rapido di rovinarsi', 'Ridurre dopo un drawdown, aumentare solo con regole scritte', 'Mai raddoppiare dopo una perdita'], ["Riassumiamo.", "Cambiare il rischio per umore è il modo più rapido di rovinarsi.", "Riduci dopo un drawdown, e aumenta solo con regole scritte in anticipo.", "E mai raddoppiare dopo una perdita."]),
 Q('Se cambi il rischio per **come ti senti**, il tuo piano è già finito.', "Se cambi il rischio per come ti senti, il tuo piano è già finito."),
])
