from h import *
LEZIONE = L('4.5', 'Modulo 4', 'Dimensionare la posizione', 'Più posizioni insieme: esposizione e correlazione', [
 T('LEZIONE 4.5', 'Più posizioni, **un solo rischio**?', 'Quando tre trade sono in realtà uno solo.', "Lezione quattro punto cinque. Più posizioni insieme: esposizione e correlazione."),
 F('L\'esposizione totale', 'Rischio aperto = somma dei rischi di tutte le posizioni', [('Tre trade all\'1%', 'rischio aperto 3%'), ('Limite tipico', 'tra 2% e 4%, deciso prima'), ('Cosa include', 'solo i trade con stop non ancora a pareggio')],
  ["Ogni posizione ha il suo rischio, ma conta anche quello totale.", "Il rischio aperto è la somma dei rischi di tutte le posizioni. Tre trade all'uno per cento portano il rischio aperto al tre.", "Un limite tipico è tra il due e il quattro per cento, deciso prima.", "Conta solo ciò che puoi ancora perdere: una posizione con stop a pareggio non aggiunge rischio."]),
 P('Il problema della correlazione', [('Alcuni strumenti si muovono insieme', 'EURUSD, GBPUSD e AUDUSD spesso reagiscono allo stesso dollaro'), ('Tre buy possono essere una sola scommessa', 'sul dollaro debole'), ('Se la tesi sbaglia, sbagliano tutti e tre', 'e perdi tre stop insieme')],
  ["Il problema è la correlazione.", "Alcuni strumenti si muovono insieme. EURUSD, GBPUSD e AUDUSD spesso reagiscono tutti allo stesso dollaro.", "Tre operazioni di acquisto possono essere una sola scommessa, sul dollaro debole.", "E se la tesi è sbagliata, sbagliano tutte e tre insieme: perdi tre stop nello stesso momento."]),
 CF('Tre posizioni, due situazioni', dict(t='Diversificate', punti=[['EURUSD long', '1%'], ['Oro long', '1%'], ['Indice short', '1%'], ['Rischio effettivo', '~3% ma sparso']]), dict(t='Correlate', punti=[['EURUSD long', '1%'], ['GBPUSD long', '1%'], ['AUDUSD long', '1%'], ['Rischio effettivo', '~3% su una tesi']]),
  ["Guarda tre posizioni da uno per cento.", "Se sono su mercati diversi, come un cambio, l'oro e un indice, il rischio è tre per cento ma distribuito su idee diverse.", "Se sono tre coppie contro il dollaro, il rischio è tre per cento su una sola tesi: dollaro debole.", "Nel caso peggiore, la seconda situazione si comporta come una posizione al tre per cento."], 'Stesso rischio nominale. Rischio reale molto diverso.'),
 P('Regole pratiche', [('Fissa un limite al rischio aperto', 'per esempio 3% in totale'), ('Conta le posizioni correlate come un unico trade', 'e dividi tra loro un solo rischio'), ('Verifica la direzione contro la stessa valuta', 'tre buy contro USD sono un solo trade')],
  ["Tre regole pratiche.", "Fissa un limite al rischio aperto totale, per esempio tre per cento.", "Conta le posizioni correlate come un unico trade: dividi tra loro un solo rischio, non tre.", "E controlla sempre la valuta in comune: tre acquisti contro il dollaro sono, di fatto, un solo trade."]),
 *ES('rischio aperto', [['Posizioni', '4, ciascuna 0,75%'], ['Di cui correlate', '3 (tutte contro USD)'], ['Domanda', 'rischio aperto totale e su una tesi?']], [['Totale', '4 × 0,75% = 3,0%'], ['Tesi USD', '3 × 0,75% = 2,25%']], 'Totale 3,0%; di cui 2,25% su un\'unica tesi',
  ["Esercizio. Hai quattro posizioni da zero virgola settantacinque per cento ciascuna, tre delle quali tutte contro il dollaro. Qual è il rischio aperto totale e quanto è concentrato su una sola tesi?", "Il totale è tre per cento. Tre posizioni sono sulla stessa tesi: due virgola venticinque per cento su un'unica idea. Se hai fissato un limite al due per cento per tesi, devi ridurre."]),
 RIEP(['Rischio aperto = somma dei rischi di tutte le posizioni', 'Strumenti correlati = una sola scommessa', 'Fissa un limite totale e un limite per tesi'], ["Riassumiamo.", "Il rischio aperto è la somma dei rischi di tutte le posizioni.", "Strumenti correlati valgono come una sola scommessa.", "E fissa un limite totale e uno per ogni tesi. Con questo il modulo quattro è finito: da qui passiamo a simulare."]),
 Q('Tre posizioni sulla stessa idea sono **un solo trade** con **tre volte il rischio**.', "Tre posizioni sulla stessa idea sono un solo trade con tre volte il rischio."),
])
