from h import *
LEZIONE = L('5.1', 'Modulo 5', 'Simulare', 'Cos\'è la simulazione Monte Carlo', [
 T('LEZIONE 5.1', 'La simulazione **Monte Carlo**', 'Un solo passato non basta: simuliamo migliaia di futuri possibili.', "Lezione cinque punto uno. Cos'è la simulazione Monte Carlo."),
 P('Il limite di un backtest', [('Un backtest mostra una sola sequenza di trade', 'quella che è realmente accaduta'), ('Con un ordine diverso, lo stesso sistema avrebbe avuto un altro drawdown', 'le statistiche sono uguali, il percorso no'), ('Il futuro sarà un\'altra sequenza', 'quindi serve vedere molte sequenze possibili')],
  ["Un backtest mostra una sola sequenza di operazioni, quella che è realmente accaduta.", "Con un ordine diverso, lo stesso sistema avrebbe avuto un altro drawdown. Le statistiche sono uguali, il percorso no.", "E il futuro sarà un'altra sequenza ancora. Serve quindi vedere molte sequenze possibili."]),
 P('Come funziona', [('1. Parti dalle statistiche del sistema', 'win rate, guadagno medio, perdita media'), ('2. Genera una sequenza casuale di trade', 'ogni trade vince o perde con la probabilità data'), ('3. Calcola l\'andamento del conto con il tuo rischio', 'e registra capitale finale e drawdown'), ('4. Ripeti migliaia di volte', 'e guarda la distribuzione dei risultati')],
  ["Ecco come funziona.", "Primo: parti dalle statistiche del sistema, cioè win rate, guadagno medio e perdita medio.", "Secondo: generi una sequenza casuale di trade, dove ognuno vince o perde con la probabilità data.", "Terzo: calcoli l'andamento del conto con il tuo rischio per trade, e registri capitale finale e drawdown.", "Quarto: ripeti migliaia di volte, e osservi la distribuzione dei risultati."]),
 G('Un ventaglio di futuri', 'montecarlo', ["Ecco il risultato per il nostro sistema di esempio, a rischio uno per cento, su duecento operazioni. Le linee grigie sono singoli percorsi simulati.", "La linea verde è la mediana, quella che ti aspetti nel caso tipico. Le linee azzurre racchiudono l'ottanta per cento dei casi: sotto la linea inferiore ci finisce il dieci per cento dei percorsi, sopra la superiore un altro dieci."], 'Stesso sistema, centinaia di percorsi diversi.'),
 CF('Cosa può e non può fare', dict(t='Può', punti=[['Mostrare la gamma di esiti', ''], ['Stimare drawdown e rovina', ''], ['Confrontare livelli di rischio', '']]), dict(t='Non può', punti=[['Prevedere il futuro', ''], ['Correggere statistiche sbagliate', ''], ['Considerare cambi di mercato', '']]),
  ["Cosa può e cosa non può fare.", "Può mostrare la gamma di esiti possibili, stimare drawdown e probabilità di rovina, e confrontare livelli di rischio diversi.", "Non può prevedere il futuro, non corregge statistiche sbagliate, e non considera i cambi di regime del mercato.", "È uno strumento per capire l'ordine di grandezza del rischio, non una palla di vetro."], 'Garbage in, garbage out: le stime in ingresso contano.'),
 *ES('Monte Carlo', [['Domanda', 'perché un solo backtest non basta?']], [['Risposta', 'È una sola sequenza possibile'], ['Con un altro ordine', 'cambiano drawdown e percorso']], 'Servono molte sequenze per vedere la gamma',
  ["Domanda per te. Perché un solo backtest non basta a giudicare il rischio?", "Perché è una sola sequenza possibile. Con un altro ordine delle stesse operazioni, il drawdown sarebbe stato diverso. Servono molte sequenze per vedere la gamma di esiti."]),
 RIEP(['Il backtest è una sola sequenza possibile', 'Monte Carlo simula migliaia di sequenze dalle statistiche del sistema', 'Mostra la gamma di esiti, non una previsione'], ["Riassumiamo.", "Il backtest è una sola sequenza possibile.", "Monte Carlo simula migliaia di sequenze partendo dalle statistiche del sistema.", "Mostra la gamma di esiti, non una previsione."]),
 Q('Non chiederti cosa **succederà**. Chiediti cosa **può succedere**.', "Non chiederti cosa succederà. Chiediti cosa può succedere."),
])
