from h import *
LEZIONE = L('5.2', 'Modulo 5', 'Simulare', 'Leggere il ventaglio dei risultati', [
 T('LEZIONE 5.2', 'Leggere il **ventaglio**', 'Mediana, percentili e cosa significa «caso brutto».', "Lezione cinque punto due. Leggere il ventaglio dei risultati."),
 P('I tre numeri da guardare', [('Mediana', 'il risultato in mezzo: metà dei percorsi fa meglio, metà peggio'), ('10° percentile', 'solo un percorso su dieci va peggio di così: il caso sfortunato'), ('90° percentile', 'solo uno su dieci va meglio: il caso fortunato')],
  ["Tre numeri da guardare in una simulazione.", "La mediana: il risultato in mezzo. Metà dei percorsi fa meglio, metà fa peggio.", "Il decimo percentile: solo un percorso su dieci va peggio di così. È il caso sfortunato.", "Il novantesimo percentile: solo uno su dieci va meglio. È il caso fortunato."]),
 TB('Sistema di esempio, rischio 1%, 200 trade', ['Misura', 'Risultato'], [['10° percentile', 'circa +28%'], ['Mediana', 'circa +65%'], ['90° percentile', 'circa +112%'], ['Percorsi che finiscono sotto lo zero', 'meno dell\'1%'], ['Drawdown massimo tipico', 'circa −10%']],
  ["Ecco i numeri del nostro sistema di esempio, rischiando l'uno per cento su duecento operazioni.", "Nel caso sfortunato, il decimo percentile, il capitale cresce comunque di circa il ventotto per cento.", "Nel caso tipico di circa il sessantacinque.", "Nel caso fortunato, di circa il centododici.", "Meno dell'uno per cento dei percorsi finisce sotto il capitale iniziale.", "E il drawdown massimo tipico è intorno al dieci per cento."], nota='Simulazione illustrativa: non è una previsione.'),
 CF('Stesso sistema, due rischi', dict(t='Rischio 1%', punti=[['Caso sfortunato (10°)', '+28%'], ['Tipico', '+65%'], ['Drawdown tipico', '−10%']]), dict(t='Rischio 2%', punti=[['Caso sfortunato (10°)', '+59%'], ['Tipico', '+161%'], ['Drawdown tipico', '−19%']]),
  ["Cosa succede raddoppiando il rischio?", "Con l'uno per cento: caso sfortunato più ventotto, tipico più sessantacinque, drawdown tipico meno dieci.", "Con il due per cento: caso sfortunato più cinquantanove, tipico più centosessantuno, drawdown tipico meno diciannove.", "Il guadagno tipico sale di due volte e mezzo, il drawdown raddoppia. Ma la scelta dipende da quanto sopporti, non dal risultato più alto."], 'Più rendimento, ma anche più dolore.'),
 P('Strumenti: i calcolatori Riskly (un mio prodotto)', [('Puoi ripetere questa simulazione con i tuoi numeri', 'inserendo win rate, rapporto, rischio e numero di trade'), ('Sul sito riskly.trade ci sono calcolatori gratuiti', 'sono miei: li dichiaro, come tutti i prodotti Riskly'), ('Va bene qualunque strumento, anche un foglio di calcolo', 'l\'importante è usare numeri onesti')],
  ["Puoi ripetere questa simulazione con i tuoi numeri, inserendo win rate, rapporto, rischio e numero di operazioni.", "Sul sito riskly punto trade ci sono calcolatori gratuiti. Dichiaro che sono miei, come tutti i prodotti Riskly.", "Ma va bene qualunque strumento, anche un foglio di calcolo: l'importante è usare numeri onesti."]),
 *ES('leggere i percentili', [['Simulazione', '10° percentile: −8%'], ['', 'Mediana: +30%'], ['', '90° percentile: +75%'], ['Domanda', 'cosa significa il −8%?']], [['Significato', 'Un percorso su dieci finisce peggio di −8%'], ['Non significa', 'che il peggior caso possibile sia −8%']], 'Il caso peggiore reale può essere peggiore',
  ["Esercizio. In una simulazione il decimo percentile è meno otto per cento, la mediana più trenta, il novantesimo più settantacinque. Cosa significa il meno otto?", "Che un percorso su dieci finisce peggio di meno otto per cento. Non significa che meno otto sia il caso peggiore: il peggiore esistente può essere molto peggiore. Guarda sempre anche le code."]),
 RIEP(['Guarda mediana, 10° e 90° percentile', 'Il 10° percentile è un caso sfortunato, non il peggiore', 'Raddoppiare il rischio raddoppia circa il drawdown: scegli in base al tuo comfort'], ["Riassumiamo.", "Guarda la mediana e il decimo e novantesimo percentile.", "Il decimo percentile è un caso sfortunato, non il peggiore possibile.", "E scegli il rischio in base al tuo comfort, non al risultato più alto."]),
 Q('La mediana ti dice **cosa aspettarti**. Il decimo percentile ti dice **cosa sopportare**.', "La mediana ti dice cosa aspettarti. Il decimo percentile ti dice cosa sopportare."),
])
