from h import *
LEZIONE = L('5.3', 'Modulo 5', 'Simulare', 'La probabilità di rovina', [
 T('LEZIONE 5.3', 'La probabilità di **rovina**', 'Quanto è probabile toccare il punto da cui non vuoi tornare indietro.', "Lezione cinque punto tre. La probabilità di rovina."),
 P('Prima di tutto, definire la rovina', [('Non è sempre «azzerare il conto»', 'per un trader prop può essere superare il limite di drawdown'), ('La definisci tu, in anticipo', 'per esempio: perdere il 30% del capitale iniziale'), ('La probabilità di rovina = percorsi che toccano quella soglia', 'su tutti i percorsi simulati')],
  ["Prima di tutto bisogna definire la rovina. Non è sempre azzerare il conto.", "La definisci tu, in anticipo. Per esempio: perdere il trenta per cento del capitale iniziale.", "La probabilità di rovina è la percentuale di percorsi simulati che toccano quella soglia."]),
 TB('Probabilità di toccare −30% dal capitale iniziale', ['Rischio per trade', 'Probabilità', 'Lettura'], [['0,5%', '~0%', 'molto sicuro'], ['1%', '~0%', 'molto sicuro'], ['2%', '~0,7%', 'bassa'], ['3%', '~4%', 'da non ignorare'], ['5%', '~17%', 'rischio alto']],
  ["Per il nostro sistema di esempio, su duecento operazioni, ecco la probabilità di perdere almeno il trenta per cento del capitale iniziale.", "Con lo zero virgola cinque e con l'uno per cento: praticamente zero.", "Con il due per cento: circa lo zero virgola sette per cento.", "Con il tre per cento: circa il quattro per cento. Una volta su venticinque.", "Con il cinque per cento: circa il diciassette. Quasi una volta su sei."], nota='Sistema: 45% di vincite, +1,8 R / −1 R. Simulazione, non previsione.', k=[1,2,3,4,6]),
 P('Attenzione: la rovina dipende dal sistema', [('Con un win rate più basso la rovina sale molto', 'vedremo cosa succede nello stress test'), ('Le stime sono ottimistiche se il vantaggio è sovrastimato', 'un sistema senza vantaggio ha rovina molto più alta'), ('Non è mai zero', 'anche con rischio basso, un\'ipotesi sbagliata può rovinare tutto')],
  ["Attenzione: la rovina dipende dal sistema.", "Con un win rate più basso la probabilità sale molto, e lo vedremo nello stress test.", "Se il vantaggio è sovrastimato, le stime sono ottimistiche. Un sistema senza vantaggio ha una rovina molto più alta.", "E non è mai zero: anche con un rischio basso, un'ipotesi sbagliata può rovinare tutto."]),
 *ES('lettura', [['Rischio per trade', '3%'], ['Probabilità di rovina', '~4%'], ['Domanda', 'è accettabile?']], [['In concreto', '1 trader su 25 tocca −30%'], ['Per una prova a pagamento', 'può essere troppo'], ['Per un capitale piccolo', 'dipende dal tuo comfort']], 'Decidi tu la soglia, prima',
  ["Esercizio. Rischio tre per cento, probabilità di rovina circa quattro per cento. È accettabile?", "Significa che un trader su venticinque con questo sistema tocca il meno trenta. Per una prova a pagamento può essere troppo. Per un piccolo capitale dipende dal tuo comfort. La cosa importante è decidere la soglia prima, non dopo."]),
 RIEP(['La rovina va definita in anticipo', 'Con rischio 1% è quasi nulla; col 5% è circa una volta su sei', 'Dipende da un vantaggio reale: se non c\'è, la rovina è molto più alta'], ["Riassumiamo.", "La rovina va definita in anticipo.", "Con il sistema di esempio è quasi nulla a rischio uno per cento, e circa una volta su sei a rischio cinque per cento.", "E dipende da un vantaggio reale: se non c'è, la rovina è molto più alta."]),
 Q('La rovina non è un **evento**. È una **probabilità** che scegli tu con il rischio.', "La rovina non è un evento. È una probabilità che scegli tu con il rischio."),
])
