from h import *
LEZIONE = L('5.4', 'Modulo 5', 'Simulare', 'Lo stress test del piano', [
 T('LEZIONE 5.4', 'Lo **stress test**', 'E se le tue statistiche fossero peggiori di quelle misurate?', "Lezione cinque punto quattro. Lo stress test del piano."),
 P('Perché stressare', [('Le tue statistiche sono stime', 'con pochi trade possono essere ottimistiche'), ('I mercati cambiano', 'un vantaggio può ridursi nel tempo'), ('I costi reali possono essere più alti', 'spread, slippage, commissioni')],
  ["Perché stressare un piano? Perché le tue statistiche sono stime, e con pochi trade possono essere ottimistiche.", "Perché i mercati cambiano e un vantaggio può ridursi nel tempo.", "E perché i costi reali possono essere più alti di quelli previsti."]),
 TB('Quattro scenari, rischio 1%', ['Scenario', 'Drawdown tipico', 'Rovina (−30%)', 'Chiudono sotto zero'], [['Base: 45% vinte', '−10%', '~0%', '~1%'], ['Win rate 40%', '−13%', '~0,4%', '~14%'], ['40% con costi più alti', '−16%', '~2%', '~31%'], ['Win rate 35%', '−21%', '~9%', '~65%']],
  ["Facciamo il test con il rischio all'uno per cento. Quattro scenari.", "Base: quarantacinque per cento di vincite. Drawdown tipico meno dieci, rovina praticamente zero, solo l'uno per cento dei percorsi chiude sotto zero.", "Se il win rate è quaranta per cento: drawdown tipico meno tredici, rovina zero virgola quattro, ma quattordici percorsi su cento chiudono in perdita.", "Con il quaranta e costi più alti: meno sedici, rovina circa due per cento e un terzo dei percorsi chiude in perdita.", "Con il trentacinque per cento il sistema non ha più vantaggio: drawdown meno ventuno, rovina circa nove per cento, due percorsi su tre chiudono in perdita."], nota='Costi più alti: guadagno medio 1,74 R, perdita media 1,06 R.'),
 TB('Gli stessi scenari, rischio 2%', ['Scenario', 'Drawdown tipico', 'Rovina (−30%)'], [['Base: 45% vinte', '−19%', '~0,7%'], ['Win rate 40%', '−25%', '~9%'], ['40% con costi più alti', '−30%', '~21%'], ['Win rate 35%', '−38%', '~47%']],
  ["Ora lo stesso test con il due per cento.", "Base: meno diciannove, rovina circa zero virgola sette.", "Win rate quaranta: drawdown meno venticinque, rovina circa nove per cento.", "Con costi più alti: meno trenta, rovina circa ventuno per cento.", "Con trentacinque per cento: meno trentotto e rovina quasi una volta su due."], nota='Sistema di esempio, 200 trade.'),
 P('Cosa ne ricavi', [('Un rischio che regge solo nello scenario migliore è fragile', 'il piano deve reggere anche lo scenario brutto'), ('Dimezzare il rischio riduce molto la rovina', 'da ~9% a ~0,4% nel caso a win rate 40%, passando da 2% a 1%'), ('Se il vantaggio sparisce, nessun rischio ti salva', 'il dato più importante è sapere quando fermarti')],
  ["Cosa ne ricavi?", "Un rischio che regge solo nello scenario migliore è fragile. Il piano deve reggere anche lo scenario brutto.", "Dimezzare il rischio riduce moltissimo la rovina: nel caso a win rate quaranta, da circa nove per cento a circa zero virgola quattro, passando dal due all'uno.", "E se il vantaggio sparisce, nessun rischio ti salva. Per questo conta anche sapere quando fermarsi e riesaminare il sistema."]),
 *ES('stress test', [['Il tuo piano', 'rischio 2%'], ['Scenario win rate 40%', 'rovina ~9%'], ['Domanda', 'cosa fai?']], [['Opzione 1', 'scendere all\'1% (rovina ~0,4%)'], ['Opzione 2', 'accettare ~9% se il capitale è piccolo'], ['Regola', 'decidere con numeri, prima']], 'Meglio un piano che regge anche lo scenario brutto',
  ["Esercizio. Il tuo piano prevede il due per cento a trade. Nello scenario con win rate quaranta, la rovina è circa nove per cento. Cosa fai?", "Puoi scendere all'uno per cento, dove la rovina scende a circa zero virgola quattro. Oppure accettare il nove per cento, se il capitale in gioco è piccolo e lo hai deciso a mente fredda. Ma decidi con i numeri, prima di operare."]),
 RIEP(['Stressa il piano: win rate più basso, costi più alti', 'Dimezzare il rischio riduce molto la rovina', 'Un buon piano regge anche lo scenario brutto'], ["Riassumiamo.", "Stressa il piano: win rate più basso, costi più alti.", "Dimezzare il rischio riduce molto la probabilità di rovina.", "Un buon piano regge anche lo scenario brutto. Con questo si chiude il modulo sulla simulazione."]),
 Q('Un piano non si giudica nel caso **migliore**. Si giudica nel caso **brutto**.', "Un piano non si giudica nel caso migliore. Si giudica nel caso brutto."),
])
