from h import *
LEZIONE = L('6.1', 'Modulo 6', 'Disciplina', 'Regole scritte prima di operare', [
 T('LEZIONE 6.1', 'Le regole si scrivono **prima**', 'Decidere a mente fredda quello che non saprai decidere sotto stress.', "Lezione sei punto uno. Regole scritte prima di operare."),
 P('Perché servono regole scritte', [('Durante il trade sei sotto stress', 'e lo stress riduce la lucidità'), ('Le decisioni prese prima sono migliori', 'non c\'è un grafico che ti agita mentre le scrivi'), ('Una regola scritta toglie la scelta', 'o la rispetti o la violi: non puoi più negoziare con te stesso')],
  ["Perché servono regole scritte?", "Perché durante il trade sei sotto stress, e lo stress riduce la lucidità.", "Le decisioni prese prima sono migliori: non c'è un grafico che ti agita mentre le scrivi.", "E una regola scritta toglie la scelta. O la rispetti, o la violi. Non puoi più negoziare con te stesso."]),
 CF('Da vago a verificabile', dict(t='Vago', punti=[['«Non rischiare troppo»', ''], ['«Fermati se vai male»', ''], ['«Sii paziente»', '']]), dict(t='Verificabile', punti=[['Max 1% per trade', ''], ['Stop dopo 3 perdite in un giorno', ''], ['Max 2 trade per sessione', '']]),
  ["La differenza tra un buon proposito e una regola.", "A sinistra frasi vaghe: non rischiare troppo, fermati se vai male, sii paziente. Nessuna si può verificare.", "A destra regole verificabili: massimo uno per cento per trade, stop dopo tre perdite in un giorno, massimo due trade per sessione.", "Se non puoi controllare con un sì o un no di averla rispettata, non è una regola."], 'Una regola ha un numero e una condizione.'),
 P('Il formato: se… allora…', [('SE la perdita del giorno arriva al 3%', 'ALLORA chiudo la piattaforma fino a domani'), ('SE ho perso 3 trade di fila', 'ALLORA mi fermo per la sessione'), ('SE il rischio aperto è già al limite', 'ALLORA non apro nuove posizioni')],
  ["Un formato efficace è: se, allora.", "Se la perdita del giorno arriva al tre per cento, allora chiudo la piattaforma fino a domani.", "Se ho perso tre trade di fila, allora mi fermo per la sessione.", "Se il rischio aperto è già al limite, allora non apro nuove posizioni. Ogni regola ha la sua condizione e la sua azione, decise prima."]),
 TB('Le regole minime di un piano di rischio', ['Regola', 'Esempio'], [['Rischio per trade', '1%'], ['Rischio aperto massimo', '3%'], ['Perdita massima giornaliera', '3%'], ['Perdite di fila → stop', '3'], ['Trade massimi al giorno', '3'], ['Drawdown → riduco il rischio', 'oltre 10%']],
  ["Ecco le regole minime di un piano di rischio, con valori di esempio.", "Rischio per trade: uno per cento.", "Rischio aperto massimo: tre per cento.", "Perdita massima giornaliera: tre per cento.", "Dopo tre perdite di fila, stop.", "Massimo tre trade al giorno.", "E se il drawdown supera il dieci per cento, riduco il rischio. I valori sono i tuoi da decidere: l'importante è che esistano e siano scritti."], nota='Valori di esempio, da calibrare sul proprio sistema.'),
 *ES('trasforma in regola', [['Frase vaga', '«Quando sono giù, non esagero»']], [['Condizione', 'drawdown oltre il 10%'], ['Azione', 'rischio dimezzato finché non recupero 5%']], 'SE drawdown > 10% ALLORA rischio 0,5%',
  ["Esercizio. Trasforma in una regola verificabile la frase: quando sono giù, non esagero.", "Una possibile versione: se il drawdown supera il dieci per cento, allora il rischio per trade è dimezzato finché non recupero cinque punti. Ha una condizione, un numero e un'azione."]),
 RIEP(['Le regole si scrivono a mente fredda', 'Una regola ha un numero, una condizione e un\'azione', 'Formato: SE… ALLORA…'], ["Riassumiamo.", "Le regole si scrivono a mente fredda.", "Una regola ha un numero, una condizione e un'azione.", "Usa il formato: se, allora."]),
 Q('Una regola che puoi **negoziare** non è una regola.', "Una regola che puoi negoziare non è una regola."),
])
