from h import *
LEZIONE = L('6.2', 'Modulo 6', 'Disciplina', 'I limiti giornalieri e lo stop dopo le perdite', [
 T('LEZIONE 6.2', 'Quando **fermarsi**', 'Limite giornaliero, stop dopo N perdite e chiusura dopo l\'obiettivo.', "Lezione sei punto due. I limiti giornalieri e lo stop dopo le perdite."),
 P('La giornata storta', [('Ogni sistema ha giornate con più perdite del normale', 'è statistica, non sfortuna personale'), ('Il rischio vero è continuare a operare mentre sei fuori controllo', 'le decisioni peggiori arrivano dopo le prime perdite'), ('Un limite fisso trasforma il danno possibile in un danno massimo', 'sai già il peggio che può capitare in un giorno')],
  ["Ogni sistema ha giornate con più perdite del normale. È statistica, non sfortuna personale.", "Il rischio vero è continuare a operare quando sei fuori controllo: le decisioni peggiori arrivano dopo le prime perdite.", "Un limite fisso trasforma il danno possibile in un danno massimo: sai già il peggio che può capitare in un giorno."]),
 TB('Limite giornaliero con rischio 1%', ['Limite giornaliero', 'Perdite pienamente prese', 'Perdita reale'], [['2%', '2', '−1,99%'], ['3%', '3', '−2,97%'], ['4%', '4', '−3,94%']],
  ["Vediamo cosa significa un limite giornaliero con rischio uno per cento a trade.", "Un limite del due per cento equivale a due perdite piene: perdita reale meno uno virgola novantanove.", "Un limite del tre per cento a tre perdite piene: meno due virgola novantasette.", "Un limite del quattro per cento, quattro perdite: meno tre virgola novantaquattro. Il numero di perdite si traduce direttamente in una soglia."], nota='Composizione: 1 − 0,99ⁿ'),
 P('Tre tipi di stop', [('Limite di perdita giornaliero', 'oltre una soglia in %, chiudi la giornata'), ('Stop dopo N perdite di fila', 'per esempio 3: pausa per il resto della sessione'), ('Chiusura dopo l\'obiettivo', 'raggiunto il target giornaliero, ti fermi: non restituire i guadagni')],
  ["Tre tipi di stop.", "Il limite di perdita giornaliero: oltre una soglia in percentuale, chiudi la giornata.", "Lo stop dopo N perdite di fila: per esempio tre, e fai pausa per il resto della sessione.", "E la chiusura dopo l'obiettivo: raggiunto il target giornaliero, ti fermi. Molti perdono nel pomeriggio quello che hanno guadagnato al mattino."]),
 EX('Senza limite contro con limite', [['Giornata storta: 6 perdite da 1%', '−5,9%'], ['Con limite 3% (stop alla terza)', '−2,97%'], ['Danno evitato', 'circa 3 punti']], risultato='Il limite ti salva dalla spirale', k=[1,2,3,4],
  voce=["Mettiamo a confronto due scenari.", "Una giornata storta senza limite: sei perdite da uno per cento fanno meno cinque virgola nove per cento.", "Con un limite del tre per cento ti fermi alla terza: meno due virgola novantasette.", "Hai evitato circa tre punti di perdita. Non è tutto qui: hai anche evitato la spirale emotiva che porta a sbagliare di più."]),
 *ES('limite e perdite', [['Rischio per trade', '0,5%'], ['Limite giornaliero', '2%'], ['Domanda', 'dopo quante perdite piene ti fermi?']], [['Calcolo', '2% ÷ 0,5%'], ['Perdite', '4']], 'Dopo 4 perdite piene',
  ["Esercizio. Rischio zero virgola cinque per cento a trade, limite giornaliero due per cento. Dopo quante perdite piene ti fermi?", "Due diviso zero virgola cinque: quattro perdite."]),
 RIEP(['Un limite fisso trasforma il danno possibile in danno massimo', 'Tre stop: perdita giornaliera, N perdite di fila, obiettivo raggiunto', 'Perdite pienamente prese = limite ÷ rischio per trade'], ["Riassumiamo.", "Un limite fisso trasforma il danno possibile in danno massimo.", "Tre stop: perdita giornaliera, perdite di fila e obiettivo raggiunto.", "E il numero di perdite piene è il limite diviso il rischio per trade."]),
 Q('Il miglior trade dopo una **giornata storta** è non farlo.', "Il miglior trade dopo una giornata storta è non farlo."),
])
