from h import *
LEZIONE = L('6.3', 'Modulo 6', 'Disciplina', 'Revenge trading e overtrading', [
 T('LEZIONE 6.3', 'Revenge trading e **overtrading**', 'Riconoscere i due errori comportamentali più costosi.', "Lezione sei punto tre. Revenge trading e overtrading."),
 CF('Due errori, due cause', dict(t='Revenge trading', punti=[['Dopo una perdita', ''], ['Voglia di rifarsi subito', ''], ['Rischio più alto, setup peggiore', '']]), dict(t='Overtrading', punti=[['Troppe operazioni', ''], ['Noia o bisogno di azione', ''], ['Setup di qualità bassa e più costi', '']]),
  ["Due errori comportamentali molto costosi.", "Il revenge trading: dopo una perdita, voglia di rifarsi subito. Il rischio sale e la qualità del setup scende.", "L'overtrading: troppe operazioni, per noia o per bisogno di azione. Setup di bassa qualità e più costi."], 'Nessuno dei due è un problema di strategia.'),
 P('I segnali di allarme', [('Apri un trade senza aver aspettato il setup', 'solo perché «devi recuperare»'), ('Aumenti il lotto dopo una perdita', 'senza averlo previsto nel piano'), ('Sposti lo stop o lo tolgi', 'per non «subire» la perdita'), ('Controlli il conto ogni minuto', 'e il tuo umore dipende dal numero')],
  ["I segnali di allarme.", "Apri un trade senza aver aspettato il setup, solo perché devi recuperare.", "Aumenti il lotto dopo una perdita, senza averlo previsto nel piano.", "Sposti lo stop, o lo togli, per non subire la perdita.", "Controlli il conto ogni minuto, e il tuo umore dipende da quel numero."]),
 P('Le contromisure', [('Un tetto di operazioni al giorno', 'per esempio 3: dopo il terzo, finisce la sessione'), ('Una pausa obbligatoria dopo ogni perdita', 'per esempio 15 minuti lontano dallo schermo'), ('Un limite di perdita che chiude la giornata', 'come nella lezione precedente'), ('Segnare ogni trade fuori piano nel journal', 'così vedi quanto ti costano davvero')],
  ["Le contromisure sono concrete.", "Un tetto di operazioni al giorno: per esempio tre. Dopo il terzo, la sessione è finita.", "Una pausa obbligatoria dopo ogni perdita: per esempio quindici minuti lontano dallo schermo.", "Un limite di perdita che chiude la giornata, come nella lezione precedente.", "E segnare nel journal ogni trade fuori piano, così vedi quanto ti costano davvero."]),
 EX('Quanto costa un trade fuori piano', [['Trade nel piano', 'expectancy +0,26 R'], ['Costo di ogni trade', 'circa 0,06 R'], ['Trade fuori piano', 'vantaggio sconosciuto, stessi costi'], ['5 trade extra al giorno', '≈ −0,30 R di soli costi']], risultato='Più operazioni ≠ più guadagno', k=[1,2,3,4,5],
  voce=["Quanto costa un trade fuori piano? Facciamo un conto semplice.", "Un trade nel piano ha, nel nostro esempio, un'expectancy di più zero virgola ventisei R.", "Ogni trade costa circa zero virgola zero sei R tra spread e commissioni.", "Un trade fuori piano non ha un vantaggio dimostrato, ma paga gli stessi costi.", "Cinque trade extra al giorno sono circa meno zero virgola trenta R di soli costi: più dell'expectancy di un'intera operazione nel piano. Più operazioni non significano più guadagno."]),
 *ES('scrivi la tua regola', [['Situazione', 'hai appena perso 2 trade di fila'], ['Domanda', 'scrivi la regola SE… ALLORA…']], [['Esempio', 'SE perdo 2 trade di fila'], ['', 'ALLORA 15 minuti di pausa, poi rivaluto'], ['Se il terzo è fuori piano', 'sessione chiusa']], 'Una regola che puoi controllare con sì o no',
  ["Esercizio. Hai appena perso due trade di fila. Scrivi la tua regola nel formato se, allora.", "Un esempio: se perdo due trade di fila, allora quindici minuti di pausa e poi rivaluto. Se il terzo trade non è nel piano, la sessione è chiusa. Scrivi la tua e mettila vicino allo schermo."]),
 RIEP(['Revenge trading: rifarsi subito. Overtrading: troppe operazioni', 'Contromisure: tetto di trade, pausa dopo le perdite, limite giornaliero', 'Registra i trade fuori piano per vederne il costo'], ["Riassumiamo.", "Revenge trading significa rifarsi subito, overtrading troppe operazioni.", "Le contromisure sono un tetto di trade, una pausa dopo le perdite e un limite giornaliero.", "E registra i trade fuori piano nel journal per vederne il costo."]),
 Q('Non hai bisogno di un trade **migliore**. Hai bisogno di una **pausa**.', "Non hai bisogno di un trade migliore. Hai bisogno di una pausa."),
])
