from h import *
LEZIONE = L('6.4', 'Modulo 6', 'Disciplina', 'La checklist pre-trade', [
 T('LEZIONE 6.4', 'La **checklist** pre-trade', 'Un minuto, otto domande, prima di cliccare.', "Lezione sei punto quattro. La checklist pre-trade."),
 P('Perché funziona', [('Gli errori più costosi sono di esecuzione, non di analisi', 'sai cosa fare, ma non lo fai nel momento'), ('Una checklist è un freno', 'ti obbliga a rallentare di un minuto'), ('Piloti e chirurghi la usano', 'non perché non sappiano, ma perché sbagliare costa troppo')],
  ["Perché una checklist? Perché gli errori più costosi sono di esecuzione, non di analisi: sai cosa fare, ma non lo fai nel momento.", "Una checklist è un freno: ti obbliga a rallentare di un minuto.", "Piloti e chirurghi la usano, non perché non sappiano il mestiere, ma perché sbagliare costa troppo."]),
 P('Le otto domande', [('1. È un setup del mio piano?', 'se no, non entro'), ('2. Lo stop è dove invalida l\'idea?', 'non dove mi fa comodo'), ('3. Il rischio è quello previsto?', 'lotto calcolato, non a occhio'), ('4. Il rischio aperto totale è nei limiti?', 'e le posizioni correlate?'), ('5. Il RR è almeno quello minimo?', 'il mio minimo l\'ho deciso prima')],
  ["Le otto domande, prima parte.", "Uno: è un setup del mio piano? Se no, non entro.", "Due: lo stop è dove invalida l'idea, non dove mi fa comodo?", "Tre: il rischio è quello previsto? Il lotto è calcolato, non a occhio.", "Quattro: il rischio aperto totale è nei limiti? E le posizioni correlate?", "Cinque: il RR è almeno il minimo che ho stabilito?"]),
 P('Le ultime tre', [('6. Ci sono notizie importanti a breve?', 'spread e slippage possono saltare'), ('7. Ho raggiunto un limite giornaliero?', 'se sì, la giornata è finita'), ('8. Come sto?', 'stanco, arrabbiato, euforico: non è un buon momento')],
  ["Le ultime tre domande.", "Sei: ci sono notizie importanti a breve? Spread e slippage possono saltare.", "Sette: ho raggiunto un limite giornaliero? Se sì, la giornata è finita.", "Otto: come sto? Stanco, arrabbiato o euforico non sono buoni momenti per operare."]),
 TB('La checklist in pratica', ['Domanda', 'Sì', 'No → cosa fai'], [['Setup del piano', '✓', 'non entro'], ['Stop sull\'invalidazione', '✓', 'rivedo o salto'], ['Rischio ≤ 1%', '✓', 'riduco il lotto'], ['Rischio totale ok', '✓', 'non apro'], ['RR ≥ minimo', '✓', 'salto'], ['Niente notizie', '✓', 'aspetto'], ['Limite non raggiunto', '✓', 'chiudo'], ['Sto bene', '✓', 'pausa']],
  ["Ecco la checklist in forma pratica. Ogni domanda ha una risposta sì e una conseguenza se la risposta è no.", "Per esempio, se il setup non è del piano, non entri. Se lo stop è lontano dall'invalidazione, rivedi l'operazione o la salti. Se il rischio supera l'uno per cento, riduci il lotto.", "Se il rischio totale è oltre il limite, non apri. Se il RR è sotto il minimo, salti.", "Se ci sono notizie importanti aspetti, se hai raggiunto un limite chiudi, e se non stai bene fai una pausa."], k=[1,3,6,8]),
 *ES('applica la checklist', [['Situazione', 'hai già 2 posizioni al 1,5% ciascuna'], ['Limite rischio aperto', '3%'], ['Nuovo setup valido al 1%', 'cosa fai?']], [['Rischio aperto attuale', '3%'], ['Con il nuovo trade', '4% > limite'], ['Decisione', 'non apri (o chiudi/riduci prima)']], 'La domanda 4 blocca l\'ingresso',
  ["Esercizio. Hai già due posizioni da uno e mezzo per cento ciascuna. Il tuo limite di rischio aperto è tre per cento. Compare un nuovo setup valido all'uno per cento. Cosa fai?", "Il rischio aperto attuale è già tre per cento. Con il nuovo trade sarebbe quattro, sopra il limite. La domanda quattro blocca l'ingresso: non apri, oppure riduci o chiudi prima qualcosa."]),
 RIEP(['La checklist ti rallenta di un minuto', 'Otto domande: setup, stop, rischio, esposizione, RR, notizie, limiti, stato', 'Ogni "no" ha già una conseguenza decisa'], ["Riassumiamo.", "La checklist ti rallenta di un minuto.", "Otto domande: setup, stop, rischio, esposizione, RR, notizie, limiti e stato personale.", "E ogni risposta negativa ha già una conseguenza decisa."]),
 Q('La checklist non serve quando tutto va bene. Serve quando **hai fretta**.', "La checklist non serve quando tutto va bene. Serve quando hai fretta."),
])
