from h import *
LEZIONE = L('7.1', 'Modulo 7', 'Prop firm', 'Le regole tipiche delle prop firm', [
 T('LEZIONE 7.1', 'Le regole delle **prop firm**', 'I limiti che decidono se la prova va avanti o finisce.', "Lezione sette punto uno. Le regole tipiche delle prop firm."),
 P('Prima una precisazione', [('Le regole cambiano da firma a firma e nel tempo', 'quelle di questa lezione sono esempi'), ('Leggi sempre il regolamento attuale', 'prima di pagare e prima di operare'), ('Questo corso non è una guida a una prop specifica', 'e non ti dice quale scegliere')],
  ["Prima una precisazione importante. Le regole cambiano da una prop firm all'altra e nel tempo: quelle di questa lezione sono esempi.", "Leggi sempre il regolamento attuale, prima di pagare e prima di operare.", "Questo corso non è una guida a una prop firm specifica e non ti dice quale scegliere."]),
 TB('I limiti più comuni (esempi)', ['Regola', 'Esempio tipico', 'Cosa succede se la violi'], [['Obiettivo di profitto', '8–10% del capitale', 'la fase non si supera'], ['Perdita massima giornaliera', '4–5%', 'conto chiuso o fase fallita'], ['Perdita massima totale', '8–12%', 'conto chiuso'], ['Giorni minimi di trading', '3–5 giorni', 'fase non validata'], ['Tempo massimo', 'a volte 30 giorni, a volte nessuno', 'fase non superata']],
  ["Ecco i limiti più comuni, con valori tipici di esempio.", "L'obiettivo di profitto, spesso tra otto e dieci per cento del capitale.", "La perdita massima giornaliera, spesso tra quattro e cinque per cento.", "La perdita massima totale, spesso tra otto e dodici.", "I giorni minimi di trading, di solito pochi.", "E, in alcuni casi, un tempo massimo per completare la fase."], nota='Valori di esempio. Verifica il regolamento della tua prop.'),
 P('Due tipi di perdita massima', [('Statica', 'il limite resta fisso: capitale iniziale meno X%'), ('Trailing', 'il limite sale con i tuoi massimi: massimo raggiunto meno X%'), ('Cambia molto la gestione del rischio', 'la trailing è molto più stringente')],
  ["La perdita massima totale può essere di due tipi.", "Statica: il limite resta fisso, capitale iniziale meno una percentuale.", "Trailing: il limite sale con i tuoi massimi, massimo raggiunto meno una percentuale.", "La differenza cambia molto la gestione del rischio, e la trailing è molto più stringente."]),
 EX('Il limite giornaliero è un tetto reale', [['Capitale', '100.000 €'], ['Limite giornaliero', '5% = 5.000 €'], ['Rischio per trade', '1% = 1.000 €'], ['Perdite piene per avvicinarsi', 'circa 5']], risultato='Con 5–6 stop consecutivi sei fuori', k=[1,2,3,4,5],
  voce=["Un esempio. Capitale centomila euro.", "Limite giornaliero cinque per cento: cinquemila euro.", "Rischio per trade uno per cento: mille euro.", "Per avvicinarti al limite bastano circa cinque perdite piene.", "Cinque o sei stop consecutivi in una giornata sono rari ma possibili, e a quel punto la prova è finita. Il piano non deve arrivare lì."]),
 *ES('quante perdite', [['Limite giornaliero', '4%'], ['Rischio per trade', '0,5%'], ['Domanda', 'perdite piene per toccarlo?']], [['Calcolo', '4% ÷ 0,5%'], ['Perdite', '8']], 'Servirebbero 8 perdite piene',
  ["Esercizio. Limite giornaliero quattro per cento, rischio zero virgola cinque per cento a trade. Quante perdite piene servono per toccarlo?", "Quattro diviso zero virgola cinque: otto perdite. Un margine ampio."]),
 RIEP(['Le regole sono esempi: leggi sempre il regolamento attuale', 'Perdita giornaliera e totale sono i limiti che contano', 'Statica o trailing cambia tutto'], ["Riassumiamo.", "Le regole sono esempi: leggi sempre il regolamento attuale.", "Perdita giornaliera e perdita totale sono i limiti che contano.", "E la differenza tra perdita statica e trailing cambia tutta la gestione del rischio."]),
 Q('Non ti chiedono di essere **bravo**. Ti chiedono di **non sforare**.', "Non ti chiedono di essere bravo. Ti chiedono di non sforare."),
])
