from h import *
LEZIONE = L('7.2', 'Modulo 7', 'Prop firm', 'Dimensionare il rischio per una prova', [
 T('LEZIONE 7.2', 'Il rischio per una **prova**', 'Quanto rischiare quando il limite non è tuo ma della firma.', "Lezione sette punto due. Dimensionare il rischio per una prova."),
 P('Cosa cambia', [('Il limite non lo scegli tu', 'e superarlo vuol dire perdere la prova, non solo soldi'), ('Il tuo limite deve stare dentro il loro', 'con un margine di sicurezza'), ('Il tempo può contare', 'ma non devi cercare la velocità a ogni costo')],
  ["Cosa cambia con una prova?", "Il limite non lo scegli tu, e superarlo significa perdere la prova, non solo del denaro.", "Il tuo limite personale deve stare dentro il loro, con un margine di sicurezza.", "E se c'è un tempo massimo, non devi cercare la velocità a ogni costo."]),
 TB('Un limite personale dentro il loro', ['Limite della firma', 'Il tuo limite (metà)'], [['Giornaliero 5%', '2,5%'], ['Totale statico 10%', '5% (poi riduci il rischio)']],
  ["Una regola semplice: il tuo limite deve essere circa la metà di quello della firma.", "Se la firma permette cinque per cento al giorno, tu ti fermi a due virgola cinque.", "Se la perdita totale è dieci per cento, a cinque per cento ti fermi e rivedi il piano, riducendo il rischio. Il margine copre slippage, gap e le operazioni aperte che non hai ancora chiuso."], nota='Regola prudente di esempio.'),
 TB('Rischio per trade e probabilità di fallire', ['Rischio per trade', 'Fallisce prima del +10%', 'Trade mediani per arrivarci'], [['0,25%', '~0%', '~138'], ['0,5%', '~0,3%', '~65'], ['1%', '~5%', '~28'], ['2%', '~18%', '~8'], ['3%', '~26%', '~4']],
  ["Vediamo cosa succede su una prova con obiettivo più dieci per cento e perdita massima totale meno dieci per cento, sul nostro sistema di esempio.", "Con zero virgola venticinque per cento a trade, non fallisce praticamente mai, ma servono circa centotrentotto operazioni.", "Con zero virgola cinque: circa lo zero virgola tre per cento fallisce, e servono circa sessantacinque trade.", "Con l'uno per cento: circa il cinque per cento fallisce, ventotto trade.", "Con il due per cento: circa diciotto per cento fallisce, otto trade.", "Con il tre per cento: circa ventisei per cento fallisce. Più rischi, prima arrivi, ma più spesso perdi la prova."], nota='Sistema con vantaggio reale (45%, +1,8/−1). Con un vantaggio inferiore il risultato peggiora.'),
 P('La lezione', [('Il rischio alto non è un risparmio di tempo', 'è una scommessa sulla prova'), ('Un rischio basso è più lento ma molto più sicuro', 'purché il sistema abbia davvero un vantaggio'), ('Se hai tempo massimo, scegli un valore intermedio', 'e riduci dopo i primi profitti')],
  ["La lezione è chiara. Un rischio alto non è un risparmio di tempo: è una scommessa sulla prova.", "Un rischio basso è più lento, ma molto più sicuro, a patto che il sistema abbia davvero un vantaggio.", "Se hai un tempo massimo, scegli un valore intermedio e riduci il rischio dopo i primi profitti."]),
 *ES('limite personale', [['Capitale', '50.000 €'], ['Limite giornaliero firma', '5%'], ['Rischio per trade', '0,5%'], ['Domanda', 'quante perdite piene prima del TUO limite (2,5%)?']], [['Calcolo', '2,5% ÷ 0,5%'], ['Perdite', '5']], 'Dopo 5 perdite piene ti fermi',
  ["Esercizio. Capitale cinquantamila euro, limite giornaliero della firma cinque per cento, rischio zero virgola cinque per cento a trade. Dopo quante perdite piene ti fermi se il tuo limite è due virgola cinque per cento?", "Due virgola cinque diviso zero virgola cinque: cinque perdite piene. A quel punto ti fermi, con ancora metà del margine disponibile."]),
 RIEP(['Il tuo limite sta dentro il loro, con margine', 'Rischio alto = prova più veloce ma più fragile', 'Rischio basso = più lento ma molto più sicuro, se il vantaggio è reale'], ["Riassumiamo.", "Il tuo limite sta dentro il loro, con margine.", "Rischio alto significa prova più veloce ma più fragile.", "Rischio basso vuol dire più lenta ma molto più sicura, se il vantaggio è reale."]),
 Q('La fretta è il **costo nascosto** di ogni prova.', "La fretta è il costo nascosto di ogni prova."),
])
