from h import *
LEZIONE = L('7.3', 'Modulo 7', 'Prop firm', 'Trailing drawdown, notizie e regole di coerenza', [
 T('LEZIONE 7.3', 'Trailing drawdown e **altre trappole**', 'Le regole meno intuitive: dove si perde una prova senza accorgersene.', "Lezione sette punto tre. Trailing drawdown, notizie e regole di coerenza."),
 G('Il trailing drawdown', 'trailing', ["Questo grafico mostra la differenza tra i due tipi di limite. La linea verde è l'equity. La linea punteggiata è il limite statico: capitale iniziale meno dieci per cento, fisso.", "La linea rossa tratteggiata è il limite trailing: il massimo raggiunto dall'equity meno dieci per cento. Sale ogni volta che l'equity fa un nuovo massimo, e non scende mai.", "Il risultato: dopo una buona crescita, lo spazio che hai davvero per sbagliare resta di dieci punti rispetto al massimo, non rispetto al capitale iniziale."], 'Il limite trailing segue i massimi e non torna indietro.'),
 EX('Un esempio numerico', [['Capitale iniziale', '100.000 €'], ['Limite trailing 10%', 'parte da 90.000 €'], ['L\'equity sale a', '108.000 €'], ['Il limite sale a', '97.200 €'], ['Spazio dal massimo', '10.800 €, sempre il 10% del massimo']], risultato='Ogni nuovo massimo alza il pavimento', k=[1,2,3,4,5,6],
  voce=["Un esempio numerico. Capitale centomila euro, limite trailing dieci per cento.", "All'inizio il limite è novantamila euro.", "L'equity sale a centoottomila euro.", "Il limite sale a novantasettemiladuecento: massimo meno dieci per cento.", "Lo spazio che hai è sempre il dieci per cento dell'ultimo massimo, cioè diecimilaottocento euro.", "Attenzione: se il massimo include profitti non ancora chiusi, un ritracciamento di un trade aperto può consumare lo spazio. Ogni nuovo massimo, anche momentaneo, alza il pavimento."]),
 P('Altre regole da leggere bene', [('Regola di coerenza', 'alcune firme limitano il peso di un singolo giorno sul profitto totale'), ('Notizie', 'alcune vietano o limitano le operazioni attorno agli annunci'), ('Fine settimana e overnight', 'alcune vietano di tenere posizioni aperte'), ('Strumenti ed EA', 'alcune limitano certi strumenti o l\'uso di automatismi')],
  ["Altre regole da leggere bene.", "La regola di coerenza: alcune firme limitano il peso di un singolo giorno sul profitto totale.", "Le notizie: alcune vietano o limitano le operazioni attorno agli annunci.", "Il fine settimana e la notte: alcune vietano di tenere posizioni aperte.", "Strumenti e robot: alcune limitano certi strumenti o l'uso di automatismi. Tutto questo cambia da firma a firma: leggi il regolamento."]),
 CF('Cosa fare prima di iniziare', dict(t='Da fare', punti=[['Leggere le regole intere', ''], ['Scrivere i limiti nel tuo piano', ''], ['Testare in demo', '']]), dict(t='Da evitare', punti=[['Fidarsi di un riassunto', ''], ['Scoprire le regole dopo la violazione', ''], ['Aumentare il rischio per recuperare tempo', '']]),
  ["Cosa fare prima di iniziare.", "Leggere le regole intere, scrivere i limiti nel tuo piano e testare in demo.", "Da evitare: fidarsi di un riassunto, scoprire le regole dopo averle violate, aumentare il rischio per recuperare tempo."], 'Una prova persa per una regola non letta è la più evitabile.'),
 *ES('trailing', [['Capitale iniziale', '50.000 €'], ['Limite trailing', '8%'], ['Equity massima raggiunta', '54.000 €']], [['Limite attuale', '54.000 × 0,92'], ['Valore', '49.680 €']], 'Il limite è salito sopra il capitale iniziale',
  ["Esercizio. Capitale cinquantamila euro, limite trailing otto per cento, equity massima raggiunta cinquantaquattromila. Dov'è il limite adesso?", "Cinquantaquattromila per zero virgola novantadue: quarantanovemilaseicentoottanta. Il limite è salito sopra il capitale iniziale: ora anche chiudere in pareggio rispetto al punto di partenza ti lascia con poco margine."]),
 RIEP(['Il trailing sale con i massimi e non scende', 'Leggi regole di coerenza, notizie, weekend e strumenti', 'Scrivi i limiti della firma nel tuo piano'], ["Riassumiamo.", "Il trailing sale con i massimi e non scende mai.", "Leggi le regole di coerenza, le notizie, il fine settimana e gli strumenti consentiti.", "E scrivi i limiti della firma nel tuo piano."]),
 Q('La regola che non hai letto è quella che ti **farà perdere** la prova.', "La regola che non hai letto è quella che ti farà perdere la prova."),
])
