from h import *
LEZIONE = L('7.4', 'Modulo 7', 'Prop firm', 'Più conti e rischio aggregato', [
 T('LEZIONE 7.4', 'Più conti, **un solo rischio**', 'Quando operi su più conti, il rischio si somma anche se non lo vedi.', "Lezione sette punto quattro. Più conti e rischio aggregato."),
 P('Perché si usano più conti', [('Diversificare tra firme o fasi', 'non mettere tutto su una sola prova'), ('Usare conti di dimensioni diverse', 'uno piccolo, uno più grande'), ('Separare strategie diverse', 'ogni conto con il suo piano')],
  ["Perché si usano più conti?", "Per diversificare tra firme o fasi, non mettendo tutto su una sola prova.", "Per usare conti di dimensioni diverse.", "Oppure per separare strategie diverse, ognuna con il suo piano."]),
 CF('Stesso trade su più conti', dict(t='3 conti, 1% ciascuno', punti=[['Se la stessa idea perde', '−1% su tutti'], ['Perdita in € se 100k ciascuno', '3.000 €'], ['Rischio come un solo conto', '3%']]), dict(t='3 conti, idee diverse', punti=[['Perdite in momenti diversi', ''], ['Rischio concentrato', 'basso'], ['Serve però più lavoro', '']]),
  ["Il rischio nascosto: lo stesso trade su più conti.", "Se apri la stessa idea su tre conti da uno per cento ciascuno, quando perde, perdi su tutti e tre insieme: con tre conti da centomila euro, tremila euro in un solo colpo. Come se avessi un solo conto con rischio del tre per cento.", "Con idee diverse su conti diversi, le perdite arrivano in momenti diversi, ma serve più lavoro di gestione."], 'Lo stesso segnale su tre conti = un rischio triplo.'),
 P('Attenzione alle regole', [('Molte prop limitano o vietano di replicare le stesse operazioni su più conti', 'è un tema di regolamento, non solo di rischio'), ('Verifica cosa è ammesso prima di farlo', 'rischi di perdere tutti i conti insieme'), ('Questo corso non ti dice di replicare operazioni', 'ti dice di capire il rischio aggregato se lo fai')],
  ["Attenzione alle regole. Molte prop firm limitano o vietano di replicare le stesse operazioni su più conti: è un tema di regolamento, non solo di rischio.", "Verifica cosa è ammesso prima di farlo, perché rischi di perdere tutti i conti insieme.", "Questo corso non ti dice di replicare operazioni: ti dice di capire il rischio aggregato, nel caso in cui lo faccia."]),
 TB('Il rischio aggregato', ['Conti', 'Rischio per conto', 'Stesso segnale su tutti'], [['1', '1%', '1% di un conto'], ['3', '1%', '3 conti × 1% = 3 unità di rischio'], ['5', '0,5%', '5 conti × 0,5% = 2,5 unità']],
  ["Ecco come si somma il rischio aggregato quando il segnale è lo stesso.", "Un conto all'uno per cento: una unità di rischio.", "Tre conti all'uno per cento: tre unità.", "Cinque conti allo zero virgola cinque per cento: due unità e mezza. Se vuoi mantenere la stessa esposizione totale, il rischio per conto deve scendere quando aumentano i conti."], nota='Se i conti hanno capitali diversi, si ragiona in euro.'),
 *ES('rischio aggregato', [['Conti', '4 da 50.000 €'], ['Rischio per conto', '1%'], ['Stessa idea su tutti', '']], [['Rischio per conto', '500 €'], ['Totale', '4 × 500 = 2.000 €']], 'Perdita totale possibile: 2.000 € in un colpo',
  ["Esercizio. Quattro conti da cinquantamila euro, rischio uno per cento ciascuno, stessa idea su tutti. Quanto perdi in totale se va male?", "Cinquecento euro per conto, per quattro: duemila euro in un solo colpo. Se per te è troppo, riduci il rischio per conto."]),
 RIEP(['Più conti con lo stesso segnale = rischio che si somma', 'Verifica cosa permette il regolamento', 'Calcola il rischio totale in euro'], ["Riassumiamo.", "Più conti con lo stesso segnale: il rischio si somma.", "Verifica cosa permette il regolamento.", "E calcola sempre il rischio totale in euro. Con questo il modulo sulle prop firm è completo."]),
 Q('Cinque conti, **un solo errore**.', "Cinque conti, un solo errore."),
])
