from h import *
LEZIONE = L('8.1', 'Modulo 8', 'Gestire la posizione', 'Break-even e trailing stop', [
 T('LEZIONE 8.1', 'Break-even e **trailing stop**', 'Come proteggere un trade in guadagno senza soffocarlo.', "Lezione otto punto uno. Break-even e trailing stop."),
 P('Due strumenti, due scopi', [('Break-even', 'sposti lo stop al prezzo di ingresso: il trade non può più perdere (spread a parte)'), ('Trailing stop', 'lo stop segue il prezzo a distanza fissa o a livelli: blocca parte del guadagno'), ('Nessuno dei due è gratis', 'proteggere troppo presto costa trade vincenti')],
  ["Due strumenti con due scopi.", "Il break-even: sposti lo stop al prezzo di ingresso, e il trade non può più perdere, spread a parte.", "Il trailing stop: lo stop segue il prezzo a una distanza fissa o a livelli, e blocca parte del guadagno.", "Nessuno dei due è gratis: proteggere troppo presto costa trade che sarebbero arrivati a target."]),
 CF('Il costo di spostare troppo presto', dict(t='Break-even a +12 pip (metà stop)', punti=[['Perdite piene', 'meno'], ['Trade che arrivano a target', 'meno'], ['Pareggi', 'molti']]), dict(t='Break-even a +25 pip (stop intero)', punti=[['Perdite piene', 'più'], ['Trade che arrivano a target', 'più'], ['Pareggi', 'meno']]),
  ["Il compromesso è chiaro. Prendi un trade con stop a venticinque pip.", "Spostare il break-even presto, a dodici pip di profitto, cioè a metà dello stop, ti riduce le perdite piene, ma fa chiudere in pareggio molti trade che sarebbero arrivati a target.", "Spostarlo più tardi, a venticinque pip, lascia respirare il trade, ma più operazioni tornano allo stop pieno.", "Non esiste un valore giusto in assoluto: va testato sui tuoi dati."], 'Va misurato con il proprio sistema.'),
 P('Regole pratiche', [('Decidi in anticipo il livello di break-even', 'e applicalo sempre: non a sensazione'), ('Lascia spazio al rumore', 'uno stop troppo vicino al prezzo scatta per un semplice ritracciamento'), ('Misura l\'effetto di ogni regola nel journal', 'con almeno 100 trade')],
  ["Tre regole pratiche.", "Decidi in anticipo il livello di break-even e applicalo sempre, non a sensazione.", "Lascia spazio al rumore: uno stop troppo vicino al prezzo scatta per un semplice ritracciamento.", "E misura l'effetto di ogni regola nel journal, con almeno cento trade."]),
 *ES('trailing', [['Ingresso', '1,2000'], ['Stop iniziale', '1,1960 (40 pip)'], ['Prezzo attuale', '1,2080 (+80 pip)'], ['Domanda', 'dove va lo stop con trailing a scatti di 40 pip?']], [['Prezzo a +80 pip', 'stop a +40 pip'], ['Livello dello stop', '1,2000 + 0,0040 = 1,2040']], 'Stop a 1,2040',
  ["Esercizio. Entri a uno virgola due, stop a quaranta pip. Il prezzo è a uno virgola due zero otto zero, cioè ottanta pip di guadagno. Dove va lo stop con trailing a scatti di quaranta pip?", "A ottanta pip di guadagno, lo stop va a quaranta pip di guadagno: ingresso più quaranta pip, cioè uno virgola due zero quattro zero."]),
 RIEP(['Break-even: stop al prezzo di ingresso', 'Trailing: lo stop segue il prezzo e blocca guadagno', 'Proteggere troppo presto costa: testa le regole sui tuoi dati'], ["Riassumiamo.", "Break-even significa stop al prezzo di ingresso.", "Il trailing fa seguire lo stop al prezzo e blocca parte del guadagno.", "Proteggere troppo presto costa: testa le regole sui tuoi dati."]),
 Q('Proteggere un trade **troppo presto** è un altro modo di perdere.', "Proteggere un trade troppo presto è un altro modo di perdere."),
])
