from h import *
LEZIONE = L('8.1', 'Modulo 8', 'Gestire la posizione', 'Break-even e trailing stop', [
 T('LEZIONE 8.1', 'Break-even e **trailing stop**', 'Come proteggere un trade in guadagno senza soffocarlo.', "Lezione otto punto uno. Break-even e trailing stop."),
 P('Due strumenti, due scopi', [('Break-even', 'sposti lo stop al prezzo di ingresso: il trade non può più perdere (spread a parte)'), ('Trailing stop', 'lo stop segue il prezzo a distanza fissa o a livelli: blocca parte del guadagno'), ('Nessuno dei due è gratis', 'proteggere troppo presto costa trade vincenti')],
  ["Due strumenti con due scopi.", "Il break-even: sposti lo stop al prezzo di ingresso, e il trade non può più perdere, spread a parte.", "Il trailing stop: lo stop segue il prezzo a una distanza fissa o a livelli, e blocca parte del guadagno.", "Nessuno dei due è gratis: proteggere troppo presto costa trade che sarebbero arrivati a target."]),
 CF('Il costo di spostare troppo presto', dict(t='Break-even a +0,5 R', punti=[['Trade che arrivano a target', 'meno'], ['Perdite piene', 'meno'], ['Molti pareggi', '']]), dict(t='Break-even a +1 R', punti=[['Trade che arrivano a target', 'più'], ['Perdite piene', 'più'], ['Meno pareggi', '']]),
  ["Il compromesso è chiaro.", "Spostare il break-even presto, per esempio a mezzo R di profitto, ti riduce le perdite piene, ma fa chiudere in pareggio molti trade che sarebbero arrivati a target.", "Spostarlo più tardi, a un R, lascia respirare il trade, ma più operazioni tornano allo stop pieno.", "Non esiste un valore giusto in assoluto: va testato sui tuoi dati, in R, come ogni altra regola."], 'Va misurato con il proprio sistema.'),
 EX('Trailing a scatti', [['Ingresso', '1,1000'], ['Stop iniziale', '1,0975 (−25 pip = −1 R)'], ['A +1 R (1,1025)', 'stop a pareggio 1,1000'], ['A +2 R (1,1050)', 'stop a +1 R = 1,1025'], ['A +3 R (1,1075)', 'stop a +2 R = 1,1050']], risultato='Il guadagno minimo sale a ogni scatto', k=[1,2,3,4,5,6],
  voce=["Un esempio di trailing a scatti. Entri a uno virgola uno zero zero zero.", "Stop iniziale a venticinque pip: meno un R.", "Quando il prezzo arriva a più un R, sposti lo stop a pareggio.", "A più due R, lo stop va a più un R.", "A più tre R, lo stop va a più due R.", "A ogni scatto, il guadagno minimo che hai assicurato sale di un R. Non devi indovinare il massimo: segui il prezzo a distanza."]),
 P('Regole pratiche', [('Decidi in anticipo il livello di break-even', 'e applicalo sempre: non a sensazione'), ('Lascia spazio al rumore', 'uno stop troppo vicino al prezzo scatta per un semplice ritracciamento'), ('Misura in R l\'effetto di ogni regola', 'nel journal, con almeno 100 trade')],
  ["Tre regole pratiche.", "Decidi in anticipo il livello di break-even e applicalo sempre, non a sensazione.", "Lascia spazio al rumore: uno stop troppo vicino al prezzo scatta per un semplice ritracciamento.", "E misura in R l'effetto di ogni regola nel journal, con almeno cento trade."]),
 *ES('trailing', [['Ingresso', '1,2000'], ['Stop iniziale', '1,1960 (40 pip)'], ['Prezzo attuale', '1,2080 (+2 R)'], ['Domanda', 'dove va lo stop con trailing a scatti di 1 R?']], [['+2 R', 'stop a +1 R'], ['Prezzo dello stop', '1,2000 + 0,0040 = 1,2040']], 'Stop a 1,2040',
  ["Esercizio. Entri a uno virgola due, stop a quaranta pip. Il prezzo è a uno virgola due zero otto zero, cioè più due R. Dove va lo stop con trailing a scatti di un R?", "A più due R, lo stop va a più un R: ingresso più quaranta pip, cioè uno virgola due zero quattro zero."]),
 RIEP(['Break-even: stop al prezzo di ingresso', 'Trailing: lo stop segue il prezzo e blocca guadagno', 'Proteggere troppo presto costa: testa le regole in R'], ["Riassumiamo.", "Break-even significa stop al prezzo di ingresso.", "Il trailing fa seguire lo stop al prezzo e blocca parte del guadagno.", "Proteggere troppo presto costa: testa le regole in R."]),
 Q('Proteggere un trade **troppo presto** è un altro modo di perdere.', "Proteggere un trade troppo presto è un altro modo di perdere."),
])
