from h import *
LEZIONE = L('8.2', 'Modulo 8', 'Gestire la posizione', 'Le uscite a scaglioni', [
 T('LEZIONE 8.2', 'Uscite a **scaglioni**', 'Dividere la posizione in più parti con target diversi.', "Lezione otto punto due. Le uscite a scaglioni."),
 P('L\'idea', [('Una sola uscita è tutto o niente', 'o arrivi al target, o ti ferma lo stop'), ('Più uscite distribuiscono il risultato', 'incassi una parte presto e lasci correre il resto'), ('Riduce lo stress, non il rischio iniziale', 'il rischio massimo resta quello deciso')],
  ["L'idea delle uscite a scaglioni.", "Con una sola uscita è tutto o niente: o arrivi al target, o ti ferma lo stop.", "Con più uscite distribuisci il risultato: incassi una parte presto e lasci correre il resto.", "Riduce lo stress, ma non il rischio iniziale: la perdita massima resta quella che hai deciso."]),
 TB('Esempio: 3 scaglioni, rischio 100 €', ['Scaglione', 'Quota', 'Uscita a', 'Se va a target'], [['TP1', '50%', '+1 R', '+50 €'], ['TP2', '30%', '+2 R', '+60 €'], ['TP3', '20%', '+3 R', '+60 €'], ['Totale', '100%', '', '+170 € = +1,7 R']],
  ["Un esempio con tre scaglioni e un rischio di cento euro.", "Primo scaglione: metà della posizione esce a più un R, e incassa cinquanta euro.", "Secondo: il trenta per cento esce a più due R, e incassa sessanta.", "Terzo: il venti per cento esce a più tre R, e incassa sessanta.", "Se va tutto a target, il totale è centosettanta euro, cioè più uno virgola sette R."], nota='Quota × distanza in R × rischio.'),
 TB('Scenari diversi, stessa posizione', ['Scenario', 'Risultato'], [['Stop subito', '−1 R'], ['TP1 poi stop a pareggio', '+0,5 R'], ['TP1 e TP2, poi stop sul resto a +1 R', '+0,5 + 0,6 + 0,2 = +1,3 R'], ['Tutti e tre i target', '+1,7 R']],
  ["Vediamo come cambia il risultato a seconda di come va il trade.", "Se lo stop scatta subito: meno un R.", "Se il primo target viene colpito e poi sposti lo stop a pareggio e il resto torna indietro: più zero virgola cinque R, la metà della posizione al primo target.", "Se colpisci il primo e il secondo e poi il resto esce a più un R: più uno virgola tre R.", "E se arrivi a tutti e tre i target: più uno virgola sette R. Il risultato migliora in molti scenari, ma il massimo possibile è più basso del trade intero a target pieno."]),
 CF('Pro e contro', dict(t='Pro', punti=[['Incassi qualcosa presto', ''], ['Meno stress psicologico', ''], ['Resti dentro i trend lunghi', '']]), dict(t='Contro', punti=[['Guadagno massimo ridotto', ''], ['Più costi (più ordini)', ''], ['Più complessità', '']]),
  ["Pro e contro.", "Incassi qualcosa presto, hai meno stress e resti dentro i trend lunghi con una parte della posizione.", "Il guadagno massimo è ridotto, hai più costi perché ci sono più ordini, e più complessità da gestire."], 'Dipende dal sistema e da come ti comporti.'),
 *ES('scaglioni', [['Rischio', '120 €'], ['TP1', '60% a +1 R'], ['TP2', '40% a +2,5 R']], [['TP1', '0,6 × 1 = 0,6 R'], ['TP2', '0,4 × 2,5 = 1,0 R'], ['Totale', '1,6 R = 192 €']], 'Se arrivi a entrambi: +1,6 R',
  ["Esercizio. Rischio centoventi euro. Il sessanta per cento esce a più un R, il quaranta per cento a più due virgola cinque R. Quanto fai se arrivi a entrambi?", "Zero virgola sei per uno: zero virgola sei R. Zero virgola quattro per due virgola cinque: un R. Totale uno virgola sei R, cioè centonovantadue euro."]),
 RIEP(['Gli scaglioni distribuiscono il risultato', 'Il rischio iniziale non cambia', 'Calcola sempre il risultato di ogni scenario in R'], ["Riassumiamo.", "Gli scaglioni distribuiscono il risultato.", "Il rischio iniziale non cambia.", "E calcola sempre il risultato di ogni scenario in R, prima di usarli."]),
 Q('Uscire a pezzi cambia **come vinci**. Non quanto **rischi**.', "Uscire a pezzi cambia come vinci. Non quanto rischi."),
])
