from h import *
LEZIONE = L('8.2', 'Modulo 8', 'Gestire la posizione', 'Le uscite a scaglioni', [
 T('LEZIONE 8.2', 'Uscite a **scaglioni**', 'Dividere la posizione in più parti con target diversi.', "Lezione otto punto due. Le uscite a scaglioni."),
 P('L\'idea', [('Una sola uscita è tutto o niente', 'o arrivi al target, o ti ferma lo stop'), ('Più uscite distribuiscono il risultato', 'incassi una parte presto e lasci correre il resto'), ('Riduce lo stress, non il rischio iniziale', 'il rischio massimo resta quello deciso')],
  ["L'idea delle uscite a scaglioni.", "Con una sola uscita è tutto o niente: o arrivi al target, o ti ferma lo stop.", "Con più uscite distribuisci il risultato: incassi una parte presto e lasci correre il resto.", "Riduce lo stress, ma non il rischio iniziale: la perdita massima resta quella che hai deciso."]),
 TB('Esempio: 0,4 lotti divisi in 3 scaglioni, stop 25 pip', ['Scaglione', 'Quota', 'Chiude a', 'Contributo'], [['TP1', '50%', '+25 pip', '0,5 × 25 = 12,5 pip'], ['TP2', '30%', '+50 pip', '0,3 × 50 = 15 pip'], ['TP3', '20%', '+75 pip', '0,2 × 75 = 15 pip'], ['Totale', '100%', '', '42,5 pip ≈ 170 €']],
  ["Un esempio con zero virgola quattro lotti, divisi in tre scaglioni, e uno stop a venticinque pip.", "Primo scaglione: metà della posizione esce a più venticinque pip. Contribuisce con dodici virgola cinque pip.", "Secondo: il trenta per cento esce a più cinquanta. Contribuisce con quindici pip.", "Terzo: il venti per cento esce a più settantacinque. Altri quindici pip.", "Se va tutto a target, il guadagno medio è quarantadue virgola cinque pip: con un pip che vale quattro euro, circa centosettanta euro."], nota='Con 0,4 lotti, 1 pip vale 4 €.'),
 TB('Scenari diversi, stessa posizione', ['Scenario', 'Risultato'], [['Stop subito', '−25 pip  (−100 €)'], ['TP1, poi stop a pareggio', '+12,5 pip  (+50 €)'], ['TP1 e TP2, poi il resto esce a +25 pip', '+32,5 pip  (+130 €)'], ['Tutti e tre i target', '+42,5 pip  (+170 €)']],
  ["Vediamo come cambia il risultato a seconda di come va il trade.", "Se lo stop scatta subito: meno venticinque pip, cioè meno cento euro.", "Se il primo target viene colpito e poi sposti lo stop a pareggio e il resto torna indietro: più dodici virgola cinque pip, la metà della posizione al primo target.", "Se colpisci il primo e il secondo e poi il resto esce a più venticinque pip: più trentadue virgola cinque pip.", "E se arrivi a tutti e tre i target: più quarantadue virgola cinque pip. Il risultato migliora in molti scenari, ma il massimo possibile è più basso di tenere tutta la posizione fino al target più lontano."]),
 CF('Pro e contro', dict(t='Pro', punti=[['Incassi qualcosa presto', ''], ['Meno stress psicologico', ''], ['Resti dentro i trend lunghi', '']]), dict(t='Contro', punti=[['Guadagno massimo ridotto', ''], ['Più costi (più ordini)', ''], ['Più complessità', '']]),
  ["Pro e contro.", "Incassi qualcosa presto, hai meno stress e resti dentro i trend lunghi con una parte della posizione.", "Il guadagno massimo è ridotto, hai più costi perché ci sono più ordini, e più complessità da gestire."], 'Dipende dal sistema e da come ti comporti.'),
 *ES('scaglioni', [['Stop', '30 pip'], ['Scaglione 1', '60% a +30 pip'], ['Scaglione 2', '40% a +75 pip']], [['Scaglione 1', '0,6 × 30 = 18 pip'], ['Scaglione 2', '0,4 × 75 = 30 pip'], ['Totale', '48 pip']], 'Se arrivi a entrambi: +48 pip',
  ["Esercizio. Stop trenta pip. Il sessanta per cento della posizione esce a più trenta pip, il quaranta per cento a più settantacinque. Quanti pip fai in media se arrivi a entrambi?", "Zero virgola sei per trenta: diciotto pip. Zero virgola quattro per settantacinque: trenta pip. Totale quarantotto pip."]),
 RIEP(['Gli scaglioni distribuiscono il risultato', 'Il rischio iniziale non cambia', 'Calcola il risultato di ogni scenario, in pip e in euro'], ["Riassumiamo.", "Gli scaglioni distribuiscono il risultato.", "Il rischio iniziale non cambia.", "E calcola il risultato di ogni scenario, in pip e in euro, prima di usarli."]),
 Q('Uscire a pezzi cambia **come vinci**. Non quanto **rischi**.', "Uscire a pezzi cambia come vinci. Non quanto rischi."),
])
