from h import *
LEZIONE = L('8.3', 'Modulo 8', 'Gestire la posizione', 'Aggiungere a una posizione vincente', [
 T('LEZIONE 8.3', 'Aggiungere a un trade **vincente**', 'La piramide: quando ha senso, e quanto rischio porta.', "Lezione otto punto tre. Aggiungere a una posizione vincente."),
 P('Cosa significa piramidare', [('Si aggiunge solo quando il trade è già in guadagno', 'mai per «mediare» una perdita'), ('Ogni aggiunta è più piccola della precedente', 'la posizione cresce, ma il rischio resta sotto controllo'), ('Lo stop si sposta per proteggere il rischio totale', 'altrimenti si accumula esposizione')],
  ["Piramidare significa aggiungere a una posizione che sta già andando bene.", "Si aggiunge solo quando il trade è in guadagno, mai per mediare una perdita.", "Ogni aggiunta è più piccola della precedente, così la posizione cresce ma il rischio resta sotto controllo.", "E lo stop si sposta per proteggere il rischio totale: senza questo accumuli esposizione."]),
 CF('Mediare una perdita, aggiungere a un vincente', dict(t='Mediare in perdita', punti=[['Aggiungi mentre perdi', ''], ['Rischio totale cresce', ''], ['Il piano è violato', '']]), dict(t='Piramidare', punti=[['Aggiungi mentre guadagni', ''], ['Rischio totale controllato', ''], ['Il piano lo prevede', '']]),
  ["Non confondere le due cose.", "Mediare in perdita significa aggiungere mentre perdi: il rischio totale cresce e il piano è violato.", "Piramidare significa aggiungere mentre guadagni, con il rischio totale controllato e con una regola già scritta nel piano."], 'La prima è un errore. La seconda, se scritta nel piano, una tecnica.'),
 EX('Esempio: rischio totale controllato', [['Posizione iniziale', '0,4 lotti, stop 25 pip = rischio 100 €'], ['Il prezzo sale di 25 pip', 'stop a pareggio: rischio 0 €'], ['Aggiungi 0,2 lotti a +25 pip', 'con stop a 25 pip: rischio 50 €'], ['Rischio totale', '50 €, non 150 €']], risultato='Ogni aggiunta usa il guadagno come cuscinetto', k=[1,2,3,4,5],
  voce=["Un esempio di rischio controllato. Parti con zero virgola quattro lotti e uno stop di venticinque pip: cento euro di rischio.", "Il prezzo sale di venticinque pip, e sposti lo stop a pareggio. Il rischio rimasto è zero.", "A quel punto aggiungi zero virgola due lotti, con uno stop a venticinque pip: cinquanta euro di rischio.", "Il rischio totale è cinquanta euro, non centocinquanta.", "Hai usato il guadagno come cuscinetto per aggiungere. Se tutto torna indietro, perdi al massimo profitto non realizzato, mai capitale."]),
 P('Regole per non farsi male', [('Decidi quante aggiunte, massimo', 'per esempio una o due, mai di più'), ('Ogni aggiunta più piccola', 'altrimenti il prezzo medio si avvicina al prezzo di ingresso peggiore'), ('Non aggiungere dopo una forte estensione', 'il ritracciamento è più probabile e fa male a tutta la posizione')],
  ["Regole per non farsi male.", "Decidi quante aggiunte al massimo: per esempio una o due, mai di più.", "Ogni aggiunta più piccola, altrimenti il prezzo medio si avvicina all'ingresso peggiore.", "E non aggiungere dopo una forte estensione: il ritracciamento è più probabile e colpisce tutta la posizione."]),
 *ES('rischio totale', [['Posizione 1', '0,4 lotti, stop a pareggio'], ['Aggiunta', '0,2 lotti, stop a 25 pip'], ['Valore pip', '10 € per lotto']], [['Rischio aggiunta', '0,2 × 25 × 10 = 50 €'], ['Rischio posizione 1', '0 €'], ['Totale', '50 €']], 'Rischio totale = 50 €',
  ["Esercizio. La prima posizione è da zero virgola quattro lotti con stop a pareggio. Aggiungi zero virgola due lotti con stop a venticinque pip. Valore del pip dieci euro per lotto. Qual è il rischio totale?", "Zero virgola due per venticinque per dieci: cinquanta euro. La prima posizione, a pareggio, non rischia più. Totale cinquanta euro."]),
 RIEP(['Piramidare = aggiungere a un trade in guadagno, mai in perdita', 'Aggiunte più piccole, stop che protegge il rischio totale', 'Scrivi nel piano il numero massimo di aggiunte'], ["Riassumiamo.", "Piramidare significa aggiungere a un trade in guadagno, mai in perdita.", "Aggiunte più piccole, con lo stop che protegge il rischio totale.", "E scrivi nel piano il numero massimo di aggiunte."]),
 Q('Aggiungi solo con i **soldi del mercato**, mai con i tuoi.', "Aggiungi solo con i soldi del mercato, mai con i tuoi."),
])
