from h import *
LEZIONE = L('8.4', 'Modulo 8', 'Gestire la posizione', 'Automatizzare le regole', [
 T('LEZIONE 8.4', 'Automatizzare le **regole**', 'Lasciare a un software ciò che non vuoi decidere sotto stress.', "Lezione otto punto quattro. Automatizzare le regole."),
 P('Cosa si può automatizzare', [('Il calcolo del lotto', 'dalla distanza dello stop e dal rischio in percentuale'), ('I limiti giornalieri', 'chiusura o blocco dopo una perdita o un numero di perdite'), ('Break-even e trailing', 'applicati con regole fisse, senza esitazioni'), ('Le uscite a scaglioni', 'ordini e target preimpostati')],
  ["Cosa si può automatizzare nella gestione del rischio?", "Il calcolo del lotto, dalla distanza dello stop e dal rischio in percentuale.", "I limiti giornalieri: blocco dopo una perdita o dopo un numero di perdite.", "Break-even e trailing, applicati con regole fisse, senza esitazioni.", "E le uscite a scaglioni, con ordini e target preimpostati."]),
 P('Cosa non si automatizza', [('La decisione di entrare', 'resta tua: gli strumenti di gestione non danno segnali'), ('La responsabilità del piano', 'un software esegue le regole che gli dai, buone o cattive'), ('Il controllo', 'serve verificare che stia facendo ciò che vuoi')],
  ["Cosa non si automatizza.", "La decisione di entrare resta tua: gli strumenti di gestione del rischio non danno segnali.", "La responsabilità del piano: un software esegue le regole che gli dai, buone o cattive.", "E il controllo: devi verificare che stia facendo quello che vuoi."]),
 TB('Gli strumenti Riskly (miei prodotti, dichiarato)', ['Strumento', 'Cosa fa'], [['RiskGuard', 'pausa dopo una perdita, stop dopo N perdite, limite giornaliero, chiusura al target, blocco di MetaTrader'], ['TradeManager', 'sposta lo stop a pareggio e segue il prezzo (trailing)'], ['ScaleIn', 'divide la posizione in più take profit'], ['Riskly Pro', 'riunisce le funzioni in un unico strumento per MT4 e MT5'], ['Journal', 'raccoglie le operazioni e calcola le statistiche']],
  ["Dichiaro apertamente che i prossimi sono prodotti miei.", "RiskGuard: pausa dopo una perdita, stop dopo un numero di perdite, limite giornaliero, chiusura al target e blocco della piattaforma.", "TradeManager: sposta lo stop a pareggio e segue il prezzo, il trailing.", "ScaleIn: divide la posizione in più take profit.", "Riskly Pro: riunisce queste funzioni in un unico strumento, per MetaTrader quattro e cinque.", "E il journal, che raccoglie le operazioni e calcola le statistiche."], nota='Non danno segnali e non aprono operazioni. Info e prezzi su riskly.trade.'),
 CF('Software o fatto a mano?', dict(t='Fatto a mano', punti=[['Costo zero', ''], ['Serve disciplina costante', ''], ['Errori nei momenti di stress', '']]), dict(t='Con software', punti=[['Ha un costo', ''], ['Regole applicate sempre', ''], ['Va configurato e controllato', '']]),
  ["Software o fatto a mano?", "A mano non costa nulla, ma richiede disciplina costante e gli errori arrivano nei momenti di stress.", "Con un software hai un costo, ma le regole vengono applicate sempre. Va però configurato e controllato.", "Non è obbligatorio: puoi applicare tutto quello che hai imparato anche con un foglio di calcolo e molta disciplina. Gli strumenti servono a chi vuole togliersi la decisione di mezzo."], 'Scegli in base a te, non perché te lo dico io.'),
 *ES('cosa automatizzare', [['Il tuo punto debole', 'dopo 2 perdite apri trade fuori piano'], ['Domanda', 'quale regola automatizzeresti?']], [['Regola', 'stop dopo 2–3 perdite di fila'], ['Come', 'blocco automatico o pausa obbligatoria']], 'Automatizza il tuo punto debole, non tutto',
  ["Esercizio. Il tuo punto debole è che dopo due perdite apri trade fuori piano. Quale regola automatizzeresti?", "Uno stop automatico dopo due o tre perdite di fila, con un blocco o una pausa obbligatoria. Automatizza il tuo punto debole, non tutto."]),
 RIEP(['Si automatizza l\'esecuzione delle regole, non la decisione di entrare', 'Gli strumenti Riskly sono miei prodotti: non sono obbligatori', 'Automatizza il tuo punto debole'], ["Riassumiamo.", "Si automatizza l'esecuzione delle regole, non la decisione di entrare.", "Gli strumenti Riskly sono miei prodotti, e non sono obbligatori.", "Automatizza il tuo punto debole. E con questo il corso tecnico è finito: manca solo il tuo piano."]),
 Q('Il miglior strumento è quello che ti **impedisce** di fare ciò che sai di non dover fare.', "Il miglior strumento è quello che ti impedisce di fare ciò che sai di non dover fare."),
])
