from h import *
LEZIONE = L('9.1', 'Modulo 9', 'Tecniche avanzate', 'Il compounding', [
 T('LEZIONE 9.1', 'Il **compounding**', 'Far lavorare i guadagni sui guadagni, e capire quando lavora contro di te.', "Lezione nove punto uno. Il compounding, cioè l'interesse composto."),
 P('Che cos\'è', [('Ogni guadagno entra nel capitale', 'e il trade successivo si calcola sul capitale più grande'), ('La crescita accelera nel tempo', 'non è una linea retta, è una curva'), ('Funziona da solo con il rischio in percentuale', 'l\'1% di un conto più grande sono più euro')],
  ["Il compounding è l'interesse composto applicato al trading.", "Ogni guadagno entra nel capitale, e l'operazione successiva si calcola sul capitale più grande.", "Per questo la crescita accelera nel tempo: non è una linea retta, è una curva.", "E se rischi una percentuale fissa del capitale corrente, come abbiamo visto nel modulo quattro, il compounding funziona da solo: l'uno per cento di un conto più grande sono più euro."]),
 G('Lineare contro composto', 'compounding', ["Ecco la differenza su un conto di diecimila euro. La linea tratteggiata guadagna duecento euro fissi al mese: dopo tre anni arriva a diciassettemiladuecento.", "La linea verde guadagna il due per cento al mese sul capitale corrente: dopo dodici mesi è a dodicimilaseicentottantadue, dopo ventiquattro a sedicimilaottantaquattro, dopo trentasei a oltre ventimila. Stesso punto di partenza, stesso due per cento iniziale: la differenza la fa il tempo."], 'Esempio matematico, non una previsione di rendimento.'),
 TB('I numeri dell\'esempio', ['Mesi', 'Lineare (+200 €/mese)', 'Composto (+2%/mese)', 'Differenza'], [['12', '12.400 €', '12.682 €', '+282 €'], ['24', '14.800 €', '16.084 €', '+1.284 €'], ['36', '17.200 €', '20.399 €', '+3.199 €']],
  ["Gli stessi numeri in tabella.", "Dopo un anno la differenza è piccola: duecentottantadue euro.", "Dopo due anni è milleduecentottantaquattro.", "Dopo tre anni supera i tremila euro. Il compounding premia soprattutto la costanza e il tempo, non il singolo mese brillante."], nota='Formula: capitale × (1 + r)ⁿ'),
 CF('Funziona anche al contrario', dict(t='+10% poi −10%', punti=[['10.000 → 11.000', ''], ['11.000 → 9.900', ''], ['Risultato', '−1%']]), dict(t='+20% poi −20%', punti=[['10.000 → 12.000', ''], ['12.000 → 9.600', ''], ['Risultato', '−4%']]),
  ["Attenzione: il compounding funziona anche al contrario.", "Guadagni il dieci per cento e poi perdi il dieci: da diecimila a undicimila, poi a novemilanovecento. Sei sotto dell'uno per cento.", "Guadagni il venti e perdi il venti: da diecimila a dodicimila, poi a novemilaseicento. Sei sotto del quattro per cento.", "Più il conto oscilla, più l'interesse composto lavora contro di te. Ecco perché un rendimento stabile cresce più di uno identico in media ma molto altalenante."], 'Più oscillazioni = meno crescita composta.'),
 P('I benefici, e come proteggerli', [('Crescita che accelera senza aumentare il rischio %', 'il rischio in percentuale resta lo stesso'), ('Le posizioni si riducono da sole nelle perdite', 'il compounding frena anche la discesa'), ('Proteggilo dalle oscillazioni', 'drawdown bassi = curva composta più alta'), ('Decidi in anticipo cosa prelevi', 'ogni prelievo rallenta la curva: è una scelta, non un errore')],
  ["I benefici e come proteggerli.", "La crescita accelera senza che tu aumenti il rischio in percentuale.", "Nelle perdite le posizioni si riducono da sole: il compounding frena anche la discesa.", "Proteggilo dalle oscillazioni: drawdown bassi significano una curva composta più alta.", "E decidi in anticipo quanto prelevi. Ogni prelievo rallenta la curva: è una scelta legittima, ma va fatta a mente fredda."]),
 *ES('compounding', [['Capitale', '10.000 €'], ['Rendimento', '+3% al mese, 12 mesi'], ['Domanda', 'lineare o composto: quanto?']], [['Lineare', '10.000 + 12 × 300 = 13.600 €'], ['Composto', '10.000 × 1,03¹² = 14.258 €']], 'Differenza: +658 € in un anno',
  ["Esercizio. Diecimila euro, più tre per cento al mese per dodici mesi. Quanto ottieni in modo lineare e quanto in modo composto?", "Lineare: diecimila più dodici volte trecento, tredicimilaseicento. Composto: diecimila per uno virgola zero tre alla dodicesima, circa quattordicimiladuecentocinquantotto euro. Seicentocinquantotto euro in più, solo grazie al compounding."]),
 RIEP(['Il compounding fa lavorare i guadagni sui guadagni', 'Con il rischio in % funziona da solo', 'Le oscillazioni lo frenano: proteggi il conto dai grandi drawdown'], ["Riassumiamo ora i punti principali di questa lezione.", "Il compounding fa lavorare i guadagni sui guadagni.", "Con il rischio in percentuale funziona da solo.", "E le oscillazioni lo frenano: proteggere il conto dai grandi drawdown è il modo migliore per farlo crescere."]),
 Q('Il compounding non premia chi corre. Premia chi **resta in gioco**.', "Il compounding non premia chi corre. Premia chi resta in gioco."),
])
