from h import *
LEZIONE = L('9.1', 'Modulo 9', 'Il tuo piano', 'Scrivere il piano di gestione del rischio', [
 T('LEZIONE 9.1', 'Il tuo **piano**', 'Una pagina, con i numeri, scritta prima di operare.', "Lezione nove punto uno. Scrivere il piano di gestione del rischio."),
 P('Perché una pagina', [('Un piano lungo non si rilegge', 'una pagina sì, ogni mattina'), ('Ogni riga è un numero o una regola', 'niente aggettivi'), ('Si firma e si data', 'è un impegno con te stesso')],
  ["Perché una sola pagina?", "Un piano lungo non si rilegge. Una pagina sì, ogni mattina.", "Ogni riga è un numero o una regola, niente aggettivi.", "E la firmi e la data: è un impegno con te stesso."]),
 TB('Le sette sezioni del piano', ['Sezione', 'Cosa contiene'], [['1 · Il sistema', 'win rate, RR medio, expectancy, numero di trade misurati'], ['2 · Il rischio', 'rischio per trade, rischio aperto massimo, metodo di calcolo del lotto'], ['3 · I limiti', 'perdita giornaliera, perdite di fila → stop, trade massimi'], ['4 · Drawdown', 'soglie per ridurre il rischio e per fermarsi'], ['5 · La gestione', 'break-even, trailing, scaglioni, aggiunte'], ['6 · La checklist', 'le domande prima di ogni ingresso'], ['7 · La revisione', 'quando e come controllo il piano']],
  ["Ecco le sette sezioni.", "Il sistema: win rate, RR medio, expectancy e numero di trade su cui sono misurati.", "Il rischio: per trade, aperto massimo e come calcoli il lotto.", "I limiti: perdita giornaliera, perdite di fila che fermano la sessione, trade massimi.", "Il drawdown: soglie per ridurre il rischio e per fermarsi.", "La gestione: break-even, trailing, scaglioni e aggiunte.", "La checklist: le domande prima di ogni ingresso.", "E la revisione: quando e come controlli il piano."]),
 TB('Un piano compilato (valori di esempio)', ['Voce', 'Valore'], [['Sistema', 'WR 45%, RR 1,8, E = +0,26 R (200 trade)'], ['Rischio per trade', '1% del capitale corrente'], ['Rischio aperto massimo', '3%'], ['Stop giornaliero', '−3% o 3 perdite di fila'], ['Trade massimi al giorno', '3'], ['Drawdown > 10%', 'rischio 0,5%'], ['Drawdown > 15%', 'sospendo e rivedo il sistema']],
  ["Un esempio di piano compilato, con valori di esempio.", "Il sistema: win rate quarantacinque per cento, RR uno virgola otto, expectancy più zero virgola ventisei R su duecento trade.", "Rischio per trade: uno per cento del capitale corrente.", "Rischio aperto massimo: tre per cento.", "Stop giornaliero: meno tre per cento oppure tre perdite di fila.", "Massimo tre trade al giorno.", "Con un drawdown oltre il dieci per cento, il rischio scende a zero virgola cinque.", "E oltre il quindici per cento, sospendo e rivedo il sistema."], nota='Esempio: non è un consiglio. I tuoi valori dipendono dal tuo sistema.'),
 P('Prima di firmare, tre verifiche', [('Ogni numero è coerente con il drawdown che sopporto?', 'usa la tabella della lezione 3.5'), ('Il piano regge lo stress test?', 'prova con win rate più basso e costi più alti'), ('Posso rispettarlo anche nel giorno peggiore?', 'se no, è troppo ambizioso')],
  ["Prima di firmare, tre verifiche.", "Ogni numero è coerente con il drawdown che sopporti? Usa la tabella della lezione tre punto cinque.", "Il piano regge lo stress test? Prova con un win rate più basso e costi più alti.", "E puoi rispettarlo anche nel giorno peggiore? Se no, è troppo ambizioso: riducilo ora, non dopo."]),
 *ES('il tuo piano', [['Compito', 'compila le sette sezioni con i TUOI numeri'], ['Tempo', '30 minuti'], ['Poi', 'stampa, firma, data']], [['Controlla', 'drawdown tollerabile'], ['', 'stress test'], ['', 'giorno peggiore']], 'Un piano firmato vale più di cento buoni propositi',
  ["Compito per te. Compila le sette sezioni con i tuoi numeri. Ti serviranno circa trenta minuti. Poi stampa, firma e data.", "Controlla tre cose: il drawdown tollerabile, lo stress test e se puoi rispettarlo nel giorno peggiore. Un piano firmato vale più di cento buoni propositi."]),
 RIEP(['Il piano sta in una pagina e ogni riga è un numero', 'Sette sezioni: sistema, rischio, limiti, drawdown, gestione, checklist, revisione', 'Verifica coerenza, stress test e giorno peggiore prima di firmare'], ["Riassumiamo.", "Il piano sta in una pagina, e ogni riga è un numero.", "Sette sezioni, dal sistema alla revisione.", "E prima di firmare verifica coerenza, stress test e giorno peggiore."]),
 Q('Un piano che non hai **scritto** non esiste.', "Un piano che non hai scritto non esiste."),
])
