from h import *
LEZIONE = L('9.2', 'Modulo 9', 'Tecniche avanzate', 'Il trailing stop loss in tutte le sue forme', [
 T('LEZIONE 9.2', 'Il **trailing stop** in tutte le sue forme', 'Cinque modi di far seguire lo stop al prezzo, con pregi e difetti.', "Lezione nove punto due. Il trailing stop loss, in tutte le sue forme."),
 P('Perché usarlo', [('Blocca una parte del guadagno mentre il trade corre', 'senza dover indovinare il massimo'), ('Lascia correre i trade migliori', 'non c\'è un target fisso che ti fa uscire troppo presto'), ('Toglie la decisione a caldo', 'la regola sposta lo stop al posto tuo')],
  ["Nella lezione otto punto uno abbiamo visto il trailing a scatti. Qui li vediamo tutti. Perché usarlo?", "Blocca una parte del guadagno mentre il trade corre, senza dover indovinare il massimo.", "Lascia correre i trade migliori: non c'è un target fisso che ti fa uscire troppo presto.", "E toglie la decisione a caldo: è la regola a spostare lo stop, non l'emozione."]),
 TB('Cinque tipi di trailing', ['Tipo', 'Come funziona', 'Esempio'], [['A distanza fissa', 'lo stop resta X pip sotto il massimo', '20 pip sotto il massimo'], ['A scatti', 'lo stop sale a gradini', '+25 pip → pareggio, +50 → +25'], ['Strutturale', 'lo stop va sotto l\'ultimo minimo', 'sotto ogni nuovo minimo crescente'], ['Con ATR', 'distanza = k × ATR', '2 × ATR(14)'], ['Temporale', 'esci se non succede nulla', 'dopo 4 ore senza movimento']],
  ["Ecco cinque tipi di trailing.", "A distanza fissa: lo stop resta sempre a un certo numero di pip sotto il massimo raggiunto, per esempio venti.", "A scatti: lo stop sale a gradini. A più venticinque pip va a pareggio, a più cinquanta va a più venticinque.", "Strutturale: lo stop va sotto l'ultimo minimo crescente, seguendo la struttura del grafico.", "Con l'ATR: la distanza è un multiplo della volatilità, per esempio due volte l'ATR.", "E temporale: se dopo un certo tempo il trade non si è mosso, esci. Non segue il prezzo, ma limita il tempo esposto al rischio."]),
 EX('Esempio: trailing a distanza fissa di 20 pip', [['Ingresso', '1,1000 · stop iniziale 1,0975'], ['Il prezzo sale a 1,1030', 'stop a 1,1010 (+10 pip)'], ['Il prezzo sale a 1,1060', 'stop a 1,1040 (+40 pip)'], ['Il prezzo torna a 1,1040', 'esci a +40 pip']], risultato='Hai tenuto 40 dei 60 pip del movimento', k=[1,2,3,4,5],
  voce=["Un esempio di trailing a distanza fissa, di venti pip. Entri a uno virgola uno zero zero zero, con lo stop iniziale venticinque pip sotto.", "Il prezzo sale a uno virgola uno zero tre zero: lo stop sale a venti pip di distanza, cioè a più dieci.", "Il prezzo sale fino a uno virgola uno zero sei zero: lo stop è a uno virgola uno zero quattro zero, più quaranta pip.", "Poi il prezzo torna indietro e tocca lo stop: esci a più quaranta pip.", "Il movimento massimo era di sessanta pip; ne hai tenuti quaranta, senza aver dovuto decidere nulla a caldo."]),
 TB('Pregi e difetti di ciascuno', ['Tipo', 'Pregio', 'Difetto'], [['Distanza fissa', 'semplice', 'ignora la volatilità'], ['A scatti', 'protegge per gradi', 'lascia indietro pip tra uno scatto e l\'altro'], ['Strutturale', 'segue il mercato', 'serve leggere il grafico'], ['Con ATR', 'si adatta alla volatilità', 'più largo nei mercati nervosi'], ['Temporale', 'libera capitale e attenzione', 'può chiudere un trade appena prima del movimento']],
  ["Pregi e difetti.", "La distanza fissa è semplice, ma ignora la volatilità.", "A scatti protegge per gradi, ma lascia indietro dei pip tra uno scatto e l'altro.", "Lo strutturale segue il mercato, ma richiede di saper leggere il grafico.", "Quello con l'ATR si adatta alla volatilità, ma diventa più largo quando il mercato è nervoso.", "Il temporale libera capitale e attenzione, ma a volte chiude un trade appena prima del movimento. Non esiste il migliore in assoluto: si sceglie e si misura."]),
 P('Gli errori più comuni', [('Trailing troppo stretto', 'esci al primo ritracciamento normale'), ('Cambiare tipo durante il trade', 'è una decisione a caldo travestita da regola'), ('Non misurarne l\'effetto', 'confronta nel journal i pip medi con e senza trailing')],
  ["Gli errori più comuni.", "Un trailing troppo stretto: esci al primo ritracciamento normale.", "Cambiare tipo di trailing durante il trade: è una decisione a caldo travestita da regola.", "E non misurarne l'effetto: confronta nel journal i pip medi con e senza trailing, su almeno cento operazioni."]),
 *ES('trailing a distanza fissa', [['Ingresso', '1,2000'], ['Trailing', '30 pip dal massimo'], ['Massimo raggiunto', '1,2075']], [['Stop', '1,2075 − 0,0030 = 1,2045'], ['Guadagno bloccato', '+45 pip']], 'Stop a 1,2045: +45 pip assicurati',
  ["Esercizio. Entri a uno virgola due zero zero zero, trailing a trenta pip dal massimo. Il prezzo ha toccato uno virgola due zero sette cinque. Dov'è lo stop e quanti pip hai già bloccato?", "Lo stop è trenta pip sotto il massimo: uno virgola due zero quattro cinque. Hai già assicurato quarantacinque pip."]),
 RIEP(['Cinque tipi: distanza fissa, scatti, strutturale, ATR, temporale', 'Il trailing blocca guadagni senza indovinare il massimo', 'Sceglilo prima e misuralo nel journal'], ["Riassumiamo ora i punti principali di questa lezione.", "Esistono cinque tipi di trailing: distanza fissa, a scatti, strutturale, con l'ATR e temporale.", "Il trailing blocca guadagni senza dover indovinare il massimo.", "Sceglilo prima di entrare, e misuralo nel journal."]),
 Q('Il trailing non cerca il **massimo**. Cerca di non restituire **tutto**.', "Il trailing non cerca il massimo. Cerca di non restituire tutto."),
])
