from h import *
LEZIONE = L('9.2', 'Modulo 9', 'Il tuo piano', 'La revisione mensile e il punto di arrivo', [
 T('LEZIONE 9.2', 'La **revisione** e il punto di arrivo', 'Come tenere vivo il piano e cosa ricordare del corso.', "Lezione nove punto due, l'ultima. La revisione mensile e il punto di arrivo."),
 P('Una revisione al mese', [('Stessa ora, stesso formato', 'quindici minuti, con i dati del journal'), ('Guardi i numeri, non le sensazioni', 'expectancy, profit factor, drawdown, regole rispettate'), ('Decidi solo cambiamenti piccoli e documentati', 'mai dopo una singola giornata storta')],
  ["Una volta al mese fai una revisione.", "Stessa ora, stesso formato, quindici minuti, con i dati del journal.", "Guardi i numeri, non le sensazioni: expectancy, profit factor, drawdown e regole rispettate.", "E decidi solo cambiamenti piccoli e documentati, mai dopo una singola giornata storta."]),
 TB('Gli indicatori della revisione', ['Indicatore', 'Cosa ti dice'], [['Expectancy in R', 'il sistema ha ancora un vantaggio?'], ['Profit factor', 'guadagni contro perdite'], ['Drawdown massimo del mese', 'ho rispettato i limiti?'], ['R previsto contro realizzato', 'sto eseguendo il piano?'], ['% di checklist rispettata', 'quanto sono disciplinato?'], ['Trade fuori piano', 'quanto mi costano?']],
  ["Gli indicatori della revisione.", "L'expectancy in R: il sistema ha ancora un vantaggio?", "Il profit factor: guadagni contro perdite.", "Il drawdown massimo del mese: hai rispettato i limiti?", "R previsto contro realizzato: stai eseguendo il piano?", "La percentuale di checklist rispettata: quanto sei disciplinato?", "E i trade fuori piano: quanto ti costano?"]),
 TB('Quando cambiare il piano', ['Situazione', 'Azione'], [['Poche operazioni (meno di ~100)', 'nessun cambiamento sul sistema'], ['Errori di esecuzione', 'lavora sulle regole, non sul sistema'], ['Expectancy negativa su 100+ trade', 'sospendi e rivedi il sistema'], ['Drawdown oltre la soglia scritta', 'applica la regola già decisa']],
  ["Quando cambiare il piano?", "Con poche operazioni, meno di cento circa, non cambiare il sistema: è rumore.", "Se il problema sono errori di esecuzione, lavora sulle regole e non sul sistema.", "Se l'expectancy è negativa su cento o più trade, sospendi e rivedi.", "E se il drawdown supera la soglia scritta, applica la regola già decisa, senza discuterla."]),
 P('Le tre domande, con le tue risposte', [('Quanto posso perdere al massimo su un trade?', 'il tuo rischio per trade'), ('Quante perdite di fila posso reggere?', 'il tuo limite e il tuo rischio, dalla lezione 3.3'), ('Quando mi fermo?', 'i tuoi stop giornalieri e di drawdown')],
  ["Ricordi le tre domande della prima lezione? Ora hai le risposte.", "Quanto posso perdere al massimo su un trade? Il tuo rischio per trade.", "Quante perdite di fila posso reggere? Il tuo limite e il tuo rischio, calcolati con la composizione.", "E quando mi fermo? I tuoi stop giornalieri e di drawdown."]),
 P('Cosa portare via', [('Il rischio viene prima della strategia', 'decide se sopravvivi e quanto soffri'), ('Misura tutto in R', 'e tienilo in un journal'), ('Dimensiona con numeri, non con l\'umore', 'rischio fisso, volatilità, Kelly come tetto'), ('Scrivi le regole prima', 'e rivedile con calma, una volta al mese')],
  ["Cosa portare via da questo corso.", "Il rischio viene prima della strategia: decide se sopravvivi e quanto soffri.", "Misura tutto in R e tienilo in un journal.", "Dimensiona con i numeri, non con l'umore: rischio fisso, volatilità e Kelly come tetto.", "Scrivi le regole prima, e rivedile con calma, una volta al mese."]),
 dict(tipo='avviso', titolo='Un ultimo avviso', testo=["**Questo corso è educativo e non è consulenza finanziaria.**", "Il trading con leva comporta un rischio elevato: **puoi perdere tutto il capitale**.", "Numeri, tabelle e simulazioni sono esempi: **non prevedono risultati futuri**.", "Gli strumenti Riskly citati sono **prodotti miei**: non sono necessari per applicare quanto hai imparato."],
  voce=["Un ultimo avviso, perché è importante. Questo corso è educativo e non è consulenza finanziaria. Il trading con leva comporta un rischio elevato: puoi perdere tutto il capitale. Numeri, tabelle e simulazioni sono esempi, e non prevedono risultati futuri. Gli strumenti Riskly citati sono prodotti miei, e non sono necessari per applicare quello che hai imparato."]),
 Q('Non puoi controllare il mercato. Puoi controllare **quanto rischi**.', "Grazie per essere arrivato fino in fondo. Non puoi controllare il mercato. Puoi controllare quanto rischi."),
])
