from h import *
LEZIONE = L('9.3', 'Modulo 9', 'Tecniche avanzate', 'Ingressi a scaglioni', [
 T('LEZIONE 9.3', 'Entrare a **scaglioni**', 'Dividere l\'ingresso su più livelli, con il rischio calcolato prima.', "Lezione nove punto tre. Gli ingressi a scaglioni."),
 P('L\'idea', [('Invece di entrare tutto a un prezzo, dividi l\'ingresso', 'per esempio tre ordini su tre livelli'), ('Lo stop è unico per tutti gli scaglioni', 'è il livello in cui l\'idea è sbagliata'), ('Il rischio si calcola come se entrassero tutti', 'è il caso peggiore')],
  ["L'idea è semplice: invece di entrare con tutta la posizione a un solo prezzo, dividi l'ingresso su più livelli. Per esempio tre ordini.", "Lo stop è unico per tutti gli scaglioni: è il livello in cui l'idea è sbagliata.", "E il rischio si calcola come se entrassero tutti, perché è il caso peggiore."]),
 D('Tre ingressi, uno stop', 'ingressi', ['ordini', 'e1', 'e2', 'e3', 'media'],
  ["Vediamolo sul grafico.", "Piazzi tre ordini da zero virgola due lotti: a uno virgola uno zero zero zero, a uno virgola zero nove nove zero e a uno virgola zero nove otto zero. Lo stop comune è a uno virgola zero nove sei zero.", "Il prezzo scende e prende il primo ingresso: il suo stop è a quaranta pip.", "Poi il secondo, a trenta pip dallo stop.", "Poi il terzo, a venti pip dallo stop.", "Il prezzo medio è uno virgola zero nove nove zero. Il rischio totale è zero virgola due lotti per dieci euro, per quaranta più trenta più venti pip: centottanta euro."],
  didascalia='Esempio illustrativo con prezzi simulati.'),
 EX('Il rischio va deciso prima', [['Rischio massimo voluto', '1% di 10.000 € = 100 €'], ['Pip di rischio dei tre scaglioni', '40 + 30 + 20 = 90 pip'], ['Lotti per scaglione', '100 ÷ (90 × 10) = 0,11'], ['Se entra solo il primo', 'rischio 0,11 × 10 × 40 = 44 €']], risultato='Con 0,11 lotti per scaglione, al massimo perdi 100 €', k=[1,2,3,4,5],
  voce=["Il rischio va deciso prima. Se vuoi rischiare al massimo l'uno per cento di diecimila euro, cioè cento euro,", "sommi i pip di rischio dei tre scaglioni: quaranta più trenta più venti, novanta pip.", "I lotti per scaglione sono cento diviso novanta per dieci: zero virgola undici.", "Se entra solo il primo, rischi appena quarantaquattro euro.", "Se entrano tutti e tre, perdi al massimo cento euro. Mai di più, qualunque cosa succeda."]),
 CF('Scaglioni pianificati contro mediare in perdita', dict(t='Scaglioni pianificati', punti=[['Livelli decisi prima', ''], ['Stop unico e fisso', ''], ['Rischio totale calcolato', '']]), dict(t='Mediare in perdita', punti=[['Aggiungi perché perdi', ''], ['Stop spostato o assente', ''], ['Rischio che cresce', '']]),
  ["Attenzione a non confonderli con il mediare in perdita.", "Gli scaglioni pianificati hanno livelli decisi prima, uno stop unico e fisso, e un rischio totale calcolato.", "Mediare in perdita significa aggiungere perché stai perdendo, spesso spostando o togliendo lo stop. Il rischio cresce senza limite."], 'La differenza è tutta nel piano scritto prima.'),
 TB('Benefici e limiti', ['', 'Ingressi a scaglioni'], [['Beneficio', 'prezzo medio migliore se il prezzo ritraccia'], ['Beneficio', 'meno ansia di «indovinare» il punto esatto'], ['Beneficio', 'se entra solo una parte, rischi meno'], ['Limite', 'nei trade migliori entra solo il primo scaglione'], ['Limite', 'il terzo scaglione entra spesso quando il trade va male']],
  ["Benefici e limiti.", "Ottieni un prezzo medio migliore se il prezzo ritraccia.", "Hai meno ansia di indovinare il punto esatto.", "E se entra solo una parte, rischi meno.", "Il limite è che nei trade migliori spesso entra solo il primo scaglione, quindi guadagni meno.", "E l'ultimo scaglione entra spesso proprio quando il trade sta andando male. Per questo il rischio totale va sempre calcolato sul caso peggiore."]),
 *ES('ingressi a scaglioni', [['Scaglione 1', '0,1 lotti a 1,2000'], ['Scaglione 2', '0,1 lotti a 1,1980'], ['Stop comune', '1,1950'], ['Valore pip', '10 € per lotto']], [['Scaglione 1', '50 pip × 1 € = 50 €'], ['Scaglione 2', '30 pip × 1 € = 30 €']], 'Rischio totale: 80 €',
  ["Esercizio. Due scaglioni da zero virgola uno lotti, a uno virgola due zero zero zero e uno virgola uno nove otto zero. Stop comune a uno virgola uno nove cinque zero. Qual è il rischio totale?", "Il primo ha cinquanta pip di stop, il secondo trenta. Con zero virgola uno lotti un pip vale un euro: cinquanta più trenta, ottanta euro di rischio totale."]),
 RIEP(['Ingresso diviso su più livelli, con stop unico', 'Il rischio si calcola come se entrassero tutti', 'Pianificato prima: non è mediare in perdita'], ["Riassumiamo ora i punti principali di questa lezione.", "Gli ingressi a scaglioni dividono l'ingresso su più livelli, con uno stop unico.", "Il rischio si calcola come se entrassero tutti.", "E si pianificano prima: non è mediare in perdita."]),
 Q('Entrare a scaglioni cambia il **prezzo medio**. Non deve cambiare il **rischio massimo**.', "Entrare a scaglioni cambia il prezzo medio. Non deve cambiare il rischio massimo."),
])
