from h import *
LEZIONE = L('9.4', 'Modulo 9', 'Tecniche avanzate', 'Uscite a scaglioni e break-even sui restanti', [
 T('LEZIONE 9.4', 'Scaglioni in uscita, **in pratica**', 'Target vicini, break-even sul resto: come funziona e quanto deve funzionare.', "Lezione nove punto quattro. Le uscite a scaglioni con il break-even sui restanti."),
 P('Lo schema tipico', [('Posizione divisa in più parti uguali', 'per esempio 3 parti da 0,2 lotti'), ('Target vicini sulle prime parti', 'per esempio +10 e +20 pip'), ('Dopo il primo target, stop a pareggio sul resto', 'il trade non può più diventare una perdita piena'), ('L\'ultima parte corre', 'con trailing o target lontano')],
  ["Uno schema molto usato, anche con i bot, è questo.", "Dividi la posizione in più parti uguali, per esempio tre parti da zero virgola due lotti.", "Metti target vicini sulle prime parti: per esempio più dieci e più venti pip.", "Dopo il primo target, sposti lo stop a pareggio su tutto il resto: il trade non può più diventare una perdita piena.", "E l'ultima parte corre, con un trailing o con un target lontano."]),
 TB('Gli scenari, con 0,6 lotti e stop a 25 pip', ['Scenario', 'Calcolo', 'Risultato'], [['Stop subito', '0,6 × 10 € × 25 pip', '−150 €'], ['TP1, poi pareggio', '0,2 × 10 × 10', '+20 €'], ['TP1 e TP2, poi pareggio', '20 + 0,2 × 10 × 20', '+60 €'], ['TP1, TP2, ultima parte a +50', '20 + 40 + 0,2 × 10 × 50', '+160 €']],
  ["Vediamo gli scenari con zero virgola sei lotti e uno stop di venticinque pip.", "Se lo stop scatta subito, perdi su tutta la posizione: meno centocinquanta euro.", "Se prendi il primo target e il resto torna a pareggio: più venti euro.", "Se prendi il primo e il secondo, e l'ultima parte torna a pareggio: più sessanta euro.", "E se l'ultima parte corre fino a più cinquanta pip: più centosessanta euro."], nota='0,2 lotti = 2 € a pip per ogni scaglione.'),
 N('La spiegazione che quasi nessuno dà', '88%', ["C'è un dettaglio che quasi nessuno spiega.", "Se il caso più comune è primo target e poi pareggio, guadagni venti euro, ma quando va male ne perdi centocinquanta. Per andare in pari, il primo target deve essere raggiunto circa ottantotto volte su cento.", "Target molto vicini danno tante piccole vittorie, ma richiedono una percentuale di successo altissima. Solo il journal ti dice se il tuo sistema ci arriva."], 'dei trade devono toccare il primo target per andare in pari, se il resto va a pareggio'),
 TB('Benefici e attenzioni', ['', 'Uscite a scaglioni con break-even'], [['Beneficio', 'incassi presto: la giornata «non è mai a zero»'], ['Beneficio', 'dopo TP1 il trade non può più perdere tutto'], ['Beneficio', 'l\'ultima parte ti tiene dentro i movimenti grandi'], ['Attenzione', 'il primo target troppo vicino richiede un win rate altissimo'], ['Attenzione', 'il break-even troppo presto chiude trade che sarebbero arrivati lontano']],
  ["Benefici e attenzioni.", "Incassi presto: la giornata non è mai a zero.", "Dopo il primo target, il trade non può più perdere tutto.", "L'ultima parte ti tiene dentro i movimenti grandi.", "Ma attenzione: un primo target troppo vicino richiede un win rate altissimo.", "E il break-even troppo presto chiude trade che sarebbero arrivati lontano. Registra nel journal i lotti e l'esito di ogni scaglione: così vedi quale parte del tuo schema rende davvero. Il Riskly Journal lo fa, ed è un mio prodotto; anche un foglio di calcolo funziona."]),
 *ES('scaglioni in uscita', [['Posizione', '3 parti da 0,1 lotti'], ['TP1', '+15 pip'], ['TP2', '+30 pip'], ['Terza parte', 'chiusa a pareggio dopo TP2']], [['TP1', '0,1 × 10 × 15 = 15 €'], ['TP2', '0,1 × 10 × 30 = 30 €'], ['Terza parte', '0 €']], 'Totale: +45 €',
  ["Esercizio. Tre parti da zero virgola uno lotti. Il primo target a più quindici pip, il secondo a più trenta. La terza parte viene chiusa a pareggio dopo il secondo target. Quanto guadagni?", "Il primo scaglione vale quindici euro, il secondo trenta, il terzo zero. Totale quarantacinque euro."]),
 RIEP(['Parti uguali, target vicini, break-even sul resto, ultima parte che corre', 'Calcola ogni scenario in pip ed euro', 'Target troppo vicini richiedono un win rate altissimo: misuralo'], ["Riassumiamo ora i punti principali di questa lezione.", "Lo schema è: parti uguali, target vicini, break-even sul resto e un'ultima parte che corre.", "Calcola ogni scenario in pip e in euro.", "E ricorda che target troppo vicini richiedono un win rate altissimo: misuralo prima di fidarti."]),
 Q('Tante piccole vittorie valgono solo se **le perdite** restano **rare**.', "Tante piccole vittorie valgono solo se le perdite restano rare."),
])
