from h import *
LEZIONE = L('9.5', 'Modulo 9', 'Tecniche avanzate', 'Mitigare il rischio di un trade aperto', [
 T('LEZIONE 9.5', '**Mitigare** il rischio', 'Cosa puoi fare quando il trade è già aperto, e cosa non devi fare mai.', "Lezione nove punto cinque. Come mitigare il rischio di un trade già aperto."),
 P('Mitigare non vuol dire scappare', [('Ridurre il rischio di un trade aperto è legittimo', 'se segui una regola decisa prima'), ('Non è mitigare: allargare lo stop o mediare in perdita', 'quelle azioni aumentano il rischio'), ('Ogni tecnica ha un costo', 'di solito riduce anche il guadagno possibile')],
  ["Mitigare il rischio non vuol dire scappare dal trade.", "Ridurre il rischio di una posizione aperta è legittimo, se segui una regola decisa prima.", "Non è mitigare allargare lo stop o mediare in perdita: quelle azioni aumentano il rischio.", "E ogni tecnica di mitigazione ha un costo: di solito riduce anche il guadagno possibile."]),
 TB('Le tecniche principali', ['Tecnica', 'Cosa riduce', 'Cosa costa'], [['Chiusura parziale', 'l\'esposizione', 'una parte del guadagno futuro'], ['Stop a pareggio', 'la perdita piena', 'trade chiusi a zero'], ['Uscita su invalidazione', 'la perdita, prima dello stop', 'qualche trade che sarebbe ripartito'], ['Stop temporale', 'il tempo esposto', 'qualche movimento tardivo'], ['Ridurre prima delle notizie', 'il rischio di gap e slippage', 'i movimenti delle notizie']],
  ["Le tecniche principali.", "La chiusura parziale riduce l'esposizione, e costa una parte del guadagno futuro.", "Lo stop a pareggio elimina la perdita piena, ma chiude alcuni trade a zero.", "L'uscita su invalidazione: se il motivo del trade sparisce prima dello stop, esci. Riduci la perdita, ma qualche trade sarebbe ripartito.", "Lo stop temporale riduce il tempo in cui sei esposto, ma perdi i movimenti tardivi.", "E ridurre la posizione prima delle notizie riduce il rischio di gap e slippage, rinunciando ai movimenti delle notizie."]),
 EX('Esempio: chiusura parziale', [['Posizione', '0,4 lotti, stop a 25 pip = rischio 100 €'], ['Il prezzo è a +15 pip', 'chiudi metà: incassi 0,2 × 10 × 15 = 30 €'], ['Resto: 0,2 lotti, stop invariato', 'rischio rimasto 0,2 × 10 × 25 = 50 €'], ['Caso peggiore ora', '30 − 50 = −20 €']], risultato='Da −100 € a −20 € nel caso peggiore', k=[1,2,3,4,5],
  voce=["Un esempio di chiusura parziale. Hai zero virgola quattro lotti con lo stop a venticinque pip: cento euro di rischio.", "Il prezzo è a più quindici pip e chiudi metà posizione: incassi trenta euro.", "Il resto, zero virgola due lotti con lo stop dove era, rischia ancora cinquanta euro.", "Nel caso peggiore, se il prezzo torna allo stop, il trade chiude a meno venti euro.", "Prima rischiavi cento euro, ora venti. Il prezzo da pagare è che, se il trade va a target, guadagni su metà posizione in meno."]),
 EX('Esempio: uscita su invalidazione', [['Entri long: l\'idea è il rimbalzo dal supporto', 'stop a −25 pip'], ['Il prezzo chiude sotto il supporto, a −10 pip', 'il motivo del trade non c\'è più'], ['Esci subito', '−10 pip invece di −25']], risultato='Con 0,4 lotti: −40 € invece di −100 €', k=[1,2,3,4],
  voce=["Un esempio di uscita su invalidazione. Entri long perché il prezzo rimbalza da un supporto, con lo stop a venticinque pip.", "Una candela chiude sotto il supporto, quando sei a meno dieci pip. Il motivo per cui sei entrato non esiste più.", "Esci subito: meno dieci pip invece di meno venticinque.", "Con zero virgola quattro lotti, perdi quaranta euro invece di cento. Ma attenzione: la condizione di invalidazione va scritta nel piano, non decisa per paura."]),
 P('Le regole per farlo bene', [('Scrivi prima quale tecnica usi e quando', 'per esempio: chiudo metà a +15 pip'), ('Mai allargare lo stop, mai aggiungere in perdita', 'queste non sono mitigazioni'), ('Misura nel journal quanto ti costa e quanto ti salva', 'su almeno 100 trade')],
  ["Le regole per farlo bene.", "Scrivi prima quale tecnica usi e quando: per esempio, chiudo metà a più quindici pip.", "Mai allargare lo stop, mai aggiungere in perdita: queste non sono mitigazioni.", "E misura nel journal quanto ti costa e quanto ti salva, su almeno cento trade."]),
 *ES('chiusura parziale', [['Posizione', '0,6 lotti, stop a 25 pip'], ['Prezzo', '+20 pip'], ['Azione', 'chiudi un terzo (0,2 lotti)']], [['Incassi', '0,2 × 10 × 20 = 40 €'], ['Rischio rimasto', '0,4 × 10 × 25 = 100 €'], ['Caso peggiore', '40 − 100 = −60 €']], 'Da −150 € a −60 € nel caso peggiore',
  ["Esercizio. Hai zero virgola sei lotti con stop a venticinque pip. Il prezzo è a più venti pip e chiudi un terzo della posizione. Qual è ora il caso peggiore?", "Incassi quaranta euro. Il resto, zero virgola quattro lotti, rischia cento euro. Il caso peggiore diventa meno sessanta euro invece di meno centocinquanta."]),
 RIEP(['Mitigare = ridurre il rischio con una regola decisa prima', 'Chiusure parziali, pareggio, invalidazione, stop temporale, notizie', 'Allargare lo stop o mediare in perdita non è mitigare'], ["Riassumiamo ora i punti principali di questa lezione.", "Mitigare significa ridurre il rischio con una regola decisa prima.", "Le tecniche sono chiusure parziali, pareggio, uscita su invalidazione, stop temporale e attenzione alle notizie.", "Allargare lo stop o mediare in perdita non è mitigare: è il contrario."]),
 Q('Si mitiga con una **regola**, non con la **paura**.', "Si mitiga con una regola, non con la paura."),
])
