from h import *
LEZIONE = L('9.6', 'Modulo 9', 'Tecniche avanzate', 'L\'hedging', [
 T('LEZIONE 9.6', 'L\'**hedging**', 'Coprire una posizione con una opposta: cosa fa davvero, e cosa non fa.', "Lezione nove punto sei. L'hedging, cioè la copertura."),
 P('Che cos\'è', [('Apri una posizione opposta a quella che hai', 'sullo stesso strumento o su uno correlato'), ('Le due posizioni si compensano', 'il risultato smette di muoversi'), ('Si usa per congelare un\'esposizione', 'non per cancellare una perdita')],
  ["L'hedging, o copertura, significa aprire una posizione opposta a quella che hai già: sullo stesso strumento, oppure su uno correlato.", "Le due posizioni si compensano, e il risultato complessivo smette di muoversi.", "Si usa per congelare un'esposizione, non per cancellare una perdita."]),
 D('Cosa succede sul grafico', 'hedge', ['buy', 'sell', 'muove', 'fermo'],
  ["Vediamo un esempio sul grafico.", "Compri zero virgola quattro lotti a uno virgola uno zero zero zero.", "Il prezzo scende di venti pip. Invece di chiudere, apri una vendita da zero virgola quattro lotti a uno virgola zero nove otto zero. In quel momento sei a meno ottanta euro.", "Ora il prezzo può salire o scendere quanto vuole.", "Il risultato resta fermo a meno ottanta euro, più spread e costi di mantenimento. La perdita non è sparita: è congelata."],
  didascalia='Esempio illustrativo con prezzi simulati.'),
 CF('Hedging contro chiusura', dict(t='Chiudi a −20 pip', punti=[['Perdita', '−80 €'], ['Costi in più', 'nessuno'], ['Decisioni ancora da prendere', 'nessuna']]), dict(t='Copri a −20 pip', punti=[['Perdita', '−80 € (congelata)'], ['Costi in più', 'spread, swap'], ['Decisioni ancora da prendere', 'quando togliere quale gamba']]),
  ["Confrontiamo copertura e chiusura.", "Se chiudi a meno venti pip, perdi ottanta euro e basta. Nessun costo aggiuntivo, nessuna decisione da prendere.", "Se copri, perdi gli stessi ottanta euro, ma paghi in più spread e swap, e prima o poi devi decidere quale delle due posizioni chiudere per prima. È la stessa decisione che avresti dovuto prendere subito, solo rimandata."], 'Sullo stesso strumento, coprire equivale a chiudere, con più costi.'),
 TB('Prima di usarlo: regole e limiti', ['Contesto', 'Cosa sapere'], [['Conti MT5 «netting»', 'non puoi tenere due posizioni opposte: la seconda riduce la prima'], ['Conti MT5 «hedging» e MT4', 'puoi tenerle, ma paghi spread e swap su entrambe'], ['Broker statunitensi', 'la regola FIFO vieta di tenere posizioni opposte sullo stesso strumento'], ['Prop firm', 'molte vietano l\'hedging, soprattutto tra conti diversi: leggi il regolamento']],
  ["Prima di usarlo, conosci i limiti.", "Sui conti MetaTrader cinque di tipo netting non puoi tenere due posizioni opposte: la seconda riduce la prima.", "Sui conti di tipo hedging e su MetaTrader quattro puoi tenerle, ma paghi spread e swap su entrambe.", "Con i broker statunitensi, la regola FIFO vieta di tenere posizioni opposte sullo stesso strumento.", "E molte prop firm vietano l'hedging, soprattutto tra conti diversi. Leggi sempre il regolamento."]),
 P('Quando ha senso, e quando no', [('Ha senso: proteggere un portafoglio di lungo periodo', 'per esempio azioni coperte temporaneamente con un indice'), ('Ha senso: coprire un\'esposizione valutaria', 'per esempio incassi in dollari e conti in euro'), ('Non ha senso: evitare di prendere lo stop', 'è solo un modo di non accettare la perdita, pagando di più')],
  ["Quando ha senso?", "Per proteggere un portafoglio di lungo periodo, per esempio azioni che non vuoi vendere, coperte temporaneamente con un indice.", "Oppure per coprire un'esposizione valutaria, per esempio se incassi in dollari e hai i conti in euro.", "Non ha senso per evitare di prendere lo stop in un trade di breve periodo: è solo un modo di non accettare la perdita, pagando di più."]),
 *ES('hedging', [['Buy', '0,2 lotti a 1,2500'], ['Il prezzo scende a', '1,2460: apri sell 0,2 lotti'], ['Poi il prezzo va a', '1,2400'], ['Domanda', 'risultato totale?']], [['Buy', '−100 pip × 2 € = −200 €'], ['Sell', '+60 pip × 2 € = +120 €'], ['Totale', '−80 €, come al momento della copertura']], 'Il risultato non cambia: la perdita è congelata, più i costi',
  ["Esercizio. Compri zero virgola due lotti a uno virgola due cinque zero zero. Il prezzo scende a uno virgola due quattro sei zero e apri una vendita da zero virgola due lotti. Poi il prezzo arriva a uno virgola due quattro zero zero. Qual è il risultato totale?", "L'acquisto perde cento pip, cioè duecento euro. La vendita guadagna sessanta pip, centoventi euro. Totale: meno ottanta euro, esattamente come al momento della copertura. Più i costi."]),
 RIEP(['L\'hedging congela un\'esposizione: non cancella la perdita', 'Sullo stesso strumento equivale a chiudere, con più costi', 'Ha senso per portafogli e valute; verifica broker e prop firm'], ["Riassumiamo ora i punti principali di questa lezione.", "L'hedging congela un'esposizione: non cancella la perdita.", "Sullo stesso strumento equivale a chiudere, con più costi e una decisione rimandata.", "Ha senso per portafogli e valute, e va sempre verificato con le regole del broker e della prop firm. Con questo il modulo sulle tecniche avanzate è completo: resta il tuo piano."]),
 Q('Una perdita **coperta** è ancora una **perdita**.', "Una perdita coperta è ancora una perdita."),
])
