# Parlato in stile lezione (insegnante che parla allo studente). Sostituisce la voce delle slide indicate:
# PARLATO[lezione][indice slide] = lista di passaggi (stesso numero dei passaggi originali, per restare in sincronia).
PARLATO = {}
PARLATO['0.0'] = {
 0: ["Ciao, e benvenuto in questo corso. Oggi cominciamo a parlare di una cosa che quasi tutti trascurano quando iniziano a fare trading: la gestione del rischio. Ti accompagnerò passo per passo, dalle basi fino alle tecniche che usano i professionisti. E ti anticipo subito l'idea che ci guiderà fino alla fine: il mercato non lo puoi controllare, ma quanto rischi lo decidi tu."],
 1: ["Prima di tutto, vediamo per chi è pensato questo corso. Sono tre tipi di persone, e probabilmente ti riconosci in almeno uno.",
     "Il primo è chi sta iniziando adesso. Se sei qui, hai un vantaggio enorme: puoi partire con le regole giuste, prima di perdere i primi soldi per imparare.",
     "Il secondo è chi ha già un conto. Magari qualche mese va bene e qualche mese va male, e hai la sensazione che i risultati dipendano più dall'umore della giornata che da un metodo.",
     "Il terzo è chi sta affrontando la sfida di una prop firm. Lì un limite superato anche di poco significa perdere tutto il lavoro fatto, e la gestione del rischio diventa la cosa più importante."],
 2: ["Com'è organizzato? Il corso è diviso in dieci moduli e quarantasei lezioni brevi. Ogni lezione affronta un solo argomento, così puoi guardarla anche in pausa pranzo.",
     "In ogni lezione ti spiego prima il perché delle cose, con parole semplici. Solo dopo arrivano i numeri, e ogni volta li facciamo insieme con un esempio concreto, come se fossimo seduti allo stesso tavolo.",
     "E alla fine del percorso non avrai solo visto dei video: avrai scritto il tuo piano personale di gestione del rischio, su una sola pagina, con i tuoi numeri."],
 3: ["Ecco la mappa del viaggio. Partiamo dalle basi: quanto rischiare, dove mettere lo stop, come calcolare il lotto. Poi impariamo a capire se un sistema funziona davvero, e cosa succede al conto quando arrivano le perdite. Vediamo come dimensionare le posizioni, come simulare il futuro, come costruire la disciplina e come affrontare le prop firm. Poi parliamo di gestione della posizione aperta e delle tecniche avanzate, come compounding, trailing stop, scaglioni e hedging. E chiudiamo scrivendo insieme il tuo piano."],
 4: ["Prima di cominciare, però, c'è una cosa che voglio dirti con chiarezza. Questo è un corso educativo, non una consulenza finanziaria. Fare trading con la leva, su forex, CFD o futures, è rischioso, e si può perdere tutto il capitale. I numeri che vedrai sono esempi e simulazioni: servono a capire, non sono promesse di guadagno. E quando ti mostrerò uno strumento Riskly te lo dirò chiaramente, perché sono prodotti miei."],
 5: ["Bene, allora cominciamo davvero. Tieni a mente questa frase, perché la ritroverai in tutto il corso: non controlli il mercato, ma controlli quanto rischi."],
}
PARLATO['1.1'] = {
 0: ["Eccoci alla prima lezione. Oggi vediamo perché il rischio viene prima della strategia, e ti mostro un esempio che di solito cambia il modo di vedere il trading."],
 1: ["Quando si comincia, quasi tutti la pensano allo stesso modo: se trovo la strategia giusta, allora guadagno. È un pensiero normale, l'ho avuto anche io.",
     "E così si passano settimane a studiare indicatori, pattern, segnali, sempre alla ricerca di quello perfetto.",
     "E la domanda su quanto rischiare a ogni operazione? Arriva dopo. A volte non arriva proprio. Ed è proprio questo l'errore: l'ordine è sbagliato."],
 2: ["Ti faccio vedere perché con un esempio. Immagina due trader che usano esattamente la stessa strategia. Vincono quarantacinque operazioni su cento, e quando vincono guadagnano quasi il doppio di quello che rischiano. L'unica differenza tra loro è quanto rischiano a ogni trade. Ho simulato duecento operazioni per ciascuno, e questi sono i risultati tipici.",
     "Il trader B rischia l'uno per cento del conto a operazione. Nel suo momento peggiore, di solito, si trova sotto di circa il dieci per cento. E dopo duecento trade il suo conto è cresciuto di circa due terzi.",
     "Il trader A rischia il quattro per cento. Sulla carta guadagna molto di più, il conto può arrivare a quasi sette volte quello iniziale. Ma guarda il prezzo da pagare: nel momento peggiore è tipicamente sotto del trentacinque per cento, e una volta su dieci perde più della metà del conto.",
     "E allora la vera domanda non è chi guadagna di più. È un'altra: tu riusciresti a vedere il tuo conto sotto del trentacinque per cento, senza cambiare piano, senza raddoppiare per recuperare, senza mollare proprio nel momento sbagliato? La maggior parte delle persone, sinceramente, no."],
 3: ["Quindi il rischio per operazione decide due cose molto concrete.",
     "La prima: se sopravvivi. Con un rischio troppo alto, una normale serie di perdite, di quelle che capitano a tutti, può distruggere il conto.",
     "La seconda: quanto soffri lungo la strada. Anche se il conto non salta, un calo profondo ti mette sotto pressione e ti fa prendere decisioni sbagliate. E un piano bellissimo sulla carta non serve a niente, se poi non riesci a seguirlo."],
 4: ["Per questo, lezione dopo lezione, risponderemo insieme a tre domande.",
     "Prima domanda: quanto posso perdere, al massimo, su una singola operazione?",
     "Seconda domanda: quante perdite di fila posso sopportare, senza che il conto ne esca distrutto?",
     "Terza domanda: quando mi fermo, prima che sia troppo tardi? Se alla fine del corso avrai scritto tre risposte precise, con dei numeri, avrai già fatto metà del lavoro."],
 5: ["Facciamo un esempio ancora più semplice, con un conto da diecimila euro. Cinque perdite di fila non sono una sfortuna rara: capitano a qualsiasi sistema, prima o poi.",
     "Se rischi l'uno per cento a operazione, dopo cinque perdite il conto passa da diecimila a circa novemilacinquecento euro. Hai perso poco meno del cinque per cento. Fastidioso, ma si recupera tranquillamente.",
     "Se invece rischi il cinque per cento, le stesse cinque perdite ti portano a circa settemilasettecento euro. Hai perso quasi un quarto del conto, e per tornare a diecimila ti serve guadagnare quasi il trenta per cento.",
     "Hai notato? La serie di perdite è esattamente la stessa. L'unica cosa che cambia è quanto rischiavi. È il rischio, non la sfortuna, a trasformare una brutta settimana in un disastro."],
 6: ["Adesso tocca a te. Se vuoi, metti in pausa il video e prova a fare i conti. Hai un conto da ventimila euro e rischi il due per cento a operazione. Quanto perdi al massimo su un singolo trade? E quanto ti rimane dopo tre perdite di fila?"],
 7: ["Vediamo insieme. Il due per cento di ventimila euro sono quattrocento euro: questa è la perdita massima su un trade. Dopo la prima perdita hai diciannovemilaseicento euro, e il due per cento successivo lo calcoli su questa cifra, non su ventimila. Dopo tre perdite ti restano circa diciottomilaottocentoventiquattro euro. Hai perso il cinque virgola nove per cento, non il sei: perché ogni volta il due per cento si applica a un conto un po' più piccolo."],
 8: ["Facciamo un piccolo riepilogo di questa prima lezione.",
     "Quanto rischi a ogni operazione decide se sopravvivi, e anche quanto soffri lungo la strada.",
     "Con la stessa identica strategia, due livelli di rischio diversi portano a risultati e a esperienze completamente diverse.",
     "E da qui in avanti ci servono tre numeri scritti: la perdita massima per operazione, quante perdite di fila puoi reggere, e il punto in cui ti fermi."],
 9: ["E prima di passare alla prossima lezione, ricordati questa frase: prima di chiederti quanto puoi guadagnare, chiediti quanto sei disposto a perdere."],
}
PARLATO['1.2'] = {
 0: ["Bentornato. In questa lezione parliamo del concetto più importante di tutto il corso: il rischio per singola operazione."],
 1: ["Partiamo da una domanda semplice: cosa vuol dire rischiare? Vuol dire quanto perdi se l'operazione va male, cioè se il prezzo arriva al tuo stop loss.",
     "E questo rischio lo misuriamo in percentuale del conto. Non in pip, e nemmeno in lotti, perché sono numeri che da soli non ti dicono quanto stai mettendo in gioco.",
     "E soprattutto, il rischio si decide prima di entrare. Mai a operazione già aperta, quando le emozioni sono già in movimento."],
 2: ["Facciamo un esempio concreto. Diciamo che hai un conto da diecimila euro.",
     "E decidi che su ogni operazione rischi l'uno per cento.",
     "L'uno per cento di diecimila euro sono cento euro. Quindi, su ogni singolo trade, la perdita massima che accetti è di cento euro.",
     "Se il trade va male, perdi cento euro, e non un euro di più. E la cosa bella è che questo numero lo conosci prima di cliccare. Niente sorprese."],
 3: ["Ma quanto è giusto rischiare? Ti do qualche ordine di grandezza, sempre su un conto da diecimila euro.",
     "Lo zero virgola cinque per cento, cioè cinquanta euro, è un rischio prudente. È tipico di chi affronta una prop firm, dove i limiti sono stretti.",
     "L'uno per cento, cioè cento euro, è il riferimento più usato.",
     "Il due per cento, duecento euro, è già alto: qualche perdita di fila e il conto ne risente parecchio.",
     "Il cinque per cento, cinquecento euro a operazione, è molto aggressivo. Bastano poche perdite di fila per fare un danno serio.",
     "Non esiste un numero giusto per tutti. Dipende dal tuo sistema e da quanto calo del conto riesci davvero a sopportare, senza perdere la testa. Nei prossimi moduli impareremo a calcolarlo con precisione."],
 4: ["Ci sono tre errori che vedo fare continuamente, e voglio che tu li conosca.",
     "Il primo: rischiare di più dopo una perdita, per rifarsi subito. È la strada più veloce per trasformare una giornata storta in un disastro.",
     "Il secondo: rischiare di più quando ti senti sicuro di un trade. Il mercato non sa quanto sei sicuro.",
     "Il terzo: non sapere quanto stai rischiando finché non sei già dentro. Il rischio si decide prima, con un numero preciso, ogni volta."],
 5: ["C'è un dettaglio importante: la percentuale resta sempre la stessa, ma l'importo in euro cambia insieme al conto.",
     "Con diecimila euro, l'uno per cento sono cento euro.",
     "Se il conto cresce fino a dodicimila, l'uno per cento diventa centoventi euro. Rischi un po' di più in euro, ma in proporzione è sempre lo stesso.",
     "E se il conto scende a ottomila, l'uno per cento diventa ottanta euro. Vedi cosa succede? Quando perdi, le tue posizioni diventano automaticamente più piccole. È come un freno che si attiva da solo e ti protegge."],
 6: ["Proviamo con un esercizio veloce. Hai un conto da venticinquemila euro e decidi di rischiare mezzo punto percentuale a operazione. Quanto rischi in euro su ogni trade?"],
 7: ["Facile: lo zero virgola cinque per cento di venticinquemila euro sono centoventicinque euro. Questa è la tua perdita massima su ogni operazione."],
 8: ["Ricapitoliamo quello che abbiamo visto oggi.",
     "Il rischio è quanto perdi se il trade va male, cioè se il prezzo tocca il tuo stop.",
     "Si esprime in percentuale del conto, e si decide prima di entrare, mai dopo.",
     "E in euro si adatta da solo: quando il conto scende, anche le posizioni si rimpiccioliscono."],
 9: ["E ricordati: il rischio è un numero che decidi prima di entrare, non una sensazione che provi dopo."],
}
PARLATO['1.3'] = {
 0: ["In questa lezione parliamo dello stop loss: dove si mette, e perché una volta messo non va più spostato nella direzione sbagliata."],
 1: ["Per prima cosa togliamo di mezzo un equivoco. Lo stop loss non è il punto in cui la perdita comincia a farti male. È il punto in cui la tua idea di trading si rivela sbagliata.",
     "E fa una cosa fondamentale: trasforma una perdita che non conosci in una perdita che conosci. È proprio lo stop che rende il rischio un numero preciso.",
     "Senza stop, il rischio per operazione semplicemente non esiste. Esiste solo la speranza che il prezzo torni indietro. E la speranza non è una strategia."],
 2: ["Quindi, dove si mette? Oltre un livello che, se viene superato, rende la tua idea non più valida. Per esempio sotto un minimo importante, sopra un massimo, o fuori da un range.",
     "Ma con un po' di margine. Il prezzo oscilla continuamente, e uno stop troppo vicino rischia di scattare per un movimento casuale, anche se poi il mercato va nella direzione giusta.",
     "E qui c'è la cosa più importante: lo stop non si sceglie in base a quanto vuoi rischiare. Prima si mette lo stop dove ha senso sul grafico, e solo dopo si adatta la dimensione dell'operazione. Ne parliamo nella prossima lezione."],
 3: ["Vediamolo insieme su un grafico. Qui il prezzo scende, poi rimbalza e forma un minimo.",
     "Ecco il minimo importante, a uno virgola zero nove otto zero. Se il prezzo scende sotto questo livello, la nostra idea di acquisto non ha più senso.",
     "Decidiamo di comprare dopo il rimbalzo, a uno virgola uno zero zero zero.",
     "E lo stop lo mettiamo un po' sotto il minimo, a uno virgola zero nove sette cinque, cioè venticinque pip sotto il nostro ingresso. Quei cinque pip in più servono a non farci fermare da un semplice movimento casuale. Nota bene: abbiamo deciso lo stop guardando il grafico, non il portafoglio."],
 4: ["In pratica, ci sono due modi di ragionare. Uno funziona, l'altro no.",
     "Il modo giusto: prima ti chiedi in quale punto la tua idea diventa sbagliata, e lì metti lo stop. Poi decidi quanto rischiare, per esempio l'uno per cento. E solo alla fine calcoli il lotto.",
     "Il modo sbagliato, purtroppo molto comune: scegli un lotto che ti piace, metti lo stop dove ti sembra comodo, e il rischio è quello che viene fuori. Cioè, non lo decidi tu.",
     "Quindi ricordati: lo stop comanda, il lotto si adatta."],
 5: ["E c'è una regola che ti proteggerà moltissimo: lo stop si può avvicinare, ma non si allontana mai.",
     "Quando il prezzo si avvicina al tuo stop, la tentazione di spostarlo solo un pochino è fortissima. Ma ogni volta che lo fai, hai aumentato il rischio senza averlo deciso a mente fredda.",
     "E se ti accorgi che non sei pronto ad accettare quella perdita, la soluzione non è spostare lo stop. È non entrare proprio."],
 6: ["Rivediamo l'esempio passo per passo, con i numeri. Vuoi comprare a uno virgola uno zero zero zero.",
     "L'ultimo minimo importante è a uno virgola zero nove otto zero: se il prezzo va sotto, l'idea non vale più.",
     "Aggiungi un margine di cinque pip, perché il prezzo può toccare un livello e poi ripartire senza romperlo davvero.",
     "Quindi lo stop va a uno virgola zero nove sette cinque.",
     "Che significa venticinque pip di distanza dal tuo ingresso.",
     "E ancora una volta, nota l'ordine: hai deciso lo stop guardando il grafico, non pensando a quanto avresti voluto rischiare."],
 7: ["Ora proviamo un esercizio. Supponi di voler rischiare sessanta euro, e il tuo stop, deciso dal grafico, è a trenta pip. Secondo te, quanto deve valere ogni pip perché, se va male, perdi esattamente sessanta euro?"],
 8: ["Vediamo. Sessanta euro diviso trenta pip fa due euro per pip. E siccome su molti conti un lotto intero vale circa dieci euro a pip, ti serve un quinto di lotto, cioè zero virgola due lotti. Nella prossima lezione trasformiamo proprio questo ragionamento in un calcolo semplice da usare ogni giorno."],
 9: ["Ricapitoliamo quello che abbiamo visto sullo stop loss.",
     "Lo stop è il punto in cui la tua idea si rivela sbagliata.",
     "Si sceglie guardando il grafico, e poi il lotto si adatta al rischio che vuoi correre.",
     "E si può avvicinare, ma non si allontana mai."],
 10: ["Ricordati: lo stop non è il costo del trading. È il biglietto d'ingresso per fare trading."],
}
PARLATO['1.4'] = {
 0: ["Benvenuto in questa lezione. Oggi rispondiamo a una domanda pratica: quanto devo comprare? Cioè, come si calcola il lotto giusto per ogni operazione."],
 1: ["Prima di fare i conti, ci servono tre parole. Te le spiego in modo semplice.",
     "Il pip è il più piccolo movimento di prezzo che si usa normalmente. Su euro dollaro, per esempio, è la quarta cifra dopo la virgola: se il prezzo passa da uno virgola uno zero zero zero a uno virgola uno zero zero uno, si è mosso di un pip.",
     "Il lotto è la dimensione della tua operazione. Un lotto standard corrisponde a centomila unità della valuta che compri.",
     "E il valore del pip ti dice quanto guadagni o perdi per ogni pip di movimento. Su euro dollaro, con un lotto intero e un conto in dollari, ogni pip vale circa dieci dollari."],
 2: ["Adesso mettiamo insieme i pezzi. Esiste un calcolo che lega rischio, stop e lotto.",
     "In parole semplici: prendi quanto vuoi rischiare in euro, e lo dividi per la distanza dello stop in pip moltiplicata per il valore di un pip. Il risultato è il numero di lotti.",
     "Il rischio in euro l'abbiamo deciso nella lezione sul rischio per trade: per esempio l'uno per cento del conto.",
     "La distanza dello stop l'abbiamo decisa guardando il grafico, nella lezione precedente.",
     "E il valore del pip dipende dallo strumento che usi. Te lo mostra la tua piattaforma, o il tuo broker."],
 3: ["Facciamo i conti insieme. Hai un conto da diecimila euro e rischi l'uno per cento: quindi puoi perdere al massimo cento euro.",
     "Il tuo stop è a venticinque pip, e ogni pip vale dieci euro per lotto.",
     "Allora: venticinque pip per dieci euro fa duecentocinquanta euro per lotto. Ma tu vuoi rischiarne solo cento. Cento diviso duecentocinquanta fa zero virgola quattro lotti.",
     "Con quattro decimi di lotto, se il prezzo arriva allo stop perdi esattamente cento euro. Né più, né meno. Ecco il bello di fare i conti prima."],
 4: ["Questi conti li puoi fare anche con un calcolatore. Questo che vedi è uno strumento gratuito che trovi sul sito riskly punto trade, e ti dico chiaramente che è un mio prodotto. Ma ottieni lo stesso risultato con la formula, o con un semplice foglio di calcolo.",
     "Inserisci il saldo, diecimila euro, e il rischio, l'uno per cento: sono cento euro da rischiare.",
     "Poi la distanza dello stop, venticinque pip, e il valore del pip, dieci euro per lotto.",
     "E il risultato è proprio zero virgola quaranta lotti, con cento euro di rischio. Esattamente il numero che abbiamo calcolato a mano."],
 5: ["E se lo stop fosse più largo? Vediamo cosa succede.",
     "Con lo stop a venticinque pip, come abbiamo visto, ti servono zero virgola quaranta lotti.",
     "Con lo stop a cinquanta pip, cioè il doppio della distanza, i lotti si dimezzano: zero virgola venti.",
     "E la cosa interessante è che il rischio in euro resta identico: cento euro in entrambi i casi. Cambia la dimensione dell'operazione, non quanto puoi perdere. Ecco perché lo stop comanda e il lotto si adatta."],
 6: ["Prima di cliccare, ti consiglio sempre tre piccoli controlli.",
     "Primo: il lotto si arrotonda sempre per difetto, mai per eccesso. Meglio rischiare qualche euro in meno che qualche euro in più.",
     "Secondo: il valore del pip deve essere quello del tuo strumento e della valuta del tuo conto. Su un conto in euro, per esempio, non è esattamente dieci.",
     "Terzo: ricordati che spread e commissioni non sono dentro lo stop. Il rischio reale è sempre un pochino più alto di quello che hai calcolato."],
 7: ["Facciamo un secondo esempio, con un conto più grande ma un rischio più prudente.",
     "Hai ventimila euro e rischi lo zero virgola cinque per cento: sono sempre cento euro.",
     "Questa volta lo stop è a quaranta pip.",
     "Quaranta pip per dieci euro fa quattrocento euro per lotto. Cento diviso quattrocento fa zero virgola venticinque lotti."],
 8: ["Adesso prova tu. Hai un conto da cinquemila euro, rischi il due per cento, il tuo stop è a venti pip e ogni pip vale dieci euro per lotto. Quanti lotti devi aprire? Metti in pausa e fai il calcolo."],
 9: ["Vediamo insieme. Il due per cento di cinquemila euro sono cento euro. Venti pip per dieci euro fa duecento euro per lotto. Cento diviso duecento fa zero virgola cinque: ti serve mezzo lotto."],
 10: ["Ricapitoliamo quello che abbiamo imparato.",
     "Il lotto si calcola dividendo il rischio in euro per la distanza dello stop moltiplicata per il valore del pip.",
     "Se lo stop è più largo, il lotto diventa più piccolo, ma il rischio in euro resta lo stesso.",
     "E arrotonda sempre per difetto, controllando il valore del pip sul tuo conto."],
 11: ["Ricorda: il lotto non si sceglie a sensazione. Si calcola."],
}
PARLATO['1.5'] = {
 0: ["In questa lezione parliamo del rapporto tra rischio e rendimento: cioè, per ogni euro che rischi, quanto punti a guadagnare."],
 1: ["Questo rapporto si chiama, in breve, R R, e ti dice quanto vuoi guadagnare rispetto a quanto sei disposto a perdere.",
     "Si calcola in modo semplice: prendi la distanza tra il tuo ingresso e il take profit, e la dividi per la distanza tra il tuo ingresso e lo stop loss.",
     "Per esempio, se rischi venticinque pip per puntare a guadagnarne quarantacinque, il tuo rapporto è uno virgola otto: punti a guadagnare quasi il doppio di quello che rischi."],
 2: ["Facciamo un esempio con i prezzi. Entri a uno virgola uno zero zero zero.",
     "Il tuo stop è venticinque pip sotto.",
     "Il tuo take profit è quarantacinque pip sopra.",
     "Quarantacinque diviso venticinque fa uno virgola otto. In pratica: rischi uno, per guadagnare uno virgola otto."],
 3: ["Vediamolo sul grafico, così è più chiaro.",
     "Ecco il punto in cui entri, a uno virgola uno zero zero zero.",
     "Qui sotto c'è lo stop, a venticinque pip: la zona rossa è quello che puoi perdere.",
     "E qui sopra c'è il target, a quarantacinque pip: la zona verde è quello che puoi guadagnare. Il rapporto rischio rendimento è semplicemente la zona verde divisa per quella rossa.",
     "Se il prezzo arriva al target, come in questo caso, guadagni quarantacinque pip, quasi il doppio di quello che rischiavi. Se invece fosse sceso fino allo stop, avresti perso venticinque pip."],
 4: ["Attenzione però: un rapporto alto, da solo, non basta.",
     "Più metti lontano il take profit, più è difficile che il prezzo ci arrivi. Quindi la percentuale di operazioni vincenti tende a scendere.",
     "Al contrario, se il rapporto è basso, devi vincere quasi sempre. Per esempio, se rischi venti per guadagnarne dieci, devi vincere due volte su tre solo per andare in pari.",
     "Quello che conta davvero è la combinazione tra il rapporto rischio rendimento e quante volte vinci. Ed è proprio l'argomento della prossima lezione."],
 5: ["Ti mostro perché questo rapporto è così potente. Prendiamo cinque operazioni, tutte con stop a venticinque pip e target a quarantacinque.",
     "La prima arriva al target: più quarantacinque pip.",
     "La seconda va allo stop: meno venticinque.",
     "Anche la terza va allo stop: altri meno venticinque.",
     "La quarta arriva al target: più quarantacinque.",
     "La quinta va allo stop: meno venticinque. Hai vinto solo due operazioni su cinque, il quaranta per cento.",
     "Eppure, se fai i conti, hai guadagnato novanta pip e ne hai persi settantacinque. Sei in positivo di quindici pip, pur avendo perso più volte di quante hai vinto. Ecco il potere di un buon rapporto rischio rendimento."],
 6: ["Vediamo la stessa idea su dieci operazioni, sempre con lo stop a venticinque pip, cambiando il target.",
     "Se il target è a settantacinque pip, cioè tre volte lo stop, ti bastano tre vittorie su dieci: guadagni duecentoventicinque pip, ne perdi centosettantacinque, e chiudi a più cinquanta.",
     "Se il target è a cinquanta pip, il doppio dello stop, ti servono quattro vittorie su dieci: duecento pip guadagnati, centocinquanta persi, ancora più cinquanta.",
     "Se invece target e stop sono uguali, con cinque vittorie su dieci sei esattamente in pari. E questo prima di contare spread e commissioni."],
 7: ["Prova tu. Il tuo stop è a venticinque pip e il target a cinquanta. Su dieci operazioni ne vinci quattro e ne perdi sei. Quanti pip hai fatto in totale?"],
 8: ["Vediamo. Quattro vittorie da cinquanta pip fanno duecento pip. Sei perdite da venticinque fanno centocinquanta pip. Duecento meno centocinquanta: sei in positivo di cinquanta pip, pur avendo perso sei volte su dieci."],
 9: ["Ricapitoliamo.",
     "Il rapporto rischio rendimento è quanto punti a guadagnare diviso quanto rischi.",
     "Un rapporto alto, da solo, non basta: va sempre guardato insieme a quante volte vinci.",
     "E si può guadagnare anche vincendo meno della metà delle volte, se quando vinci guadagni di più di quanto perdi quando sbagli."],
 10: ["Il messaggio di oggi è questo: non devi avere ragione spesso. Devi guadagnare di più quando hai ragione."],
}
PARLATO['1.6'] = {
 0: ["In questa lezione rispondiamo a una domanda che si fanno tutti: quante volte devo vincere per guadagnare?"],
 1: ["Partiamo dalla definizione. Il win rate è la percentuale di operazioni che chiudi in guadagno. Se su cento operazioni ne vinci quarantacinque, il tuo win rate è il quarantacinque per cento.",
     "Ma attenzione: il win rate da solo non ti dice se stai guadagnando. Puoi vincere sette volte su dieci e perdere soldi, oppure vincere solo tre volte su dieci e guadagnare.",
     "Va sempre letto insieme al rapporto rischio rendimento che abbiamo visto nella lezione precedente. È la coppia che conta."],
 2: ["E qui arriva un concetto molto utile: il win rate di pareggio. È la percentuale minima di vittorie che ti serve per non perdere soldi.",
     "Si calcola così: uno diviso uno più il tuo rapporto rischio rendimento.",
     "Detto in parole semplici: se vinci più spesso di questa soglia, il tuo sistema guadagna. Se vinci meno spesso, perde."],
 3: ["Vediamo i valori più importanti, così ti fai un'idea.",
     "Se rischi venti per guadagnarne dieci, cioè un rapporto di zero virgola cinque, devi vincere due volte su tre solo per andare in pari.",
     "Se rischi e punti la stessa cifra, devi vincere metà delle volte.",
     "Se punti una volta e mezza quello che rischi, ti basta vincere il quaranta per cento delle volte.",
     "Se punti il doppio, basta vincere una volta su tre.",
     "E se punti il triplo, basta vincere una volta su quattro."],
 4: ["Ecco lo stesso concetto in un grafico. La linea è il pareggio: sopra la linea, cioè vincendo più spesso, guadagni. Sotto la linea perdi.",
     "Vedi che più alzi il rapporto rischio rendimento, più la soglia scende? Ma ricordati quello che abbiamo detto: target più lontani di solito si raggiungono meno spesso. Quindi devi sempre controllare i tuoi numeri reali."],
 5: ["Mettiamo insieme le due cose con un esempio concreto.",
     "Supponi di aver misurato le tue operazioni e di vincere quarantacinque volte su cento.",
     "Il tuo rapporto rischio rendimento medio è uno virgola otto. Quindi la soglia di pareggio è uno diviso due virgola otto, circa il trentasei per cento.",
     "Tu vinci il quarantacinque per cento, la soglia è il trentasei: hai nove punti di margine. Un buon segno.",
     "Il sistema ha un vantaggio. Nel prossimo modulo vedremo come trasformare tutto questo in un solo numero, che ti dice quanto vale in media ogni operazione."],
 6: ["Prova tu. Il tuo sistema punta a guadagnare tre volte quello che rischia, e vinci il ventotto per cento delle volte. Sei sopra o sotto la soglia di pareggio?"],
 7: ["Vediamo. Uno diviso uno più tre fa un quarto, cioè il venticinque per cento. Tu vinci il ventotto, quindi sei sopra di tre punti. Bene, ma è un margine sottile: con poche operazioni potrebbe essere solo fortuna. Ne parliamo meglio nel prossimo modulo."],
 8: ["Ricapitoliamo.",
     "Il win rate è la percentuale di operazioni che vinci.",
     "La soglia di pareggio è uno diviso uno più il rapporto rischio rendimento.",
     "Vincere il trentacinque per cento può bastare, se quando vinci guadagni tanto. E vincere il settanta per cento può non bastare, se quando vinci guadagni poco."],
 9: ["Ricordati: il win rate da solo è solo un numero che fa piacere. La coppia tra win rate e rapporto rischio rendimento, invece, ti dice la verità."],
}
PARLATO['1.7'] = {
 0: ["Benvenuto all'ultima lezione del primo modulo. Oggi ti presento uno strumento che usano tutti i trader seri per confrontare le loro operazioni: l'unità R."],
 1: ["Partiamo da un problema. Come fai a confrontare due operazioni? Mettiamo che una abbia fatto cinquanta pip con un lotto grande, e l'altra venti pip con un lotto piccolo. Quale è andata meglio?",
     "Gli euro non bastano, perché dipendono da quanto era grande il conto e da quanti lotti avevi aperto quel giorno.",
     "E nemmeno i pip bastano, perché cinquanta pip sull'oro e cinquanta pip su euro dollaro non hanno lo stesso peso."],
 2: ["La soluzione è misurare tutto in R.",
     "Un R è semplicemente quanto rischiavi su quell'operazione. Se avevi messo lo stop in modo da perdere cento euro, un R vale cento euro.",
     "A questo punto ogni risultato diventa un multiplo di R. Se guadagni duecento euro su un rischio di cento, hai fatto più due R: hai guadagnato il doppio di quello che rischiavi.",
     "E se prendi lo stop, il risultato è sempre meno un R, qualunque sia lo strumento e qualunque sia la dimensione. Negli esempi di prezzo continueremo a ragionare in pip, che sono più intuitivi. L'R lo useremo soprattutto per le statistiche, quando dobbiamo confrontare operazioni con stop diversi."],
 3: ["Guarda queste quattro operazioni, fatte su strumenti diversi e con un rischio di cento euro ciascuna.",
     "Sull'oro hai guadagnato centottanta euro. Siccome rischiavi cento, sono più uno virgola otto R.",
     "Su euro dollaro hai preso lo stop: meno cento euro, cioè meno un R.",
     "Su un indice hai guadagnato centocinquanta euro: più uno virgola cinque R.",
     "E su sterlina dollaro di nuovo stop: meno un R. Strumenti diversi, lotti diversi, pip diversi. Ma in R diventano tutti confrontabili."],
 4: ["Proviamo a sommare una serie di operazioni in R.",
     "La prima chiude a più uno virgola otto R.",
     "La seconda va allo stop, meno un R.",
     "La terza chiude a più uno virgola cinque R.",
     "La quarta va allo stop, meno un R.",
     "E anche la quinta va allo stop, meno un R.",
     "In totale fai più zero virgola tre R. Se il tuo R vale cento euro, hai guadagnato trenta euro. E la cosa bella è che questo calcolo funziona allo stesso modo con qualsiasi conto, grande o piccolo."],
 5: ["Ma perché funziona così bene? Prima di tutto ti obbliga a decidere il rischio prima di entrare, perché senza uno stop l'R non esiste.",
     "Poi ti permette di confrontare sistemi, strumenti e periodi diversi, senza farti ingannare dalla dimensione del conto.",
     "E infine ti prepara al prossimo modulo, perché tutte le statistiche che misurano un sistema si calcolano proprio in R."],
 6: ["Prova tu. Hai fatto sei operazioni: più due R, meno uno, meno uno, più mezzo, meno uno, e più tre. Quanto hai fatto in totale? E quanto in euro, se un R vale ottanta euro?"],
 7: ["Facciamolo insieme. Più due, meno uno, meno uno, fa zero. Più mezzo fa mezzo. Meno uno fa meno mezzo. Più tre fa più due e mezzo. Quindi due virgola cinque R, che a ottanta euro per R sono duecento euro."],
 8: ["Ricapitoliamo questa lezione.",
     "Un R è quanto rischiavi su quell'operazione.",
     "Ogni risultato si esprime come multiplo di R, e uno stop preso vale sempre meno un R.",
     "E in R puoi confrontare strumenti, dimensioni e periodi diversi. Con questo abbiamo chiuso il primo modulo: nel prossimo impariamo a capire se un sistema funziona davvero."],
 9: ["Ricorda: se non sai quanto rischiavi, non puoi sapere davvero quanto hai guadagnato."],
}
