PARLATO = {}
PARLATO['4.1'] = {
 0: ["Benvenuto nel quarto modulo, dedicato a come dimensionare le posizioni. Partiamo dal metodo più semplice e più usato: il rischio fisso in percentuale."],
 1: ["Esistono tre modi principali per decidere quanto grande fare un'operazione. Vediamoli uno per uno.",
     "Il primo è il lotto fisso: apri sempre la stessa dimensione, per esempio zero virgola quattro lotti, qualunque sia lo stop e qualunque sia il conto.",
     "Il secondo è l'importo fisso: rischi sempre la stessa cifra, per esempio cento euro, anche se il conto nel frattempo è sceso.",
     "Il terzo è la percentuale fissa: rischi sempre la stessa percentuale del conto che hai in quel momento, per esempio l'uno per cento, e il lotto si calcola di conseguenza."],
 2: ["Per capire la differenza, guardiamo cosa succede quando il conto scende del venti per cento, da diecimila a ottomila euro.",
     "Con il lotto fisso, continui a rischiare cento euro. Ma cento euro su ottomila non sono più l'uno per cento: sono l'uno virgola venticinque. Stai rischiando di più proprio quando sei in difficoltà.",
     "Con l'importo fisso succede la stessa cosa: cento euro su un conto più piccolo pesano di più.",
     "Con la percentuale fissa, invece, il rischio resta l'uno per cento: ottanta euro su ottomila. Le tue posizioni si rimpiccioliscono da sole mentre il conto scende, e questo ti protegge."],
 3: ["Vediamo come si traduce in lotti, dopo quella discesa del venti per cento.",
     "Il conto adesso vale ottomila euro.",
     "L'uno per cento di ottomila sono ottanta euro: questo è quanto puoi rischiare.",
     "Il tuo stop è sempre a venticinque pip, con dieci euro a pip per lotto.",
     "Venticinque pip per dieci euro fa duecentocinquanta euro per lotto. Ottanta diviso duecentocinquanta fa zero virgola trentadue lotti. Prima, con diecimila euro, erano zero virgola quaranta: la posizione si è ridotta da sola del venti per cento, esattamente come il conto."],
 4: ["Questo metodo ha vantaggi e limiti, ed è giusto conoscerli.",
     "I vantaggi: ti protegge dopo le perdite, è semplice da calcolare e funziona con qualsiasi strumento.",
     "I limiti: dopo una serie di perdite il recupero è un po' più lento, perché le posizioni sono più piccole. Devi rifare il calcolo a ogni operazione. E non tiene conto di quanto si muove il mercato, ma a questo pensiamo nella prossima lezione."],
 5: ["Prova tu. Hai un conto da quattordicimila euro, rischi l'uno e mezzo per cento, il tuo stop è a trenta pip e ogni pip vale dieci euro per lotto. Quanti lotti apri?"],
 6: ["Vediamo. L'uno e mezzo per cento di quattordicimila euro sono duecentodieci euro. Trenta pip per dieci euro fa trecento euro per lotto. Duecentodieci diviso trecento fa zero virgola settanta lotti."],
 7: ["Ricapitoliamo.",
     "Con la percentuale fissa, le posizioni si riducono da sole quando perdi.",
     "Il lotto si calcola partendo dal conto attuale per la percentuale, diviso lo stop per il valore del pip.",
     "È una base solida, che nella prossima lezione adattiamo a quanto si muove il mercato."],
 8: ["Ricordati: il tuo lotto deve seguire il conto, non l'umore della giornata."],
}
PARLATO['4.2'] = {
 0: ["In questa lezione parliamo di come adattare lo stop a quanto si sta muovendo il mercato, usando un indicatore molto semplice: l'ATR."],
 1: ["Ti faccio una domanda: uno stop di venti pip è tanto o poco? La risposta è: dipende. Dipende da quanto si sta muovendo il mercato in quel momento.",
     "Se il mercato è molto agitato, venti pip possono essere troppo pochi: lo stop scatta per un normale movimento, e vieni fermato anche se la tua idea era giusta.",
     "Se invece il mercato è molto tranquillo, venti pip possono essere troppi: rischi più del necessario per quella operazione."],
 2: ["Per misurare quanto si muove il mercato si usa l'ATR, che sta per Average True Range. In pratica ti dice quanto si muove in media una candela.",
     "Di solito si calcola sulle ultime quattordici candele del grafico che stai guardando.",
     "E non devi calcolarlo a mano: è un indicatore che trovi già pronto su qualsiasi piattaforma, MetaTrader compresa."],
 3: ["L'idea è semplice: invece di usare sempre lo stesso stop, metti lo stop a un multiplo dell'ATR.",
     "Il multiplo di solito è tra uno e mezzo e due. Quale usare lo decidi provando sul tuo sistema.",
     "Per esempio, se l'ATR è venti pip e usi un multiplo di due, il tuo stop sarà a quaranta pip.",
     "E poi il lotto lo calcoli esattamente come abbiamo già imparato: rischio diviso stop per valore del pip."],
 4: ["Vediamo cosa succede in tre situazioni diverse, rischiando sempre cento euro.",
     "Mercato tranquillo, ATR di dieci pip: lo stop va a venti pip e apri mezzo lotto.",
     "Mercato normale, ATR di venti pip: lo stop va a quaranta pip e apri un quarto di lotto.",
     "Mercato agitato, ATR di quaranta pip: lo stop va a ottanta pip e apri circa un ottavo di lotto.",
     "Il bello è che il rischio in euro è sempre lo stesso, cento euro. Quando il mercato si agita, la tua posizione diventa più piccola da sola."],
 5: ["Ci sono tre cose a cui fare attenzione. La prima: se lo stop si allarga, per mantenere lo stesso rapporto rischio rendimento anche il target deve allontanarsi.",
     "La seconda: non vale per tutte le strategie. Se la tua idea ha un livello preciso sul grafico che la rende sbagliata, conta quello, non l'ATR.",
     "La terza: prova il multiplo sui tuoi dati. Uno e mezzo e due possono dare risultati molto diversi a seconda del sistema."],
 6: ["Prova tu. Vuoi rischiare centoventi euro. L'ATR è trenta pip, usi un multiplo di due, e ogni pip vale dieci euro per lotto. Quanti lotti apri?"],
 7: ["Vediamo. Lo stop è due volte trenta, cioè sessanta pip. Sessanta pip per dieci euro fa seicento euro per lotto. Centoventi diviso seicento fa zero virgola venti lotti."],
 8: ["Ricapitoliamo.",
     "L'ATR ti dice quanto si sta muovendo il mercato.",
     "Lo stop si può mettere a un multiplo dell'ATR, di solito tra uno e mezzo e due.",
     "E quando il mercato si agita, la posizione si rimpicciolisce, mentre il rischio in euro resta lo stesso."],
 9: ["Ricordati: è il mercato a decidere quanto spazio serve allo stop. Sei tu a decidere quanto rischiare."],
}
PARLATO['4.3'] = {
 0: ["In questa lezione ti presento una formula famosa, il criterio di Kelly. Ti spiego cosa dice, e soprattutto perché nessuno serio la usa così com'è."],
 1: ["L'idea di Kelly è affascinante: esiste un livello di rischio che fa crescere il conto il più velocemente possibile nel lungo periodo.",
     "E una formula ti dice qual è, partendo da quante volte vinci e da quanto guadagni rispetto a quanto perdi.",
     "Ma la parte più sorprendente è un'altra: se rischi più di quel livello, il conto cresce di meno. E se esageri, il conto comincia a scendere, anche con un sistema vincente. Rischiare troppo non è solo pericoloso: ti fa proprio perdere."],
 2: ["La formula, detta a parole, è questa: prendi la percentuale di volte che vinci, e togli la percentuale di volte che perdi divisa per il tuo rapporto tra guadagno e perdita.",
     "Il risultato è la frazione del conto da rischiare su ogni operazione.",
     "W è la percentuale di operazioni che vinci.",
     "E R è quanto guadagni in media rispetto a quanto perdi in media."],
 3: ["Facciamo il calcolo con il nostro sistema. Vince il quarantacinque per cento delle volte.",
     "E quando vince guadagna uno virgola otto volte quello che perde.",
     "La percentuale di volte che perdi è il cinquantacinque per cento. Diviso uno virgola otto, fa circa zero virgola trentuno.",
     "Quarantacinque meno trentuno fa circa quattordici.",
     "Quindi Kelly ti direbbe di rischiare il quattordici per cento del conto su ogni operazione. Ti sembra tantissimo? Lo è. Ed è proprio qui che arriva la parte importante."],
 4: ["Guarda questo grafico. Ti mostra quanto cresce il conto rischiando più o meno di quello che dice Kelly.",
     "Rischiando esattamente quello che dice Kelly, la crescita è massima, ma i cali del conto sono enormi. Rischiando la metà, ottieni circa tre quarti della crescita. Rischiando un quarto, ottieni quasi la metà della crescita, con molto meno stress.",
     "E guarda la parte destra: se rischi il doppio di quello che dice Kelly, la crescita scende quasi a zero. Hai raddoppiato il rischio e hai buttato via tutto il vantaggio."],
 5: ["Per questo, nella pratica, si usa solo una frazione di Kelly.",
     "Il primo motivo è che i tuoi numeri sono stime. Se pensi di vincere il quarantacinque per cento ma in realtà vinci il quaranta, il Kelly pieno è già troppo.",
     "Il secondo motivo è che con il Kelly pieno i cali del conto sono molto profondi, e quasi nessuno riesce a sopportarli.",
     "E con un quarto o metà del Kelly riduci tantissimo il rischio, perdendo solo una parte della crescita. Nel nostro esempio, un quarto di Kelly è circa il tre e mezzo per cento: comunque alto per la maggior parte delle persone."],
 6: ["Prova tu. Il tuo sistema vince il quaranta per cento delle volte, e quando vince guadagna il doppio di quello che perde. Quanto dice Kelly? E quanto è un quarto di Kelly?"],
 7: ["Vediamo. Perdi il sessanta per cento delle volte. Sessanta diviso due fa trenta. Quaranta meno trenta fa dieci: Kelly dice il dieci per cento. Un quarto di Kelly è il due virgola cinque per cento."],
 8: ["Ricapitoliamo.",
     "Kelly ti dice quale rischio farebbe crescere il conto più velocemente.",
     "Ma se rischi più di Kelly la crescita cala, fino ad azzerarsi.",
     "Per questo nella pratica si usa un quarto o metà Kelly, partendo da stime prudenti."],
 9: ["Ricordati: Kelly è un tetto da non superare, non un obiettivo da raggiungere."],
}
PARLATO['4.4'] = {
 0: ["In questa lezione rispondiamo a una domanda molto pratica: quando è giusto aumentare il rischio, e quando è meglio ridurlo?"],
 1: ["Prima di tutto, parliamo della tentazione. Quella che viene a tutti.",
     "Dopo qualche vittoria pensi: sono in forma, adesso rischio di più. Ma è solo fiducia eccessiva che si traveste da strategia.",
     "Dopo qualche perdita pensi: devo recuperare, adesso rischio di più. Ed è il modo più veloce per trasformare un brutto periodo in un disastro.",
     "In entrambi i casi stai decidendo con le emozioni. E le emozioni non conoscono le statistiche del tuo sistema."],
 2: ["Il caso più estremo ha un nome: la martingala. Consiste nel raddoppiare il rischio dopo ogni perdita, sperando che una sola vittoria ti faccia recuperare tutto. Vediamo cosa succede con sei perdite di fila, partendo dall'uno per cento.",
     "Prima perdita, rischiavi l'uno per cento: ti resta il novantanove per cento del conto.",
     "Seconda perdita, rischiavi il due: ti resta il novantasette.",
     "Terza perdita, rischiavi il quattro: ti resta circa il novantatré.",
     "Quarta perdita, rischiavi l'otto: ti resta circa l'ottantasei.",
     "Quinta perdita, rischiavi il sedici: ti resta il settantadue.",
     "Sesta perdita, rischiavi il trentadue: ti resta meno della metà del conto.",
     "Sei perdite di fila, che come abbiamo visto capitano davvero, e hai perso più della metà del conto. Ecco perché la martingala è una trappola."],
 3: ["Ci sono però regole sane per cambiare il rischio.",
     "La prima: ridurre il rischio dopo un calo del conto. Per esempio, dimezzarlo se il conto scende di più del dieci per cento.",
     "La seconda: tornare al rischio normale solo dopo aver recuperato, non dopo una sola operazione vincente.",
     "La terza: aumentare il rischio solo poco alla volta, quando il conto fa nuovi massimi, dopo tante operazioni e seguendo regole scritte prima."],
 4: ["Ecco un esempio di regola scritta, così vedi come potrebbe essere.",
     "In condizioni normali rischi l'uno per cento.",
     "Se il conto scende di più del dieci per cento dal massimo, scendi a mezzo punto per cento.",
     "Se scende di più del quindici per cento, scendi a un quarto di punto, oppure ti fermi del tutto a rivedere il sistema.",
     "E solo quando il conto fa un nuovo massimo, dopo almeno cinquanta operazioni, puoi valutare di aumentare di un quarto di punto. Questi numeri sono un esempio: i tuoi li decidi a mente fredda, e li scrivi."],
 5: ["Prova tu. Parti rischiando il due per cento e raddoppi dopo ogni perdita: due, quattro, otto, sedici per cento. Quanto ti rimane del conto dopo quattro perdite di fila?"],
 6: ["Vediamo. Dopo la prima perdita ti resta il novantotto per cento, poi il novantasei di quello, poi il novantadue, poi l'ottantaquattro. Moltiplicando tutto, ti resta circa il settantatré per cento del conto. Hai perso più di un quarto del conto in sole quattro operazioni."],
 7: ["Ricapitoliamo.",
     "Cambiare il rischio in base all'umore è il modo più veloce per rovinare un conto.",
     "Si riduce dopo un calo, e si aumenta solo con regole scritte prima.",
     "E non si raddoppia mai dopo una perdita."],
 8: ["Ricordati: se cambi il rischio in base a come ti senti, il tuo piano è già finito."],
}
PARLATO['4.5'] = {
 0: ["Ultima lezione del quarto modulo. Oggi parliamo di cosa succede quando hai più operazioni aperte insieme. Perché a volte tre operazioni, in realtà, sono una sola."],
 1: ["Ogni operazione ha il suo rischio, ma conta anche il rischio totale di tutte quelle aperte insieme.",
     "Il rischio aperto è la somma dei rischi di tutte le posizioni. Se hai tre operazioni aperte, ognuna all'uno per cento, stai rischiando il tre per cento del conto in quel momento.",
     "Di solito si fissa un limite, per esempio tra il due e il quattro per cento in totale, e lo si decide prima.",
     "E conta solo quello che puoi ancora perdere. Un'operazione con lo stop già spostato a pareggio non aggiunge rischio."],
 2: ["Ma c'è un problema più sottile: la correlazione.",
     "Alcuni strumenti si muovono insieme. Per esempio, euro dollaro, sterlina dollaro e dollaro australiano spesso reagiscono allo stesso modo alle notizie sul dollaro.",
     "Quindi se compri tutti e tre, non hai fatto tre scommesse diverse. Hai fatto una sola scommessa: che il dollaro si indebolisca.",
     "E se quella idea è sbagliata, sbagliano tutte e tre insieme, e prendi tre stop nello stesso momento."],
 3: ["Guarda la differenza tra queste due situazioni, sempre con tre operazioni da uno per cento ciascuna.",
     "Nella prima hai comprato euro dollaro, comprato oro e venduto un indice. Sono tre mercati diversi: il rischio totale è il tre per cento, ma distribuito su tre idee diverse.",
     "Nella seconda hai comprato euro dollaro, sterlina dollaro e dollaro australiano. È sempre il tre per cento, ma tutto sulla stessa idea: dollaro debole.",
     "Nel caso peggiore, la seconda situazione si comporta come una sola operazione con il tre per cento di rischio. Sulla carta il rischio è lo stesso, nella realtà no."],
 4: ["Quindi, tre regole pratiche.",
     "Fissa un limite al rischio totale delle posizioni aperte, per esempio il tre per cento.",
     "Considera le operazioni correlate come se fossero una sola, e dividi tra loro un unico rischio.",
     "E controlla sempre la valuta in comune. Tre acquisti contro il dollaro sono, di fatto, una sola operazione."],
 5: ["Prova tu. Hai quattro operazioni aperte, ognuna con lo zero virgola settantacinque per cento di rischio. Tre di queste sono tutte contro il dollaro. Qual è il rischio totale, e quanto è concentrato sulla stessa idea?"],
 6: ["Vediamo. Quattro per zero virgola settantacinque fa il tre per cento di rischio totale. Ma tre operazioni sono sulla stessa idea, cioè il due virgola venticinque per cento su un'unica scommessa. Se il tuo limite per singola idea è il due per cento, devi ridurre qualcosa."],
 7: ["Ricapitoliamo questo modulo.",
     "Il rischio aperto è la somma del rischio di tutte le posizioni.",
     "Strumenti che si muovono insieme valgono come una sola operazione.",
     "Per questo serve un limite totale, e un limite per ogni singola idea. Nel prossimo modulo impariamo a simulare il futuro del nostro conto."],
 8: ["Ricordati: tre operazioni sulla stessa idea sono una sola operazione, con il triplo del rischio."],
}
