PARLATO = {}
PARLATO['3.1'] = {
 0: ["Benvenuto nel terzo modulo. Qui parliamo di quello che succede al conto quando le cose vanno male, e partiamo da una parola che sentirai spessissimo: drawdown."],
 1: ["Il drawdown è quanto è sceso il tuo conto rispetto al punto più alto che aveva raggiunto. Attenzione: non rispetto a quanto avevi all'inizio, ma rispetto al massimo.",
     "Si esprime in percentuale. In pratica: di quanto sei sceso dal tuo punto più alto, diviso il punto più alto.",
     "E il drawdown massimo è semplicemente la discesa peggiore che il tuo conto abbia mai avuto."],
 2: ["Facciamo un esempio con i numeri. Parti con un conto da diecimila euro.",
     "Le cose vanno bene e il conto sale fino a dodicimila euro. Questo è il tuo massimo.",
     "Poi arriva un periodo difficile e il conto scende fino a novemilaseicento euro.",
     "Quanto sei sceso dal massimo? Da dodicimila a novemilaseicento sono duemilaquattrocento euro. Diviso dodicimila, fa il venti per cento.",
     "Quindi il tuo drawdown è del venti per cento. E nota una cosa curiosa: rispetto a quando hai iniziato hai perso solo il quattro per cento. Ma rispetto al tuo momento migliore sei sotto del venti, ed è quello che senti davvero."],
 3: ["Vediamolo su un grafico, che rende tutto più chiaro. Questa è la curva del tuo conto, che sale e scende nel tempo.",
     "Qui il conto arriva a dodicimila euro: è il punto più alto.",
     "E qui scende fino a novemilaseicento: è il punto più basso dopo il massimo.",
     "La distanza tra questi due punti, in percentuale, è il drawdown: meno venti per cento. Ricorda: si misura sempre partendo dal picco, non dal punto di partenza."],
 4: ["Ma perché è così importante guardarlo?",
     "Perché è la misura del dolore. Ti dice quanto stai soffrendo rispetto al momento migliore che hai avuto.",
     "Perché è proprio il numero che controllano le prop firm, con limiti molto rigidi. Lo vedremo bene nel modulo sette.",
     "E soprattutto perché decide se riesci a seguire il tuo piano. Se il drawdown supera quello che riesci a sopportare, finirai per cambiare le regole proprio nel momento peggiore."],
 5: ["Ci sono tre modi di guardare il drawdown. Il primo è il drawdown attuale: quanto sei sotto il massimo adesso.",
     "Il secondo è il drawdown massimo: la discesa peggiore di tutta la storia del conto.",
     "E il terzo è la durata: quanto tempo ci metti a tornare al massimo. Spesso è proprio la durata, più che la profondità, a far perdere la pazienza e la disciplina. Tre mesi passati sotto il massimo sono pesanti, anche se il calo è piccolo."],
 6: ["Prova tu. Il punto più alto del tuo conto è stato quindicimila euro. Adesso il conto vale dodicimilasettecentocinquanta euro. Qual è il tuo drawdown?"],
 7: ["Vediamo. Da quindicimila a dodicimilasettecentocinquanta sei sceso di duemiladuecentocinquanta euro. Duemiladuecentocinquanta diviso quindicimila fa il quindici per cento. Il tuo drawdown attuale è del quindici per cento."],
 8: ["Ricapitoliamo.",
     "Il drawdown è quanto sei sceso, in percentuale, dal tuo punto più alto.",
     "Va tenuto d'occhio in tre modi: quello attuale, quello massimo, e quanto dura.",
     "E decide se riesci a seguire il piano, e se rispetti i limiti delle prop firm."],
 9: ["Ricordati: il drawdown non si può evitare. Si può solo dimensionare, decidendo quanto rischiare."],
}
PARLATO['3.2'] = {
 0: ["In questa lezione ti mostro una cosa che sorprende quasi tutti: perché recuperare una perdita costa sempre più fatica della perdita stessa."],
 1: ["Partiamo da una domanda. Hai diecimila euro, perdi il cinquanta per cento, e poi guadagni il cinquanta per cento. Sei tornato a diecimila euro? Vediamolo insieme sul grafico.",
     "Il conto parte da diecimila euro.",
     "Perdi il cinquanta per cento, e ti rimangono cinquemila euro.",
     "Ora guadagni il cinquanta per cento. Ma attenzione: è il cinquanta per cento di cinquemila, cioè duemilacinquecento euro. Arrivi a settemilacinquecento, non a diecimila.",
     "Per tornare a diecimila partendo da cinquemila devi raddoppiare il conto, cioè guadagnare il cento per cento. Il motivo è semplice: dopo una perdita, i guadagni si calcolano su una cifra più piccola."],
 2: ["Esiste un modo semplice per sapere quanto devi guadagnare per recuperare. Dividi uno per quello che ti è rimasto, e togli uno.",
     "Per esempio, se hai perso il trenta per cento, ti è rimasto il settanta per cento, cioè zero virgola sette.",
     "Uno diviso zero virgola sette fa circa uno virgola quarantatré. Togli uno, e ottieni zero virgola quarantatré: ti serve un guadagno di circa il quarantatré per cento per tornare dove eri."],
 3: ["Ecco la tabella completa. Guardala bene, perché è una delle più importanti del corso.",
     "Se perdi il dieci per cento, ti serve guadagnare circa l'undici per cento per recuperare. Quasi uguale.",
     "Se perdi il venti, ti serve il venticinque.",
     "Se perdi il trenta, ti serve quasi il quarantatré.",
     "Se perdi il quaranta, ti serve circa il sessantasette.",
     "Se perdi la metà del conto, devi raddoppiarlo: ti serve il cento per cento.",
     "Se perdi il sessanta, ti serve il centocinquanta.",
     "Se perdi il settanta, ti serve più del duecentotrenta per cento.",
     "Se perdi l'ottanta, devi quintuplicare il conto: il quattrocento per cento.",
     "E se perdi il novanta per cento, ti serve il novecento per cento. In pratica, il conto è perso."],
 4: ["Sul grafico si vede ancora meglio. Fino a una perdita del venti per cento circa, la curva sale dolcemente. Poi diventa sempre più ripida, e oltre la metà del conto diventa quasi verticale.",
     "Ecco perché molti trader esperti si danno limiti di drawdown intorno al dieci o al venti per cento. Oltre quella soglia, tornare in pari diventa una montagna sempre più alta."],
 5: ["Prova tu. Il tuo conto è sceso del trentacinque per cento dal massimo. Quanto devi guadagnare per tornare al punto più alto?"],
 6: ["Vediamo. Ti è rimasto il sessantacinque per cento del conto. Uno diviso zero virgola sessantacinque fa circa uno virgola cinquantaquattro. Togli uno: ti serve un guadagno di circa il cinquantaquattro per cento. Molto più del trentacinque che hai perso."],
 7: ["Ricapitoliamo.",
     "Per recuperare una perdita serve sempre guadagnare più di quanto hai perso.",
     "Il guadagno necessario lo trovi dividendo uno per quello che ti è rimasto, e togliendo uno.",
     "E oltre la metà del conto il recupero diventa quasi impossibile. La soluzione migliore è non arrivarci mai."],
 8: ["Ricordati: il tuo primo lavoro è non perdere troppo. Il secondo è guadagnare."],
}
PARLATO['3.3'] = {
 0: ["In questa lezione parliamo delle serie di perdite. Ti mostro quante perdite di fila sono normali, e ti assicuro che sono più di quante pensi."],
 1: ["C'è un pensiero che prima o poi viene a tutti: ho perso sei volte di fila, qualcosa non va nel mio sistema.",
     "A volte è vero. Ma molto spesso è semplicemente statistica. Le serie di perdite fanno parte di qualsiasi sistema, anche di quelli che funzionano bene.",
     "Il vero problema non è la serie di perdite in sé. È quanto rischi a ogni operazione, perché è quello che decide quanto ti costa quella serie."],
 2: ["Guarda questo grafico. Ti mostra la serie di perdite più lunga che puoi aspettarti, nel caso tipico, su duecento operazioni, a seconda di quante volte vinci.",
     "Se vinci il trentacinque per cento delle volte, aspettati circa dieci perdite di fila. Se vinci il quarantacinque, circa otto. E perfino se vinci il sessanta per cento delle volte, cinque perdite consecutive sono assolutamente normali."],
 3: ["Facciamo un esempio con un sistema che vince il quarantacinque per cento delle volte. Su duecento operazioni, quanto è probabile una serie lunga di perdite?",
     "Una serie di almeno cinque perdite è praticamente certa: succede novantanove volte su cento.",
     "Sei perdite di fila: novantatré volte su cento.",
     "Otto perdite di fila: circa una volta su due. Come lanciare una moneta.",
     "Dieci perdite di fila: circa una volta su cinque.",
     "E dodici perdite di fila: circa una volta su sedici. Rara, ma possibile."],
 4: ["E quanto ti costa una serie di perdite? Dipende tutto da quanto rischi a ogni operazione.",
     "Se rischi l'uno per cento, otto perdite di fila ti costano circa l'otto per cento del conto, e dieci perdite circa il dieci per cento.",
     "Se rischi il due per cento, otto perdite ti costano circa il quindici per cento, e dieci perdite più del diciotto.",
     "E se rischi il cinque per cento, otto perdite ti costano più di un terzo del conto, e dieci perdite il quaranta per cento. La serie di perdite è la stessa, ma il danno è cinque volte più grande."],
 5: ["Ora un esercizio un po' più impegnativo. Vuoi essere sicuro che, anche con dieci perdite di fila, il conto non scenda più del quindici per cento. Quanto puoi rischiare al massimo su ogni operazione?"],
 6: ["Vediamo il ragionamento. Dopo dieci perdite deve restarti almeno l'ottantacinque per cento del conto. Facendo il calcolo, il rischio massimo per operazione viene circa uno virgola sei per cento. Quindi, se rischi l'uno e mezzo per cento, sei tranquillo: dieci perdite di fila non ti porteranno oltre il quindici per cento di calo."],
 7: ["Ricapitoliamo.",
     "Le serie di perdite sono normali in qualsiasi sistema, anche in quelli buoni.",
     "Se vinci il quarantacinque per cento delle volte, otto perdite di fila su duecento operazioni capitano circa una volta su due.",
     "E quanto ti costa una serie dipende da quanto rischi. Per questo il rischio va scelto pensando alla serie peggiore che può capitarti, non alla media."],
 8: ["Ricordati: il rischio per operazione si sceglie pensando alla serie di perdite peggiore, non al caso medio."],
}
PARLATO['3.4'] = {
 0: ["In questa lezione vediamo come si accumulano le perdite. E scoprirai perché otto perdite del cinque per cento non fanno meno quaranta."],
 1: ["Il principio è questo: ogni perdita si calcola su quello che ti è rimasto, non su quello che avevi all'inizio.",
     "Quindi, man mano che il conto scende, le perdite successive valgono un po' meno in euro, anche se la percentuale è sempre la stessa.",
     "Il risultato è che il totale è sempre un po' meno grave della semplice somma. E per i guadagni succede il contrario: crescono un po' più della somma. È quello che si chiama interesse composto."],
 2: ["Il calcolo funziona così: ogni volta che perdi, il tuo conto viene moltiplicato per quello che ti resta. Se rischi il cinque per cento, ti resta il novantacinque per cento, cioè zero virgola novantacinque.",
     "Il rischio va espresso come numero decimale: il cinque per cento è zero virgola zero cinque.",
     "E questa moltiplicazione la ripeti tante volte quante sono le perdite di fila.",
     "Alla fine, quello che hai perso è la differenza tra uno e il risultato di queste moltiplicazioni."],
 3: ["Facciamo i conti con otto perdite di fila, rischiando il cinque per cento ogni volta.",
     "Dopo ogni perdita ti resta il novantacinque per cento del conto di prima.",
     "Se moltiplichi zero virgola novantacinque per sé stesso otto volte, ottieni circa zero virgola sessantasei. Cioè ti resta il sessantasei per cento del conto.",
     "Quindi hai perso circa il trentaquattro per cento, non il quaranta che avresti pensato sommando otto volte il cinque per cento."],
 4: ["Ecco la stessa cosa su un grafico. La linea tratteggiata è la somma semplice, quella rossa è la perdita vera. Più perdite si accumulano, più le due linee si allontanano.",
     "Ma attenzione a non consolarti troppo. Questa differenza gioca a tuo favore nelle perdite, ma ricordati della lezione precedente: per recuperare devi guadagnare molto più di quanto hai perso."],
 5: ["Ecco una tabella utile da tenere a portata di mano.",
     "Se rischi l'uno per cento, cinque perdite di fila ti costano circa il cinque per cento, dieci perdite quasi il dieci, quindici perdite il quattordici.",
     "Se rischi il due per cento, cinque perdite ti costano quasi il dieci per cento, dieci perdite circa il diciotto, quindici perdite il ventisei.",
     "Se rischi il tre per cento, cinque perdite ti costano il quattordici, dieci perdite il ventisei, quindici perdite quasi il trentasette.",
     "E se rischi il cinque per cento, cinque perdite ti costano quasi un quarto del conto, dieci perdite il quaranta, e quindici perdite più della metà."],
 6: ["Prova tu. Rischi il tre per cento a operazione e ti capitano otto perdite di fila. Quanto hai perso in totale?"],
 7: ["Vediamo. Dopo ogni perdita ti resta il novantasette per cento. Ripetuto otto volte, ti resta circa il settantotto per cento del conto. Quindi hai perso circa il ventidue per cento, non il ventiquattro che avresti ottenuto sommando."],
 8: ["Ricapitoliamo.",
     "Ogni perdita si calcola su quello che ti è rimasto.",
     "Per sapere quanto perdi in tutto, moltiplichi quello che ti resta dopo ogni perdita, tante volte quante sono le perdite.",
     "E le percentuali non si sommano mai: si moltiplicano."],
 9: ["Ricordati: le percentuali non si sommano, si moltiplicano."],
}
PARLATO['3.5'] = {
 0: ["Ultima lezione del terzo modulo. Oggi colleghiamo tutto quello che abbiamo visto: quanto rischi per operazione, e quanto calo del conto devi aspettarti."],
 1: ["Questa è forse la relazione più importante di tutto il corso: più alto è il rischio per operazione, più profondo sarà il calo del tuo conto.",
     "Il drawdown massimo che vivrai dipende dall'ordine in cui arrivano vittorie e perdite. Quindi non è un numero fisso: è un ventaglio di possibilità.",
     "E possiamo stimarlo con una simulazione, partendo dai numeri del sistema."],
 2: ["Usiamo il nostro solito sistema di esempio. Vince quarantacinque volte su cento.",
     "Quando vince guadagna uno virgola otto volte quello che rischia.",
     "Quando perde, perde quello che rischiava.",
     "Quindi in media ogni operazione vale zero virgola ventisei R.",
     "Simuliamo duecento operazioni di fila.",
     "E ripetiamo la simulazione quarantamila volte per ogni livello di rischio, per vedere cosa succede nel caso tipico e nei casi più sfortunati."],
 3: ["Ecco il risultato: il calo massimo del conto nel caso tipico, cioè quello che capita a metà delle simulazioni.",
     "Rischiando mezzo punto per cento, il calo tipico è intorno al cinque per cento. Con l'uno per cento, intorno al dieci. Con il due, circa il diciannove. Con il tre, circa il ventotto. E con il cinque per cento, il calo tipico arriva al quarantatré per cento.",
     "Hai notato? Il calo cresce più o meno come il rischio. Se raddoppi il rischio, raddoppi anche il calo che devi aspettarti."],
 4: ["Ma il caso tipico non basta. Bisogna guardare anche i casi sfortunati. Qui ti mostro il calo che non viene superato nove volte su dieci.",
     "Con mezzo punto per cento di rischio: calo tipico del cinque, e quasi sempre sotto l'otto.",
     "Con l'uno per cento: tipico del dieci, e quasi sempre sotto il quindici.",
     "Con il due per cento: tipico del diciannove, e quasi sempre sotto il ventotto.",
     "Con il tre per cento: tipico del ventotto, e quasi sempre sotto il quaranta.",
     "E con il cinque per cento: tipico del quarantatré, e nei casi sfortunati oltre il cinquantanove. Più di metà del conto."],
 5: ["Come si usano questi numeri? Si parte dalla fine. Prima ti chiedi quanto calo del conto sei disposto a sopportare, e solo dopo scegli il rischio. Non il contrario.",
     "E lascia sempre un po' di margine, perché nei periodi sfortunati il calo è molto più profondo di quello tipico.",
     "Infine, rifai questi calcoli con i numeri del tuo sistema, perché win rate e rapporto rischio rendimento cambiano tutto. Nel modulo cinque ti mostro come farlo con un simulatore."],
 6: ["Prova tu. Ti conosci bene e sai che riesci a sopportare un calo del conto di circa il venti per cento. Con il nostro sistema di esempio, quanto rischieresti per operazione?"],
 7: ["Guardando la tabella, il due per cento ti dà un calo tipico del diciannove per cento: sembrerebbe giusto. Ma nei casi sfortunati arrivi al ventotto. Per questo è più saggio scendere tra l'uno e l'uno e mezzo per cento: così hai margine anche quando le cose vanno peggio del previsto."],
 8: ["Ricapitoliamo questo modulo.",
     "Rischio per operazione e calo del conto crescono insieme.",
     "Il calo non è un numero fisso: guarda sempre sia il caso tipico, sia quello sfortunato.",
     "E parti sempre da quanto puoi sopportare di perdere, poi scegli il rischio di conseguenza."],
 9: ["Ricordati: il rischio non si sceglie pensando a quanto vuoi guadagnare. Si sceglie pensando a quanto puoi permetterti di perdere."],
}
