PARLATO = {}
PARLATO['5.1'] = {
 0: ["Benvenuto nel quinto modulo. Qui impariamo a guardare il futuro del nostro conto in modo diverso, con uno strumento che si chiama simulazione Monte Carlo. Il nome fa paura, ma l'idea è semplicissima."],
 1: ["Partiamo da un limite che hanno tutti i backtest. Un backtest ti mostra una sola sequenza di operazioni: quella che è successa davvero nel passato.",
     "Ma pensaci: se le stesse operazioni fossero arrivate in un ordine diverso, per esempio con tutte le perdite all'inizio, il calo del conto sarebbe stato completamente diverso. Le statistiche sono le stesse, ma il percorso cambia.",
     "E il futuro sarà ancora un'altra sequenza, che nessuno conosce. Per questo ci serve vedere tante sequenze possibili, non una sola."],
 2: ["Ecco come funziona, in quattro passaggi.",
     "Primo: parti dai numeri del tuo sistema. Quante volte vinci, quanto guadagni in media quando vinci, e quanto perdi in media quando perdi.",
     "Secondo: il computer crea una sequenza casuale di operazioni, dove ognuna vince o perde con la probabilità del tuo sistema. Un po' come lanciare un dado truccato.",
     "Terzo: calcola come si muove il conto con il tuo rischio per operazione, e si annota dove arriva alla fine e quale è stato il calo peggiore.",
     "Quarto: ripete tutto questo migliaia di volte. Alla fine non hai un solo futuro, ma migliaia di futuri possibili, e puoi vedere quali sono i più probabili."],
 3: ["Vediamolo prendere forma, un passo alla volta.",
     "Questa è una sola simulazione: duecento operazioni del nostro sistema di esempio, rischiando l'uno per cento. È un possibile futuro.",
     "Aggiungiamone altre cinque. Stesse regole, stesso sistema, ma vedi come ogni percorso è diverso dagli altri?",
     "Con sessanta percorsi si comincia a vedere un ventaglio: alcuni finiscono molto in alto, altri decisamente più in basso.",
     "E con centinaia di percorsi possiamo disegnare tre linee. Quella centrale è il risultato tipico. Le due linee azzurre racchiudono otto casi su dieci: sotto quella inferiore finisce un percorso su dieci, sopra quella superiore un altro su dieci."],
 4: ["È importante sapere cosa questo strumento può fare e cosa no.",
     "Può mostrarti tutti i risultati possibili, stimare quanto calo del conto aspettarti e quanto è probabile un disastro, e confrontare diversi livelli di rischio.",
     "Non può prevedere il futuro. Non può correggere numeri sbagliati: se inserisci statistiche troppo ottimistiche, otterrai risultati troppo ottimistici. E non sa se il mercato cambierà.",
     "Quindi usalo per capire l'ordine di grandezza dei rischi che corri. Non come una sfera di cristallo."],
 5: ["Una domanda per te. Perché, secondo te, un solo backtest non basta per capire quanto rischi?"],
 6: ["Perché un backtest è una sola sequenza tra le tante possibili. Se le stesse operazioni fossero arrivate in un altro ordine, il calo del conto sarebbe stato diverso. Per avere un'idea realistica servono tante sequenze, ed è proprio quello che fa la simulazione."],
 7: ["Ricapitoliamo.",
     "Un backtest ti mostra una sola delle sequenze possibili.",
     "La simulazione Monte Carlo ne crea migliaia, partendo dai numeri del tuo sistema.",
     "E ti mostra tutto il ventaglio dei risultati possibili, senza pretendere di prevedere il futuro."],
 8: ["Ricordati: non chiederti cosa succederà. Chiediti cosa può succedere."],
}
PARLATO['5.2'] = {
 0: ["In questa lezione impariamo a leggere i risultati di una simulazione. Ti bastano tre numeri."],
 1: ["Quando guardi una simulazione, concentrati su tre numeri.",
     "La mediana è il risultato che sta esattamente in mezzo: metà dei percorsi fa meglio, metà fa peggio. È quello che puoi considerare il caso tipico.",
     "Il decimo percentile ti dice il caso sfortunato: solo un percorso su dieci va peggio di così.",
     "E il novantesimo percentile ti dice il caso fortunato: solo un percorso su dieci va meglio."],
 2: ["Ecco i numeri del nostro sistema di esempio, rischiando l'uno per cento su duecento operazioni. Immagina di partire da diecimila euro.",
     "Nel caso sfortunato, il conto cresce comunque di circa il ventotto per cento: arrivi a circa dodicimilaottocento euro.",
     "Nel caso tipico cresce di circa il sessantacinque per cento: arrivi intorno ai sedicimilacinquecento euro.",
     "Nel caso fortunato cresce di circa il centododici per cento: più del doppio.",
     "Meno di un percorso su cento finisce sotto i diecimila euro iniziali.",
     "E il calo massimo tipico lungo la strada è intorno al dieci per cento."],
 3: ["Cosa succede se raddoppiamo il rischio, dall'uno al due per cento?",
     "Con l'uno per cento, come abbiamo visto: caso sfortunato più ventotto, caso tipico più sessantacinque, e un calo tipico del dieci per cento.",
     "Con il due per cento: caso sfortunato più cinquantanove, caso tipico più centosessantuno. Ma il calo tipico sale al diciannove per cento.",
     "Il guadagno tipico è circa due volte e mezzo più alto, ma il calo del conto raddoppia. E qui arriva la vera domanda: quanto calo riesci davvero a sopportare? La scelta giusta dipende da questo, non dal numero più alto."],
 4: ["Questa simulazione la puoi fare anche tu, con i tuoi numeri: quante volte vinci, quanto guadagni rispetto a quanto perdi, quanto rischi e su quante operazioni.",
     "Sul sito riskly punto trade ci sono dei calcolatori gratuiti che lo fanno. Ti dico chiaramente che sono miei.",
     "Ma va bene qualsiasi strumento, anche un foglio di calcolo. Quello che conta è inserire numeri onesti."],
 5: ["Prova a interpretare questo risultato. In una simulazione il decimo percentile è meno otto per cento, la mediana più trenta, e il novantesimo percentile più settantacinque. Cosa significa quel meno otto per cento?"],
 6: ["Significa che un percorso su dieci finisce peggio di meno otto per cento. Ma attenzione: non vuol dire che meno otto sia il peggio che possa capitare. Il caso peggiore in assoluto può essere molto più brutto. Guarda sempre anche gli estremi."],
 7: ["Ricapitoliamo.",
     "Guarda sempre tre numeri: la mediana, il decimo e il novantesimo percentile.",
     "Il decimo percentile è un caso sfortunato, non il peggiore possibile.",
     "E se raddoppi il rischio, raddoppi più o meno anche il calo del conto. Scegli in base a quanto riesci a sopportare."],
 8: ["Ricordati: la mediana ti dice cosa aspettarti. Il decimo percentile ti dice cosa devi essere pronto a sopportare."],
}
PARLATO['5.3'] = {
 0: ["In questa lezione parliamo di una parola che nessuno vuole sentire: rovina. E di come calcolare quanto è probabile."],
 1: ["Prima di tutto, cosa intendiamo per rovina? Non deve per forza voler dire perdere tutto il conto. Per chi fa una prop firm, per esempio, la rovina è superare il limite di perdita.",
     "La definisci tu, in anticipo. Per esempio: per me la rovina è perdere il trenta per cento del capitale iniziale. Su diecimila euro, significa scendere sotto i settemila.",
     "E la probabilità di rovina è semplicemente la percentuale di simulazioni in cui il conto tocca quella soglia."],
 2: ["Ecco i risultati per il nostro sistema di esempio, su duecento operazioni: qual è la probabilità di perdere almeno il trenta per cento del conto?",
     "Rischiando mezzo punto o l'uno per cento: praticamente zero.",
     "Rischiando il due per cento: meno di una volta su cento.",
     "Rischiando il tre per cento: circa il quattro per cento, cioè una volta su venticinque. Già da non sottovalutare.",
     "E rischiando il cinque per cento: circa il diciassette per cento, cioè quasi una volta su sei. È come giocare alla roulette russa con il proprio conto."],
 3: ["Attenzione però: questi numeri valgono per il nostro sistema di esempio.",
     "Se il tuo sistema vince meno spesso, la probabilità di rovina sale molto. Lo vedremo nella prossima lezione.",
     "E se hai sopravvalutato il tuo vantaggio, la realtà sarà peggiore della simulazione. Un sistema senza vantaggio ha una probabilità di rovina molto più alta.",
     "Infine, non è mai davvero zero. Anche con un rischio basso, se le tue ipotesi sono sbagliate, il conto può andare male."],
 4: ["Prova tu. Rischi il tre per cento a operazione, e la simulazione ti dice che la probabilità di rovina è circa il quattro per cento. Secondo te, è accettabile?"],
 5: ["Dipende, ma ragioniamo. Quattro per cento vuol dire che un trader su venticinque, con questo sistema, perde il trenta per cento del conto. Se stai pagando una prop firm, probabilmente è troppo. Se si tratta di un piccolo capitale che puoi permetterti di perdere, forse lo accetti. L'importante è decidere la soglia prima, a mente fredda, e non dopo."],
 6: ["Ricapitoliamo.",
     "La rovina va definita prima, con un numero preciso.",
     "Con il nostro sistema è quasi nulla rischiando l'uno per cento, e diventa circa una volta su sei rischiando il cinque.",
     "E tutto dipende dall'avere un vantaggio reale: se non c'è, la rovina è molto più probabile."],
 7: ["Ricordati: la rovina non è un evento che capita per caso. È una probabilità che scegli tu, decidendo quanto rischiare."],
}
PARLATO['5.4'] = {
 0: ["Ultima lezione del quinto modulo. Oggi mettiamo alla prova il nostro piano con uno stress test: cosa succede se le cose vanno peggio del previsto?"],
 1: ["Perché fare uno stress test? Primo, perché i tuoi numeri sono stime, e se li hai misurati su poche operazioni potrebbero essere troppo ottimistici.",
     "Secondo, perché i mercati cambiano, e un vantaggio che c'era può ridursi nel tempo.",
     "Terzo, perché i costi reali possono essere più alti di quelli che hai previsto."],
 2: ["Facciamo la prova rischiando l'uno per cento, con quattro scenari.",
     "Lo scenario di base, con il quarantacinque per cento di vittorie: calo tipico del dieci per cento, rovina praticamente zero, e solo un percorso su cento finisce in perdita.",
     "Se in realtà vinci il quaranta per cento delle volte: il calo tipico sale al tredici, la rovina resta bassissima, ma quattordici percorsi su cento finiscono in perdita.",
     "Se vinci il quaranta per cento e in più i costi sono più alti: calo tipico del sedici, rovina intorno al due per cento, e un percorso su tre finisce in perdita.",
     "E se vinci solo il trentacinque per cento, il sistema non ha più vantaggio: calo tipico del ventuno, rovina intorno al nove per cento, e due percorsi su tre finiscono in perdita."],
 3: ["Ora la stessa prova, ma rischiando il due per cento.",
     "Scenario di base: calo tipico del diciannove per cento, rovina sotto l'uno per cento.",
     "Con il quaranta per cento di vittorie: calo tipico del venticinque, e la rovina sale a circa il nove per cento.",
     "Con il quaranta per cento e costi più alti: calo tipico del trenta, e rovina intorno al ventuno per cento. Una volta su cinque.",
     "E con il trentacinque per cento: calo tipico del trentotto, e rovina quasi una volta su due."],
 4: ["Cosa ci insegna questo stress test?",
     "Primo: un rischio che funziona solo se tutto va come previsto è fragile. Il tuo piano deve reggere anche lo scenario brutto.",
     "Secondo: dimezzare il rischio riduce tantissimo la probabilità di rovina. Nello scenario con il quaranta per cento di vittorie, passando dal due all'uno per cento la rovina scende da circa nove a quasi zero.",
     "Terzo: se il vantaggio sparisce, nessun livello di rischio ti salva. Per questo è importante sapere anche quando fermarsi e rivedere il sistema."],
 5: ["Prova tu. Il tuo piano prevede di rischiare il due per cento a operazione. Ma nello scenario in cui vinci il quaranta per cento delle volte, la probabilità di rovina sale a circa il nove per cento. Cosa fai?"],
 6: ["Hai due strade. Puoi scendere all'uno per cento, e la rovina in quello scenario diventa quasi nulla. Oppure puoi accettare quel nove per cento, se il capitale è piccolo e hai deciso a mente fredda che puoi permetterti di perderlo. L'importante è scegliere con i numeri davanti, prima di operare."],
 7: ["Ricapitoliamo.",
     "Metti sotto stress il tuo piano: prova con meno vittorie e costi più alti.",
     "Dimezzare il rischio riduce moltissimo la probabilità di rovina.",
     "E un buon piano regge anche quando le cose vanno peggio del previsto. Con questo chiudiamo il modulo sulle simulazioni."],
 8: ["Ricordati: un piano non si giudica quando va tutto bene. Si giudica quando le cose si mettono male."],
}
