PARLATO = {}
PARLATO['8.1'] = {
 0: ["Benvenuto nell'ottavo modulo, dedicato a come gestire un'operazione mentre è aperta. Partiamo da due strumenti fondamentali: il break-even e il trailing stop."],
 1: ["Sono due strumenti con due scopi diversi.",
     "Il break-even significa spostare lo stop al prezzo in cui sei entrato. Da quel momento l'operazione non può più andare in perdita, a parte lo spread.",
     "Il trailing stop significa far seguire lo stop al prezzo, a una certa distanza o a gradini. Così blocchi una parte del guadagno mentre l'operazione va nella direzione giusta.",
     "Ma attenzione: nessuno dei due è gratis. Se proteggi troppo presto, chiudi operazioni che sarebbero arrivate al target."],
 2: ["Vediamo un trailing a gradini su un grafico, con gradini di venticinque pip.",
     "Entri con lo stop iniziale venticinque pip sotto il prezzo di ingresso.",
     "Il prezzo sale di venticinque pip: sposti lo stop al prezzo di ingresso. Da adesso l'operazione non può più perdere.",
     "Il prezzo arriva a cinquanta pip di guadagno: lo stop sale a più venticinque. Una parte del guadagno è già al sicuro.",
     "A settantacinque pip di guadagno, lo stop sale a più cinquanta.",
     "Poi il prezzo torna indietro e tocca lo stop: esci con cinquanta pip di guadagno. Non hai dovuto indovinare il massimo: hai solo seguito il prezzo."],
 3: ["Ma quando conviene spostare lo stop a pareggio? È un compromesso. Prendiamo un'operazione con lo stop a venticinque pip.",
     "Se sposti lo stop a pareggio presto, per esempio dopo dodici pip di guadagno, cioè a metà dello stop, avrai meno perdite piene. Ma molte operazioni torneranno indietro e chiuderanno a zero, anche se poi sarebbero arrivate al target.",
     "Se lo sposti più tardi, dopo venticinque pip, lasci più respiro all'operazione e più operazioni arrivano al target. Ma ne prenderai anche di più allo stop pieno.",
     "Non esiste un valore giusto per tutti. Va provato sui tuoi dati, misurando i risultati nel journal."],
 4: ["Tre regole pratiche per usarli bene.",
     "Decidi in anticipo quando sposti lo stop a pareggio, e fallo sempre allo stesso modo. Non a sensazione.",
     "Lascia spazio al movimento normale del prezzo: uno stop troppo vicino scatta per un semplice ritracciamento.",
     "E misura nel journal l'effetto di ogni regola, su almeno cento operazioni, prima di decidere se ti conviene."],
 5: ["Prova tu. Sei entrato a uno virgola due zero zero zero, con lo stop quaranta pip sotto. Adesso il prezzo è a uno virgola due zero otto zero, cioè sei in guadagno di ottanta pip. Se usi un trailing a gradini di quaranta pip, dove va lo stop?"],
 6: ["A ottanta pip di guadagno, con gradini da quaranta, lo stop va a quaranta pip sopra il tuo ingresso, cioè a uno virgola due zero quattro zero. Hai già quaranta pip al sicuro, qualunque cosa succeda."],
 7: ["Ricapitoliamo.",
     "Il break-even porta lo stop al prezzo di ingresso, e l'operazione non può più perdere.",
     "Il trailing fa seguire lo stop al prezzo, e blocca una parte del guadagno.",
     "Ma proteggere troppo presto ha un costo: prova le regole sui tuoi dati."],
 8: ["Ricordati: proteggere un'operazione troppo presto è solo un altro modo di perdere."],
}
PARLATO['8.2'] = {
 0: ["In questa lezione parliamo delle uscite a scaglioni: cioè dividere la posizione in più parti, ognuna con il suo obiettivo."],
 1: ["L'idea di fondo è questa.",
     "Con una sola uscita è tutto o niente: o il prezzo arriva al target, o arriva allo stop.",
     "Con più uscite, invece, distribuisci il risultato: incassi una parte presto, e lasci correre il resto.",
     "Attenzione però: gli scaglioni riducono lo stress, ma non riducono il rischio iniziale. Se il prezzo va subito allo stop, perdi esattamente quanto avevi deciso."],
 2: ["Vediamolo sul grafico.",
     "Entri con lo stop venticinque pip sotto, e tre obiettivi: più venticinque, più cinquanta e più settantacinque pip.",
     "Il prezzo sale e tocca il primo obiettivo: chiudi metà della posizione e incassi.",
     "Continua a salire e tocca il secondo obiettivo: chiudi un altro trenta per cento.",
     "Arriva al terzo obiettivo: chiudi l'ultimo venti per cento.",
     "Alla fine, in media, hai guadagnato quarantadue pip e mezzo per ogni lotto. Te lo spiego meglio nella prossima slide."],
 3: ["Facciamo i conti con zero virgola quattro lotti, divisi in tre parti, e lo stop a venticinque pip.",
     "La prima parte, metà della posizione, chiude a più venticinque pip. Contribuisce con dodici pip e mezzo.",
     "La seconda parte, il trenta per cento, chiude a più cinquanta pip. Contribuisce con quindici pip.",
     "La terza parte, il venti per cento, chiude a più settantacinque pip. Altri quindici pip.",
     "In totale, se arrivano tutti gli obiettivi, guadagni in media quarantadue pip e mezzo. Con zero virgola quattro lotti ogni pip vale quattro euro, quindi circa centosettanta euro."],
 4: ["Ma cosa succede se le cose vanno diversamente? Vediamo gli scenari.",
     "Se il prezzo va subito allo stop, perdi venticinque pip su tutta la posizione, cioè cento euro.",
     "Se prendi il primo obiettivo, poi sposti lo stop a pareggio e il resto torna indietro, guadagni dodici pip e mezzo, cioè cinquanta euro.",
     "Se prendi i primi due obiettivi e l'ultima parte esce a più venticinque, guadagni trentadue pip e mezzo, circa centotrenta euro.",
     "E se arrivano tutti e tre gli obiettivi, guadagni quarantadue pip e mezzo, circa centosettanta euro. Come vedi, il risultato migliora in tanti scenari, ma il guadagno massimo è più basso di quello che avresti tenendo tutta la posizione fino all'obiettivo più lontano."],
 5: ["Ricapitoliamo pro e contro.",
     "I vantaggi: incassi qualcosa presto, hai meno stress, e resti dentro i movimenti lunghi con una parte della posizione.",
     "Gli svantaggi: il guadagno massimo si riduce, paghi più costi perché fai più ordini, e la gestione è più complicata. Se ti conviene o no dipende dal tuo sistema e da come reagisci tu."],
 6: ["Prova tu. Il tuo stop è a trenta pip. Il sessanta per cento della posizione chiude a più trenta pip, il quaranta per cento a più settantacinque. Se arrivano entrambi gli obiettivi, quanti pip guadagni in media?"],
 7: ["Vediamo. Sessanta per cento di trenta fa diciotto pip. Quaranta per cento di settantacinque fa trenta pip. In totale, quarantotto pip in media."],
 8: ["Ricapitoliamo.",
     "Gli scaglioni distribuiscono il risultato su più uscite.",
     "Ma il rischio iniziale resta lo stesso.",
     "E prima di usarli, calcola sempre il risultato di ogni scenario, in pip e in euro."],
 9: ["Ricordati: uscire a pezzi cambia il modo in cui vinci, non quanto rischi."],
}
PARLATO['8.3'] = {
 0: ["In questa lezione parliamo di come aggiungere a un'operazione che sta già andando bene. Si chiama piramidare."],
 1: ["Piramidare significa aumentare la posizione mentre il trade va nella direzione giusta.",
     "Si aggiunge solo quando l'operazione è già in guadagno. Mai, e ripeto mai, per mediare una perdita.",
     "Ogni aggiunta è più piccola della precedente: così la posizione cresce, ma il rischio resta sotto controllo.",
     "E lo stop si sposta in modo da proteggere il rischio totale. Senza questo passaggio, stai solo accumulando rischio."],
 2: ["È fondamentale non confondere due cose molto diverse.",
     "Mediare in perdita vuol dire aggiungere mentre stai perdendo, sperando che il prezzo torni indietro. Il rischio cresce, e stai violando il tuo piano.",
     "Piramidare vuol dire aggiungere mentre stai guadagnando, con il rischio totale sotto controllo e con una regola scritta prima. La prima cosa è un errore. La seconda, se è nel tuo piano, è una tecnica."],
 3: ["Vediamo un esempio con i numeri. Apri zero virgola quattro lotti con lo stop a venticinque pip: stai rischiando cento euro.",
     "Il prezzo sale di venticinque pip, e sposti lo stop al prezzo di ingresso. Adesso su questa posizione rischi zero.",
     "A questo punto aggiungi zero virgola due lotti, con lo stop venticinque pip sotto: su questa aggiunta rischi cinquanta euro.",
     "Il rischio totale è cinquanta euro, non centocinquanta.",
     "In pratica hai usato il guadagno della prima posizione come cuscinetto per aggiungere. Se il prezzo torna indietro, nel caso peggiore perdi una parte del guadagno, ma non il tuo capitale."],
 4: ["Tre regole per non farti male.",
     "Decidi prima quante aggiunte al massimo: una o due, mai di più.",
     "Ogni aggiunta deve essere più piccola della precedente. Altrimenti il tuo prezzo medio si avvicina troppo al prezzo peggiore.",
     "E non aggiungere dopo un movimento molto forte: è proprio lì che il prezzo spesso torna indietro, e colpisce tutta la posizione."],
 5: ["Prova tu. La tua prima posizione è da zero virgola quattro lotti, con lo stop già a pareggio. Aggiungi zero virgola due lotti, con lo stop a venticinque pip. Ogni pip vale dieci euro per lotto. Qual è il tuo rischio totale?"],
 6: ["Zero virgola due lotti per venticinque pip per dieci euro fa cinquanta euro. La prima posizione, con lo stop a pareggio, non rischia più niente. Quindi il rischio totale è cinquanta euro."],
 7: ["Ricapitoliamo.",
     "Piramidare vuol dire aggiungere a un'operazione in guadagno, mai a una in perdita.",
     "Le aggiunte devono essere sempre più piccole, e lo stop deve proteggere il rischio totale.",
     "E il numero massimo di aggiunte va scritto nel piano."],
 8: ["Ricordati: si aggiunge solo con i soldi che il mercato ti ha già dato, mai con i tuoi."],
}
PARLATO['8.4'] = {
 0: ["Ultima lezione dell'ottavo modulo. Parliamo di come automatizzare le regole, cioè lasciare a un software le decisioni che sotto stress rischi di sbagliare."],
 1: ["Cosa si può automatizzare nella gestione del rischio? Tante cose.",
     "Il calcolo del lotto, partendo dalla distanza dello stop e dalla percentuale di rischio.",
     "I limiti della giornata: per esempio il blocco dopo una certa perdita, o dopo un certo numero di perdite di fila.",
     "Lo spostamento a pareggio e il trailing stop, applicati sempre con la stessa regola, senza esitazioni.",
     "E le uscite a scaglioni, con gli ordini e gli obiettivi già impostati."],
 2: ["Ma ci sono cose che non si automatizzano.",
     "La decisione di entrare resta tua. Gli strumenti di gestione del rischio non danno segnali e non aprono operazioni al posto tuo.",
     "La responsabilità del piano resta tua. Un software esegue le regole che gli dai, che siano buone o cattive.",
     "E il controllo resta tuo. Devi verificare che stia facendo esattamente quello che vuoi."],
 3: ["Ti mostro gli strumenti Riskly. Te lo dico chiaramente: sono prodotti miei.",
     "RiskGuard ti mette in pausa dopo una perdita, ti ferma dopo un certo numero di perdite, applica un limite giornaliero, chiude al raggiungimento dell'obiettivo e può bloccare MetaTrader.",
     "TradeManager sposta lo stop a pareggio e segue il prezzo con il trailing.",
     "ScaleIn divide la posizione in più take profit, come abbiamo visto nella lezione sugli scaglioni.",
     "Riskly Pro riunisce tutte queste funzioni in un unico strumento, per MetaTrader quattro e cinque.",
     "E il journal raccoglie le operazioni e calcola le statistiche."],
 4: ["Vediamo un esempio concreto: RiskGuard. Come ti dicevo, è un mio prodotto.",
     "Ti impone una pausa dopo una perdita, e ti blocca dopo il numero di perdite di fila che scegli tu.",
     "Applica il limite di perdita e di operazioni giornaliere: esattamente le regole che abbiamo visto nella lezione sei punto due.",
     "E può chiudere all'obiettivo e bloccare MetaTrader. Il software non decide al posto tuo: applica quello che hai scritto nel piano."],
 5: ["Ma conviene usare un software, o fare tutto a mano?",
     "Fare tutto a mano non costa niente, ma richiede una disciplina costante. E gli errori arrivano proprio nei momenti di stress.",
     "Un software ha un costo, ma applica le regole sempre, anche quando tu non ne avresti voglia. Va però configurato bene e controllato.",
     "Non è obbligatorio. Tutto quello che hai imparato in questo corso lo puoi applicare anche con un foglio di calcolo e tanta disciplina. Gli strumenti servono a chi vuole togliersi la tentazione di mezzo."],
 6: ["Prova tu. Il tuo punto debole è che, dopo due perdite di fila, cominci ad aprire operazioni fuori dal tuo piano. Quale regola automatizzeresti?"],
 7: ["Una buona soluzione è uno stop automatico dopo due o tre perdite di fila, con un blocco o una pausa obbligatoria. Il consiglio è questo: non serve automatizzare tutto. Automatizza il tuo punto debole."],
 8: ["Ricapitoliamo.",
     "Si automatizza l'esecuzione delle regole, non la decisione di entrare.",
     "Gli strumenti Riskly sono miei prodotti, e non sono obbligatori.",
     "E il consiglio migliore è automatizzare il tuo punto debole. Nel prossimo modulo vediamo le tecniche avanzate: compounding, trailing, scaglioni, mitigazione e hedging."],
 9: ["Ricordati: lo strumento migliore è quello che ti impedisce di fare quello che sai di non dover fare."],
}
