PARLATO = {}
PARLATO['6.1'] = {
 0: ["Benvenuto nel sesto modulo, dedicato alla disciplina. Partiamo da un principio semplice ma potentissimo: le regole si scrivono prima di operare, non durante."],
 1: ["Perché servono regole scritte? Ci sono tre motivi.",
     "Il primo: quando sei dentro un'operazione sei sotto stress, anche se non te ne accorgi. E lo stress riduce la lucidità.",
     "Il secondo: le decisioni prese prima, a mente fredda, sono migliori. Mentre le scrivi non c'è un grafico che si muove e ti mette ansia.",
     "Il terzo: una regola scritta ti toglie la possibilità di scegliere. O la rispetti, o la violi. Non puoi più metterti a negoziare con te stesso."],
 2: ["C'è però una differenza enorme tra un buon proposito e una regola vera.",
     "A sinistra vedi dei buoni propositi: non rischiare troppo, fermati se va male, sii paziente. Suonano bene, ma come fai a dire se li hai rispettati?",
     "A destra vedi delle regole vere: massimo l'uno per cento per operazione, stop dopo tre perdite nella giornata, massimo due operazioni per sessione. Qui la risposta è sì o no, senza discussioni.",
     "Ecco il test: se alla fine della giornata non puoi rispondere con un sì o con un no alla domanda l'ho rispettata, allora non è una regola."],
 3: ["Un modo molto efficace di scrivere le regole è usare la forma se, allora.",
     "Per esempio: se la perdita della giornata arriva al tre per cento, allora chiudo la piattaforma fino a domani.",
     "Oppure: se ho perso tre operazioni di fila, allora mi fermo per il resto della sessione.",
     "Oppure ancora: se il rischio aperto è già al limite, allora non apro nuove operazioni. Ogni regola ha una condizione precisa e un'azione precisa, decise prima."],
 4: ["Ecco le regole minime che ogni piano di rischio dovrebbe avere. I numeri sono solo un esempio.",
     "Il rischio per operazione: per esempio l'uno per cento.",
     "Il rischio totale delle operazioni aperte insieme: per esempio il tre per cento.",
     "La perdita massima in una giornata: per esempio il tre per cento.",
     "Quante perdite di fila ti fanno fermare: per esempio tre.",
     "Quante operazioni al massimo in una giornata: per esempio tre.",
     "E quando ridurre il rischio: per esempio se il conto scende di più del dieci per cento dal massimo. I tuoi numeri li decidi tu. L'importante è che esistano, e che siano scritti."],
 5: ["Prova tu. Trasforma questa frase in una regola vera: quando sono giù, non esagero."],
 6: ["Una possibile versione è questa: se il conto è sceso di più del dieci per cento dal massimo, allora dimezzo il rischio per operazione, finché non recupero almeno cinque punti. Adesso c'è una condizione, un numero e un'azione. E alla fine della giornata sai rispondere con un sì o con un no."],
 7: ["Ricapitoliamo.",
     "Le regole si scrivono a mente fredda, prima di operare.",
     "Una regola vera ha un numero, una condizione e un'azione.",
     "E il formato più semplice è se, allora."],
 8: ["Ricordati: una regola che puoi negoziare con te stesso non è una regola."],
}
PARLATO['6.2'] = {
 0: ["In questa lezione parliamo di una delle abilità più importanti per un trader: sapere quando fermarsi."],
 1: ["Ogni sistema, anche il migliore, ha giornate con molte più perdite del normale. Non è sfortuna personale: è statistica.",
     "Il vero pericolo è continuare a operare quando hai perso il controllo. Le decisioni peggiori, di solito, arrivano proprio dopo le prime perdite della giornata.",
     "Un limite fisso trasforma il danno possibile in un danno massimo. Sai già, prima di iniziare, qual è il peggio che può capitarti in un giorno."],
 2: ["Vediamo cosa significa un limite giornaliero se rischi l'uno per cento a operazione.",
     "Con un limite del due per cento, ti fermi dopo due perdite piene. In pratica perdi poco meno del due per cento.",
     "Con un limite del tre per cento, ti fermi dopo tre perdite piene, e perdi poco meno del tre per cento.",
     "Con un limite del quattro per cento, dopo quattro perdite. Come vedi, il numero di perdite si traduce direttamente in una soglia chiara."],
 3: ["Ci sono tre tipi di stop che puoi usare.",
     "Il primo è il limite di perdita giornaliero: se perdi una certa percentuale nella giornata, chiudi tutto fino al giorno dopo.",
     "Il secondo è lo stop dopo un certo numero di perdite di fila: per esempio, dopo tre stop consecutivi fai pausa per il resto della sessione.",
     "Il terzo è lo stop dopo l'obiettivo: se hai raggiunto il guadagno che ti eri prefissato per la giornata, ti fermi. Tantissimi trader perdono il pomeriggio quello che hanno guadagnato la mattina."],
 4: ["Mettiamo a confronto due giornate storte, con un conto da diecimila euro e l'uno per cento di rischio.",
     "Senza nessun limite: arrivano sei perdite di fila e perdi circa il sei per cento, quasi seicento euro.",
     "Con un limite del tre per cento: ti fermi alla terza perdita e perdi circa trecento euro.",
     "Hai risparmiato circa trecento euro. Ma soprattutto hai evitato la spirale emotiva, quella che ti porta a sbagliare sempre di più man mano che la giornata va male."],
 5: ["Prova tu. Rischi lo zero virgola cinque per cento a operazione e il tuo limite giornaliero è il due per cento. Dopo quante perdite piene ti fermi?"],
 6: ["Semplice: due diviso zero virgola cinque fa quattro. Ti fermi dopo quattro perdite piene."],
 7: ["Ricapitoliamo.",
     "Un limite fisso trasforma il danno possibile in un danno massimo, che conosci prima.",
     "Ci sono tre tipi di stop: la perdita massima della giornata, un certo numero di perdite di fila, e l'obiettivo raggiunto.",
     "E per sapere dopo quante perdite ti fermi, dividi il limite per il rischio di ogni operazione."],
 8: ["Ricordati: dopo una giornata storta, l'operazione migliore è quella che non fai."],
}
PARLATO['6.3'] = {
 0: ["In questa lezione parliamo di due errori di comportamento che costano carissimo: il revenge trading e l'overtrading."],
 1: ["Sono due errori diversi, con cause diverse.",
     "Il revenge trading è la voglia di vendicarsi del mercato dopo una perdita: vuoi rifarti subito, aumenti il rischio e prendi operazioni che non rispettano il tuo piano.",
     "L'overtrading è fare troppe operazioni, per noia o perché senti il bisogno di essere sempre dentro il mercato. Il risultato sono operazioni di qualità bassa, e tanti costi."],
 2: ["Come riconoscerli? Ecco quattro segnali d'allarme.",
     "Apri un'operazione senza aspettare il tuo setup, solo perché devi recuperare.",
     "Aumenti il lotto dopo una perdita, anche se il tuo piano non lo prevede.",
     "Sposti lo stop, o addirittura lo togli, per non dover accettare la perdita.",
     "Controlli il conto ogni minuto, e il tuo umore sale e scende insieme a quel numero."],
 3: ["Le contromisure sono molto concrete.",
     "Un limite di operazioni al giorno: per esempio tre. Dopo la terza, la sessione è finita, qualunque cosa succeda.",
     "Una pausa obbligatoria dopo ogni perdita: per esempio quindici minuti lontano dallo schermo. Ti alzi, bevi un bicchiere d'acqua, fai due passi.",
     "Un limite di perdita che chiude la giornata, come abbiamo visto nella lezione precedente.",
     "E segnare nel journal ogni operazione fatta fuori dal piano, così vedi nero su bianco quanto ti costano."],
 4: ["Ma quanto costa davvero un'operazione fuori piano? Facciamo un conto semplice.",
     "Un'operazione che segue il piano, nel nostro esempio, vale in media zero virgola ventisei R.",
     "Ogni operazione costa circa zero virgola zero sei R tra spread e commissioni.",
     "Un'operazione fuori piano non ha un vantaggio dimostrato, ma paga comunque gli stessi costi.",
     "Quindi, se fai cinque operazioni in più al giorno, paghi circa zero virgola trenta R di soli costi. È più di quanto guadagni in media con un'intera operazione fatta bene. Più operazioni non vogliono dire più guadagno, anzi."],
 5: ["Prova tu. Hai appena perso due operazioni di fila. Scrivi una regola, con la forma se, allora, per evitare il revenge trading."],
 6: ["Un esempio potrebbe essere: se perdo due operazioni di fila, allora faccio quindici minuti di pausa lontano dallo schermo, poi rivaluto con calma. E se la terza operazione non è nel mio piano, chiudo la sessione. Scrivi la tua versione, e mettila vicino al monitor."],
 7: ["Ricapitoliamo.",
     "Il revenge trading è la voglia di rifarsi subito, l'overtrading è fare troppe operazioni.",
     "Le contromisure sono un limite di operazioni, una pausa dopo le perdite e un limite giornaliero.",
     "E segnare nel journal le operazioni fuori piano ti mostra quanto ti costano davvero."],
 8: ["Ricordati: in quei momenti non hai bisogno di un'operazione migliore. Hai bisogno di una pausa."],
}
PARLATO['6.4'] = {
 0: ["Ultima lezione del modulo sulla disciplina. Oggi costruiamo insieme uno strumento semplicissimo ma potentissimo: la checklist da controllare prima di ogni operazione."],
 1: ["Perché funziona? Perché gli errori più costosi, quasi sempre, non sono di analisi ma di esecuzione. Sai benissimo cosa dovresti fare, ma nel momento non lo fai.",
     "Una checklist è un freno. Ti obbliga a rallentare di un minuto prima di cliccare.",
     "Pensa ai piloti di aereo o ai chirurghi. La usano sempre, non perché non sappiano fare il loro lavoro, ma perché un errore costa troppo."],
 2: ["Ecco le otto domande. Partiamo dalle prime cinque.",
     "Prima domanda: è un setup del mio piano? Se la risposta è no, non entro.",
     "Seconda: lo stop è nel punto in cui la mia idea diventa sbagliata, o l'ho messo dove mi faceva comodo?",
     "Terza: il rischio è quello previsto? Il lotto l'ho calcolato, o l'ho scelto a occhio?",
     "Quarta: il rischio totale delle operazioni aperte è dentro il mio limite? E ho controllato se ho già altre operazioni sulla stessa idea?",
     "Quinta: il rapporto tra guadagno possibile e rischio è almeno quello minimo che ho deciso?"],
 3: ["E ora le ultime tre.",
     "Sesta: ci sono notizie importanti in arrivo a breve? Durante le notizie spread e slippage possono esplodere.",
     "Settima: ho già raggiunto uno dei miei limiti della giornata? Se sì, per oggi ho finito.",
     "Ottava, e forse la più importante: come sto? Se sono stanco, arrabbiato o troppo euforico, non è il momento di operare."],
 4: ["Ecco la checklist in forma pratica. Per ogni domanda, se la risposta è no, sai già cosa fare.",
     "Se il setup non è del piano, non entri. Se lo stop non è sul punto di invalidazione, rivedi l'operazione oppure la salti. Se il rischio è troppo alto, riduci il lotto.",
     "Se il rischio totale supera il limite, non apri. Se il rapporto rischio rendimento è sotto il minimo, salti l'operazione.",
     "Se stanno per uscire notizie importanti, aspetti. Se hai raggiunto un limite, chiudi. E se non stai bene, fai una pausa."],
 5: ["Prova tu. Hai già due operazioni aperte, ognuna con l'uno e mezzo per cento di rischio. Il tuo limite di rischio totale è il tre per cento. Ti si presenta un nuovo setup valido, da uno per cento. Cosa fai?"],
 6: ["Facciamo i conti. Hai già il tre per cento di rischio aperto. Con la nuova operazione arriveresti al quattro, sopra il tuo limite. La quarta domanda della checklist blocca l'ingresso: o non entri, oppure prima riduci o chiudi qualcosa."],
 7: ["Ricapitoliamo.",
     "La checklist ti fa rallentare di un minuto prima di ogni operazione.",
     "Sono otto domande: setup, stop, rischio, rischio totale, rapporto rischio rendimento, notizie, limiti e come stai.",
     "E per ogni risposta negativa hai già deciso cosa fare. Con questo chiudiamo il modulo sulla disciplina."],
 8: ["Ricordati: la checklist non serve quando tutto va bene. Serve quando hai fretta."],
}
