PARLATO = {}
PARLATO['2.1'] = {
 0: ["Benvenuto nel secondo modulo. Qui impariamo a capire se un sistema funziona davvero, e partiamo dal numero più importante di tutti: l'expectancy, cioè quanto vale in media ogni tua operazione."],
 1: ["Ti faccio una domanda. Se oggi hai chiuso in guadagno, vuol dire che il tuo sistema funziona? No. Un singolo trade, o una singola giornata, non ti dice quasi niente. Un sistema si giudica guardando cosa succede in media, su tante operazioni.",
     "Quella media ha un nome: expectancy, che in italiano possiamo tradurre come aspettativa.",
     "E ti dice una cosa molto concreta: quanto vale, in media, una singola operazione del tuo sistema. La misuriamo in R, così vale per qualsiasi conto."],
 2: ["Come si calcola? È più semplice di quanto sembra. Prendi quanto guadagni in media quando vinci, e lo moltiplichi per la percentuale di volte che vinci. Poi togli quanto perdi in media quando perdi, moltiplicato per la percentuale di volte che perdi.",
     "La W che vedi è il tuo win rate, la percentuale di operazioni vinte.",
     "Il guadagno medio è quanto porti a casa, in media, quando vinci, espresso in R.",
     "E la perdita media è quanto perdi, in media, quando perdi. Se rispetti sempre lo stop, è un R."],
 3: ["Facciamolo con un esempio, passo per passo.",
     "Mettiamo che tu vinca quarantacinque volte su cento.",
     "Quando vinci, guadagni in media uno virgola otto volte quello che rischi.",
     "E quando perdi, perdi esattamente quello che rischiavi, cioè un R.",
     "Prima parte: quarantacinque per cento di uno virgola otto fa zero virgola ottantuno. È quanto ti portano, in media, le vittorie.",
     "Seconda parte: cinquantacinque per cento di uno fa zero virgola cinquantacinque. È quanto ti costano, in media, le perdite.",
     "Zero virgola ottantuno meno zero virgola cinquantacinque fa zero virgola ventisei.",
     "Quindi ogni operazione di questo sistema vale, in media, un quarto abbondante di quello che rischi. È un vantaggio positivo."],
 4: ["Ma cosa vuol dire in pratica, in pip e in euro? Con uno stop di venticinque pip, zero virgola ventisei R sono circa sei pip e mezzo guadagnati in media per ogni operazione.",
     "Se apri zero virgola quattro lotti, ogni pip vale quattro euro: quindi in media guadagni circa ventisei euro a operazione.",
     "Su cento operazioni fanno circa seicentocinquanta pip, cioè intorno ai duemilaseicento euro.",
     "Attenzione però a una parola: in media. Non è una promessa. Le prossime cento operazioni potrebbero andare molto meglio o molto peggio, ed è proprio per questo che più avanti le simuleremo.",
     "La cosa più importante dell'expectancy è il segno. Se è positiva, hai un vantaggio da proteggere. Se è zero o negativa, nessuna gestione del rischio può salvarti: puoi solo perdere più lentamente."],
 5: ["Confrontiamo tre sistemi diversi, tutti con una perdita media di un R, e vediamo quale conviene davvero.",
     "Il sistema A vince solo trentacinque volte su cento. Sembra poco, vero? Però quando vince guadagna tre volte quello che rischia. Risultato: ogni operazione vale in media zero virgola quaranta R. È il migliore dei tre.",
     "Il sistema B vince sessanta volte su cento, ma quando vince guadagna poco, zero virgola otto R. Ogni operazione vale appena zero virgola zero otto R. Vince spesso, ma guadagna poco.",
     "E il sistema C vince metà delle volte, ma guadagna troppo poco quando vince. Risultato: meno zero virgola dieci R a operazione. Ti sembra un buon sistema perché vinci spesso, ma nel tempo ti svuota il conto."],
 6: ["Guarda questo grafico. Sono otto serie simulate di cento operazioni, tutte dello stesso sistema da più zero virgola ventisei R.",
     "La linea tratteggiata è la media che ci aspettiamo. Ma vedi quanto si allontanano le singole serie? Alcune finiscono addirittura in perdita, altre molto più in alto. Questo ti dice una cosa importante: anche con un vantaggio positivo, puoi attraversare periodi lunghi in cui sei sotto zero. È normale, e devi aspettartelo."],
 7: ["Prova tu. Il tuo sistema vince quaranta volte su cento. Quando vince guadagna in media due virgola cinque R, quando perde perde un R. Quanto vale in media ogni operazione?"],
 8: ["Vediamo. Quaranta per cento di due virgola cinque fa uno. Sessanta per cento di uno fa zero virgola sei. Uno meno zero virgola sei fa zero virgola quattro. Quindi ogni operazione vale in media zero virgola quaranta R: un ottimo vantaggio, pur vincendo meno della metà delle volte."],
 9: ["Ricapitoliamo questa lezione.",
     "L'expectancy ti dice quanto vale, in media, una tua operazione.",
     "Si calcola con tre numeri: quante volte vinci, quanto guadagni quando vinci, e quanto perdi quando perdi.",
     "Se è positiva hai un vantaggio. Se è zero o negativa, nessuna gestione del rischio può salvare il sistema."],
 10: ["Ricordati questa frase: la gestione del rischio protegge un vantaggio, ma non lo crea."],
}
PARLATO['2.2'] = {
 0: ["In questa lezione vediamo un altro indicatore molto usato, semplice da capire: il profit factor."],
 1: ["Il profit factor risponde a una domanda molto diretta: per ogni euro che perdi, quanti euro guadagni?",
     "Si calcola così: prendi tutto quello che hai guadagnato con le operazioni vinte, e lo dividi per tutto quello che hai perso con le operazioni perse.",
     "Per esempio, se in un mese hai guadagnato in totale tremila euro sui trade vinti, e perso duemila euro su quelli persi, il tuo profit factor è uno virgola cinque.",
     "La regola è semplice: se il profit factor è sopra uno, il sistema guadagna. Se è sotto uno, perde."],
 2: ["Proviamo con il nostro sistema di esempio, su cento operazioni.",
     "Quarantacinque operazioni vinte, ognuna da uno virgola otto R: in totale ottantuno R di guadagni.",
     "Cinquantacinque operazioni perse, ognuna da un R: in totale cinquantacinque R di perdite.",
     "Ottantuno diviso cinquantacinque fa circa uno virgola quarantasette. In parole semplici: per ogni euro che perdi, ne guadagni quasi uno e mezzo."],
 3: ["Ma come si legge questo numero? Ti do qualche riferimento. Sotto uno, il sistema perde soldi.",
     "Tra uno e uno virgola tre, il margine è sottile: basta un po' di spread o di commissioni in più per mangiarselo.",
     "Tra uno virgola tre e due siamo in una zona sana, tipica di molti sistemi che funzionano.",
     "E sopra due e mezzo, fai attenzione. Spesso vuol dire che hai fatto troppo poche operazioni, oppure che hai adattato troppo il sistema ai dati del passato. Un numero troppo bello, nel trading, è più un campanello d'allarme che una buona notizia."],
 4: ["Ma allora, che differenza c'è tra expectancy e profit factor?",
     "L'expectancy ti dice quanto vale in media ogni operazione, in R. Il sistema è in attivo se è sopra zero.",
     "Il profit factor ti dice quanto guadagni per ogni euro perso. Il sistema è in attivo se è sopra uno.",
     "In realtà sono due modi di guardare la stessa cosa: se uno è positivo, lo è anche l'altro. Usali insieme: l'expectancy ti dice quanto è grande il vantaggio, il profit factor te lo fa capire con un colpo d'occhio."],
 5: ["Prova tu. Hai fatto cento operazioni: quaranta vinte, ognuna da uno virgola cinque R, e sessanta perse da un R. Qual è il tuo profit factor?"],
 6: ["Facciamo i conti. Quaranta per uno virgola cinque fa sessanta R di guadagni. Sessanta per uno fa sessanta R di perdite. Sessanta diviso sessanta fa uno: sei esattamente in pari. E se aggiungi spread e commissioni, in realtà sei in perdita. Questo ti fa capire quanto possa ingannare guardare solo quante volte vinci."],
 7: ["Ricapitoliamo.",
     "Il profit factor è quello che guadagni diviso quello che perdi.",
     "Sopra uno il sistema è in attivo, e tra uno virgola tre e due sei in una zona sana.",
     "E se è troppo alto, prima di festeggiare controlla bene i dati."],
 8: ["Ricorda: un risultato troppo bello va sempre controllato due volte."],
}
PARLATO['2.3'] = {
 0: ["In questa lezione parliamo di un errore che fanno quasi tutti: giudicare un sistema dopo troppo poche operazioni."],
 1: ["Immagina di fare trenta operazioni e di vincerne venti. Sembra un sistema fantastico, vero? Il problema è che anche il caso, ogni tanto, produce serie così belle.",
     "La fortuna può regalarti serie bellissime e serie terribili, senza che il tuo sistema c'entri niente.",
     "E allora come facciamo a distinguere un vero vantaggio dalla fortuna? Servono abbastanza dati. Vediamo quanti."],
 2: ["Facciamo un esperimento mentale. Supponi che il tuo sistema, in realtà, vinca quarantacinque volte su cento. Cosa vedresti misurandolo?",
     "Con trenta operazioni, potresti misurare un win rate tra circa il ventisette e il sessantatré per cento. Cioè potresti pensare di avere un sistema scarso, o un sistema eccezionale, ed è sempre lo stesso sistema.",
     "Con cento operazioni l'incertezza scende a circa dieci punti, in più o in meno.",
     "E con quattrocento operazioni scende a circa cinque punti. Solo a quel punto il numero comincia a essere davvero affidabile."],
 3: ["E per l'expectancy, cioè per sapere se il sistema guadagna, è ancora più difficile. Prendiamo il nostro sistema, che in realtà vale più zero virgola ventisei R.",
     "Con trenta operazioni potresti misurare qualsiasi cosa tra meno zero virgola ventiquattro e più zero virgola settantasei. Cioè non sapresti nemmeno se il sistema guadagna o perde.",
     "Con cento operazioni, il risultato sta tra circa zero e più zero virgola cinquantatré. Siamo appena al limite.",
     "Solo con quattrocento operazioni sei ragionevolmente sicuro che il sistema sia davvero positivo. Per questo venti o trenta trade non dimostrano niente, né in un senso né nell'altro."],
 4: ["Quindi, in pratica, cosa fai? Prima di giudicare un sistema, raccogli almeno cento operazioni, e se puoi duecento o più.",
     "Non cambiare le regole dopo dieci perdite. Cambiale solo se scopri un errore nel modo in cui le applichi, non perché i risultati sono andati male per un po'.",
     "E per raccogliere i dati usa un conto demo, oppure un rischio minimo. I dati costano molto meno del capitale."],
 5: ["Prova tu. Hai fatto venti operazioni e ne hai vinte quattordici, il settanta per cento. Secondo te, questo dimostra che il tuo sistema funziona?"],
 6: ["Purtroppo no. Con sole venti operazioni l'incertezza è di circa venti punti, in più o in meno. Quel settanta per cento potrebbe nascondere un sistema che in realtà vince solo la metà delle volte, e magari hai avuto un periodo fortunato. Per dirlo con sicurezza servono molte più operazioni."],
 7: ["Ricapitoliamo.",
     "Con poche operazioni c'è tanto rumore, cioè tanta fortuna o sfortuna.",
     "Per giudicare un sistema servono almeno cento operazioni, meglio duecento o più.",
     "E le regole non si cambiano per una serie di perdite."],
 8: ["Ricordati: dieci operazioni sono una storia, mille operazioni sono una statistica."],
}
PARLATO['2.4'] = {
 0: ["In questa lezione parliamo dei costi nascosti del trading: spread, commissioni e slippage. Sembrano piccoli, ma possono mangiarsi tutto il tuo vantaggio."],
 1: ["Ci sono tre costi che riducono il risultato di ogni operazione.",
     "Il primo è lo spread, cioè la differenza tra il prezzo a cui compri e quello a cui vendi. Lo paghi nel momento stesso in cui entri.",
     "Il secondo sono le commissioni: una cifra fissa per ogni lotto, tipica dei conti che hanno uno spread molto basso.",
     "Il terzo è lo slippage: la differenza tra il prezzo che volevi e quello che ottieni davvero. Succede soprattutto durante le notizie, o quando scatta uno stop in un mercato veloce."],
 2: ["Per capire quanto pesano, conviene ragionare in pip.",
     "Il tuo guadagno medio netto per operazione, in pip, è il vantaggio del tuo sistema moltiplicato per lo stop, meno i costi.",
     "Per esempio, se il tuo sistema vale zero virgola ventisei R e usi uno stop di venticinque pip, guadagni in media circa sei pip e mezzo lordi a operazione.",
     "Lo stop è la distanza che usi normalmente, in pip.",
     "E i costi sono spread, commissioni e slippage, sempre in pip. Il punto chiave è questo: un costo fisso pesa poco se lo stop è largo, e pesa moltissimo se lo stop è stretto."],
 3: ["Guarda cosa succede con un costo di un pip e mezzo a operazione, sempre con lo stesso sistema.",
     "Con uno stop di cinquanta pip guadagni in media tredici pip lordi. Tolti i costi, ne restano undici e mezzo. I costi quasi non si sentono.",
     "Con uno stop di venticinque pip guadagni sei pip e mezzo lordi, e te ne restano cinque. I costi si sono già mangiati un quarto del guadagno.",
     "Con uno stop di dieci pip guadagni due pip e sei lordi, e te ne resta poco più di uno. Più di metà del vantaggio è sparita.",
     "E con uno stop di cinque pip guadagni uno virgola tre pip lordi, ma i costi sono uno e mezzo. Risultato: perdi soldi, pur avendo un sistema che sulla carta funziona."],
 4: ["Cosa ci insegna tutto questo? Tre cose pratiche.",
     "Prima: gli stop molto stretti sono molto sensibili ai costi. Per fare scalping servono costi bassissimi e un vantaggio forte.",
     "Seconda: misura i costi sul tuo conto reale, guardando i tuoi trade. Non fidarti solo delle pubblicità del broker.",
     "Terza: quando provi un sistema, includi sempre i costi. Altrimenti ti sembrerà più redditizio di quello che è."],
 5: ["Prova tu. Usi uno stop di venti pip, paghi due pip tra spread e commissioni, e il tuo sistema vale zero virgola trenta R prima dei costi. Quanti pip ti restano in tasca, in media, per ogni operazione?"],
 6: ["Vediamo. Zero virgola trenta per venti pip fa sei pip lordi. Togli i due pip di costi e te ne restano quattro. Un terzo del tuo guadagno se n'è andato in costi."],
 7: ["Ricapitoliamo.",
     "Spread, commissioni e slippage riducono il risultato di ogni operazione.",
     "Per capire quanto pesano, confrontali con il tuo stop e con il tuo guadagno medio in pip.",
     "E più lo stop è stretto, più i costi pesano: mettili sempre nei tuoi calcoli."],
 8: ["Ricordati: un vantaggio che non sopravvive ai costi non è un vantaggio."],
}
PARLATO['2.5'] = {
 0: ["Ultima lezione del secondo modulo. Parliamo del journal, cioè il diario delle tue operazioni, e di come usarlo per scoprire dove perdi davvero."],
 1: ["Perché tenere un journal? Perché la memoria ci inganna. Tendiamo a ricordare i trade belli e a dimenticare i piccoli errori.",
     "I numeri, invece, non hanno umore. Ti mostrano esattamente quando e dove perdi.",
     "E ti aiutano a trasformare una sensazione in un dato preciso. Invece di pensare oggi ho tradato male, scopri che hai infranto una regola specifica, sempre la stessa."],
 2: ["Cosa scrivere per ogni operazione? Ecco le cose essenziali.",
     "Data, ora e strumento: ti servono per scoprire in quali orari e su quali mercati perdi di più.",
     "Ingresso, stop e target: per sapere quanto rischiavi e quanto speravi di guadagnare.",
     "Il rischio, in euro e in percentuale: per controllare che tu stia rispettando il tuo piano.",
     "Il risultato, che ti permette di confrontare tutte le operazioni tra loro.",
     "E infine un campo per l'errore o la regola che hai infranto. Perché le perdite evitabili sono diverse da quelle normali, e sono quelle su cui puoi lavorare."],
 3: ["Ma la cosa più preziosa che il journal ti mostra è la differenza tra quello che avevi previsto e quello che hai fatto davvero.",
     "Facciamo un esempio. Avevi pianificato di comprare a uno virgola uno zero zero zero, con lo stop venticinque pip sotto e il target quarantacinque pip sopra. Il tuo piano prevedeva di guadagnare quarantacinque pip.",
     "Ma poi, durante l'operazione, hai avuto paura e hai chiuso a mano dopo diciotto pip.",
     "Hai lasciato sul tavolo ventisette pip. E se questo succede spesso, il tuo sistema sulla carta funziona, ma tu nella realtà guadagni molto meno."],
 4: ["Quanto costa davvero questa abitudine? Prendiamo quel trade: ventisette pip in meno rispetto al piano.",
     "Il nostro sistema guadagna in media circa sei pip e mezzo a operazione. Se chiudi in anticipo per paura anche solo una volta su cinque, perdi in media più di cinque pip a operazione. Cioè ti mangi più dell'ottanta per cento del tuo vantaggio.",
     "Capisci il punto? Il problema non è il sistema, è come lo esegui. E lo puoi scoprire solo se scrivi i numeri."],
 5: ["Per tenere un journal ti basta un foglio di calcolo, con una colonna per ogni informazione e due formule semplici per i totali.",
     "Oppure puoi usare il Riskly Journal, che ti dico chiaramente è un mio prodotto. Raccoglie le operazioni, calcola le statistiche e ti mostra, per esempio, in quali orari perdi di più.",
     "In realtà va bene qualsiasi strumento. L'importante è compilarlo ogni giorno, senza saltare le operazioni che non ti piacciono."],
 6: ["Ecco come appare una schermata del Riskly Journal, con dei dati dimostrativi. Vedrai che ci sono proprio le misure che hai imparato in questo modulo.",
     "Il win rate e il profit factor, calcolati su tutte le operazioni registrate.",
     "Il drawdown massimo, cioè la discesa più grande dal punto più alto, e la serie più lunga di vittorie e di perdite.",
     "E l'aspettativa per operazione, cioè l'expectancy che abbiamo visto all'inizio del modulo. Ricorda: con un foglio di calcolo ottieni gli stessi numeri."],
 7: ["Ricapitoliamo.",
     "Il journal trasforma le sensazioni in dati concreti.",
     "Per ogni operazione scrivi il rischio, quello che avevi previsto e quello che è successo davvero.",
     "E confrontare il previsto con il realizzato ti mostra gli errori di esecuzione, che spesso costano più di un sistema imperfetto. Con questo chiudiamo il secondo modulo."],
 8: ["Ricorda: quello che non misuri, non lo puoi migliorare."],
}
