PARLATO = {}
PARLATO['10.1'] = {
 0: ["Benvenuto nell'ultimo modulo. Adesso mettiamo insieme tutto quello che hai imparato e scriviamo il tuo piano di gestione del rischio. Una pagina sola, con i tuoi numeri."],
 1: ["Perché proprio una pagina?",
     "Perché un piano lungo non lo rilegge nessuno. Una pagina, invece, la puoi rileggere ogni mattina in un minuto, prima di aprire la piattaforma.",
     "Ogni riga deve essere un numero o una regola. Niente aggettivi, niente buoni propositi.",
     "E alla fine la firmi e ci metti la data. Non è una formalità: è un impegno che prendi con te stesso."],
 2: ["Il piano ha sette sezioni. Vediamole una per una.",
     "Il sistema: quante volte vinci, quanto guadagni rispetto a quanto perdi, quanto vale in media ogni operazione, e su quante operazioni hai misurato questi numeri.",
     "Il rischio: quanto rischi per operazione, quanto al massimo su tutte le operazioni aperte, e come calcoli il lotto.",
     "I limiti: la perdita massima della giornata, dopo quante perdite di fila ti fermi, e quante operazioni al massimo fai in un giorno.",
     "Il drawdown: a che punto riduci il rischio, e a che punto ti fermi del tutto.",
     "La gestione: quando sposti lo stop a pareggio, come usi il trailing, gli scaglioni e le eventuali aggiunte.",
     "La checklist: le domande che ti fai prima di ogni operazione.",
     "E la revisione: quando e come controlli il piano."],
 3: ["Ecco un esempio di piano compilato. Ricorda che sono valori di esempio, non un consiglio.",
     "Il sistema: vince il quarantacinque per cento delle volte, guadagna uno virgola otto volte quello che rischia, e ogni operazione vale in media zero virgola ventisei R, misurato su duecento operazioni.",
     "Rischio per operazione: l'uno per cento del conto attuale.",
     "Rischio massimo su tutte le operazioni aperte: il tre per cento.",
     "Stop giornaliero: meno tre per cento, oppure tre perdite di fila.",
     "Massimo tre operazioni al giorno.",
     "Se il conto scende di più del dieci per cento dal massimo, il rischio scende a mezzo punto per cento.",
     "E se scende di più del quindici per cento, mi fermo e rivedo tutto il sistema."],
 4: ["Prima di firmare, fai tre verifiche.",
     "Prima verifica: ogni numero è coerente con il calo del conto che riesci a sopportare? Usa la tabella della lezione tre punto cinque.",
     "Seconda verifica: il piano regge lo stress test? Prova a immaginare di vincere meno spesso e di pagare più costi.",
     "Terza verifica: riusciresti a rispettarlo anche nella tua giornata peggiore? Se la risposta è no, il piano è troppo ambizioso. Riducilo adesso, non quando sarà troppo tardi."],
 5: ["Adesso è il tuo turno, ed è il compito più importante di tutto il corso. Prenditi trenta minuti, compila le sette sezioni con i tuoi numeri, poi stampa il foglio, firmalo e scrivi la data."],
 6: ["Quando hai finito, controlla tre cose: che il calo del conto sia sopportabile per te, che il piano regga lo stress test, e che tu riesca a rispettarlo anche nel giorno peggiore. Credimi: un piano firmato vale più di cento buoni propositi."],
 7: ["Ricapitoliamo.",
     "Il piano sta in una pagina, e ogni riga è un numero o una regola.",
     "Le sezioni sono sette: sistema, rischio, limiti, drawdown, gestione, checklist e revisione.",
     "E prima di firmare verifica che sia coerente, che regga lo stress test e che tu possa rispettarlo nel giorno peggiore."],
 8: ["Ricordati: un piano che non hai scritto, semplicemente, non esiste."],
}
PARLATO['10.2'] = {
 0: ["Eccoci all'ultima lezione del corso. Parliamo di come tenere vivo il tuo piano nel tempo, con una revisione mensile, e di cosa portarti a casa da questo percorso."],
 1: ["Una volta al mese, fai una revisione.",
     "Sempre alla stessa ora e nello stesso modo: bastano quindici minuti, con i dati del tuo journal davanti.",
     "Guardi i numeri, non le sensazioni. Come è andato il sistema, quanto è sceso il conto, quante regole hai rispettato.",
     "E decidi solo cambiamenti piccoli e scritti. Mai dopo una singola giornata storta."],
 2: ["Ecco cosa guardare durante la revisione.",
     "Quanto vale in media ogni operazione: il sistema ha ancora un vantaggio?",
     "Il profit factor: quanto guadagni per ogni euro che perdi.",
     "Il calo massimo del mese: hai rispettato i tuoi limiti?",
     "La differenza tra quello che avevi previsto e quello che hai fatto: stai seguendo il piano?",
     "Quante volte hai rispettato la checklist: quanto sei stato disciplinato?",
     "E le operazioni fuori dal piano: quante sono, e quanto ti sono costate?"],
 3: ["E quando bisogna cambiare il piano?",
     "Se hai fatto poche operazioni, meno di cento, non cambiare il sistema. Quello che vedi è ancora rumore.",
     "Se il problema sono errori di esecuzione, lavora sulle regole e sulla disciplina, non sul sistema.",
     "Se dopo cento o più operazioni il sistema non ha più un vantaggio, fermati e rivedilo.",
     "E se il calo del conto supera la soglia che hai scritto, applica la regola che hai già deciso, senza discutere con te stesso."],
 4: ["Ti ricordi le tre domande della primissima lezione? Adesso hai le risposte.",
     "Quanto posso perdere al massimo su un'operazione? È il tuo rischio per operazione, scritto nel piano.",
     "Quante perdite di fila posso sopportare? Lo sai, perché hai calcolato come si accumulano le perdite con il tuo rischio.",
     "E quando mi fermo? Te lo dicono i tuoi limiti giornalieri e le tue soglie di drawdown."],
 5: ["Ecco cosa portarti a casa da questo corso.",
     "Il rischio viene prima della strategia: decide se sopravvivi e quanto soffri lungo la strada.",
     "Misura tutto e scrivilo in un journal, perché quello che non misuri non lo puoi migliorare.",
     "Dimensiona le posizioni con i numeri, non con l'umore della giornata.",
     "E scrivi le regole prima di operare, poi rivedile con calma, una volta al mese."],
 6: ["Prima di salutarci, ti ripeto un avviso importante. Questo corso è educativo, non è una consulenza finanziaria. Il trading con la leva è rischioso, e si può perdere tutto il capitale. I numeri e le simulazioni che hai visto sono esempi, e non garantiscono risultati futuri. Gli strumenti Riskly che ti ho mostrato sono prodotti miei, e non ti servono per applicare quello che hai imparato."],
 7: ["Grazie davvero per aver seguito il corso fino alla fine. Ti lascio con la frase da cui siamo partiti: non puoi controllare il mercato, ma puoi sempre controllare quanto rischi. In bocca al lupo."],
}
