PARLATO = {}
PARLATO['9.1'] = {
 0: ["Benvenuto nel nono modulo, quello delle tecniche avanzate. Partiamo da una cosa che tutti hanno sentito nominare, ma che pochi sfruttano bene: il compounding, cioè l'interesse composto."],
 1: ["Che cos'è il compounding? In parole semplici: i guadagni che fai entrano nel conto, e le operazioni successive si calcolano su un conto più grande.",
     "Così i guadagni producono altri guadagni, e la crescita accelera nel tempo. Non è una linea dritta, è una curva che sale sempre più in fretta.",
     "E la cosa bella è che se rischi una percentuale fissa del conto, come abbiamo visto nel modulo quattro, il compounding funziona da solo. L'uno per cento di un conto più grande sono semplicemente più euro.",
     "Vediamo con un esempio quanto può fare la differenza."],
 2: ["Prendiamo un conto da diecimila euro. La linea tratteggiata guadagna sempre duecento euro al mese, fissi: dopo tre anni arriva a diciassettemiladuecento euro.",
     "La linea verde guadagna invece il due per cento al mese, ma sul conto del momento. Dopo un anno è a circa dodicimilaseicentottanta euro, dopo due anni a sedicimila, e dopo tre anni supera i ventimila. Il punto di partenza è lo stesso, il primo mese è uguale: la differenza la fa il tempo."],
 3: ["Ecco gli stessi numeri in tabella, così li vedi meglio.",
     "Dopo un anno la differenza è piccola: circa duecentottanta euro.",
     "Dopo due anni è già di quasi milletrecento euro.",
     "E dopo tre anni supera i tremila euro. Il compounding premia soprattutto la costanza e il tempo, non il singolo mese spettacolare."],
 4: ["Ma attenzione: il compounding funziona anche al contrario.",
     "Se guadagni il dieci per cento e poi perdi il dieci per cento, passi da diecimila a undicimila, e poi a novemilanovecento. Sei sotto dell'uno per cento, anche se i numeri sembravano pari.",
     "Se guadagni il venti e poi perdi il venti, passi da diecimila a dodicimila, e poi a novemilaseicento. Sei sotto del quattro per cento.",
     "Questo ci insegna una cosa importante: più il conto sale e scende, più il compounding lavora contro di te. Un rendimento stabile cresce di più di uno che in media è uguale ma va su e giù."],
 5: ["Quindi, quali sono i benefici, e come proteggerli?",
     "Il conto cresce sempre più in fretta, senza che tu debba aumentare la percentuale di rischio.",
     "Quando perdi, le posizioni si riducono da sole: il compounding frena anche le discese.",
     "Per proteggerlo, evita i grandi cali del conto. Meno oscillazioni vuol dire una curva composta più alta.",
     "E decidi prima quanto prelevi dai guadagni. Ogni prelievo rallenta la crescita. È una scelta legittima, ma va fatta a mente fredda."],
 6: ["Prova tu. Hai diecimila euro e guadagni il tre per cento al mese per dodici mesi. Quanto ottieni guadagnando sempre la stessa cifra fissa, e quanto con il compounding?"],
 7: ["Vediamo. Con la cifra fissa, trecento euro al mese per dodici mesi, arrivi a tredicimilaseicento euro. Con il compounding arrivi a circa quattordicimiladuecentocinquanta euro. Sono circa seicentocinquanta euro in più in un anno, solo perché i guadagni hanno lavorato a loro volta."],
 8: ["Ricapitoliamo.",
     "Il compounding fa lavorare i guadagni per produrre altri guadagni.",
     "Se rischi una percentuale fissa del conto, funziona da solo.",
     "E le oscillazioni lo frenano: proteggere il conto dai grandi cali è il modo migliore per farlo crescere."],
 9: ["Ricordati: il compounding non premia chi corre. Premia chi resta in gioco."],
}
PARLATO['9.2'] = {
 0: ["In questa lezione vediamo il trailing stop in tutte le sue forme. Nel modulo otto abbiamo visto quello a gradini, ora li vediamo tutti."],
 1: ["Perché usare un trailing stop? Per tre motivi.",
     "Primo: blocca una parte del guadagno mentre l'operazione va avanti, senza dover indovinare dove si fermerà il prezzo.",
     "Secondo: lascia correre le operazioni migliori. Non c'è un target fisso che ti fa uscire troppo presto.",
     "Terzo: toglie la decisione a caldo. È la regola a spostare lo stop, non le tue emozioni."],
 2: ["Ecco i cinque tipi principali di trailing.",
     "A distanza fissa: lo stop resta sempre a un certo numero di pip sotto il prezzo più alto raggiunto. Per esempio venti pip.",
     "A gradini: lo stop sale a scatti. Per esempio, a più venticinque pip va a pareggio, a più cinquanta va a più venticinque, e così via.",
     "Strutturale: lo stop segue il grafico, e si sposta sotto ogni nuovo minimo crescente.",
     "Con l'ATR: la distanza dello stop dipende da quanto si muove il mercato, per esempio due volte l'ATR.",
     "E temporale: se dopo un certo tempo l'operazione non si è mossa, esci. Non segue il prezzo, ma limita il tempo in cui rimani esposto."],
 3: ["Vediamo un esempio con il trailing a distanza fissa di venti pip. Entri a uno virgola uno zero zero zero, con lo stop iniziale venticinque pip sotto.",
     "Il prezzo sale a uno virgola uno zero tre zero. Lo stop lo segue a venti pip di distanza, cioè a più dieci pip.",
     "Il prezzo continua a salire fino a uno virgola uno zero sei zero. Lo stop sale a uno virgola uno zero quattro zero, cioè più quaranta pip.",
     "Poi il prezzo torna indietro e tocca lo stop: esci con quaranta pip di guadagno.",
     "Il movimento massimo era di sessanta pip, e tu ne hai portati a casa quaranta, senza dover prendere nessuna decisione sotto pressione."],
 4: ["Ogni tipo ha pregi e difetti.",
     "Quello a distanza fissa è semplicissimo, ma non tiene conto di quanto si muove il mercato.",
     "Quello a gradini protegge per passi, ma tra un gradino e l'altro lascia indietro qualche pip.",
     "Quello strutturale segue il mercato in modo naturale, ma devi saper leggere il grafico.",
     "Quello con l'ATR si adatta alla volatilità, ma diventa più largo proprio quando il mercato è agitato.",
     "E quello temporale libera capitale e attenzione, ma ogni tanto chiude un'operazione proprio un attimo prima che parta. Non esiste il migliore in assoluto: si sceglie e si misura."],
 5: ["E ora gli errori più comuni.",
     "Il primo è un trailing troppo stretto: esci al primo piccolo ritracciamento, anche se l'operazione era ancora valida.",
     "Il secondo è cambiare tipo di trailing a operazione aperta. È una decisione presa a caldo, travestita da regola.",
     "Il terzo è non misurarne l'effetto. Confronta nel journal i risultati con e senza trailing, su almeno cento operazioni."],
 6: ["Prova tu. Sei entrato a uno virgola due zero zero zero, con un trailing a trenta pip dal massimo. Il prezzo ha toccato uno virgola due zero sette cinque. Dove si trova adesso lo stop, e quanti pip hai già al sicuro?"],
 7: ["Lo stop è trenta pip sotto il massimo, cioè a uno virgola due zero quattro cinque. Quindi hai già quarantacinque pip di guadagno al sicuro, qualunque cosa succeda."],
 8: ["Ricapitoliamo.",
     "Ci sono cinque tipi di trailing: a distanza fissa, a gradini, strutturale, con l'ATR e temporale.",
     "Il trailing blocca una parte del guadagno senza dover indovinare il massimo.",
     "Sceglilo prima di entrare, e misura i risultati nel journal."],
 9: ["Ricordati: il trailing non cerca di prendere il massimo. Cerca di non restituire tutto."],
}
PARLATO['9.3'] = {
 0: ["In questa lezione parliamo di come entrare a scaglioni, cioè dividere l'ingresso su più livelli di prezzo."],
 1: ["L'idea è semplice: invece di entrare con tutta la posizione a un solo prezzo, la dividi in più parti. Per esempio piazzi tre ordini a tre livelli diversi.",
     "Lo stop però è uno solo per tutti gli scaglioni: è il livello in cui la tua idea diventa sbagliata.",
     "E il rischio lo calcoli come se entrassero tutti e tre, perché è il caso peggiore."],
 2: ["Vediamolo sul grafico.",
     "Piazzi tre ordini da zero virgola due lotti: il primo a uno virgola uno zero zero zero, il secondo a uno virgola zero nove nove zero, il terzo a uno virgola zero nove otto zero. Lo stop è uno solo, a uno virgola zero nove sei zero.",
     "Il prezzo scende e prende il primo ordine. Quel primo scaglione è a quaranta pip dallo stop.",
     "Il prezzo continua a scendere e prende il secondo, che è a trenta pip dallo stop.",
     "E poi il terzo, a venti pip dallo stop.",
     "Il tuo prezzo medio di ingresso è uno virgola zero nove nove zero. E il rischio totale? Zero virgola due lotti per dieci euro, moltiplicato per quaranta più trenta più venti pip: centottanta euro."],
 3: ["Proprio per questo il rischio va deciso prima. Supponi di voler rischiare al massimo l'uno per cento di diecimila euro, cioè cento euro.",
     "Sommi i pip di rischio di tutti e tre gli scaglioni: quaranta più trenta più venti fa novanta pip.",
     "Allora i lotti per ogni scaglione sono cento diviso novanta per dieci: circa zero virgola undici lotti.",
     "Se entra solo il primo scaglione, rischi appena quarantaquattro euro.",
     "E se entrano tutti e tre, perdi al massimo cento euro. Mai di più, qualunque cosa succeda."],
 4: ["Attenzione a non confondere gli scaglioni con il mediare in perdita.",
     "Gli scaglioni pianificati hanno i livelli decisi prima, uno stop unico che non si sposta, e un rischio totale calcolato in anticipo.",
     "Mediare in perdita significa aggiungere solo perché stai perdendo, spesso spostando o togliendo lo stop. E il rischio cresce senza nessun limite."],
 5: ["Vediamo benefici e limiti.",
     "Primo beneficio: ottieni un prezzo medio migliore se il prezzo ritraccia prima di partire.",
     "Secondo beneficio: hai meno ansia di dover indovinare il punto esatto di ingresso.",
     "Terzo beneficio: se entra solo una parte, stai rischiando meno.",
     "Primo limite: nelle operazioni migliori spesso entra solo il primo scaglione, perché il prezzo parte subito, e quindi guadagni meno.",
     "Secondo limite: l'ultimo scaglione entra spesso proprio quando l'operazione sta andando male. Per questo il rischio va sempre calcolato sul caso peggiore."],
 6: ["Prova tu. Hai due scaglioni da zero virgola uno lotti: uno a uno virgola due zero zero zero e uno a uno virgola uno nove otto zero. Lo stop comune è a uno virgola uno nove cinque zero, e ogni pip vale dieci euro per lotto. Qual è il rischio totale?"],
 7: ["Vediamo. Il primo scaglione è a cinquanta pip dallo stop, il secondo a trenta. Con zero virgola uno lotti un pip vale un euro. Quindi cinquanta euro più trenta euro: ottanta euro di rischio totale."],
 8: ["Ricapitoliamo.",
     "Entrare a scaglioni vuol dire dividere l'ingresso su più livelli, con un unico stop.",
     "Il rischio si calcola sempre come se entrassero tutti gli scaglioni.",
     "E si pianifica prima: non ha niente a che fare con il mediare in perdita."],
 9: ["Ricordati: entrare a scaglioni cambia il tuo prezzo medio, ma non deve mai cambiare il tuo rischio massimo."],
}
PARLATO['9.4'] = {
 0: ["In questa lezione vediamo nel dettaglio uno schema molto usato, anche con i bot: le uscite a scaglioni con lo stop a pareggio sulla parte restante."],
 1: ["Ecco come funziona lo schema tipico.",
     "Dividi la posizione in più parti uguali. Per esempio tre parti da zero virgola due lotti.",
     "Metti obiettivi vicini sulle prime parti: per esempio più dieci e più venti pip.",
     "Quando arriva il primo obiettivo, sposti lo stop a pareggio su tutto il resto. Da quel momento l'operazione non può più diventare una perdita piena.",
     "E l'ultima parte la lasci correre, con un trailing o con un obiettivo lontano."],
 2: ["Vediamo i diversi scenari, con zero virgola sei lotti e lo stop a venticinque pip.",
     "Se lo stop scatta subito, perdi su tutta la posizione: centocinquanta euro.",
     "Se prendi il primo obiettivo e poi il resto torna a pareggio, guadagni venti euro.",
     "Se prendi il primo e il secondo obiettivo, e l'ultima parte torna a pareggio, guadagni sessanta euro.",
     "E se l'ultima parte corre fino a più cinquanta pip, guadagni centosessanta euro."],
 3: ["Ora ti spiego una cosa che quasi nessuno dice.",
     "Pensa allo scenario più comune: prendi il primo obiettivo e poi il resto torna a pareggio. Guadagni venti euro. Ma quando va male perdi centocinquanta euro. Per andare semplicemente in pari, il primo obiettivo deve essere raggiunto circa ottantotto volte su cento.",
     "Capisci il punto? Obiettivi molto vicini ti danno tante piccole vittorie e una bella sensazione, ma richiedono una percentuale di successo altissima. Solo il tuo journal ti può dire se il tuo sistema ci arriva davvero."],
 4: ["Vediamo benefici e attenzioni di questo schema.",
     "Primo beneficio: incassi presto, e la giornata non è quasi mai a zero.",
     "Secondo beneficio: dopo il primo obiettivo, l'operazione non può più perdere tutto.",
     "Terzo beneficio: l'ultima parte ti tiene dentro i movimenti grandi.",
     "Prima attenzione: un primo obiettivo troppo vicino richiede un win rate altissimo.",
     "Seconda attenzione: spostare lo stop a pareggio troppo presto chiude operazioni che sarebbero arrivate lontano. Per questo conviene registrare nel journal i lotti e l'esito di ogni scaglione, così vedi quale parte del tuo schema rende davvero. Il Riskly Journal lo fa, ed è un mio prodotto, ma anche un foglio di calcolo va benissimo."],
 5: ["Prova tu. Hai tre parti da zero virgola uno lotti. Il primo obiettivo è a più quindici pip, il secondo a più trenta. La terza parte viene chiusa a pareggio dopo il secondo obiettivo. Quanto hai guadagnato?"],
 6: ["Vediamo. La prima parte guadagna quindici euro, la seconda trenta euro, la terza zero. In totale quarantacinque euro."],
 7: ["Ricapitoliamo.",
     "Lo schema è: parti uguali, obiettivi vicini, pareggio sul resto e un'ultima parte che corre.",
     "Calcola sempre ogni scenario, in pip e in euro.",
     "E ricordati che obiettivi troppo vicini richiedono di vincere quasi sempre: misuralo prima di fidarti."],
 8: ["Ricordati: tante piccole vittorie valgono qualcosa solo se le perdite restano rare."],
}
PARLATO['9.5'] = {
 0: ["In questa lezione parliamo di come ridurre il rischio di un'operazione già aperta. Si chiama mitigazione. E vediamo anche cosa non devi fare mai."],
 1: ["Prima di tutto, mitigare il rischio non vuol dire scappare dall'operazione.",
     "Ridurre il rischio di una posizione aperta è legittimo, a una condizione: che tu segua una regola decisa prima.",
     "Invece allargare lo stop o aggiungere a un'operazione in perdita non è mitigare. È esattamente il contrario: aumenta il rischio.",
     "E ricordati che ogni tecnica di mitigazione ha un costo: di solito riduce anche il guadagno possibile."],
 2: ["Ecco le tecniche principali.",
     "La chiusura parziale: chiudi una parte della posizione. Riduci l'esposizione, ma rinunci a una parte del guadagno futuro.",
     "Lo stop a pareggio: elimini il rischio di una perdita piena, ma alcune operazioni chiuderanno a zero.",
     "L'uscita quando l'idea non è più valida: se il motivo per cui sei entrato sparisce prima dello stop, esci. Perdi meno, ma ogni tanto un'operazione sarebbe ripartita.",
     "Lo stop temporale: esci se dopo un certo tempo non succede niente. Riduci il tempo in cui sei esposto, ma perdi qualche movimento arrivato tardi.",
     "E ridurre la posizione prima delle notizie importanti: eviti il rischio di salti di prezzo improvvisi, ma rinunci ai movimenti delle notizie."],
 3: ["Facciamo un esempio di chiusura parziale. Hai zero virgola quattro lotti con lo stop a venticinque pip: stai rischiando cento euro.",
     "Il prezzo va a più quindici pip, e tu chiudi metà della posizione. Incassi trenta euro.",
     "L'altra metà, zero virgola due lotti con lo stop dove era, rischia ancora cinquanta euro.",
     "Quindi, nel caso peggiore, se il prezzo torna fino allo stop, l'operazione chiude a meno venti euro.",
     "Prima rischiavi cento euro, adesso al massimo venti. Il prezzo da pagare? Se l'operazione arriva al target, guadagni solo sulla metà della posizione."],
 4: ["Ora un esempio di uscita quando l'idea non è più valida. Sei entrato in acquisto perché il prezzo rimbalzava su un supporto, con lo stop a venticinque pip.",
     "Una candela chiude sotto il supporto, e sei a meno dieci pip. Il motivo per cui eri entrato non esiste più.",
     "Esci subito: meno dieci pip invece di meno venticinque.",
     "Con zero virgola quattro lotti perdi quaranta euro invece di cento. Ma attenzione: la condizione per uscire deve essere scritta nel piano, non decisa sul momento per paura."],
 5: ["Ecco le regole per farlo bene.",
     "Scrivi prima quale tecnica usi e quando. Per esempio: chiudo metà della posizione a più quindici pip.",
     "Non allargare mai lo stop e non aggiungere mai in perdita: queste non sono tecniche di mitigazione.",
     "E misura nel journal quanto ti costa e quanto ti salva ogni tecnica, su almeno cento operazioni."],
 6: ["Prova tu. Hai zero virgola sei lotti con lo stop a venticinque pip. Il prezzo è a più venti pip e chiudi un terzo della posizione. Qual è ora il caso peggiore?"],
 7: ["Vediamo. Chiudendo zero virgola due lotti a più venti pip incassi quaranta euro. I restanti zero virgola quattro lotti rischiano ancora cento euro. Quindi il caso peggiore è meno sessanta euro, invece dei meno centocinquanta di prima."],
 8: ["Ricapitoliamo.",
     "Mitigare significa ridurre il rischio seguendo una regola decisa prima.",
     "Le tecniche principali sono chiusure parziali, pareggio, uscita quando l'idea non vale più, stop temporale e attenzione alle notizie.",
     "Allargare lo stop o aggiungere in perdita non è mitigare: è il contrario."],
 9: ["Ricordati: il rischio si riduce con una regola, non con la paura."],
}
PARLATO['9.6'] = {
 0: ["Ultima lezione delle tecniche avanzate. Parliamo di hedging, cioè la copertura. Ti spiego cosa fa davvero, e soprattutto cosa non fa."],
 1: ["Fare hedging significa aprire un'operazione opposta a quella che hai già. Sullo stesso strumento, oppure su uno che si muove in modo simile.",
     "Le due operazioni si compensano, e il risultato totale smette di muoversi.",
     "Si usa per congelare un'esposizione, non per cancellare una perdita. Questa è la cosa più importante da capire."],
 2: ["Vediamo un esempio sul grafico.",
     "Compri zero virgola quattro lotti a uno virgola uno zero zero zero.",
     "Il prezzo scende di venti pip. Invece di chiudere, apri una vendita da zero virgola quattro lotti a uno virgola zero nove otto zero. In quel momento sei in perdita di ottanta euro.",
     "Ora il prezzo può salire o scendere quanto vuole.",
     "Il risultato totale resta fermo a meno ottanta euro, più lo spread e i costi per tenere aperte le posizioni. La perdita non è sparita: è solo congelata."],
 3: ["Confrontiamo la copertura con la semplice chiusura.",
     "Se chiudi a meno venti pip, perdi ottanta euro e basta. Nessun costo in più, nessuna decisione ancora da prendere.",
     "Se copri, perdi comunque gli stessi ottanta euro, ma in più paghi spread e costi notturni. E prima o poi devi decidere quale delle due operazioni chiudere per prima. In pratica è la stessa decisione che avresti dovuto prendere subito, solo rimandata."],
 4: ["Prima di usarlo, conosci bene le regole.",
     "Sui conti MetaTrader cinque di tipo netting non puoi avere due operazioni opposte: la seconda riduce semplicemente la prima.",
     "Sui conti di tipo hedging e su MetaTrader quattro puoi tenerle entrambe, ma paghi spread e costi notturni su tutte e due.",
     "Con i broker americani c'è una regola che vieta proprio di tenere operazioni opposte sullo stesso strumento.",
     "E molte prop firm vietano l'hedging, soprattutto tra conti diversi. Leggi sempre il regolamento."],
 5: ["Allora, quando ha senso fare hedging?",
     "Ha senso per proteggere un portafoglio di lungo periodo. Per esempio, hai delle azioni che non vuoi vendere, e le copri temporaneamente con un indice durante un periodo agitato.",
     "Ha senso anche per coprire un'esposizione in valuta. Per esempio, se incassi in dollari ma i tuoi conti sono in euro.",
     "Non ha senso, invece, per evitare di prendere lo stop in un'operazione di breve periodo. In quel caso è solo un modo di non accettare la perdita, pagando pure di più."],
 6: ["Prova tu. Compri zero virgola due lotti a uno virgola due cinque zero zero. Il prezzo scende a uno virgola due quattro sei zero e apri una vendita da zero virgola due lotti. Poi il prezzo scende ancora fino a uno virgola due quattro zero zero. Qual è il risultato totale?"],
 7: ["Vediamo. L'acquisto perde cento pip, cioè duecento euro. La vendita guadagna sessanta pip, cioè centoventi euro. In totale sei a meno ottanta euro: esattamente come al momento della copertura. E in più ci sono i costi."],
 8: ["Ricapitoliamo.",
     "L'hedging congela un'esposizione, ma non cancella la perdita.",
     "Sullo stesso strumento equivale a chiudere, solo con più costi e una decisione rimandata.",
     "Ha senso per i portafogli e per le valute, e va sempre controllato con le regole del broker e della prop firm. Con questo chiudiamo il modulo sulle tecniche avanzate: resta solo il tuo piano."],
 9: ["Ricordati: una perdita coperta è comunque una perdita."],
}
