PARLATO = {}
PARLATO['7.1'] = {
 0: ["Benvenuto nel settimo modulo, dedicato alle prop firm. Se stai pensando di fare una sfida per ottenere un conto finanziato, qui trovi le cose che fanno davvero la differenza. Partiamo dalle regole tipiche."],
 1: ["Prima di tutto una precisazione importante. Le regole cambiano da una prop firm all'altra, e cambiano anche nel tempo. Quelle che vedrai qui sono solo esempi.",
     "Prima di pagare, e prima di operare, leggi sempre il regolamento completo e aggiornato della firma che hai scelto.",
     "E questo corso non ti dice quale prop firm scegliere: ti insegna a gestire il rischio dentro le loro regole."],
 2: ["Ecco i limiti più comuni, con valori tipici.",
     "L'obiettivo di profitto: di solito tra l'otto e il dieci per cento del conto. Se non lo raggiungi, la fase non è superata.",
     "La perdita massima giornaliera: di solito tra il quattro e il cinque per cento. Se la superi, anche solo per un attimo, il conto viene chiuso.",
     "La perdita massima totale: di solito tra l'otto e il dodici per cento. Anche qui, se la superi, è finita.",
     "I giorni minimi di trading: spesso tre, quattro o cinque giorni in cui devi aprire almeno un'operazione.",
     "E a volte c'è un tempo massimo, per esempio trenta giorni, mentre altre firme non lo hanno."],
 3: ["La perdita massima totale può essere di due tipi, ed è importante capire la differenza.",
     "Statica: il limite resta sempre fermo. Per esempio, su un conto da centomila euro con limite del dieci per cento, non puoi mai scendere sotto i novantamila.",
     "Trailing: il limite sale insieme ai tuoi massimi. Se il conto arriva a centoottomila, il limite sale a novantasettemiladuecento.",
     "E questa differenza cambia completamente il modo di gestire il rischio. La versione trailing è molto più severa, e la vediamo meglio nella lezione sette punto tre."],
 4: ["Vediamo un esempio concreto di quanto sia vicino il limite giornaliero. Hai un conto da centomila euro.",
     "Il limite giornaliero è il cinque per cento, cioè cinquemila euro.",
     "Rischi l'uno per cento a operazione, cioè mille euro.",
     "Bastano circa cinque perdite piene nella stessa giornata per avvicinarti al limite.",
     "Cinque o sei stop di fila in un giorno sono rari, ma possono capitare. E se capitano, la sfida è finita. Il tuo piano non deve mai lasciarti arrivare così vicino."],
 5: ["Prova tu. Il limite giornaliero della tua prop firm è il quattro per cento, e tu rischi mezzo punto per cento a operazione. Quante perdite piene ti servirebbero per toccare il limite?"],
 6: ["Quattro diviso zero virgola cinque fa otto. Ti servirebbero otto perdite piene nella stessa giornata: un margine molto ampio, ed è esattamente quello che vuoi."],
 7: ["Ricapitoliamo.",
     "Le regole cambiano da firma a firma: leggi sempre il regolamento aggiornato.",
     "I limiti che contano di più sono la perdita giornaliera e la perdita totale.",
     "E la differenza tra limite statico e trailing cambia tutto il modo di gestire il rischio."],
 8: ["Ricordati: alla prop firm non devi dimostrare di essere bravo. Devi dimostrare di non sforare mai i limiti."],
}
PARLATO['7.2'] = {
 0: ["In questa lezione vediamo quanto rischiare quando fai una sfida con una prop firm. Perché qui il limite non lo decidi tu."],
 1: ["Cosa cambia rispetto al tuo conto personale?",
     "Prima di tutto, il limite non lo scegli tu. E se lo superi, non perdi solo dei soldi: perdi la sfida, e il costo che hai pagato per farla.",
     "Per questo il tuo limite personale deve stare ben dentro il loro, con un margine di sicurezza.",
     "E se la sfida ha un tempo massimo, non devi farti prendere dalla fretta. Lo vediamo tra poco."],
 2: ["Una regola semplice e prudente è questa: il tuo limite personale deve essere circa la metà di quello della prop firm.",
     "Se la firma ti permette di perdere il cinque per cento in un giorno, tu ti fermi al due e mezzo.",
     "E se la perdita massima totale è il dieci per cento, quando arrivi al cinque ti fermi, rivedi il piano e riduci il rischio. Quel margine ti protegge da slippage, da aperture improvvise del mercato e dalle operazioni ancora aperte."],
 3: ["Ora la parte più interessante. Ho simulato una sfida con obiettivo più dieci per cento e perdita massima del dieci per cento, usando il nostro sistema di esempio. Vediamo cosa succede cambiando il rischio per operazione.",
     "Rischiando un quarto di punto per cento, la sfida praticamente non fallisce mai, ma servono in media circa centotrentotto operazioni per arrivare all'obiettivo.",
     "Rischiando mezzo punto per cento, fallisci solo tre volte su mille, e servono circa sessantacinque operazioni.",
     "Rischiando l'uno per cento, fallisci circa una volta su venti, e servono circa ventotto operazioni.",
     "Rischiando il due per cento, fallisci quasi una volta su cinque, anche se ti bastano otto operazioni.",
     "E rischiando il tre per cento, fallisci più di una volta su quattro. Vedi il punto? Più rischi, prima arrivi al traguardo, ma molto più spesso perdi la sfida."],
 4: ["Quindi qual è la lezione? Rischiare tanto non ti fa risparmiare tempo: ti fa scommettere sulla sfida.",
     "Un rischio basso è più lento, ma molto più sicuro. A una condizione: che il tuo sistema abbia davvero un vantaggio.",
     "E se la sfida ha un tempo massimo, scegli un rischio intermedio, e riducilo appena hai accumulato un po' di profitto."],
 5: ["Prova tu. Fai una sfida su un conto da cinquantamila euro. Il limite giornaliero della firma è il cinque per cento, tu rischi mezzo punto a operazione, e il tuo limite personale è il due e mezzo per cento. Dopo quante perdite piene ti fermi?"],
 6: ["Due e mezzo diviso zero virgola cinque fa cinque. Dopo cinque perdite piene ti fermi per la giornata, e hai ancora metà del margine della prop firm a disposizione. Proprio come deve essere."],
 7: ["Ricapitoliamo.",
     "Il tuo limite personale deve stare dentro quello della prop firm, con un buon margine.",
     "Rischiare tanto rende la sfida più veloce, ma molto più fragile.",
     "Rischiare poco è più lento, ma molto più sicuro, se il tuo vantaggio è reale."],
 8: ["Ricordati: la fretta è il costo nascosto di ogni sfida."],
}
PARLATO['7.3'] = {
 0: ["In questa lezione vediamo le regole delle prop firm meno intuitive, quelle che fanno perdere la sfida senza nemmeno accorgersene. A cominciare dal trailing drawdown."],
 1: ["Guarda questo grafico. La linea verde è il tuo conto. La linea puntinata in basso è un limite statico: il capitale iniziale meno il dieci per cento, sempre fermo.",
     "La linea rossa tratteggiata, invece, è il limite trailing: sta sempre al dieci per cento sotto il punto più alto che il conto ha raggiunto. Ogni volta che il conto fa un nuovo massimo, il limite sale. E non scende mai più.",
     "Il risultato? Anche dopo una bella crescita, lo spazio che hai per sbagliare resta sempre del dieci per cento dal tuo massimo, non dal capitale iniziale. I guadagni non ti danno più margine."],
 2: ["Facciamo un esempio con i numeri. Parti da centomila euro, con un limite trailing del dieci per cento.",
     "All'inizio, il limite è novantamila euro.",
     "Le cose vanno bene e il conto sale a centoottomila euro.",
     "Il limite sale con lui: adesso è novantasettemiladuecento euro.",
     "Quindi il tuo spazio per sbagliare è sempre diecimilaottocento euro, cioè il dieci per cento del tuo massimo.",
     "E attenzione a un dettaglio: con alcune firme il massimo si calcola anche sulle operazioni ancora aperte. Quindi se un'operazione va molto in guadagno e poi torna indietro, il limite è già salito, e ti ritrovi con molto meno spazio. Ogni nuovo massimo, anche solo momentaneo, alza il pavimento."],
 3: ["Ci sono altre regole da leggere con attenzione.",
     "La regola di coerenza: alcune firme non vogliono che una singola giornata faccia la maggior parte del profitto totale. Se fai tutto in un giorno, potresti non superare la fase.",
     "Le notizie: alcune firme vietano o limitano le operazioni nei minuti intorno ai dati economici importanti.",
     "Il fine settimana e la notte: alcune vietano di tenere operazioni aperte durante il weekend.",
     "E gli strumenti e i robot: alcune limitano certi strumenti, o l'uso di sistemi automatici. Tutto questo cambia da firma a firma, quindi leggi sempre il regolamento."],
 4: ["Allora, cosa fare prima di iniziare una sfida?",
     "Leggi le regole intere, non solo un riassunto. Scrivi i limiti della firma nel tuo piano. E prova prima tutto in un conto demo.",
     "E cosa evitare? Fidarti di un riassunto trovato online, scoprire una regola solo dopo averla violata, e aumentare il rischio per recuperare tempo. Una sfida persa per una regola non letta è la più evitabile di tutte."],
 5: ["Prova tu. Hai un conto da cinquantamila euro con un limite trailing dell'otto per cento. Il conto è arrivato al massimo a cinquantaquattromila euro. Dove si trova adesso il limite?"],
 6: ["Vediamo. L'otto per cento sotto cinquantaquattromila è quarantanovemilaseicentottanta euro. Hai notato? Il limite adesso è sopra il capitale iniziale. Se il conto tornasse a cinquantamila, pur essendo in pari rispetto all'inizio, ti resterebbero solo trecentoventi euro di margine."],
 7: ["Ricapitoliamo.",
     "Il limite trailing sale insieme ai tuoi massimi, e non scende mai.",
     "Leggi bene le regole su coerenza, notizie, weekend e strumenti.",
     "E scrivi i limiti della tua prop firm direttamente nel tuo piano."],
 8: ["Ricordati: la regola che non hai letto è proprio quella che ti farà perdere la sfida."],
}
PARLATO['7.4'] = {
 0: ["Ultima lezione sulle prop firm. Parliamo di cosa succede quando operi su più conti contemporaneamente, perché il rischio si somma anche se non lo vedi."],
 1: ["Perché si usano più conti? Ci sono diversi motivi.",
     "Per diversificare, per esempio tra prop firm diverse, invece di mettere tutto su una sola sfida.",
     "Per avere conti di dimensioni diverse, uno più piccolo e uno più grande.",
     "Oppure per separare strategie diverse, ognuna con il suo piano."],
 2: ["Il rischio nascosto arriva quando fai la stessa operazione su più conti.",
     "Mettiamo che tu abbia tre conti da centomila euro e apra la stessa operazione su tutti e tre, rischiando l'uno per cento su ciascuno. Se l'operazione va male, perdi su tutti e tre insieme: tremila euro in un colpo solo. È come avere un solo conto e rischiare il tre per cento.",
     "Se invece su ogni conto fai operazioni diverse, le perdite arrivano in momenti diversi e il rischio è più distribuito. Ma richiede molto più lavoro."],
 3: ["E qui c'è un punto molto importante: molte prop firm limitano o vietano di copiare le stesse operazioni su più conti. Non è solo una questione di rischio, è una questione di regolamento.",
     "Quindi verifica sempre cosa è permesso, prima di farlo. Altrimenti rischi di perdere tutti i conti in una volta sola.",
     "E per chiarezza: questo corso non ti consiglia di copiare le operazioni su più conti. Ti spiega solo come calcolare il rischio totale, se decidi di farlo."],
 4: ["Vediamo come si somma il rischio quando l'operazione è la stessa su tutti i conti.",
     "Un conto, rischio dell'uno per cento: hai una unità di rischio.",
     "Tre conti, sempre all'uno per cento: hai tre unità di rischio sulla stessa idea.",
     "Cinque conti a mezzo punto per cento: due unità e mezza. In pratica, se aumenti il numero di conti e vuoi mantenere lo stesso rischio totale, devi ridurre il rischio su ciascun conto."],
 5: ["Prova tu. Hai quattro conti da cinquantamila euro, rischi l'uno per cento su ciascuno, e apri la stessa operazione su tutti. Quanto perdi in totale se va male?"],
 6: ["L'uno per cento di cinquantamila sono cinquecento euro per conto. Per quattro conti fanno duemila euro, in un colpo solo. Se ti sembra troppo, riduci il rischio su ciascun conto."],
 7: ["Ricapitoliamo.",
     "Se apri la stessa operazione su più conti, il rischio si somma.",
     "Controlla sempre cosa permette il regolamento della prop firm.",
     "E calcola il rischio totale in euro, non solo la percentuale su ogni conto. Con questo chiudiamo il modulo sulle prop firm."],
 8: ["Ricordati: cinque conti, ma un solo errore li colpisce tutti insieme."],
}
